### ISSUE TITLE
Help Update Id Field option value

### ISSUE THREAD

**Issue by Infolu** [rilwis/meta-box#1001]
Personal need of help Hello, I know that is not part of the support would most like to receive a light

Today when I need to update a field whether it be any of a post type I use
`$wpdb-> query ("UPDATE $ wpdb-> postmeta SET meta_key = 'name of the new field' WHERE meta_key = 'name of the old field' ');`

However this only works when the field in the database has only one data

Mb_settings_pages all information is stored within a single field option_value

In mb_settings_pages have a field with the ID: NAME and need to upgrade to ID: newname how to update the name field of a option_value ID without losing information?

![image](https://cloud.githubusercontent.com/assets/16593922/19495500/619c1670-9562-11e6-8ce2-5a74207bb2f8.png)

**Comment by rilwis** [comment]
Hi,


You can run the following code:

```php
$option = get_option( 'option_name' );
$option[$field_id] = $new_value;
update_option( 'option_name', $option );
```

**Comment by Infolu** [comment]
Hello thanks for the return, using the above command it updates the data expecificado FIELD_ID, however it erases all other leaving blank.

How do him only update the data of a FIELD_ID without affecting the other, as are various information in a single option_value.

**Comment by funkedgeek** [comment]
This should do the trick:
```
$option = get_option( 'option_name' );
$option['new_id'] = $option['old_id'];
update_option( 'option_name', $option );
```

**Comment by Infolu** [comment]
@funkedgeek it works to change the FIELD_ID name, however he loses the information stored on old_field_id.

I do not know if I'm being clear in explaining my need to apologize.

More basically change the fiield_id without losing the information supplied in these fields.

**Comment by funkedgeek** [comment]
Remove the third line
```
$option = get_option( 'option_name' );
$option['new_id'] = $option['old_id'];
update_option( 'option_name', $option );
```

**Comment by Infolu** [comment]
@funkedgeek This worked for me at the moment. Thank you
