### ISSUE TITLE
Type field post search

### ISSUE THREAD

**Issue by Infolu** [rilwis/meta-box#1005]
Hello now have a field type post registered in a metabox however it just search the title of a post, how do I get beyond the title get a expecifico field of post type set?

I tried to add the query_args
     'Meta_key' => 'my-field', // (string) - Custom field key.
or
     'Meta_value' => 'my-field', // (string) - Custom field value.

However unsuccessful or am I doing wrong?

![image](https://cloud.githubusercontent.com/assets/16593922/19601879/cebfe816-9789-11e6-9004-b6868495dbae.png)

![image](https://cloud.githubusercontent.com/assets/16593922/19601907/eaa860c6-9789-11e6-8461-b0f716b19364.png)

`				array(
					'id'    => $PrefixField . 'default_customers',
					'name'        => __( 'Post', 'your-prefix' ),
					'type'        => 'post',
					// 'clone'       => true,
					// 'multiple'    => true,
					// Post type: string (for single post type) or array (for multiple post types)
					'post_type'   => array( 'customers' ),
					// Default selected value (post ID)
					'std'         => 1,
					// Field type, either 'select' or 'select_advanced' (default)
					'field_type'  => 'select_advanced',
					// Placeholder
					'placeholder' => __( 'Select an Item', 'your-prefix' ),
					// Query arguments (optional). No settings means get all published posts
					// @see https://codex.wordpress.org/Class_Reference/WP_Query
					'query_args'  => array(
						'post_status'    => 'publish',
						'posts_per_page' => - 1,
						'meta_key' => 'customers_mf_default_phones',                    //(string) - Custom field key.
						//'meta_value' => 'customers_mf_default_phones',                //(string) - Custom field value.
					),
				),`

**Comment by funkedgeek** [comment]
Related to https://github.com/rilwis/meta-box/commit/0d096cb5f1a49e83d5cc255135ba1b722eb3c321L:
Use the `rwmb_{$field_id}_choice_label` filter, where `$field_id is the id of the field`:

```
function some_post_filter( $label, $field, $post )
{
    //Get Meta field from post, then return it
}

add_filter("'rwmb_{ $PrefixField . 'default_customers'}_choice_label", 'some_user_filter', 10, 3 );
```

**Comment by Infolu** [comment]
@funkedgeek hello, I'm lost with the filters can help me?

I'm putting the filter on a field type post, this post have a field called customers_mf_default_name as I put it in the filter below?
![image](https://cloud.githubusercontent.com/assets/16593922/19643131/73c4b9a6-99c7-11e6-8143-144e867817b3.png)

Grateful

`function some_post_filter( $label, $field, $post )
{
    //Get Meta field from post, then return it
   return $field = rwmb_meta( 'customers_mf_default_name' );
   //return $field->customers_mf_default_name;
}
add_filter( 'rwmb_service_orders_mf_default_customers_choice_label', 'some_post_filter', 10, 3);`

**Comment by funkedgeek** [comment]
You have to provide the post_id for rwmb_meta because you want the meta field from customers post, not your current one:

```
function some_post_filter( $label, $field, $post ) { 
    $field = rwmb_meta(  'customers_mf_default_name', array(), $post->ID  ); 
}
add_filter( 'rwmb_service_orders_mf_default_customers_choice_label', 'some_post_filter', 10, 3);
```
