### ISSUE TITLE
When I change the metabox select to multiple true does not keep the value

### ISSUE THREAD

**Issue by davidperezgar** [rilwis/meta-box#1006]
Hello, 
I use meta-box and for a meta I've set a select box, and I want to change multiple to true. The problem is that I've already saved a lot of entries and I wouldn't want to loose all of my work. 

How can I keep the value selected when the box is changed to multiple true?

Thanks.

**Comment by davidperezgar** [comment]
Or any way to convert it?

**Comment by funkedgeek** [comment]
Have you tried?  Changing a select to multiple should not cause any loss in data.  Going the other way; from multiple to single, would

**Comment by davidperezgar** [comment]
Yes, I've tried. It does not keep it, becouse the multiple value is an array. The plugin should detect the string and convert it in array if it this couses the changes...

**Comment by funkedgeek** [comment]
Can you post the code you are using for the field?

**Comment by davidperezgar** [comment]
Yes!
See that {$prefix}depvarimgprod is the one that I want to change it as multiple...

`
				array(
    			'name'   => __( 'Group Image Product', 'pbc' ),
					'id'     => "{$prefix}imgprodgroup",
					'type'   => 'group',
					'clone'  => true,
					'sort_clone' => true,
					'fields' => array(
		    			// SELECT BOX VARIATIONS
		    			array(
		    				'name'        => __( 'Variation', 'pbc' ),
		    				'id'          => "{$prefix}depvarimgprod",
		    				'type'        => 'select',
		    				'options'     => $var_options,
		    				'multiple'    => false,
		    				'std'         => '',
		    				'placeholder' => __( 'Not depends of a Variation', 'pbc' ),
		    			),
		    			// IMAGE ADVANCED (WP 3.5+)
		    			array(
		    				'name'             => __( 'Image Product', 'pbc' ),
		    				'id'               => "{$prefix}imgprod",
		    				'type'             => 'image_advanced',
		    				'max_file_uploads' => 1,
		    			),
					),
				), //array`

**Comment by funkedgeek** [comment]
It's a clone; that's why.  Give a second

**Comment by davidperezgar** [comment]
What's the better solution?

**Comment by rilwis** [comment]
HI @davidperezgar ,

You are using a `group` field to wrap all the sub-fields. Because `group` saves its value as a serialized array in 1 row in the post meta, there's no simple way to convert the values from the field **Variation** from single to multiple.

If you defined the field as a standalone field, not inside a group, switching `multiple` between `true`/`false` will work.

**Comment by davidperezgar** [comment]
Hello @rilwis, I know that, but a I need it in a group. I've made a script to change old values, and I share with you. The problem is only that is not getting the single value as an array. 

I think with this, I'll solve it.

`
$svariations = get_posts('posts_per_page=-1&post_type=variation&meta_key=pbc_imgprodgroup&fields=ids');
if(!empty($svariations)){
   foreach($svariations as $varId){
       $pbc_imgprodgroup = get_post_meta($varId, 'pbc_imgprodgroup', true);
       if(!empty($pbc_imgprodgroup)){
           foreach($pbc_imgprodgroup as $key => $values){
               if(isset($values['pbc_depvarimgprod']) && !is_array($values['pbc_depvarimgprod'])){
                   $pbc_imgprodgroup[$key]['pbc_depvarimgprod'] = array($values['pbc_depvarimgprod']);
               }
           }
       }
       update_post_meta($varId, 'pbc_imgprodgroup', $pbc_imgprodgroup);
   }
}
`

**Comment by rilwis** [comment]
@davidperezgar Yes, manual updating the value is the only way to do that.

Your script looks good 👍 Thanks for sharing.

**Comment by davidperezgar** [comment]
Thanks for your plugin. It's amazing.
