### ISSUE TITLE
Call to undefined wp_scripts (Wordpress 4.1, Meta-box 4.9.8)

### ISSUE THREAD

**Issue by fred777** [rilwis/meta-box#1009]
I am not able to edit pages with WordPress 4.1 anymore - all I'm getting is a blank page.

I tracked this down to meta-box (version 4.8.6 included with Cardinal theme) causing `Call to undefined function wp_scripts()`-errors. I manually updated meta-box within the theme directory to 4.9.8 => the wp_scripts error in media.php seems fixed now but I’m still getting a similar one:

```
Call to undefined function wp_scripts() in /home/domains/wordpress/******/themes/cardinal/includes/meta-box/inc/field.php on line 30
```

And there is another place where wp_scripts is called, which could potentially cause that error: `inc/fields/datetime.php`

The error was introduced with https://github.com/rilwis/meta-box/commit/6627171c4c6b8112e3d52ac9ed905aa51d79ed59

When I revert back to tag 4.8.5, everything is fine.

**Comment by rilwis** [comment]
Can you update the WordPress to the latest version?

**Comment by fred777** [comment]
I wish I could, but I am forced to use wordpress coming with Debian Jessie.

**Comment by rilwis** [comment]
Please try the fix above :)

**Comment by fred777** [comment]
Thanks! Seems to work :)
