### ISSUE TITLE
UI Issues

### ISSUE THREAD

**Issue by ehsanagh** [rilwis/meta-box#1010]
![screen shot 2016-10-31 at 11 56 50](https://cloud.githubusercontent.com/assets/6294823/19848217/305df5a2-9f61-11e6-9755-abc96ad9d8ad.png)

Hi,
there are a lot's of UI issues on this, check the screenshot,
remove and edit button are showing top right corner because "position relative" property has not been set on the container element.
and Also when I click on remove button, It will only add "removed" class to the "li", it's not removing it at all.
Please do one testing on this and fix these simple things and feel free for asking any other detailed information.

**Comment by funkedgeek** [comment]
That looks like a really old version of the plugin.  Current version doesn't have this issue.  Please update the code to the latest version
