### ISSUE TITLE
How to order the result that comes from a "cloned" field

### ISSUE THREAD

**Issue by Sammyskills** [rilwis/meta-box#1011]
Hi,

I'm using Metabox 4.9.8 and I have a field which I added the `clone => true` parameter. I understand that the fields are stored as a json object in the `wp_postmeta` table of my database.

I want to be able to retrieve the results in the frontend of my site, based on the time the field(s) are updated. Something like `ORDERING` my frontend result based on how the fields are added.

Is this possible?

**Comment by rilwis** [comment]
Do you use `sort_clone` param? It allows you to sort the values in the backend.

By the way, the data returned is always the same as in the backend, isn't it?

**Comment by Sammyskills** [comment]
No, I don't use `sort_clone` param. 

But is there no way I can `ORDER` the results that have been saved in the db in `ASC` or `DESC` without sorting from the backend?

**Comment by rilwis** [comment]
You just get the data and sort in any way you want ;)

```php
$data = rwmb_meta( 'field_id' );
sort( $data ); // Sort ASC
print_r( $data);
```

**Comment by Sammyskills** [comment]
Okay thank you.

Is `sort( $data )` just for sorting in `ASC` alone, or is there a different way for sorting in `DESC`?

What I mean is, do I need to pass the `ASC` or `DESC` in the `sort( $data )` ? And where?

**Comment by rilwis** [comment]
Yes, [`rsort`](http://php.net/rsort) is what you need.

Also check out PHP sorting functions ;)

**Comment by Sammyskills** [comment]
Okay thank you very much.
