### ISSUE TITLE
Gumroad delivers Meta box Group version 1.0.7

### ISSUE THREAD

**Issue by JeppeSigaard** [rilwis/meta-box#1013]
Current version of the extension is 1.1.6.
I get a call to undefined index error (field_name on line 59, the class file) when trying to run the 1.0.7 extension on Meta Box version 4.9.8

Do I need to re-purchase, or will the Gumroad dl be updated?

**Comment by rilwis** [comment]
Hi,

When did you buy the extension? And what's your email?

If you bought the extension more than 1 year ago, then you need to re-purchase it as each purchase has only 1 year of update and support.

**Comment by JeppeSigaard** [comment]
mb
meta box group repurchased
