### ISSUE TITLE
Labels are not translated by po

### ISSUE THREAD

**Issue by davidperezgar** [rilwis/meta-box#1016]
Hello, I'm using the function __ for labels in fields, but it not translating correctly that labels. Should I do something different? Thanks

**Comment by rilwis** [comment]
Hi David,

If you register meta boxes in a theme or in a plugin, then the field labels should be translated by the theme or plugin, not by Meta Box.

**Comment by davidperezgar** [comment]
Yes of course, but I don't know why is not getting the function __, just to know if it should be different function. I've loaded all language file from the plugin but it's not getting the labels from meta box.

**Comment by rilwis** [comment]
Maybe you need to configure the poEdit to scan the folder where the PHP file is. I can't see anything different between the file/function and the other code.

**Comment by davidperezgar** [comment]
Ok Thanks.
