### ISSUE TITLE
Support for Wordpress REST API

### ISSUE THREAD

**Issue by merhawifissehaye** [rilwis/meta-box#1017]
Can you provide an easy way of getting the meta boxes in the REST API json response of the custom post type. For example if I have a custom post type called 'Music', I should be able to access all the meta boxes in addition to the default ones with `http://site.url/wp-json/wp/v2/music`

**Comment by rilwis** [comment]
Yes, that's supported with the [MB Rest API](https://metabox.io/plugins/mb-rest-api/) extension.
