### ISSUE TITLE
MetaBox Updater can't update MB Admin Columns

### ISSUE THREAD

**Issue by nicklima** [rilwis/meta-box#1018]
@rilwis, i do the upgrade, but after the success message appears when the page is refreshed I get a message saying that there is a new version of the extension plugin.

I have the latest version of the updater. I downloaded yesterday at [metabox.io](https://metabox.io).

All other extensions plugin succeeded in getting the upgrade.
The current version of **MB Admin Columns** is 1.0.1.

**Comment by rilwis** [comment]
Sorry, I put the wrong version on the host. Please just re-update the extension. Thanks for reporting!
