### ISSUE TITLE
Meta box

### ISSUE THREAD

**Issue by Xhino7** [rilwis/meta-box#1019]
Hello
i'm using this metabox:
<?php
$prefix = 'wtf_';

$meta_box = array(
	'id' => 'site',
	'title' => 'Detaje Kartvizita',
	'page' => 'post',
	'context' => 'normal',
	'priority' => 'high',
	'fields' => array(
           
                array(
			'name' => 'Tel',
			'desc' => 'Shtoni Nr e Telefonit',
			'id' => $prefix . 'tel',
			'type' => 'text',
			'std' => ''
                ),
		array(
			'name' => 'E-mail',
			'desc' => 'Shtoni E-mailin tuaj.',
			'id' => $prefix . 'mail',
			'type' => 'text',
			'std' => ''
		),
		array(
			'name' => 'Website',
			'desc' => 'Shtoni Webin tuaj.',
			'id' => $prefix . 'designer',
			'type' => 'text',
			'std' => ''
		),

		array(
			'name' => 'URL E Websit',
			'desc' => 'URL E Websit',
			'id' => $prefix . 'designurl',
			'type' => 'text',
			'std' => ''
		),		
		array(
			'name' => 'Vendndodhja',
			'desc' => 'Pershkrim Vendndodhja',
			'id' => $prefix . 'nation',
			'type' => 'text',
			'std' => ''
                ),
                 array(
			'name' => 'Facebook',
			'desc' => 'Facebook Link',
			'id' => $prefix . 'fb',
			'type' => 'text',
			'std' => ''
		),

                array(
			'name' => 'Twitter',
			'desc' => 'Twitter Link',
			'id' => $prefix . 'tw',
			'type' => 'text',
			'std' => ''
		),
                array(
			'name' => 'Instagram',
			'desc' => 'Instagram Link',
			'id' => $prefix . 'is',
			'type' => 'text',
			'std' => ''
		),
               array(
			'name' => 'Google +',
			'desc' => 'Google + Link',
			'id' => $prefix . 'gp',
			'type' => 'text',
			'std' => ''
		),

                array(
			'name' => 'Linkedin',
			'desc' => 'Linkedin Link',
			'id' => $prefix . 'in',
			'type' => 'text',
			'std' => ''
		
		)		
	)
);

add_action('admin_menu', 'mytheme_add_box');

// Add meta box
function mytheme_add_box() {
	global $meta_box;
	
	add_meta_box($meta_box['id'], $meta_box['title'], 'mytheme_show_box', $meta_box['page'], $meta_box['context'], $meta_box['priority']);
}

// Callback function to show fields in meta box
function mytheme_show_box() {
	global $meta_box, $post;
	
	// Use nonce for verification
	echo '<input type="hidden" name="mytheme_meta_box_nonce" value="', wp_create_nonce(basename(__FILE__)), '" />';
	
	echo '<table class="form-table">';

	foreach ($meta_box['fields'] as $field) {
		// get current post meta data
		$meta = get_post_meta($post->ID, $field['id'], true);
		
		echo '<tr>',
				'<th style="width:20%"><label for="', $field['id'], '">', $field['name'], '</label></th>',
				'<td>';
		switch ($field['type']) {
			case 'text':
				echo '<input type="text" name="', $field['id'], '" id="', $field['id'], '" value="', $meta ? $meta : $field['std'], '" size="30" style="width:97%" />',
					'<br />', $field['desc'];
				break;
			case 'textarea':
				echo '<textarea name="', $field['id'], '" id="', $field['id'], '" cols="60" rows="4" style="width:97%">', $meta ? $meta : $field['std'], '</textarea>',
					'<br />', $field['desc'];
				break;
			case 'select':
				echo '<select name="', $field['id'], '" id="', $field['id'], '">';
				foreach ($field['options'] as $option) {
					echo '<option', $meta == $option ? ' selected="selected"' : '', '>', $option, '</option>';
				}
				echo '</select>';
				break;
			case 'radio':
				foreach ($field['options'] as $option) {
					echo '<input type="radio" name="', $field['id'], '" value="', $option['value'], '"', $meta == $option['value'] ? ' checked="checked"' : '', ' />', $option['name'];
				}
				break;
			case 'checkbox':
				echo '<input type="checkbox" name="', $field['id'], '" id="', $field['id'], '"', $meta ? ' checked="checked"' : '', ' />';
				break;
		}
		echo 	'<td>',
			'</tr>';
	}
	
	echo '</table>';
}

add_action('save_post', 'mytheme_save_data');

// Save data from meta box
function mytheme_save_data($post_id) {
	global $meta_box;
	
	// verify nonce
	if (!wp_verify_nonce($_POST['mytheme_meta_box_nonce'], basename(__FILE__))) {
		return $post_id;
	}

	// check autosave
	if (defined('DOING_AUTOSAVE') && DOING_AUTOSAVE) {
		return $post_id;
	}

	// check permissions
	if ('page' == $_POST['post_type']) {
		if (!current_user_can('edit_page', $post_id)) {
			return $post_id;
		}
	} elseif (!current_user_can('edit_post', $post_id)) {
		return $post_id;
	}
	
	foreach ($meta_box['fields'] as $field) {
		$old = get_post_meta($post_id, $field['id'], true);
		$new = $_POST[$field['id']];
		
		if ($new && $new != $old) {
			update_post_meta($post_id, $field['id'], $new);
		} elseif ('' == $new && $old) {
			delete_post_meta($post_id, $field['id'], $old);
		}
	}
}

?>

now i want to call it on front page with
 /*
Template Name: Submit
*/
how i can do?
Thanx

**Comment by funkedgeek** [comment]
Can you explain what you are asking and what you want to do?  Just posting code here without an explanation doesn't help anybody.

**Comment by funkedgeek** [comment]
I'm closing this until you clarify
