### ISSUE TITLE
After update, the clone function is broken

### ISSUE THREAD

**Issue by pooria-m** [rilwis/meta-box#1020]
After I updated to 4.9.23, when I press '+Add more' button, I see in browser's inspector that the key of all of the instances is 0. (e.g `name="books[0]"`) so that only one of them is saved in database!

![capture](https://cloud.githubusercontent.com/assets/9452720/20384122/d22f74e6-acc7-11e6-9fdc-bdda687b762a.JPG)

**Comment by funkedgeek** [comment]
Please post the code you are using to create the meta box.

**Comment by pooria-m** [comment]
@funkedgeek 
`add_filter( 'rwmb_meta_boxes', 'prof_prefix_meta_boxes' );
function prof_prefix_meta_boxes( $meta_boxes ) {
    $meta_boxes[] = array(
        'title'      => __( 'Professor Info', 'mech' ),
        'post_types' => 'people',
        'fields'     => array(
           array(
                'id'   => 'course',
                'name' => __( 'Course', 'mech' ),
                'type' => 'text',
                'clone'      => true,
            ),
        ),
    );
return $meta_boxes;
}`
btw, I don't think that It would have any problems with the code.

**Comment by funkedgeek** [comment]
Weird, because I'm not able to replicate your issue.  You said you upgraded to 4.9.23.  Can you please upgrade to the latest, which is 4.9.8?

**Comment by pooria-m** [comment]
@funkedgeek It's weird that Wordpress doesn't recognize that there is a newer version. so I must do it manually. thanks

**Comment by pooria-m** [comment]
The problem is solved after the manual update. Thanks @funkedgeek
