### ISSUE TITLE
Meta Box and PHPmailer. Is it possible to get data between them?

### ISSUE THREAD

**Issue by spirit-infernal** [rilwis/meta-box#1024]
Hello. 
Awesome plugin, helped me a lot, thanks. It's not an issue as well, but request for assistance.
Can anyone say is it possible to get value from custom meta box, done with this plugin into custom script, which use phpmailer script? developing webpages, where use both phpmailer and meta box, so want to make this feature and make contact forms more flexible, but doesn't want to install another independent plugin like a contact form 7, etc.
Will appriciate any help with my question. 
Best wishes, Spirit

**Comment by rilwis** [comment]
You can simply use the helper function `rwmb_meta`. For more info, please check this docs:

**Comment by spirit-infernal** [comment]
Probably I've done something wrong or missed part, but already tried to make all as wrote in docs. Maybe problem is that script, which take values from frontend page and send theese values to phpmailer script is not recognize value as apropriate and throw error ''unexpected t_echo at line ...' 
used both '$mailTo = echo rwmb_meta( 'mail' );' and '$mailTo = rwmb_meta( 'mail' );'. In second time (without echo) - show white screen. 
Maybe it happens because, script, which packs mail and give it further to phpmailer is not a part of front-end? What possible to do in this situation?

**Comment by rilwis** [comment]
The 2nd statement seems correct because `rwmb_meta` returns the value and you need it to assign to `$mailTo`. So the problem is not **that** statement, probably something further in the script. You should turn on the debug, logging and see the error in the log.

**Comment by spirit-infernal** [comment]
Sorry, but still something misunderstanding(
Turned on debug mode for phpmailer and set ajax off. Getting following error: 
`Fatal error: Uncaught Error: Call to undefined function rwmb_meta() in %localserverpath%\%sitepath%\wp-content\themes\%themename%\assets\php\contactForm.php:10 Stack trace: #0 {main} thrown in %localserverpath%\%sitepath%\wp-content\themes\%themename%\assets\php\contactForm.php on line 10`

but as I understand [example ](https://github.com/rilwis/meta-box/blob/master/demo/include-by-ID-or-page-template.php) 
in my editor.php it linked this way:
`$checked_templates = array( 'front-page.php', 'Front Page', 'assets/php/contactForm.php' );` 
for contactForm file there is no template and file almost uneditable for users. And editor.php (which configures wordpress editor for front page) palced in root of theme.
it must works in linked file, or not? What I'm missing?

**Comment by spirit-infernal** [comment]
Ok, found a temporary solution for contact forms on sites, where mail address is not provided on front-end: provide mail adress from admin panel into hidden front-end text and then get this address into contact form script using `trim($_POST['mail']);` into right place alongside with other stuff from form. Probably it can be useful for somebody.
Thanks and best widhes. Spirit
