### ISSUE TITLE
std for taxonomy type

### ISSUE THREAD

**Issue by Nargilia** [rilwis/meta-box#1028]
How to make such thing works?
'type'          => 'taxonomy',
'std'           => $_GET['tax_id'],

**Comment by rilwis** [comment]
When you edit a post, the URL doesn’t have `tax_id` parameter. So it can’t work.

The `std` works as expected for `taxonomy` field.

CC @funkedgeek

**Comment by funkedgeek** [comment]
I believe WordPress clears $_GET and $_REQUEST so I don't think your code will work
