### ISSUE TITLE
Field visibility issues in v.4.9.8

### ISSUE THREAD

**Issue by wgstjf** [rilwis/meta-box#1030]
Hi guys,

Just updated to MB 4.9.8 (Condiitional logic v.1.3.4 / Columns v.1.0.0) on one of our sites and now we are experiencing field visibility issues.

Fields that are visible or hidden depending on conditional logic now continue to take up vertical space whether visible or not, leaving large gaps.  I see you are now using 'visibility: hidden;' instead of 'display:none'.

I appreciate that in your view this is due to UX improvements (https://metabox.io/support/topic/fields-are-hidden-with-visibility-property-rather-than-display/) however this is a major backwards step and we need to identify a fix for this.  Fields that are not visible should take up no space on the page.  

I see from the above URL that you suggest removing the 'columns' value but this is an unworkable solution since the vast majority of the metabox layouts we use rely on the column grid capability.

Can you please suggest a fix or release an update to resolve this asap as this has broken one site and I cannot afford to update on any others until this has been addressed.

Once again I find that updating MB has backwards compatibility issues and no warning given in advance of potential problems.  You guys know that I am a BIG supporter/fan of MB and the premium addons but it is worth mentioning that it feels like every time I update MB something breaks!

Please let me know as soon as possible what can be done to resolve the above issues.

Cheers,

Will

**Comment by tanng** [comment]
Dear Will,

To quick workaround:

-  Open `/assets/js/conditional-logic.js`,
- Replace
-- `$element.css('visibility', 'visible');` with `$element.show();`
-- $element.css('visibility', 'hidden');` with `$element.hide();`

Copy whole content of that file, then paste that in `conditional-logic.min.js`

**Comment by wgstjf** [comment]
Thanks for the workaround, very kind.

Here's hoping a permanent fix is implemented very soon :-)

**Comment by rilwis** [comment]
@tanng will update the extension soon. He made it :)

**Comment by tanng** [comment]
Dear Will, in case we have columns with 3 fields

A - B - C

If B is hidden, the field C will jump to B place immediately if we use `display:none;` instead of `visibility:hidden`. So the layout will becomes

A - C

I'll add `toggle_type` parameter support for field. By default, it will use `visibility` CSS property as currently, but when we set `'toggle_type' => 'display'`, the plugin will use CSS `display` property to toggle field.

**Comment by wgstjf** [comment]
@tanng 

Thanks for the quick reply.  

I totally understand your reasoning but with your suggested method I would argue the UI is worse since there are now large gaps where fields that are not currently visible reside.

A real world (if simplified) example.  We have a set of fields to provide a page builder capability called 'Panel Setup' and the first field is a select box that asks the user to define the type of panel by choosing either 'Images' or 'Text & Images'.

Each of the following fields is hidden by default until the user chooses from the select list.  Once chosen the relevant fields appear.  So if they chose 'Images' type then image_advanced fields are visible.  If they choose 'Text Panel' then textarea fields etc are visible.  Either way, with the latest update this results in large gaps which look awful.  See below for screenshot examples:

When Images selected: 
![image](https://cloud.githubusercontent.com/assets/3740694/21022665/53cbaade-bd75-11e6-8666-77da582ea8e7.png)

When 'Text & Image(s)' selected: 
![image](https://cloud.githubusercontent.com/assets/3740694/21022704/77998f58-bd75-11e6-9720-31b4fff4bc3f.png)

I appreciate your proposed modification to allow us to switch off the new functionality but how does the default state propose to cater for this type of issue?  If it doesn't then all future installations (at least by us) will have to disable this new feature.

Thanks again and I look forward to hearing from you.

Will

**Comment by wgstjf** [comment]
Any thoughts? :-)

**Comment by wgstjf** [comment]
In case anyone else is struggling with this my workaround is to add the following custom css to the admin area:

```css
.rwmb-field[data-visible="hidden"] {
  display: none;
}
```

Hope that helps :-)

**Comment by tanng** [comment]
Dear Will,

I've added a new `toggle_type` property for Meta Box, by default it uses `display` property to toggle elements so when you update, you don't have to do anything.

In case you want to use `visibility` property, just set `'toggle_type' => 'visibility'`.

Cheers!

**Comment by wgstjf** [comment]
@tanng 

That's great and very much appreciated, thanks!

Cheers,

Will
