### ISSUE TITLE
How to reference an array based on it's index

### ISSUE THREAD

**Issue by Sammyskills** [rilwis/meta-box#1031]
Hi, 

I'm trying to create a photo gallery section in my site, using the images that are uploaded using the `image_advanced` field. 

So far, the images are uploaded corrected, and I can fetch them correctly too. But I want to create a thumbnail section just below the big images.

I need to add `data-slide-index` which will enable the selected image to be active, but I can't because, I can't reference the array of the images based on their key.

This is my code:

```php
$imagesThumb = rwmb_meta('my_meta_id', 'size=50x50');
$arrLength = count($imagesThumb); // the length of the array
for( $i=0; $i < $arrLength; $i++ ) {
echo "<a href='{$imagesThumb[$i]['full_url']}' data-slide-index='".$i."'><img src='{$imagesThumb[$i]['url']}' width='{$imagesThumb[$i]['width']}' height='{$imagesThumb[$i]['height']}' alt='{$imagesThumb[$i]['alt']}' /></a>";
}
```

I want it to print out something like this, based on the number of images that are uploaded in the dashboard:

`<a href='the-full-url-of-the-image' data-slide-index='0'><img src='image-url' width='image-width' height='image-height' alt='image-alt' /></a>`

But so far, the images are not appearing at all.

**Comment by rilwis** [comment]
The problem is the keys of the returned array are the image IDs. You might want to change your code to something like:

```php
$images = rwmb_meta( 'my_meta_id', 'size=50x50' );
$index = 0;
foreach ( $images as $image ) {
    echo "<a href='{$image['full_url']}' data-slide-index='{$index}'><img src='{$image['url']}' width='{$image['width']}' height='{$image['height']}' alt='{$image['alt']}' /></a>";
    $index++;
}
```

**Comment by Sammyskills** [comment]
Thanks for replying, but that not what I was talking about.
 I need to print the `data-slide-index` based on the number of images in the array.
Something like:
`<a href='the-full-url-of-the-image' data-slide-index='0'><img src='image-url' width='image-width' height='image-height' alt='image-alt' /></a>`
`<a href='the-full-url-of-the-image' data-slide-index='1'><img src='image-url' width='image-width' height='image-height' alt='image-alt' /></a>`
`<a href='the-full-url-of-the-image' data-slide-index='2'><img src='image-url' width='image-width' height='image-height' alt='image-alt' /></a>` if there are only three images in the array, and so on.

**Comment by Sammyskills** [comment]
Thanks for replying, but that not what I was talking about.
 I need to print the `data-slide-index` based on the number of images in the array.
Something like:
`<a href='the-full-url-of-the-image' data-slide-index='0'><img src='image-url' width='image-width' height='image-height' alt='image-alt' /></a>`
`<a href='the-full-url-of-the-image' data-slide-index='1'><img src='image-url' width='image-width' height='image-height' alt='image-alt' /></a>`
`<a href='the-full-url-of-the-image' data-slide-index='2'><img src='image-url' width='image-width' height='image-height' alt='image-alt' /></a>` if there are only three images in the array, and so on.
