### ISSUE TITLE
Textfield with possibility to select

### ISSUE THREAD

**Issue by nepf** [rilwis/meta-box#1032]
Is there a possibility to have a textfiled for inputs, which shows all given values like in a select or better select-advanced-field - or the other way: A select-advanced-field with the possibility not only to select but to input new values as well.

**Comment by funkedgeek** [comment]
You can do this with a regular text field by adding options in the datalist argument:

```
array(
    'name'  => __( 'Text choices', 'textdomain' ),
    'id'    => 'text_choices',
    'type'  => 'text',
    'datalist' => array(
        'options' =>array(
            'Winning',
            'Losing',
            'Fighting'
        )
    ),
 ),
```

**Comment by nepf** [comment]
Yes, thank you, but i dont want to add options by hand i want to fetch them from all existing fields with the same key.
