### ISSUE TITLE
Media Event

### ISSUE THREAD

**Issue by tanng** [rilwis/meta-box#1035]
I'm trying to get all hidden fields value from Image Advanced but no luck:

```js
jQuery(document).on('change', '.rwmb-image_advanced', function ($) {
	console.log($('[name*="my_media_field"]').length);
});
```

When I add 1 image, the length is 1 and it's a `.rwmb-image_advanced` one (should be 1+1)
When I add 2 image, the length is 2, and it's a result of previous step.
And so on.

I'm not familiar with Backbone, currently, in the `addItemView()` and `removeItemView()`, I have to add
```js
$(document).trigger('selection-change');
```
to handle the event instead of current one.

So do you have any idea about this?

**Comment by rilwis** [comment]
@funkedgeek Can you please take a look at this? I thought we have this fixed?

**Comment by funkedgeek** [comment]
Should be fixed with latest commit.  I recommend changing your callback to this: 

```
jQuery(document).on('change', '.rwmb-image_advanced', function ($) {
	console.log($('.rwmb-media-input[name*="my_media_field"]').length);
});
```

because there is an extra hidden input to load initial values as part of the field, so you're old code will have plus one otherwise

**Comment by tanng** [comment]
Thanks bro.
