### ISSUE TITLE
Geolocation Tool

### ISSUE THREAD

**Issue by JonasHfr** [rilwis/meta-box#1041]
Hello,

The Geolocation Plugin is not working and I don't get how to activate it by "'geo' => true" and where to insert it.

Could someone give me a detailled step by step guide on how to set it up from the installation to the creation of Street-, City-, ZIP- and Country-Fields? The Documentation didn't help me at all.

Thanks and have a good New Year's Eve!
Jonas

**Comment by rilwis** [comment]
@tanng Can you please join this and help?

**Comment by JonasHfr** [comment]
UPDATE - 2017-01-02

I tried the test script from the documentation and it created all the fields correctly, but didn't show the suggestions/auto-completions from google as it should. 

Please help asap. Do I have to enter the API or anything?!

Thanks and Happy New Year, Jonas

**Comment by funkedgeek** [comment]
Yes, you need an api key from Google

**Comment by JonasHfr** [comment]
Dear funkedgeek,

Could you be a bit more precise? I got the API Key, but where do I need to place it?!

**Comment by tanng** [comment]
Please follow this guide:

https://metabox.io/docs/meta-box-geolocation/#section-adding-url-params

**Comment by JonasHfr** [comment]
Added it to functions.php but still doesn't work.

**Comment by tanng** [comment]
Dear Jonas,

It's weird, I've tried in my PC and it works, can you please try opening `/plugins/meta-box-geolocation/meta-box-geolocation.php`, and uncomment this line to show example meta box:

```php
require dirname( __FILE__ ). '/examples/example.php';
```
It should works by default, without entering any key.

In case it still doesn't works, can you please check browser console?

**Comment by JonasHfr** [comment]
Hey,
the metabox example is appearing now and is catching up my often-used addresses, but it's still not able to give me suggestions when I type in a new address. So I guess it's not working together with google.

I already gave Anh my Wordpress login. Would you like to take a look at it? I would then send it to you in private as well.

Thanks for the help, Jonas.

**Comment by tanng** [comment]
Hi, I'm the author of this plugin. The main purpose of this plugin is to work with Google, perhaps some conflict with other plugins. I'd take a look with him.

**Comment by rilwis** [comment]
Hi Jonas, @tanng and I are trying to help you via email. It's not actually a bug, so let's keep in touch via emails.
