### ISSUE TITLE
how to display radio and checkbox_list value

### ISSUE THREAD

**Issue by tgarda** [rilwis/meta-box#1044]
Using metabox 4.9.8. When I create a radio field, such as:

            array(
                'id'      => 'gender',
                'name'    => __( 'Gender', 'textdomain' ),
                'type'    => 'radio',
                'options' => array(
                    'm' => __( 'Male', 'textdomain' ),
                    'f' => __( 'Female', 'textdomain' ),
                ),

or a checkbox list such as:

                'id'   => 'language',
                'name' => __( 'Languages', 'textdomain' ),
                'type' => 'checkbox_list',
                'options' => array(
		       'chinese' => __( 'Chinese', 'textdomain' ),
                    'english' => __( 'English', 'textdomain' ),
                    'spanish' => __( 'Spanish', 'textdomain' ),
                ),

and display their value like so:

echo "metabox gender value: " . rwmb_meta( 'gender', '', $post->ID);
echo "metabox language value: " . rwmb_meta( 'language', '', $post->ID);

then the key of the key-value pair is printed, such as 'm', 'f', 'chinese', 'english', etc.

I expect the value of the key-value pair to be printed, such as 'Male', 'Female', Chinese', 'English', etc. Is that how it should work? 

If I am doing something wrong, please let me know.

I checked [fix bug [52cda62]](https://github.com/rilwis/meta-box/commit/52cda628c80d5653e550de54a8028e273575dbbd), but my inc/fields/choice.php file has that update (as it should).

Thank you.

**Comment by rilwis** [comment]
Hi @tgarda,

Please follow this documentation: https://metabox.io/docs/display-value-radio-checkbox-list-field/
