### ISSUE TITLE
Metabox Positioning / Priority

### ISSUE THREAD

**Issue by randysmachado** [rilwis/meta-box#1046]
I'm using metabox in a project and in the mobile version the metabox's I created are below the metabox "publish" which is the standard of wordpress. Is there a metabox mode that I created to stay below the "Publish" metabox?

http://prnt.sc/dup4ku
http://prnt.sc/dup51v

**Comment by funkedgeek** [comment]
I don't think there is a way to stay exactly below the publish box.  This [answer ](http://wordpress.stackexchange.com/questions/77224/best-practices-for-meta-box-placement)from WordPress Stack Exchange may help you

**Comment by rilwis** [comment]
Yes, there's no way to make it displayed **exactly** below the Publish box. But if you want to display in the side area and just below the Publish box (just below, not exact right below), then you can use these settings for meta box:

```
'context' => 'side',
'priority' => 'low',
```

For more infor, please read [this docs](https://metabox.io/docs/registering-meta-boxes/#section-meta-box-attributes).

**Comment by randysmachado** [comment]
I added 'context' => 'normal', 'priority' => 'high' because I want my metabox to be below the title instead of the wordpress editor.
`<?php 

    add_filter( 'rwmb_meta_boxes', 'your_prefix_meta_boxes' );

    function your_prefix_meta_boxes( $meta_boxes ) {

        $meta_boxes[] = array(

            'title'      => __( 'Informações da venda', 'textdomain' ),
            'post_types' => array( 'post', 'vendas' ),
            'context' => 'advanced',
            'priority' => 'high',
            'fields'     => array(

                //DESCRIÇÃO DO PRODUTO
                array(
                'id'   => 'descricao_produto',
                'name' => __( 'Descrição do produto', 'your-prefix' ),
                'desc' => __( 'Escreva algo bem interessante sobre o produto', 'your-prefix' ),
                'type' => 'textarea',
                'cols' => 20,
                'rows' => 3,
                ),

                //TELEFONE
                array(
                    'id'   => 'telefone',
                    'name' => __( 'Telefone', 'textdomain' ),
                    'type' => 'text',
                ),
                //CELULAR
                array(
                    'id'   => 'celular',
                    'name' => __( 'Celular', 'textdomain' ),
                    'type' => 'text',
                ),
                //EMAIL
                array(
                    'id'   => 'email',
                    'name' => __( 'Email', 'textdomain' ),
                    'type' => 'email',
                ),
                //VALOR
                array(
                    'id'   => 'valor',
                    'name' => __( 'Valor', 'textdomain' ),
                    'type' => 'text',
                ),
                // PLUPLOAD IMAGE UPLOAD (WP 3.3+)
                array(
                    'id'               => 'galeria',
                    'name'             => __( 'Adicionar imagens', 'your-prefix' ),
                    'type'             => 'plupload_image',
                    'desc'             => __( 'Arraste as imagens para alterar a ordem', 'your-prefix' ),
                    'max_file_uploads' => 6,
                ),

            ),

            'validation' => array(
            'rules'    => array(
                'descricao_produto' => array(
                    'required'  => true,
                ),
            ),

            // optional override of default jquery.validate messages
            'messages' => array(
                'descricao_produto' => array(
                    'required'  => esc_html__( 'Campo obrigatório', 'your-prefix' ),
                ),
            ),
        ),
        );
        return $meta_boxes;
    }

 ?>`

**Comment by jarodium** [comment]
In mine, I could not position it below the "Publish" like it is instructed. I would like to be able to put the fields in the right sidebar. I'm using version 4.14.11 inside a theme.

Below is the code and printscreens

`function your_prefix_get_meta_box( $meta_boxes ) {
	$prefix = 'prefix-';

	$meta_boxes[] = array(
		'id' => 'regiaosmtbx1',
		'title' => esc_html__( 'Categorias Multimédia', 'metabox-online-generator' ),
		'post_types' => array( 'post', 'page' ),
		'context' => 'side',
		'priority' => 'low',
		'autosave' => true,
		'fields' => array(
			array(
				'id' => '_resu_1',
				'name' => esc_html__( 'Vídeos', 'metabox-online-generator' ),
				'type' => 'select',
				'desc' => esc_html__( 'Escolha um ícone para representar o vídeo.', 'metabox-online-generator' ),
				'placeholder' => esc_html__( 'Escolha um Icone', 'metabox-online-generator' ),
				'options' => array(				    					
					'fa-video' => 'fa-video'
				),
			),
			array(
				'id' => '_resu_2',
				'name' => esc_html__( 'Galeria', 'metabox-online-generator' ),
				'type' => 'select',
				'desc' => esc_html__( 'Escolha um ícone para representar a galeria', 'metabox-online-generator' ),
				'placeholder' => esc_html__( 'Escolha um Icone', 'metabox-online-generator' ),
				'options' => array(				    
					'fa-images' => 'fa-images',
				),
			),			
			array(
				'id' => '_resu_3',
				'name' => esc_html__( 'Áudio', 'metabox-online-generator' ),
				'type' => 'select',
				'desc' => esc_html__( 'Escolha um ícone para representar o áudio', 'metabox-online-generator' ),
				'placeholder' => esc_html__( 'Escolha um Icone', 'metabox-online-generator' ),
				'options' => array(				    
					'fa-volume-up' => 'fa-volume-up',
				),
			),
		),
	);

	return $meta_boxes;
}
add_filter( 'rwmb_meta_boxes', 'your_prefix_get_meta_box' );`

![image](https://user-images.githubusercontent.com/1470446/42954049-a36e1888-8b73-11e8-9665-657400875bd1.png)


![image](https://user-images.githubusercontent.com/1470446/42954023-96677c1a-8b73-11e8-9c9d-72c880a96cf4.png)
