### ISSUE TITLE
Select.js - 522 Error when working with Cloudflare

### ISSUE THREAD

**Issue by Pazekal90** [rilwis/meta-box#1050]
Hey guys,

i´m working with cloudflare to enable HTTPS to my site. There is a problem while editing my Pages with Visual Composer there is the select.js file loaded in your plugin.

This file physically exists on the server but the browser is returning a 522 Error while loading that file. 
This error only occurs when the file is opened with the "ver=4.10.1" query string.

Is there a solution for that type of problem? What do you need for debugging?

File Path: GET https://neu.evangelisch-kahlgrund.de/wp-content/plugins/meta-box/js/select.js?ver=4.10.1 522 ()  => post.php?post=348&action=edit:4919 

Thanks
Pazekal

**Comment by funkedgeek** [comment]
I'm able to see the js file from the link you put up so I'm not sure what the problem is
