### ISSUE TITLE
Get custom input value from Image Media

### ISSUE THREAD

**Issue by careyestes** [rilwis/meta-box#1052]
Ive added a custom input box in the Edit Media section, which renders and saves successfully.

When I call rwmb_meta() in the WP_Query loop of a custom post type, I can get the typical arracy values (caption, alt, full_url, description), but I the custom field I created does not show up in the array.

I see here, https://metabox.io/docs/get-meta-value/, that you have to register the custom meta box using add_filter( 'rwmb_meta_boxes', 'prefix_register_meta_boxes' ); (I think).

ALthough I dont know how to write that properly.

A: Is it possible to pull custom fields from the edit media section using rwmb_meta()?
B: If so, how would you do that?

**Comment by funkedgeek** [comment]
Just call rwmb_meta using the id of the image field to get the meta from that image.
