### ISSUE TITLE
Tabs Top Padding

### ISSUE THREAD

**Issue by fahidjavid** [rilwis/meta-box#1054]
Hi!

Thanks for building a great plugin and several helpful extensions. However, I just found a very tiny styling problem while adding meta-box tabs to my theme.

Tabs sections don't have a good top space. I think if you increase little top padding it can help. See the related screenshot: http://jmp.sh/xBnR1qQ

Best Regards,

Fahid

**Comment by rilwis** [comment]
Thanks for your suggestion. The new version with the fix is released!
