### ISSUE TITLE
Image advanced and apostrophe in title not showing

### ISSUE THREAD

**Issue by xxkiefxx** [rilwis/meta-box#1060]
Hello,
I’m using meta box image advanced filed to add some images to my custom posts and I use Lightbox plugin to show them.
The problem is that when the image has an apostrophe in the title, the title is trimmed.
So, for example, if the title is “let’s go”, the title become “let” and everything after the apostrophe disappears.
I thought that the problem was the lightbox plugin I used, but I’ve noticed that if I add the title of the  image in an post using wordpress, then not using image advanced of meta box, there are not problems in showing the title with the apostrophe.

To add the image in the post I use this code:

```php
$images = rwmb_meta( 'base_images' );
  if ($images != null){
    echo "<h3 class='info'>Images</h3><br />";
    foreach ( $images as $image )
    {
     echo "<a href='{$image['full_url']}' title='{$image['title']}' rel='lightbox'><img style='padding:5px' src='{$image['url']}'  alt='{$image['alt']}' /></a>";
    }
```

and the metabox code is this:

```php
array(
  'name'             => esc_html__( 'Add Images', 'base_' ),
  'id'               => "{$prefix}images",
  'type'             => 'image_advanced',
  'width'            => 100,
  'height'           => 'auto',
  'max_file_uploads' => 20,
),
```

The only way to see the apostrophe is to write the in title & apos; or & #039; instead of the ‘ but this is something I’d like to avoid.

What I miss? How can I have this fixed?
Thank you

**Comment by rilwis** [comment]
The problem is the "echo" statement. You should escape it with `esc_attr`, like this:

```php
echo '<a href="', esc_url( $image['full_url'] ), '" title="', esc_attr( $image['title'] ), '" rel="lightbox"><img style="padding:5px" src="', esc_url( $image['url'] ), '"  alt="', esc_attr( $image['alt'] ), '"></a>';
```
