### ISSUE TITLE
Meta Box plugin problem with wordpress media uploader

### ISSUE THREAD

**Issue by ahmedgamal47** [rilwis/meta-box#1068]
sometimes the wordpress media uploader stop working just by adding metabox fields , media uploader just keeps loading but it dosent show any files , 
i uploaded the functions.php file  in attachment , if i just deleted these 3 liens
if ($_GET['post'] != '5'){
    echo "Any text";
}
everything works fine 

![untitled](https://cloud.githubusercontent.com/assets/25516522/22570758/52de0bd8-e9a5-11e6-80f5-69e103da785f.jpg)

[p.txt](https://github.com/rilwis/meta-box/files/749067/p.txt)

**Comment by funkedgeek** [comment]
Probably, that echoing is interfering with the WordPress Ajax calls that the uploader works on.  I'd recommend not echoing anything in the function.php file, since it tends to break stuff
