### ISSUE TITLE
calling metabox fields in theme

### ISSUE THREAD

**Issue by ahmedgamal47** [rilwis/meta-box#1069]
can i use the meta box fields inside my theme or its just made for wordpress dashboard ?

**Comment by funkedgeek** [comment]
What do you mean by using it inside your theme?  Do you mean adding fields to a theme settings page?

**Comment by ahmedgamal47** [comment]
no i mean calling it in a page such as home.php or single.php

**Comment by funkedgeek** [comment]
You can call the data from the field using `rwmb_meta`.  If you mean showing the field on a page for a user to fill out, this plugin does not do that.  Strictly admin.
