### ISSUE TITLE
Image is returning the attachment ID instead of the image array

### ISSUE THREAD

**Issue by OneEarthMedia** [rilwis/meta-box#1070]
Hi!

I just updated the plugin and for some my images are returning the attachment ID now instead of the Array is they were before.

I quickly researched online and saw that that other people have had a similar issue with past versions.

This hasn't however affected other websites I've developed using the MetaBox plugin. Only the one I'm working on right now.. and I just can't get my head around why?

I've resorted to using wp_get_attachment_url() to get my images right now :)

This is how I'm retrieving the image full_url :

```
$opening_section__background = rwmb_meta('oem__opening_section__background', 'size=full');
if (!empty($opening_section__background) ) {
    foreach ($opening_section__background as $background_image) {
        $opening_section['background'] = $background_image['full_url'];
    }    
}
```

And this is how I register the field:

```
array(
    'id'   => 'oem__opening_section__background',
    'name' => __('Background Image', 'oneearth'),
    'desc' => __('Upload large images with the dimensions of 1920x1280. Smaller sizes are created automatically', 'oneearth'),
    'type' => 'image_advanced',
    'max_file_uploads' => 1,
),
```

Any ideas why this might be happening?

Thanks!

Herman

**Comment by rilwis** [comment]
Hi Herman,

If you use the `rwmb_meta`, you always get an array. I see your code is correct. Can you give more details on the situation when it fails?

**Comment by OneEarthMedia** [comment]
I am using rwmb_meta on a very basic page template. I have just began development on this site so MetaBox is the only active plugin. The most recent version of WP is installed.

This is how I register the meta boxes in for the particular page template:

```
add_filter( 'rwmb_meta_boxes', 'oem_homepage_meta_boxes' );
function oem_homepage_meta_boxes($meta_boxes) {
    
    $meta_boxes;
    
    // Get Post ID
    if (isset( $_GET['post'])) {
        $post_id = $_GET['post'];
    } elseif (isset($_POST['post_ID'])) {
        $post_id = $_POST['post_ID'];
    } else {
        $post_id = get_the_ID();
    }
    
    // Only show these fields when the homepage template is active
    if (isset($post_id)) {
        $page_template = get_post_meta($post_id, '_wp_page_template', true);
        if($page_template == 'template-homepage.php' ) {
            // Remove the default editor
            remove_post_type_support('page', 'editor');
            
            // Add the custom meta boxes
            // Homepage Welcome Section
            $meta_boxes[] = array(
                'title'      => __('Opening Section', 'oneearth'),
                'post_types' => 'page',
                'fields'     => array(
                    array(
                        'id'   => 'oem__opening_section__color',
                        'name' => __('Section Color', 'oneearth'),
                        'type' => 'color',
                    ),
                    array(
                        'id'   => 'oem__opening_section__content',
                        'name' => __('Section Content', 'oneearth'),
                        'type' => 'wysiwyg',
                        'options' => array(
                            'tinymce'       => true,
                            'media_buttons' => false,
                            'textarea_rows' => 10,
                        ),
                    ),
                    array(
                        'id'   => 'oem__opening_section__background',
                        'name' => __('Background Image', 'oneearth'),
                        'desc' => __('Upload large images with the dimensions of 1920x1280. Smaller sizes are created automatically', 'oneearth'),
                        'type' => 'image_advanced',
                        'max_file_uploads' => 1,
                    ),
                ),
            );
      
        }
    }
    
    return $meta_boxes;

}
```

And this is how I get the image on the front:

`$opening_section__background = rwmb_meta('oem__opening_section__background', 'size=full');`

But when I `echo` this I get the attachment ID instead of the array.

`get_post_meta()` also gets the ID but I think this is to be expected?

There really is nothing else on the site that I can think of as a cause for this issue. All the other meta box fields work fine.

I have also tried to remove all the JS my theme loads and remove and reinstall the plugin. Nothing changed.

Thanks,

Herman

**Comment by funkedgeek** [comment]
I'm guessing that rwmb_meta is not seeing the meta box because you are hiding it in that if statement that is looking for the page template.  Try using $__REQUEST instead of $__POST and $__GET

**Comment by OneEarthMedia** [comment]
That's right. I changed the if statement to `if($page_template == 'template-homepage.php' || !is_admin())` and now it works!

Why did this only affect the images and not the other meta fields?

Thanks!

Herman

**Comment by funkedgeek** [comment]
Because all that is saved for images is an array of ids for the images themselves.  rwmb_meta pulls up the meta box data and uses that to convert the ids into the actual image data.  if it can't access the meta box data, it'll default to just returning the image ids.

**Comment by toddden** [comment]
!is_admin() is all u needed
