### ISSUE TITLE
Meta box placement manipulation

### ISSUE THREAD

**Issue by randysmachado** [rilwis/meta-box#1075]
I'll try to explain my doubt.
My problem is on mobile devices. I have a project where users can make their ads on the site so I created a specific custom post type and the ones for the necessary fields and I used the metabox for this function.
When the user enters the screen to publish his ad the "publish" meta box which is the default of wordpress already appears below the title of the post, and not the metaboxes that I created.
Today is this: http://prnt.sc/e91oqw

I would like the meta boxes I created to be below the title of the post and the metabox to publish would be down, that is, it would be the last meta box.

I would like it to look like this: http://prnt.sc/e91rpy

There is this example of how metabox behaves [HERE](http://wordpress.stackexchange.com/questions/77224/best-practices-for-meta-box-placement) , but I could not use that example.

Could you help me?

My code looks like this: ` 

    add_filter( 'rwmb_meta_boxes', 'your_prefix_meta_boxes' );

    function your_prefix_meta_boxes( $meta_boxes, $context = 'normal', $priority = 'high') {   

        $meta_boxes[] = array(

            'title'      => __( 'Informações do anúncio', 'textdomain' ),
            'post_types' => array( 'anuncios'),
            'fields'     => array(

                //DESCRIÇÃO DO PRODUTO
                array(

                'id'   => 'descricao_produto',
                'name' => __( 'Descrição do produto', 'your-prefix' ),
                'desc' => __( 'Escreva algo bem interessante sobre o produto', 'your-prefix' ),
                'type' => 'textarea',
                'cols' => 20,
                'rows' => 3,
                ),

                //TELEFONE
                array(
                    'id'   => 'telefone',
                    'name' => __( 'Telefone', 'textdomain' ),
                    'type' => 'text',
                ),
                //CELULAR
                array(
                    'id'   => 'celular',
                    'name' => __( 'Celular', 'textdomain' ),
                    'type' => 'text',
                ),
                //EMAIL
                array(
                    'id'   => 'email',
                    'name' => __( 'Email', 'textdomain' ),
                    'type' => 'email',
                ),
                //VALOR
                array(
                    'id'   => 'valor',
                    'name' => __( 'Valor', 'textdomain' ),
                    'type' => 'text',
                ),
                // PLUPLOAD IMAGE UPLOAD (WP 3.3+)
                array(
                    'id'               => 'galeria',
                    'name'             => __( 'Adicionar imagens', 'your-prefix' ),
                    'type'             => 'plupload_image',
                    'desc'             => __( 'Arraste as imagens para alterar a ordem', 'your-prefix' ),
                    'max_file_uploads' => 6,
                ),

            ),

            'validation' => array(
            'rules'    => array(
                'descricao_produto' => array(
                    'required'  => true,
                ),
            ),

            // optional override of default jquery.validate messages
            'messages' => array(
                'descricao_produto' => array(
                    'required'  => esc_html__( 'Campo obrigatório', 'your-prefix' ),
                ),
            ),
        ),
        );

        return $meta_boxes;
    }
 `

**Comment by funkedgeek** [comment]
Unfortunately, this is a limitation of how meta boxes work in WordPress.
