### ISSUE TITLE
error in WP template

### ISSUE THREAD

**Issue by jpbrightsign** [rilwis/meta-box#1076]
I am getting this error with the Gloria template when I go to edit a Post.

Fatal error: Call to undefined method RW_Meta_Box::get_class_name() in /home/digit466/public_html/wp-content/themes/gloria/framework/meta-box-group/class-rwmb-group-field.php on line 61

**Comment by rilwis** [comment]
You need to update the Group extension to compatible with the latest version of Meta Box. You can buy it here: https://metabox.io/plugins/meta-box-group/.

Or you can ask the theme author to buy and update it.
