### ISSUE TITLE
How to add the fancybox effect in PLUPLOAD IMAGE UPLOAD

### ISSUE THREAD

**Issue by randysmachado** [rilwis/meta-box#1078]
The PLUPLOAD IMAGE UPLOAD gallery has the lightbox effect as the default, but I'd like to use another effect on my images, for example the fancybox effect.

I have the fancybox scripts on my server, but I can not add the effects to the image gallery.

I use the default code to call the pictures, but where do I add the call to the fancybox effect?

```php
$images = rwmb_meta( 'gallery', 'size=YOURSIZE' ); // Since 4.8.0`
if ( !empty( $images ) ) {
    foreach ( $images as $image ) {
        echo '<a href="', esc_url( $image['full_url'] ), '" title="', esc_attr( $image['title'] ), '" rel="lightbox"><img style="padding:5px" src="', esc_url( $image['url'] ), '"  alt="', esc_attr( $image['alt'] ), '"></a>';
    }
}
```

**Comment by rilwis** [comment]
The effect is added by your code. The field doesn't handle how the data is shown in the frontend.

In the code above I see you use `rel="lightbox"`, that might be the trigger for the fancybox script.

Basically, you need to follow the steps described on [fancybox page](http://fancyapps.com/fancybox/) to enqueue scripts and call the effect.
