### ISSUE TITLE
New fields cant be saved

### ISSUE THREAD

**Issue by jeroensijbom** [rilwis/meta-box#1079]
New fields i add to the fields array cant be saved. Even i copy existing fields and change the id, value is not saved to the database. Existing field work just fine. Disabled all other plugins and still same issue.

WP: 4.7.2
Metabox: 4.10.3

**Comment by funkedgeek** [comment]
What is the code for your meta box and where are you declaring it?

**Comment by jeroensijbom** [comment]
In a seperate which i require in my functions.php. More than 20 fields that work, only this new one isnt working:

`// Zelf keuze
			array(
				'name' => __( 'Klant mag zelf kiezen uit bovenstaande greenfees', 'rwmb' ),
				'id' => "{$prefix}keuze_greenfees",
				'type' => 'checkbox',
				// Value can be 0 or 1
				'std' => 0,
			),`

**Comment by rilwis** [comment]
@jeroensijbom Do you mean the `std` value is not working? I tested with that field and it works.
