### ISSUE TITLE
Wrong javascript urls when using inside a theme with child theme

### ISSUE THREAD

**Issue by ibobo** [rilwis/meta-box#1080]
I was having strange issues with a theme I bought, the theme incorporates meta-box into the "core/vendor" path, and I created a child theme as recommended. When using Visual Composer some components didn't work correctly, and I found out the problem was that some of the meta-box javascript are not correctly loaded.
The browser is trying to load js files from:
https://www.prettyflowers.it/wp-content/themes/themes/kraft/core/vendor/meta-box/js/color.js?ver=4.8.7
that's obviously wrong.

To fix that I changed `inc/loader.php:83` to use `get_template_directory_uri()` instead of `get_stylesheet_directory_uri()`, because the latter was returning a path with a `/.` at the end that made the code fail. In general I think your plugin will be used by parent themes so this solution should work.

**Comment by rilwis** [comment]
Hi, looks like the embeded version of Meta Box is 4.8.7 which is quite old. We made some improvements for the loader. Can you try updating it to the latest version 4.10.4?

**Comment by rilwis** [comment]
So, did you resolve this problem?

I've just looked at the bug again and I can't see why `get_template_directory_uri()` works while `get_stylesheet_directory_uri()` doesn't. Also, if your theme include Meta Box in its core, the link seems to be correct to me.

**Comment by ibobo** [comment]
No, the problem is still there. I think this surfaces because I use a child theme with the parent containing meta-box, maybe when using the main theme without a child all works since other customers don't complain.

**Comment by rilwis** [comment]
I've just tried again with a parent theme included Meta Box and a child theme with a color field registered. It works without any problem. This is how it appears to me:

http://prntscr.com/eftvlz

By the way, the function `get_stylesheet_directory_uri()` is used to get the `themes` directory ([see here](https://github.com/rilwis/meta-box/blob/master/inc/loader.php#L46) - notice the `dirname`). It has to work with both child theme and parent theme.

A stupid question, is the included version of the plugin the latest version?
