### ISSUE TITLE
File upload meta/fields don't work any more since last update...

### ISSUE THREAD

**Issue by jimshell** [rilwis/meta-box#1081]
Hello,

I've been facing a problem since the last plugin update: file upload meta don't work any more...
I checked and checked in the docs, tried some changes in my code - which was working fine until the update - and could do nothing, which is very frustrating.

Here is what I get - whatever the type: file_upload, media, image_advanced, file_advanced... I can't see where the problem comes from... Instead of the WP style UI, i just get empty text inputs in the meta box, weird...

Many thanks for you help in advance!

**Comment by funkedgeek** [comment]
Can you post the code for your meta boxes and where the code is located?  Also is this the plugin or are you using a theme with Meta Box built in?

**Comment by jimshell** [comment]
Hello! Thank you for your quick reply! :)

Here is my code:

```
// Custom Fields / Meta Boxes
function jmh_property_meta_boxes($meta_boxes) {
	$prefix = 'jmh_';

	$meta_boxes[] = array(
		'title'		 => __('Caractéristiques', 'jmh'),
		'post_types' => 'property',
		'fields'	 => array(
			array(
				'id'	=> $prefix . 'surface',
				'name'	=> __('Surface', 'jmh'),
				'type'	=> 'text',
			),
			array(
				'id'	=> $prefix . 'nbrooms',
				'name'	=> __('Nombre de Chambres', 'jmh'),
				'type'	=> 'number',
				'min'	=> 1,
			),
			array(
				'id'      => $prefix . 'energy',
				'name'    => esc_html__( 'Classe énergétique', 'jmh' ),
				'type'    => 'radio',
				'options' => array(
					'A' => 'A',
					'B' => 'B',
					'C' => 'C',
					'D' => 'D',
					'E' => 'E',
					'F' => 'F',
					'G' => 'G',
				),
			),
		),
	);

	$meta_boxes[] = array(
		'title'		 => __('Description', 'jmh'),
		'post_types' => 'property',
		'fields'	 => array(
			array(
				'name' => esc_html__( 'Description', 'jmh' ),
				'desc' => esc_html__( 'Description du bien', 'jmh' ),
				'id'   => $prefix . 'description',
				'type' => 'textarea',
				'cols' => 20,
				'rows' => 4,
			),
		),
	);

	$meta_boxes[] = array(
		'title'		 => __('Visuels', 'jmh'),
		'post_types' => 'property',
		'fields'	 => array(
				'name'             => esc_html__( 'Visuels', 'jmh' ),
				'id'               => $prefix . 'visuels',
				'type'             => 'media',
		),
	);


	return $meta_boxes;
}
add_filter('rwmb_meta_boxes', 'jmh_property_meta_boxes');
```

The first metaboxes/fields work fine, as expected, unfortunately not the last, media one. I tried and change for all the other media/file upload settings, with no luck.

The above code has been right in my functions.php file since the first dev stages, and I had no issue with this...

And this is the plugin: I installed it a few days ago - I began a new project last week - and it worked like a charm... until the latest update.

Many thanks for your help!

Cheers,
Jim

**Comment by funkedgeek** [comment]
Please use file_advanced for now

**Comment by jimshell** [comment]
I've reverted back to `file_advanced`, which was my original setting...
No luck...
I will try and find the changes in the latest release that could cause the media metaboxes not to show up...

**Comment by funkedgeek** [comment]
I recommend redownloading the plugin.  Sounds like some of the files might
be missing

**Comment by jimshell** [comment]
Hello, I've just tried that.
Uninstalled the plugin completely, then re-installed it and re-enabled it.
No change whatsoever...
Unless something in the latest release is missing, all the files are there and the intallation seems all fine...
This is weird.

**Comment by rilwis** [comment]
Oh, just found the problem. It's the incorrect syntax. The last meta box should be like this:

```php
$meta_boxes[] = array(
		'title'  => __( 'Visuels', 'jmh' ),
		'fields' => array(
			array(
				'name' => esc_html__( 'Visuels', 'jmh' ),
				'id'   => $prefix . 'visuels',
				'type' => 'file_advanced',
			),
		),
	);```

E.g.: remember to wrap your field into an array. Your code makes Meta Box think there are 3 fields :)

**Comment by jimshell** [comment]
Oh thank you! I actually did not notice that! I must have deleted the inner `array(...)` inadvertently (can't see when, I can't remember when I would have modified my code after the upgrade...)

Anyway, once written the proper way, everything is working back as expected!

Thank you very much!
Jim
