### ISSUE TITLE
allow functions in meta box validation

### ISSUE THREAD

**Issue by ThomasSultana** [rilwis/meta-box#1082]
We are using the meta box plugin as a booking plugin. Part of the problem is we need to validate if a booking is allowed before having the user create the booking. To do this we would want to validate the check in, check out and property field dynamically.

We looked into the javascript validation plugin options and noticed that the remote option has an option like this: 
`
data: {
          username: function() {
            return $( "#username" ).val();
          }
        }
`

The php validation array allows us to set `"username" => "data"`, however when we type in `"username" => "function()...."` it will try send the function value as a string. This is understandable because the array is encoded into an element and never is able to know its a function. Im proposing a better way to provide these options. Could we introduce an element where we specific the validations rules via javascript?

**Comment by rilwis** [comment]
You're right about running a JS code passed via PHP. With the current enqueuing system from WP, it's kind of impossible to do that.

If you have any idea to resolve this problem, please let us know. We're happy to merge that!
