### ISSUE TITLE
rwmb_meta_boxes is triggering before init

### ISSUE THREAD

**Issue by limikael** [rilwis/meta-box#1083]
It seems that the `rwmb_meta_boxes` action is triggering before the `init` action.

This causes a problem, since I'm using the `init` action to load translations using `load_plugin_textdomain`, and hence the translations will not be available when I'm creating the meta boxes. Is this by design? If so, at which point is it recommended to call `load_plugin_textdomain` when using meta-box?

Currently I'm just calling `load_plugin_textdomain` straight from the main file, not as part of an action, and this seems to work. But it also feels like this is not the "right" way of doing it.

**Comment by rilwis** [comment]
Looks like we already resolve this issue. Not sure why Github still shows it up.

I will recap my previous answer here:

1. It's safe to call `load_plugin_textdomain` right in the plugin main file.
2. In case you need a hook, it's always recommended to use `plugins_loaded` hook, not `init`. `plugins_loaded` fires when all plugins are loaded and is safe to load plugin translation. `init` means initializing the actual work, so it's not recommended.

**Comment by limikael** [comment]
@rilwis You are absolutely right, it is resolved. Sorry if i was issue bombing.
