### ISSUE TITLE
Values not displaying on front end in template

### ISSUE THREAD

**Issue by karapally** [rilwis/meta-box#1084]
I'm having an issue where I can't get the values of my custom fields to display on the front end in my template. 

I'm using a child theme, and added the following to my child theme's functions.php file:
`require get_stylesheet_directory() . '/meta-box/meta-box.php'; `

Then, I added the following to create a meta box:
```
add_filter( 'rwmb_meta_boxes', 'trek_register_meta_boxes' );
function trek_register_meta_boxes( $meta_boxes ) {
    $prefix = 'rw_';
    $meta_boxes[] = array(
        'id'         => 'about',
        'title'      => __( 'About Trek', 'textdomain' ),
        'post_types' => array('page' ),
        'context'    => 'normal',
        'priority'   => 'high',
        'show_names' => false,
        'fields' => array(
            array(
                'name'  => __( 'Section Title', 'textdomain' ),
                'desc'  => '',
                'id'    => $prefix . 'about-title',
                'type'  => 'text',
            ),
            array(
                'name'  => __( 'About', 'textdomain' ),
                'desc'  => '',
                'id'    => $prefix . 'about-text',
                'type'  => 'wysiwyg',
            ),
        )
    );
    return $meta_boxes;
}
```

Everything seems to be working fine in the Admin, but when I add the custom field value to my theme, nothing displays. I'm using this to add it to my theme:
`<?php echo rwmb_meta('about-title', '199'); ?>`

Any idea how to fix this? Thanks

**Comment by rilwis** [comment]
You need to add the **prefix** when you call the meta in the frontend as you used it in the backend.

So the code should be:

```
echo rwmb_meta( 'rw_about-title', 199 );
```

If you don't want to use prefix, just remove it from the register function.
