### ISSUE TITLE
fields are hidden when used with WPML

### ISSUE THREAD

**Issue by the-specialist2005** [rilwis/meta-box#1085]
the meta box don’t show the fields in the secondary language while in the primary language it works.
![2017-03-14 14_23_06-new notification](https://cloud.githubusercontent.com/assets/9333195/23901028/30d1ec6a-08c4-11e7-925f-7795abf86955.png)

**Comment by rilwis** [comment]
Hi @the-specialist2005 

This is actually not a bug, but a feature request #1058 . So:

- Fields are translated are visible
- Fields are copied are disabled and visible
- Fields are not translated are hidden

**Comment by the-specialist2005** [comment]
Thanks alot

**Comment by the-specialist2005** [comment]
After marking all the metaboxes fields as translatable in the main language, i still have the same issue where in the second language only three out of 6 custom fields are visible, the other three are still hidden check this screenshot
![2017-03-14 15_05_25-edit post - real estate solutions wordpress](https://cloud.githubusercontent.com/assets/9333195/23901950/f947b6b8-08c7-11e7-812b-5db81d75b1da.png)
