### ISSUE TITLE
Search in Admin Columns

### ISSUE THREAD

**Issue by boethius** [rilwis/meta-box#1086]
I'm not able to use the search box at the top right to search the custom fields in the admin columns. Is it my shoddy implementation/going mad or this actually not implemented? 

/thanks

**Comment by rilwis** [comment]
Hi @boethius ,

The extension has no searching feature at the moment. I and my devs will work on sortable columns and searchable soon.

**Comment by boethius** [comment]
@rilwis, any update on this? 👍

**Comment by rilwis** [comment]
Hi @boethius ,

Just updated the extension to version 1.1. Now you can search if you add:

```php
'admin_columns' => array(
    'position' => 'after title',
    'searchable' => true, // THIS.
),
```

Please update.

**Comment by boethius** [comment]
@rilwis very cool, thank you so much!

I've enabled this, but it will not search. Are there any types that the search is limited to?

```array(
                'name'  =>  __('Classes', TEXT_DOMAIN ),
                'desc'  =>  __('Select a class', TEXT_DOMAIN ),
                'id'    =>  $prefix . 'class',
                'type'  =>  'post',
                'multiple' => false,
                'admin_columns' => array (
                    'position'  => 'after registration_student',
                    'sort'  => true,
                    'searchable' => true, 
                ),
                'field_type' => 'select_advanced',
                'post_type' => array( 'product' ),
                'query_args' => array(
                    'post_status'   =>  'publish',
                    'posts_per_page' => -1,
                    'tax_query' => array(
                        array(
                            'taxonomy' => 'product_cat',
                            'field' => 'slug',
                            'terms' => array('matriculation-fee'),
                            'operator' => 'NOT IN',

                        )
                    ),
                ),
            ),```

**Comment by rilwis** [comment]
Ah, the search function will search for **meta value**. In your case, the `post` field is saved with post IDs, so if you enter post ID, you will find them. It doesn't search for post title, though.
