### ISSUE TITLE
email img buttons then hide if not in use

### ISSUE THREAD

**Issue by juneink** [rilwis/meta-box#1087]
Hello,
I was hoping someone could help me with some code.

I need to add email img buttons with the mailto:etc; then hide the other email img fields if they are not used or filled out on the wp side. I am using multiple clones.

 I would need the whole php line removed to hide the email img if text field is not in use.
//Code example 

*echo '<*div *class="email1"><*a *href="..mailto:'.*$contact_main['*email_1'].'">Email</*a> ', '</*div>';

Thank you
JUNEINK

**Comment by rilwis** [comment]
I'm not sure if that's related to the plugin. Please ask for help on [StackOverflow](https://stackoverflow.com/).
