### ISSUE TITLE
Duplicate Meta boxes

### ISSUE THREAD

**Issue by chrisbrockhus** [rilwis/meta-box#1093]
In a Stratus wordpress template I have duplicate meta boxes I can't get rid off.
Has anyone an idea what this causes?

![schermafbeelding 2017-03-22 om 10 30 53](https://cloud.githubusercontent.com/assets/14179060/24191149/203f0dce-0eeb-11e7-933b-442f68115a4f.png)
![schermafbeelding 2017-03-22 om 10 30 28](https://cloud.githubusercontent.com/assets/14179060/24191150/2044d718-0eeb-11e7-892b-c7599ab40929.png)

**Comment by rilwis** [comment]
The UI looks quite strange to me. Can you show me the list of activated plugins and the admin menu (screenshots)?

**Comment by chrisbrockhus** [comment]
This is on a Stratus Wordpress (template) site with Meta Box preinstalled on a local machine in MAMP.
![schermafbeelding 2017-03-23 om 10 02 29](https://cloud.githubusercontent.com/assets/14179060/24239880/e237c23a-0faf-11e7-8f46-b10820676264.png)

**Comment by rilwis** [comment]
Where do the meta boxes appear? Can you show me a full screenshot?

**Comment by chrisbrockhus** [comment]
![screen_b](https://cloud.githubusercontent.com/assets/14179060/24240084/b11a7c5a-0fb0-11e7-9afe-3b3d45110dfe.png)
![screen_a](https://cloud.githubusercontent.com/assets/14179060/24240085/b1365b00-0fb0-11e7-8b09-e5ce007030be.png)

Do you mean this?

**Comment by chrisbrockhus** [comment]
![screen_c](https://cloud.githubusercontent.com/assets/14179060/24240153/e5e2adfe-0fb0-11e7-89d4-3e9e7fcca923.png)

**Comment by rilwis** [comment]
That's right.

I think the duplicated meta boxes causes by the JS that theme users to reorder them. It's a custom JS made by the theme author. Please contact with the theme author to check this. I will always be here if you need any help.

**Comment by chrisbrockhus** [comment]
OK thanx, I will contact him
