### ISSUE TITLE
php error autoloader  and walker

### ISSUE THREAD

**Issue by thatvideowebguy** [rilwis/meta-box#1094]
Hi all, 

I've got a strange php error on backend and front end since the last update

autoloader and walkers are pointed 

Any idea ?

thanks
 
FastCGI: server "/var/www/myurl/cgi-bin/php5.6.external" stderr: PHP message: PHP Warning:  file_exists(): File name is longer than the maximum allowed path length on this platform (4096): /htdocs/wp-content/plugins/meta-box/inc/walkers/9ct82mfugb-tve0r4sb3yeqynz8k09300ozeyjihh1--cp9ia8rpdotxlf07-zpke6s72hvxyaw8aw0w2-1cntv-p31lcgsak3i9jtky92tkgefe1k92t7fcgg-x9gkzwgp2-u6qf38k07d67hccb7f2g-yaifvxe9r7dvq5l50ibfmi9f0z0mj-9zn8exfp5az1kenufkjaexcgn5kuntv-n31lc80iw-1ejhl4z0bhabyo9dpcjho8l5ccegus3sqc0lgkf38k0hoe74d2k7fcg5-xx7d5n5mpntd-i3m4u19a31r8034cg5-x184pllp2ntn-kcanhvei9-s8ahh5nda4c-srkfz407bdt1m0el8h0pn3-cnw9tg15qfh3f02rvg3o3m7ixjtc6ofgvi7m41i9zjlb-20dmmbicbxdzsp4q822u4c0u81p-ia3ir307suqyzxdhsw4sp0iv4ay30knv9i2fe5-urba1exd7skf-18114qq317b9xt1b0z1hg5gbtkjasa61n75yuit6zkagcgwgp2au6cg-2k09vlf63-bgq5zbx0ebut-6n-jki3m-x6amrl49rrzui-9jdc523i7sqz0ighpvnmwrfhkf52nhewfqa4c7srvf11zum-9yji5mrd47qc0ogk2htkaefd2jt02hkhht-bg9yhes650nmcmb8-gg0h3fy2rvg2k3mhzgjo7dn9qev2lds4pmc5j4puk7fugb-tvezq4s58eej9m0c4bgvs-7tcgev2id87kcqw-1e1gun-8j-icm9jw5utbd4af3xk02md0oe1zum-91s2vmrl46rrxvgbgqjao3-4..., referer: http://myurl/wp-cron.php?doing_wp_cron=1490178084.2791290283203125000000

Warning: file_exists(): File name is longer than the maximum allowed path length on this platform (4096): /htdocs/wp-content/plugins/meta-box/inc/3y4-ibc7imvk03e7tyocrjqwfbcm56nkm-g8i-hc4s1il7nkf5ty9iy5bbpi3wde3y63c4i1dlmltwfa5coe66i-kpvku54414iph6qxc31iqxq5r7exhahgbakksk5agptyaty5tbuik-fgbqu2icqvfakksk98a-va6ay54bwctqkrlyo3jcf1apvht-dcvnwca8qgpb1sjxhagb5f26985bnxr24ebqu2ibqvtbrask4brai4c5o--dvcq4fitai596o7kpigy-q7tylcrjq6cz1mkdyzi-6d5ig5tbuik-fgbqu2icqvf9vflx78w4o2jbf1bskdsoe630tphmi-ow26866or4jvd0gh3vnaky164y4fi-i45pqmo-3bsgifk6gahdjoo-68ywf59kcybzjos6dxbyvcvjng8v3zpkc5vztp36tkjzj2s7dttwcfvhl4ibtfaxf6i6jc2k5-1zjwsv2854ulppt4hphcz-e-4vu2ibqvtbpesk0ir8ug5hicjbl1j7q7tyocrjqxkbccx-2bz6hz1bozdwufu-wfrad3k-gxdqlvt-devnwckiyndjnr55xtuvt1ivujn-gbkye61y62k08gbskaso965xwc9iyk4dnvt2dcudt7ir-1tbiik24ypwr2avphckwcyykr26t89jgzamwk0y162y4fiae45eh1oex8r-5x6dqxcs37jyhdtqeph6qzc31i15dt14gx68g7eshkx3wcxdix6ac1apsgq78iixic-ifncdkvab-eqplyvh84dbcrt26vixwc9iy-uu1vt-dbvn2fikqg4l4s-z16ixqck7cyicvfax6bvqs4k3kd3qnio-966oge89y5bbpi3wde3y63c4i in /htdocs/wp-content/plugins/meta-box/inc/autoloader.php on line 168

**Comment by rilwis** [comment]
Looks like your site is hacked. File name is changed. Please scan your website to check for malware. [Here](http://www.deluxeblogtips.com/protect-wordpress-websites-from-malware/) is a good guide.

**Comment by thatvideowebguy** [comment]
Hi, 
I spoked to wordfence team, and they told me that all looks fine.
Any idea where this error came from ?
I'm using WPML 

thanks again for your time

**Comment by thatvideowebguy** [comment]
here's some news from wordfence team
I'm not the only one 
We have spent some time looking at this and are happy that there is no malware present in your site. If you google the error, you can see that you are not alone:

https://www.google.co.uk/search?q=meta-box%2Finc%2Fautoloader.php%20on%20line%20168&*&rct=j

Looking at it, we think that there is something wrong with the way the files or filenames are getting mapped into memory in that plugin, but this is something their developer would need to look at.

**Comment by rilwis** [comment]
Hi,

The thing is the file name is changed to something very weird. You can see list of files of the plugin here: https://github.com/rilwis/meta-box/tree/master/inc/walkers

There's nothing like you shown.

I'd suggest you remove all the plugin files and re-install it from WordPress.org.

**Comment by thatvideowebguy** [comment]
I did it but same problem

 

De : Tran Ngoc Tuan Anh [mailto:notifications@github.com] 
Envoyé : mardi 28 mars 2017 10:00
À : rilwis/meta-box <meta-box@noreply.github.com>
Cc : thatvideowebguy <aurelien.bonsignore@gmail.com>; Author <author@noreply.github.com>
Objet : Re: [rilwis/meta-box] php error autoloader and walker (#1094)

 

Hi,

The thing is the file name is changed to something very weird. You can see list of files of the plugin here: https://github.com/rilwis/meta-box/tree/master/inc/walkers

There's nothing like you shown.

I'd suggest you remove all the plugin files and re-install it from WordPress.org.
