### ISSUE TITLE
usage of rwmb_{$field_type}_value filter with group

### ISSUE THREAD

**Issue by chrisbataille** [rilwis/meta-box#1099]
Hello,

i'm trying to override the meta field value before saving and trying to use the rwmb_{$field_type}_value filter.

My sample code is the following : 

```php
add_filter( 'rwmb_meta_boxes', 'sa_test' );
function sa_test(){
	$mb[] = array(


		'id'         => 'release',
		'title'      => __( 'Release Infos', 'sa_mb' ),
		'post_types' => array( 'post'),
		'context'    => 'normal',
		'priority'   => 'high',
		'fields' => array(
			array(
				'name'  => __( 'Release', 'sa_mb' ),
				'id'    => 'sarelease',
				'type'  => 'group',
				'clone' => false,
				'sort_clone'  => false,
				'collapsible' => false,
				'fields'=> array(
					array(
						'name'  => 'Link',
						'id'    => 'link',
						'type'  => 'url',
						'columns'=> 12,
						'size'  => 45

					)
				)
			)
		)
	);
	return $mb;
}
```

with the following filter : 

```php
add_filter('rwmb_url_value', 'save_sa_url');
function save_sa_url($new, $field, $old){
	$new = 'http://sa.com';
	error_log('old : '.$old.', new : '.$new);
	return $new;
}
```

the filter is never called.

But when i don't encapsulate my field into a group then it works.

I bought the plugins this week so i'm all up to date with core plugins and extensions.

**Comment by chrisbataille** [comment]
For the time being i'm going to create a custom Field to be able to progress on my work, but i do hope i can get a fix any time soon.

**Comment by rilwis** [comment]
Hi,

The filter fires only for the group field in this case. It doesn't fire for the sub-fields. So I think you can hook into the group and use a simple loop to find the URL field and update its value.
