### ISSUE TITLE
Last update breaks my taxonomy field.

### ISSUE THREAD

**Issue by enginne** [rilwis/meta-box#1100]
Hello.

I have a custom post type with a custom taxonomy.

I retrieve the terms of the custom tax with this code:

```
global $post;

$terms1 = rwmb_meta( '_theme_prefix_portfolio_materials_nav_items',  $post->ID );

if (!empty($terms1 )) {

	$content_ids1 = '';
	foreach ( $terms1 as $term1 )
	{
		$content_ids1 .= sprintf(
			'%2$s,',
			get_term_link( $term1, 'materials' ),
			$term1->term_id,
			$term1->term_id
		);
	}
	$content_ids1 .= '';

	$mat_terms = $content_ids1;

	// Make an array from a formatted string, you can use the explode PHP function that takes a delimiter and a string, and returns an array.
	$mat_array = explode( ',', $mat_terms );
```

and then put the resulting array in a custom WP_Query:

```
$portfolio_args = array (
	'post_type'		=> 'works',
	'tax_query'              => array(
		array(
			'taxonomy'	=> 'materials',
			'field'		=> 'term_id',
			'terms'		=> $mat_array,
		),
	),
	'posts_per_page'=> 6,
	'paged'			=> $paged,
	'post__not_in'	=> get_option( 'sticky_posts' ),
);

$portfolio_posts = new WP_Query( $portfolio_args );
```

Everything worked with meta box 4.10.3 and below, after last update ( 4.10.4 and 4.11) it gives me a error in the frontend and no post is showing from the custom query:

`
Notice: Trying to get property of non-object in /Users/…/_library/parts/portfolio/masonry.php on line 37
`
and
`
Notice: Trying to get property of non-object in /Users/…/_library/parts/portfolio/masonry.php on line 38
`

These are the two lines of error (37 and 38), from the first pice of code that i posted on top:
`
$term1->term_id,
`
`
$term1->term_id
`

I have to rollback plugin to the previous version to work.

Any help?
Sorry for any bad English.
Thanks.

**Comment by enginne** [comment]
I made a typo;

My code worked with meta box 4.10.3. and earlier 

Both the 4.10.4 and 4.11 updates are the ones that break my code.

**Comment by rilwis** [comment]
Can you try changing this line:

```php
$terms1 = rwmb_meta( '_theme_prefix_portfolio_materials_nav_items',  $post->ID );
```

to:

```php
$terms1 = rwmb_meta( '_theme_prefix_portfolio_materials_nav_items',  '', $post->ID );
```

Also, can you post the code that register meta boxes? I think there's a problem in that code.

**Comment by enginne** [comment]
Thanks for the response Rilwis.

After changing the line you recommended i get the same result. Nothing.

This is the code i use to register the meta box:
```
add_filter( 'rwmb_meta_boxes', 'theme_prefix_portfolio_template_metabox' );

function theme_prefix_portfolio_template_metabox( $meta_boxes )
{
	$prefix = '_theme_prefix_';

	$meta_boxes[] = array(
		'id'		=> 'portfolio_page_mb',
		'title'		=> __( 'Portfolio settings', 'theme_text_domain' ),
		'pages'		=> array('page'),
		'fields'	=> array(
			// TAXONOMY
			array(
				'desc'		=> __( 'Select the <b>materials</b> you wish to show.', 'theme_text_domain' ),
				'id'		        => $prefix . 'portfolio_materials_nav_items',
				'type'		=> 'taxonomy',
				'taxonomy'	=> 'materials',
				'class'		=> 'portfolio-mb-nav-items-materials',
                                'field_type'      => 'select_advanced',
				'multiple'   	=> true
			),

			// TAXONOMY
			array(
				'desc'		=> __( 'Select the <b>years</b> you wish to show.', 'theme_text_domain' ),
				'id'		        => $prefix . 'portfolio_years_nav_items',
				'type'		=> 'taxonomy',
				'taxonomy'	=> 'years',
				'class'		=> 'portfolio-mb-nav-items-years',
                                'field_type'      => 'select_advanced',
				'multiple'	        => true
			),
		),
	'only_on' => array(
			'template'		=> array( '_library/template-portfolio.php' ),
		),
	);

	foreach ( $meta_boxes as $k => $meta_box )
	{
		if ( isset( $meta_box['only_on'] ) && ! theme_prefix_maybe_include( $meta_box['only_on'] ) )
		{
			unset( $meta_boxes[$k] );
		}
	}

	return $meta_boxes;

}
```

It crossed my mind i could have messed up the code to retrieve the value in the frontend so i  used the code you provided in metabox.io exactly as is in the docs:
```
$terms = rwmb_meta( 'field_id' );
$content = '';
if ( !empty( $terms ) ) {
    $content .= '<ul>';
    foreach ( $terms as $term ) {
        $content .= sprintf(
            '<li><a title="%s" href="%s">%s</a></li>',
            esc_attr( $term->name ),
            esc_url( get_term_link( $term, 'tax_slug' ) ),
            esc_html( $term->name )
        );
    }
}
echo $content;
```
only changed the first line from:
`$terms = rwmb_meta( 'field_id' );`
to my meta box field_id
`$terms = rwmb_meta( '_theme_prefix_portfolio_materials_nav_items', '', $post->ID );`
but nothing outputs in the echo.

So either i messed big one with this and cant figure were or there's a bug in the 2 latest updates of the plugin since version 4.10.3 and below work fine.

**Comment by funkedgeek** [comment]
can you check and see what is being returned by rwmb_meta?  is it an object or something else?

**Comment by enginne** [comment]
If i use the prior to  4.8.0 code:

`$terms1 = rwmb_meta( '_theme_prefix_portfolio_materials_nav_items', 'type=taxonomy&taxonomy=materials', $post->ID );`

and print_r($terms1); i get:

`WP_Term Object
(
    [term_id] => 18
    [name] => China Ink
    [slug] => china-ink
    [term_group] => 0
    [term_taxonomy_id] => 18
    [taxonomy] => materials
    [description] => 
    [parent] => 0
    [count] => 4
    [filter] => raw
) `

If i use the new method to retrieve the data:
`$terms1 = rwmb_meta( '_theme_prefix_portfolio_materials_nav_items', $post->ID );`

and print_r($terms1); i get:

`231`

In my meta box custom taxonomy dropdown i choose 2 entries from my "Materials" taxonomy, one is "China Ink", which has an category id 18 and the other "Grafitti" which has a category id 231.

It should output both categories like the previous versions of the plugin, but it doesn't.

I may also add that i have this code outside the loop.

If i rollback the plugin to version 4.10.3 and run
`$terms1 = rwmb_meta( '_theme_prefix_portfolio_materials_nav_items', 'type=taxonomy&taxonomy=materials', $post->ID );`

print_r($terms1); gives me an array as expected:

`Array ( [0] => WP_Term Object ( [term_id] => 18 [name] => China Ink [slug] => china-ink [term_group] => 0 [term_taxonomy_id] => 18 [taxonomy] => materials [description] => [parent] => 0 [count] => 4 [filter] => raw ) [1] => WP_Term Object ( [term_id] => 231 [name] => Grafitti [slug] => grafitti [term_group] => 0 [term_taxonomy_id] => 231 [taxonomy] => materials [description] => [parent] => 0 [count] => 2 [filter] => raw ) )`

I'm a bit tired right now but tomorrow i will test this code with a fresh install of WP with twentysixteen theme to see if my custom theme might be the problem.

**Comment by enginne** [comment]
Ok, so i just tested my code with a new WP install and twentysixteen theme and it works.. :( 
So it must be something else with my custom theme.

It still is strange how it works with older versions of the plugin. 

Thanks for the support guys.

**Comment by enginne** [comment]
I just figured it out in case someone else needs it.

It seems the old rw_maybe_include() function i had was to blame. As soon as i used the one in the better-include.php demo everything worked.
