### ISSUE TITLE
Getting single fieldset_text / text_list value

### ISSUE THREAD

**Issue by irmary** [rilwis/meta-box#1101]
Hello,

I have a problem in getting single value for fieldset_text and text_list fields.

For the text_list field like this:

```
array(
   'name'    => esc_html__( 'Title', 'prefix_' ),
   'id'      => "{$prefix}id",
   'type'    => 'text_list',
   'options' => array(
      'My 1' => esc_html__( 'One', 'prefix_' ),
      'My 2' => esc_html__( 'Two', 'prefix_' ),
      'My 3' => esc_html__( 'Three', 'prefix_' ),
   ),
   'clone' => true,
   'sort_clone' => true,
),

```
When I use:

`<?php echo rwmb_meta( 'my_field' ); ?>`

It gives me just the word:

`Array`

When I use

```
$values = rwmb_meta( 'interests' );
echo implode( ', ', $values );
```

I also get just the word Array.

How can I echo just the value of the 'Three' for example?

Thank you!

**Comment by rilwis** [comment]
Because you use `clone`, the value is always an array. Besides, this is the `fieldset_text` and `text_list` which are **list** of text, so their values are also arrays.

You can use the following code to show the values:

```php
$values = rwmb_meta( 'interests' );
if ( ! empty( $values ) ) {
    foreach ( $values as $value ) {
        echo $value['My 1'];
        echo $value['My 2'];
        echo $value['My 3'];
    }
}
```
