### ISSUE TITLE
image_advanced metabox adds unordered list tags when using shortcode

### ISSUE THREAD

**Issue by lbrg** [rilwis/meta-box#1102]
Hi there,

I'm very new with metabox but one problem I can't seem to figure out is when I use image_advanced and a shortcode to display that image, it adds `<ul><li>` tags, yet with every other meta boxes that I've created it renders without any tags.

How do I fix this?

Thank you for your time. 

What I'm using to display images:

            array(
                'name'  => __( 'Post Image', 'textdomain' ),
                'desc'  => 'Primary image',
                'id'    => $prefix . 'mainimage',
                'type'  => 'image_advanced',
            ),

[rwmb_meta meta_key="mb_mainimage"]

**Comment by rilwis** [comment]
Hi,

The shortcode displays list of uploaded images in an unordered list. It's not a bug, but designed to do so. You can simply use CSS to style it whatever you want.

If you want to control the output of the field, you should use your custom code. The instruction is [here](https://metabox.io/docs/get-meta-value/).

**Comment by lbrg** [comment]
Thank you for your help. I wish there was a place I could ask general questions as this plugin has greatly improved my understanding of PHP and learning in general.

**Comment by rilwis** [comment]
You can always ask here or on the support forum at wordpress.org.
