### ISSUE TITLE
Custom oEmbed Size?

### ISSUE THREAD

**Issue by sputnik410** [rilwis/meta-box#1104]
I'm working on a portfolio site right now, and I'm using the oEmbed field in one of my metaboxes to easily embed videos into portfolio pages, however I'd like to have control over the size of the iframe that gets embedded. It seems to default to 500x281, and I can't figure out how to change it, as width and height attributes only seem to work for images. Is this functionality built in right now or do I need to find a workaround?

**Comment by rilwis** [comment]
The size of the iframes actually are not set when using the helper function `rwmb_meta`. When output the iframe in the frontend, it takes the value from global `$content_width`.

To avoid this behavior and set your own size, you can just get the URL of the field (the post meta value) and render it manually:

```php
$url = get_post_meta( get_the_ID(), 'field_id', true );
$args = array(
    'width' => 400,
);
echo wp_oembed_get( $url, $args );
```

**Comment by sputnik410** [comment]
@rilwis That worked perfectly. Thanks!
