### ISSUE TITLE
Problem with tabs

### ISSUE THREAD

**Issue by hazmicz** [rilwis/meta-box#1107]
Hi, i noticed problems with tabs:

1/ tabs defined with icons (icons don't show)
2/ every field defined with "key" shows in every tab

Here is a sample code (2):

```php
'tabs' => array(
		'tab1' => __('Title 1',TEXTDOMAIN),
		'tab2' => __('Title 2',TEXTDOMAIN),
	),
	'fields' => array(
		array(
			'id'   => "{$prefix}phone",
			'type' => 'text',
			'tab' => 'tab1'
		)
	)
```

With this code, the field shows up in every tab. Wordpress is using only meta-box plugin with this extension and Polylang.

**Comment by truongwp** [comment]
Thanks, @hazmicz,
The second problem occurs when you only register fields for one tab.
And the first problem, can you show your code? Please make sure that you followed this: https://metabox.io/docs/meta-box-tabs/#section-usage

**Comment by rilwis** [comment]
Thanks. This bug is fixed in [Meta Box Tabs](https://metabox.io/plugins/meta-box-tabs/) v1.0.2. Please update.
