### ISSUE TITLE
Cloned button in group has same id and name as previous

### ISSUE THREAD

**Issue by chromeo** [rilwis/meta-box#1108]
I have a group of 2 text fields and one button field. When I clone the group the text fields get a proper index (e.g.: prefix_first_text_field[0], prefix_first_text_field[1]), but the button does not, both are id="sg_address_query". The name attribute gets set to an indexed version, name="sg_address_group[0][sg_address_query]", but the next button has the exact same name.

My (partial) meta_box code:
```php      
    array(
        'name'       => '',
        'id'         => "{$prefix}address_group",
        'type'       => 'group',
        'columns'    => 12,
        'desc'       => 'Add another address',
        'tab'        => 'summary',
        'clone'      => true,
        'sort_clone' => false,
        'fields'     => array(
          // TEXT - House number
          array(
            'name'    => __( 'House Number', 'meta-box' ),
            'id'      => "{$prefix}house_number",
            'desc'    => __( 'ex: "2324" - used to query the nwmls table for units and statistics. Add more if the building has more than one address, as in the case of 2200 Westlake.', 'meta-box' ),
            'type'    => 'text',
            'columns' => 4,
            'clone'   => false
          ),
          // TEXT - Street name
          array(
            'name'    => __( 'Street Name', 'meta-box' ),
            'id'      => "{$prefix}street_name",
            'desc'    => __( 'ex: "1" (not "1st"), or "Terry" - also used to query the nwmls table for units and statistics. Note - if you add more house number fields, add another of this one too.', 'meta-box' ),
            'type'    => 'text',
            'columns' => 4,
            'clone'   => false
          ),
          // BUTTON - Address Query
          array(
            'name'    => __( 'Address Query', 'meta-box' ),
            'id'      => "{$prefix}address_query",
            'class'   => 'add-building-id',
            'type'    => 'button',
            'std'     => 'Search for Active Listings',
            'columns' => 4,
            'clone'   => false
          ),
        ),
      ),
```
And the result for both:
```html
<div class="rwmb-input ui-sortable">
    <a href="#" id="sg_address_query" class="rwmb-button  button hide-if-no-js" name="sg_address_group[0][sg_address_query]">Search for Active Listings</a>
</div>
```
Possibly a related issue, the labels for the cloned text fields have the same `for` attribute as well, meaning they are not indexed to match the indexed text input.

Am I initializing these incorrectly?

**Comment by funkedgeek** [comment]
Name doesn't actually do anything anyway.  The button renders as a link, so name isn't actually used.  What are you using the button for?

**Comment by chromeo** [comment]
I'm triggering an ajax script that includes data from the two text fields.
I have optional text fields to include in the query, hence the cloning
operation. But the non-unique id on the button is chucking a wobbly in my
script.


Gary Darling

**Comment by funkedgeek** [comment]
It's not changing because the button is a link and not an actual input.  Our cloning code only targets inputs to change the id.  I'll look into fixing this

**Comment by funkedgeek** [comment]
Fixed.  Button is an actual button element now
