### ISSUE TITLE
Can't save meta box field on camel case CPT 

### ISSUE THREAD

**Issue by bke-daniel** [rilwis/meta-box#1109]
Hey everyone,  

first of all, great work you did with the Plugin! Even though I found some possible bug / enhancement. Consider this:
```php
class Test
{

    /**
     * @const string
     */
    const WP_POST_TYPE = 'CamelCase';

    /**
     * Test constructor.
     */
    public function __construct()
    {
        add_action('init', [$this, 'registerCustomPostType']);
    }

    /**
     * Method registers custom post types
     */
    public function registerCustomPostType()
    {
        register_post_type(
            self::WP_POST_TYPE,
            [
                'label'  => 'CamelCases',
                'public' => TRUE,
            ]
        );
    }
}

$Test = new Test();


add_filter('rwmb_meta_boxes', 'registerMetaBoxCamelCase');

/**
 * Method registers a meta box
 *
 * @param $meta_boxes
 *
 * @return array
 */
function registerMetaBoxCamelCase($meta_boxes)
{
    $meta_boxes[] = [
        'id'         => 'camel-case-id',
        'title'      => __('Weitere Informationen'),
        'post_types' => [Test::WP_POST_TYPE],
        'context'  => 'side',
        'priority' => 'high',
        'fields'   => [
            [
                'name'        => __('Camel Case name'),
                'id'          => 'camel-case-id-input',
                'type'        => 'text',
                // Default value (optional)
                'std'         => __(''),
                // CLONES: Add to make the field cloneable (i.e. have multiple value)
                'clone'       => FALSE,
                // Placeholder
                'placeholder' => __(''),
                // Input size
                'size'        => 20,],

        ],
    ];

    return $meta_boxes;
}
```

Under these circumstances it is not possible to save the input field, but it is still displayed. If you enable 'custom-fields' on the WP CPT (Custom Post Type) and change the value manually it'll work like a charm.
The problem itself lies within the camel case CPT ID, WordPress itself [sanitizes](https://github.com/WordPress/WordPress/blob/master/wp-includes/post.php#L1113) the post type name before registering it.
Surely, I can sanitize the name on my own and therefor it's not directly a bug. Would love to hear your thoughts about it being a bug or maybe an enhancement.

Cheers,
Daniel

P.S.: Sorry for the title, but with it I'll try to make sure that someone's going to find help if he's trying to fix this in his project.

**Comment by rilwis** [comment]
Hi @bke-daniel,

Interesting thing! I've never experienced with this one, cause I always "think" the post type slug should be something_like_this.

The problem is Meta Box uses `save_post_{$post_type}` hook, which is sanitized by WP. I've just added a little enhancement to cover this issue :)

**Comment by bke-daniel** [comment]
Very cool, @rilwis! Thank you very much! :) 👍
