### ISSUE TITLE
Admin bar overlaps calendar

### ISSUE THREAD

**Issue by d2roth** [rilwis/meta-box#1112]
Basically, the issue is that the admin bar overlaps the top line of the calendar.

To reproduce the issue you need to make the calendar go above the input instead of below it. Here is a screenshot of the bug: http://prntscr.com/f1fuzf. 

Now I did find some interesting things, First off the bug only shows up if the calendar goes above the input. Secondly, The calendar only will go above the input at specific screen heights and scroll positions. third, not all screen heights trigger the bug. For example, a screen height might trigger the bug but then making the screen taller/shorter may remove the bug or visa-verse.

This is the code that I am using to register the metabox:
```PHP
$meta_boxes[] = array(
            'id' => self::$cpt . '_extra_fields',
            'title' => __('Extra Information'),
            'post_types' => array(self::$cpt),
            'context' => 'normal',
            'priority' => 'high',
            'fields' => array(
                array(
                    'name' => __('Start Date'),
                    'id' => $prefix . 'start_date',
                    'type' => 'datetime',
		    'timestamp'=>true,
                    'desc' => 'When does this event start?',
                ),
                array(
                    'name' => __('Link (optional)'),
                    'id' => $prefix . 'link',
                    'type' => 'url',
                    'desc' => 'Where can people find out more about this event?',
                ),
            ),
        );
        return $meta_boxes;
```
Registered with:
```PHP
add_action('rwmb_meta_boxes', array($this, 'register_meta_boxes'));
```

My thought is to change `z-index: 9 !important` to `z-index: 100000 !important;` in `css/datepicker.css` line 4. That would bring it above the admin bar. Would there be any other solution?

Thanks,

**Comment by funkedgeek** [comment]
How did you even make it go above the input and why would you want to?

**Comment by d2roth** [comment]
I don't intend for the calendar to be above the input, nor do I really want that effect. The problem is that JavaScript is automatically repositioning the calendar where there is space. Since the calendar can't fit fully on the screen below the input, and it fits above, the calendar is going above.

So basically this is a JavaScript bug in the positioning logic which makes the calendar appear behind the admin bar. My solution is more of a patch than a solution in that the calendar positioning logic should account for the admin bar.

**Comment by rilwis** [comment]
I think that's a problem we need to fix. As the positioning job is taken care by jQueryUI library, we can't (or shouldn't) modify the JS part, but making a small change to `z-index` for the date picker makes sense. @funkedgeek can you handle this?

**Comment by funkedgeek** [comment]
Please try the latest version on github

**Comment by d2roth** [comment]
@funkedgeek Sorry for the delay, I just got to testing this again and grabbed the latest version from GitHub and found the bug still is there. I see you raised the z-index to 5000 but the admin bar is at z-index: 99999 so the calendar is still covered. Just so the calendar works I have changed line 4 of datepicker.css to z-index: 99999.
