### ISSUE TITLE
Image advanced requires "shift" to select multiple

### ISSUE THREAD

**Issue by Quaked** [rilwis/meta-box#1115]
How do I set it up so I don't need to hold shift to select multiple images? Default behavior in WP when selecting multiple images is to just click on the ones you want, not shift+click. See "insert media, gallery" for reference.

Edit: This 'works' as an ugly work-around, but I'd rather find out how to implement this the right way..

```javascript
wp.media.view.Attachment.prototype.toggleSelectionHandler = function( event ) {
    var method = 'between';
    if ( event.shiftKey ) {
        method = 'between';
    } else {
        method = 'toggle';
    }

    this.toggleSelection({
        method: method
    });
};
```

Edit2: Okay so I found out that altering https://github.com/rilwis/meta-box/blob/master/js/media.js#L382 to ```multiple: 'add',``` works, can this be added somehow in image-advanced.js in some sort of extend?

**Comment by Quaked** [comment]
Okay so I think I managed to extend it "properly", however I'm sure this needs fixing. But it works!

**image-advanced.js**
```javascript
window.rwmb = window.rwmb || {};

jQuery( function ( $ ) {
	'use strict';

	var views = rwmb.views = rwmb.views || {},
		MediaField = views.MediaField,
		MediaItem = views.MediaItem,
		MediaList = views.MediaList,
		MediaButton = views.MediaButton,
		MediaButtonExt,
		ImageField;

	MediaButtonExt = views.MediaButton = MediaButton.extend( {
		events: {
			'click .button': function () {
				// Destroy the previous collection frame.
				if ( this._frame ) {
					//this.stopListening( this._frame );
					this._frame.dispose();
				}

				this._frame = wp.media( {
					className: 'media-frame rwmb-media-frame',
					multiple: 'add',
					title: i18nRwmbMedia.select,
					editing: true,
					library: {
						type: this.controller.get( 'mimeType' )
					}
				} );

				this._frame.on( 'select', function () {
					var selection = this._frame.state().get( 'selection' );
					this.controller.get( 'items' ).add( selection.models );
				}, this );

				this._frame.open();
			}
		},
	} );
	
	ImageField = views.ImageField = MediaField.extend( {
		createList: function () {
			this.list = new MediaList( {
				controller: this.controller,
				itemView: MediaItem.extend( {
					className: 'rwmb-image-item',
					template: wp.template( 'rwmb-image-item' ),
					initialize: function( models, options ) {
						MediaItem.prototype.initialize.call( this, models, options );
						this.$el.addClass( this.controller.get( 'imageSize' ) );
					}
				} )
			} );
		},
		createAddButton: function () {
			this.addButton = new MediaButtonExt( {controller: this.controller} );
		},
	} );


	/**
	 * Initialize image fields
	 */
	function initImageField() {
		new ImageField( {input: this, el: $( this ).siblings( 'div.rwmb-media-view' )} );
	}

	$( 'input.rwmb-image_advanced' ).each( initImageField );
	$( document ).on( 'clone', 'input.rwmb-image_advanced', initImageField )
} );
```

However, if you decide to 'fix' this, I'd still like to mimic the default WP Gallery functionality more, so your previous selections show up as "selected" when you open the modal to adjust the image selections.. or maybe just make a new image-advanced.js called image-gallery.js (?) @rilwis @funkedgeek (not sure I tagged you but worth a shot).

**Comment by funkedgeek** [comment]
What version of WordPress are you using?  Where is it default to not use shift for selecting multiple?  Using shift is the default for the Add Media button on the latest version of WordPress.

**Comment by Quaked** [comment]
Latest version of WP and using Chrome on OS X. Insert media, gallery - does
not require shift to select images and as described, multiple: 'add' is
used by WP core in gallery (afaik).

**Comment by Quaked** [comment]
I believe this is what I am referring to:
https://core.trac.wordpress.org/browser/tags/4.7.3/src/wp-includes/js/media-views.js#L804
