### ISSUE TITLE
Not getting translations to function

### ISSUE THREAD

**Issue by Quaked** [rilwis/meta-box#1116]
So I figured I'd run my own translations, so I created them using the .POT-file located in /languages. I figured I'd make 'meta-box/meta-box-sv_SE.mo and .po' inside wp-content/languages/plugins to run this "locally". Didn't work. The current locale is sv_SE and there are files for this in the plugin. However they seem to be dated. I've tried just about everything I can think of, regardless what I do the language is English.

Then I replaced the meta-box-sv_SE.mo and meta-box-sv_SE.po in plugins/meta-box/languages with my own, still English. I reverted back to default sv_SE that was included, still English. Specifically I'm looking at 'add' button etc. This is the "wp_localized" variable:

```
var i18nRwmbMedia = {"add":"+ Add Media","single":" file","multiple":" files","remove":"Remove","edit":"Edit","view":"View","noTitle":"No Title","loadingUrl":
...
,"select":"Select Files","or":"or","uploadInstructions":"Drop files here to upload"};
```

Still English for whatever reason. Any ideas? I double checked and "+ Add Media" is specifically translated in the files:
```
#: inc/fields/media.php:21
msgid "+ Add Media"
msgstr "+ Lägg till media"
```

So I have no idea what to do here.

**Comment by rilwis** [comment]
Hmm, I think WordPress has a bug for detecting the Sweden language. I tried switching to Sweden but it always roll back to English.

The locale code for Sweden in the plugin (and in some popular plugins like Jetpack, WooCommerce) is `sv-SE` but somehow WordPress only uses `sv`. Here is the language on translate.wordpress.org:

https://translate.wordpress.org/locale/sv/default/wp-plugins/meta-box

Can you switch to Sweden in the admin?

**Comment by rilwis** [comment]
I'll close this issue for now as no feedback. If you still see the bug, feel free to reopen it or leave a comment.
