### ISSUE TITLE
text_list fields not saving correctly

### ISSUE THREAD

**Issue by bucketpress** [rilwis/meta-box#1117]
I have the following:
```
array(
  'name'    => esc_html__( 'Duration', $prefix ),
    'id'      => "{$prefix}duration",
    'type'    => 'text_list',
    'options' => array(
      'Duration' => 'Duration',
      'Unit' => 'Unit',
    ),
)
```

The fields are saving wrongly/in an expected manner.
Scenario: When I edit only the first field 'Duration' and update, the field gets saved to array[1], when it originally should be array[0].

Seems like text_list always removes and saves the changed fields to the end of the array instead of updating the same array item. This poses a problem if we are retrieving the fields in the order that we have specified when registering them.

**Comment by truongwp** [comment]
Hi there,
Thank you for your report. I have just fixed it.

**Comment by bucketpress** [comment]
@truongwp 
Thanks! When will the next version be pushed to WordPress repository that includes this fix?
