### ISSUE TITLE
Problems with image plupload  reorder these photos

### ISSUE THREAD

**Issue by Infolu** [rilwis/meta-box#1122]
Hello everyone, I'm having problems with plupload_image in the last version of mb 4.11.1 WP 4.7.5 where the following situations occur:
If I have uploaded several photos and try to reorder these photos, when I click save only the photo1 is saved the others are deleted automatically, this only happens if I try to reorder the photos.

I'm grateful for that.

**Comment by Infolu** [comment]
People same with the last update of metabox 4.11.3 I am facing problems when trying to reorder the images, soon after reordering if I save or update the posts I lose the loaded images.
![reorder](https://cloud.githubusercontent.com/assets/16593922/26732566/6691f0bc-478e-11e7-8a5e-5fd16ed3b8fb.JPG)

**Comment by funkedgeek** [comment]
I'll look into this tonight

**Comment by funkedgeek** [comment]
Can you post the code you use to create the meta boxes and the list of plugins you have enabled?  I can't replicate the issue on my testbed

**Comment by Infolu** [comment]
Hello, I do not have extra active plugins, only my custom post type and metaboxio
Follow below my box
`  
function IMS_dealership_register_meta_boxes_vehicle( $meta_boxes ) {
	global $my_post_type;
  $PrefixBox = "{$my_post_type}_mb_"; // ProfixBox+Name
  $PrefixField = "{$my_post_type}_mf_"; // ProfixFild+Name+
// Metabox 02
  $meta_boxes[] = array(
    'id'         => $PrefixBox . 'media',
    'title'  => __( 'Midia', 'your-prefix' ),
    'post_types' => array( 'vehicle' ),
    'context'    => 'normal',
    'priority'   => 'high',
    'autosave'   => true,
    'tabs'      => array(
      'photos' => array(
        'label'        => __( 'Fotos', 'rwmb' ),
        //'icon'         => 'dashicons-admin-post', // Custom icon, using image
      ),
      'videos'    => array(
        'label'      => __( 'Vídeos', 'rwmb' ),
        //'icon'       => 'dashicons-admin-post', // Custom icon, using image
      ),
    ),
    // Tab style: 'default', 'box' or 'left'. Optional
    'tab_style' => 'left',
    'fields'     => array(
      array(
        'id'            => $PrefixField .'media_photos',
        'name'          => __( '', 'your-prefix' ),
        //'desc'  => __( '', 'your-prefix' ),
        'type'          => 'plupload_image',
        'tab'     => 'photos',
        // Delete image from Media Library when remove it from post meta?
        // Note: it might affect other posts if you use same image for multiple posts
        'force_delete'     => true,
        // Maximum image uploads
        'max_file_uploads' => 50,
      ),

      array(
        'id'            => $PrefixField .'media_videos',
        'name'  => __( '', 'your-prefix' ),
        'type'  => 'oembed',
        'tab'     => 'videos',
        // Allow to clone? Default is false
        'clone' => true,
        // Input size
        'size'  => 30,
        'max_clone' => 5,
      ),
    ),
  );

  return $meta_boxes;
}
add_filter( 'rwmb_meta_boxes', 'IMS_dealership_register_meta_boxes_vehicle' );`

**Comment by Infolu** [comment]
Hello, @funkedgeek  sorry for the delay, I took some time to check my entire process, I was looking at the plugins and did not look at the themes, I ended up finding a deprecated wordpress function that was causing problems.
Again I apologize for taking your time for a problem on my side.
Thank you for your attention.
