### ISSUE TITLE
Can't save repeatable key-value pairs after upgrade to 4.11.2

### ISSUE THREAD

**Issue by max-bulygin** [rilwis/meta-box#1123]
I use repeatable key-value pairs meta boxes in my theme. Here is the code I use in functions.php

function kp_skill_meter_meta_box( $meta_boxes )
{
  $meta_boxes[] = array(
    'title' => __( 'Skills Widget Area', 'kappe' ),
    'post_types' => 'page',
    'fields' => array(
      array(
        'id' => 'skill',
        'name' => __( 'Skill', 'kappe' ),
        'type' => 'key_value',
        'clone' => true,
        'sort_clone' => true
      )
    ),
  );
  return $meta_boxes;
}

add_filter( 'rwmb_meta_boxes', 'kp_skill_meter_meta_box' );

This piece of code acts like a widget and should be widgetized, but I haven't implement that yet. Anyway this stopped working properly and after saving the post all fields but first one get lost.

**Comment by truongwp** [comment]
Thanks @max-bulygin,
I fixed this.
