### ISSUE TITLE
Can't save repeatable text fields after issue #1123 fix

### ISSUE THREAD

**Issue by max-bulygin** [rilwis/meta-box#1124]
Just realized that after updating clone.js with issue #1123 fix regular repeatable text fields can't be saved. My code snippet in functions.php

```php
function kp_project_features_meta_box( $meta_boxes )
{
  $meta_boxes[] = array(
    'title' => __( 'Project Features', 'kappe' ),
    'post_types' => 'portfolio',
    'fields' => array(
      array(
        'id' => 'feature',
        'name' => __( 'Feature', 'kappe' ),
        'type' => 'text',
        'clone' => true,
        'sort_clone' => true
      )
    ),
  );
  return $meta_boxes;
}

add_filter( 'rwmb_meta_boxes', 'kp_project_features_meta_box' );
```

**Comment by truongwp** [comment]
Can you describe your issue scenario?

**Comment by max-bulygin** [comment]
Every text field is a project feature related to portfolio item. I just start filling text field and add more features, but when I update post they all gone - just one blank field as default. And key_value fields from #1123 work as expected now.

**Comment by rilwis** [comment]
Can you please make a screenshot?

**Comment by max-bulygin** [comment]
![meta-box-bug](https://cloud.githubusercontent.com/assets/18740535/26747704/4e5527d6-4800-11e7-98b1-ddfb5fbef759.gif)

hope this will help

**Comment by truongwp** [comment]
Can you list all plugins you are using? I guest WPML causes this problem

**Comment by max-bulygin** [comment]
I use Contact Form 7, Polylang, WP Translitera and Meta Box of course. All latest versions. I want to mention that everything worked fine with Meta Box 4.11.1 and I was using exact same plugins

**Comment by max-bulygin** [comment]
Thats weird. I just tested your plugin on localhost copy of my site and its works just fine! But my live version still has this bug. I think it's time to close this bug. Thanks for your support
