### ISSUE TITLE
Clone Button Text, needs fix (BUG)

### ISSUE THREAD

**Issue by Quaked** [rilwis/meta-box#1125]
https://github.com/rilwis/meta-box/blob/5a1159d9e9b76ca48e1e9cf86c4bfc5c905d3a73/inc/clone.php#L97

```php
$text = RWMB_Field::filter( 'add_clone_button_text', $field['add_button'] );
```
needs to be

```php
$text = RWMB_Field::filter( 'add_clone_button_text', $field['add_button'], $field );
```
As is, ```rwmb__add_clone_button_text``` with double underscores is a thing.

But personally I prefer using the ```'add_button' => 'text'``` when registering a field instead as that makes much more sense, however the ability to do so should be in the docs more clearly, at least for meta-box-group ext.

**Comment by rilwis** [comment]
Thank you for your feedback. The bug is fixed and the docs is updated!
