### ISSUE TITLE
Add new html5 attributes to the inputs

### ISSUE THREAD

**Issue by Infolu** [rilwis/meta-box#1127]
Hello, I need to know if there is any way to leave a field locked, I'm not talking about permission, but about disabling for editing.

I will explain, I have a frontend post form, and I would like to access my post type display field that was filled in the frontend but could not change the values of the field. Add disabled in input as attribute
![desable](https://user-images.githubusercontent.com/16593922/26884841-24adf4e2-4b77-11e7-8569-896c5a276ab3.JPG)

**Comment by funkedgeek** [comment]
Disabled fields is already built in to the plugin.  Is that what you are asking?

**Comment by Infolu** [comment]
I actually want to be able to add to the metabox fields the html5 attributes that are https://www.w3schools.com/html/html_form_attributes.asp
Autofocus, required, pattern some of these, all just found the hidden.

**Comment by funkedgeek** [comment]
Most of the html5 attributes are already built into the inputs that make sense having them.  Required is default in all fields, pattern is in all fields that inherit from the text field.  I may add autofocus and autocomplete.

**Comment by Infolu** [comment]
It would be great, if you can also add the attribute (disabled)
The disabled Attribute
The disabled attribute specifies that the input field is disabled.

A disabled input field is unusable and un-clickable.
At some point may be useful.

**Comment by funkedgeek** [comment]
like I said, disabled is already in the plugin

**Comment by Infolu** [comment]
Sorry, how do I activate this attribute in an input?
`			array(
				'id'    => $PrefixField . 'name',
				'name'       => __( 'Nome', 'your-prefix' ),
				'type'  => 'text',
				'size' => 100,
			),`
tranks

**Comment by funkedgeek** [comment]
`array( 'id' => $PrefixField . 'name', 'name' => __( 'Nome', 'your-prefix' ), 'type' => 'text', 'size' => 100, 'disabled' => true ),`

**Comment by funkedgeek** [comment]
Also, if you want to add your own attributes, you can using the `attributes` property of fields:

`array( 'id' => $PrefixField . 'name', 'name' => __( 'Nome', 'your-prefix' ), 'type' => 'text', 'size' => 100, 'attributes' => array( 'disabled' => true ) ),`

**Comment by Infolu** [comment]
Perfect, tranks
