### ISSUE TITLE
Which is the correct way to add meta-boxes that stay when switching themes?

### ISSUE THREAD

**Issue by alvaro0555** [rilwis/meta-box#1129]
In the past I have been including meta-box functionality in a file that is called from the theme's functions.php file. This means that when switching themes the meta-boxes will "disappear". This is fine if meta-boxes are only used for styling of the post (colors, sizes, etc.).

My doubt now comes if the meta-boxes contain content, lets say WYSIWYG or images, that should be there independently of the current theme. Which would be the correct way to include the meta-boxes configuration file so they are not theme dependant?

**Comment by funkedgeek** [comment]
Best way would be to create the meta boxes in a plugin instead of as part of or included with a theme.  That way, you can keep the meta boxes no matter what the theme

**Comment by rilwis** [comment]
Like @funkedgeek said, the best way is use a [functionality plugin](https://css-tricks.com/wordpress-functionality-plugins/) for your site.
