### ISSUE TITLE
Meta Box Plugin Failed After Upgraded to Wordpress 4.8

### ISSUE THREAD

**Issue by dericklts** [rilwis/meta-box#1130]
Meta box plugin failed to work after upgraded to wordpress 4.8. Asked to install meta box again but failed with the attached message. Would appreciate if someone could help me out on this.
![img_9098](https://user-images.githubusercontent.com/24364177/27020938-8da25af2-4f77-11e7-8e29-dbccd4be652d.PNG)

**Comment by truongwp** [comment]
You can delete plugin and re-install it

**Comment by rilwis** [comment]
Hi @dericklts,

As the error says, the plugin is already installed. So, you can’t re-install it. In this case, you can just ignore the message asking to install the plugin. Or you can delete and re-install it as @truongwp suggested.
