### ISSUE TITLE
MB Group - Issue with nested group collapse

### ISSUE THREAD

**Issue by wgstjf** [rilwis/meta-box#1131]
Hi guys,

We have an issue with the collapsing of a nested group.  The issue is that whilst the group can be collapsed it doesn't save the state, nor update the arrow up/down icon.  Looking at the generated code it seems that the CSS is too specific to be able to target the nested group's wrapper.  Your CSS looks like this:

![image](https://user-images.githubusercontent.com/3740694/27024727-ad75f4e2-4f4f-11e7-902e-1bebf4e7a600.png)

Which works for the top level group (as shown below)

![image](https://user-images.githubusercontent.com/3740694/27024749-c729538e-4f4f-11e7-8bb5-4bc619bde850.png)

But fails to target the wrapper for the nested group due to the rwmb-input wrapper

![image](https://user-images.githubusercontent.com/3740694/27024794-f1c8f9aa-4f4f-11e7-98d7-5495018de8f7.png)

Obviously this only explains the issue with the arrow icon not changing and doesn't cater for the fact that the state is not saved but might be related.

The code snippet for generating the nested group is as follows:

![image](https://user-images.githubusercontent.com/3740694/27024852-357a298a-4f50-11e7-9470-c2f337392c74.png)

This is what it looks like - not the red circle around the icon which should be an arrow down icon

![image](https://user-images.githubusercontent.com/3740694/27024960-9e475118-4f50-11e7-88b3-353be3c0b62d.png)

Any thoughts greatly appreciated as always.

Cheers,

Will

**Comment by truongwp** [comment]
I tested but didn't found the issue. Can you give me the code you use to register meta box?

**Comment by wgstjf** [comment]
Hi @truongwp as you can see from the following partial screenshot there would be a lot of code if I pasted the lot here.  Additionally I would rather not paste the whole thing here as the code belongs to the company.  That being said the following snippet should help, hopefully.

I wonder whether the issue arises from the fact that the problem groups are nested within two other groups.  The group layout is as follows:

- Additional Panel group - coloneable, sortable, collapseable, save state
    - Text & Image Panel group - not cloneable, not sortable, not save state
        - Panel Buttons - not cloneable, not sortable, **save state**

The Panel Buttons group is not saving the state nor is the up/down arrow icon changing when it is collapsed/expanded.

The relevant code is as follows:

```php
// Group
array(
'id' => $prefix . 'panels',
'type' => 'group',
'clone' => true,
'sort_clone' => true,
'collapsible' =>  true,
'save_state' =>  true,
'group_title' =>  array( 'field' => 'page_type, textimage_title','separator' => ': '),
'columns' => '12',
'add_button' => __( '+ Add another panel', 'meta-box' ),
// List of sub-fields
'fields' => array(
  // SELECT BOX - Panel Type
  array(
    'name'        => __( 'Panel Type', 'indigo-metaboxes' ),
    'id'          => $prefix.'type',
    'type'        => 'select',
    'class'        => 'inline',
    'options'     => array(
      'text-image' => __( 'Text & Image Panel', 'indigo-metaboxes' ),
      'promo-panel' => __( 'Promo Panel', 'indigo-metaboxes' ),
      'callout-panel' => __( 'Callout Panel', 'indigo-metaboxes' ),
      'testimonial-panel' => __( 'Testimonial Panel', 'indigo-metaboxes' ),
      'gallery-panel' => __( 'Gallery Panel', 'indigo-metaboxes' ),
      'product-categories-panel' => __( 'Product Categories Panel', 'indigo-metaboxes' ),
    ),
    'multiple'    => false,
    'placeholder'         => 'Choose Panel Type...',
    'columns'   =>  '12',
  ),
  #-----------------------------------------------------------------
  # Text / Image Panel
  #-----------------------------------------------------------------
  // BUTTONS - Group
  array(
     // 'name' => 'Below you can add a button (or buttons) to your content.', // Optional
      'id' => $prefix . 'textimage',
      'type' => 'group',
      //'class' => 'child-group',
      'clone' => false,
      //'sort_clone' => true,
      'collapsible' =>  false,
      'save_state' =>  true,
      'columns' => '12',
      'visible' => array( $prefix.'type', '=', array('text-image') ),
      'fields'	=> array(
      // HEADING
        array(
          'type' => 'heading',
          'name' => 'Now add your text and image content',
          'id'   => 'fake_id2', // Not used but needed for plugin
          'columns'   => '12',
        ),
        // BUTTONS - Group
        array(
          'name' => 'Below you can add a button (or buttons) to your content.', // Optional
          'id' => 'textimage_buttons',
          'type' => 'group',
          'class' => 'child-group',
          'clone' => false,
          //'sort_clone' => true,
          'collapsible' =>  true,
          'save_state' =>  true,
          'group_title' =>  "PANEL BUTTONS",
          'columns' => '12',
          'fields'	=> array(
            // RADIO - Show button 1
            array(
                'name'             => 'Show button 1?',
                'id'               => 'button1_show',
                'type'             => 'select',
                'options'          => array(
                  'yes'	=>	'Yes',
                  'no'	=>	'No'
                ),
                //'desc' => 'Do you want to show a button?',
                'std'              => 'no',
                'columns'  => '12',
            ),
          ),
        ),
      ),
    ),
  ),
),
```

This is what we are seeing:

![meta-box-nested-group-save-state-issues](https://user-images.githubusercontent.com/3740694/27628159-0d265376-5be6-11e7-9ac3-a1d47dd887f9.jpg)

Thanks in advance,

Will

**Comment by wgstjf** [comment]
Are you able to reproduce this issue?  If so, any thoughts on a fix?

Cheers,

Will

**Comment by wgstjf** [comment]
@rilwis - if you get a moment could try and reproduce this at your end?  Cheers, Will

**Comment by rilwis** [comment]
I will look at this issue next week. Currently cannot working :(

**Comment by wgstjf** [comment]
Great to hear that it's not just me :-)

Thanks for looking into it and do let me know, if you remember, when it's sorted.

Cheers,

Will

**Comment by rilwis** [comment]
Just want to let you know that we have fixed this issue. New version is coming soon. We're finishing another issue and want to release them in 1 version.

**Comment by rilwis** [comment]
FYI: new version is released. Please update and let me know if you see any bugs.

**Comment by wgstjf** [comment]
Outstanding work once again, thank you!  All seems to be working perfectly. :-)
