### ISSUE TITLE
MB Group + cloneable in cloneable = not working, critical

### ISSUE THREAD

**Issue by Quaked** [rilwis/meta-box#1132]
When having a cloneable field within a cloneable, data doesn't save. This is a critical bug and values aren't being stored in the db. In this case, I have a topmost field type group, within it I have 2 fields: city name and date (group with field date, cloneable).

This is the code used:
```php
// ...
array(
    'id'                => $prefix . 'dates',
    'name'              => __( 'Utbildningsort', Settings::$textdomain ),
    'label_description' => __( 'Välj stad och period för utbildningen.', Settings::$textdomain ),
    'type'              => 'group',
    'clone'             => true,
    'sort_clone'        => true,
    'collapsible'       => true,
    'group_title'       => array( 'field' => 'city' ),
    'save_state'        => true,
    'add_button'        => __( '+ Lägg till stad', Settings::$textdomain ),
    'fields'            => array(
        array(
            'name'              => esc_html__( 'Stad', Settings::$textdomain ),
            'id'                => 'city',
            'type'              => 'text',
            'std'               => false,
            'placeholder'       => __( 'Välj eller ange stad', Settings::$textdomain ),
            'size'              => 30,
            'datalist'          => array(
                'id'            => 'cities_datalist',
                'options'       => array(
                    __( 'Örebro', Settings::$textdomain ),
                    __( 'Västerås', Settings::$textdomain ),
                    __( 'Linköping', Settings::$textdomain ),
                    __( 'Kalmar', Settings::$textdomain ),
                    __( 'Malmö', Settings::$textdomain ),
                ),
            ),
        ),

        array(
            'name'              => __( 'Utbildningstillfälle', Settings::$textdomain ),
            'id'                => 'dates',
            'type'              => 'group',
            'clone'             => true,
            'add_button'        => __( '+ Lägg till ett tillfälle', Settings::$textdomain ),
            'label_description' => __( 'Detta är en beskrivning', Settings::$textdomain ),
            'fields'            => array(
                array(
                    //'name'        => 'test',
                    'id'            => 'days',
                    'type'          => 'date',
                    'inline'        => true,
                    'js_options'    => array(
                        'showButtonPanel'   => false,
                    ),
                ),
            ),
        ),
    ),
),
// ...
```

If I create a new city I can only store ONE date, regardless of how many I add. However I may add as many as I want in the first one. Something is really wrong here or I've set it up really "wrong".

The idea is that one city can have many dates. And this is true, but only for the first city. All the others are limited to 1 date, the others are not being saved.

Any suggestions? It's hard to describe as the first one works, others don't. And I can't work with that!

**EDIT:**
https://metabox.io/docs/meta-box-group/ - using the "collapsible groups" example and changing "phone" field from ```text``` to ```date``` gives the same bug. You can add as many as you want for the first "top group", but it doesn't work in clones. Can't select a date at all. I believe it's the same *bug*.

![image](https://user-images.githubusercontent.com/4580328/27076755-5f277510-502e-11e7-8400-0d49ad937a7e.png)

Seeing as the bug is most 'evident' using ```date``` type, I can only assume that's where the bug lies. Probably something with cloning date fields is wrong/glitchy.

**Comment by Quaked** [comment]
@rilwis do you have any suggestions? Seeing as the demo example breaks I can't but feel it has to be a bug. It could be the 'cloning' used with 'date' in particular or it could be clone or date I guess.

**Comment by Quaked** [comment]
This bug was present in version 1.2.3 of MB Group. Since updating to 1.2.4 and adding:
```js
if( 'undefined' == typeof options )
	return;
```
It seems to work as expected. I'll do some more testing but I'd love to see the above added or some variation of it as 'type' is undefined sometimes and breaks js.

**Comment by rilwis** [comment]
@Quaked: Thanks a lot for your fix! I will invest into the issue more and will add this check.
