### ISSUE TITLE
Set the start of the image loop

### ISSUE THREAD

**Issue by Infolu** [rilwis/meta-box#1133]
Hello I know that in what I can set the image limit,
$ Images = rwmb_meta ('mf_media_photos', 'type = image & size = medium & limit = 1');
But I wonder if it is possible to indicate the beginning of the display
Example I have 5 photos and I want the foreach to start the loop from photo 3.

Thank you for your attention.

**Comment by truongwp** [comment]
You can do it by looping through $images array

**Comment by funkedgeek** [comment]
You can also use the [array_slice](http://php.net/manual/en/function.array-slice.php) function to create a new array that starts at the 3rd item of the old array:

`$Images =array_slice(  rwmb_meta ('mf_media_photos', 'type = image & size = medium '), 2 ); //Second argument is the offset.  Offset of 2 means the array will start from the 3rd item`
