### ISSUE TITLE
Issue with Gallery. Field type "image_advanced".

### ISSUE THREAD

**Issue by santukhan** [rilwis/meta-box#1135]
The problem is that image_advanced field can store only one image, not multiple images. Can you resolve it? I have no time to contribute here although I am a wordpress developer, I have personal projects to handle. Please resolve the issue asap. Wordpress version is to it's latest released version 4.8. Thank you for your great plugin.

Warm Regards
Md. Rakibul Hasan Khan.

**Comment by truongwp** [comment]
Please give me the code you use to create meta boxes. I tested image_advanced field with no extra options and I can choose multiple images when clicking `+ Add Media`

**Comment by funkedgeek** [comment]
Also what version of the plugin are you running?

**Comment by santukhan** [comment]
Latest version of the plugin.

Code has given below

$meta_boxes[] = array(
'id' => 'digitalmarketo_portfolio',
'title' => __('Portfolio Information', 'digitalmarketo'),
'post_types' => array('portfolio'),
'context' => 'normal',
'priority' => 'high',
'fields' => array(
array(
'id'      => $prefix.'gallery',
'name'    => __( 'Gallery', 'digitalmarketo' ),
'type'    => 'image_advanced',
'clone' => false,
),
            ));

**Comment by santukhan** [comment]
$prefix = 'portfolio_';

**Comment by santukhan** [comment]
Version is 4.12.1

**Comment by funkedgeek** [comment]
can you post the code for your custom post type portfolio?

**Comment by santukhan** [comment]
Hello Manny,

Here I have given the code for portfolio post type registration below:

$labels = array(
            'name' => _x('Portfolios', 'post type general name',
'digitalmarketo'),
            'singular_name' => _x('Portfolio', 'post type singular name',
'digitalmarketo'),
            'menu_name' => _x('Portfolios', 'admin menu', 'digitalmarketo'),
            'name_admin_bar' => _x('Portfolio', 'add new on admin bar',
'digitalmarketo'),
            'add_new' => _x('Add New', 'portfolio', 'digitalmarketo'),
            'add_new_item' => __('Add New Portfolio', 'digitalmarketo'),
            'new_item' => __('New Portfolio', 'digitalmarketo'),
            'edit_item' => __('Edit Portfolio', 'digitalmarketo'),
            'view_item' => __('View Portfolio', 'digitalmarketo'),
            'all_items' => __('All Portfolios', 'digitalmarketo'),
            'search_items' => __('Search Portfolios', 'digitalmarketo'),
            'parent_item_colon' => __('Parent Portfolios:',
'digitalmarketo'),
            'not_found' => __('No portfolios found.', 'digitalmarketo'),
            'not_found_in_trash' => __('No portfolios found in Trash.',
'digitalmarketo')
        );

        $args = array(
            'labels' => $labels,
            'description' => __('Description.', 'digitalmarketo'),
            'public' => true,
            'publicly_queryable' => true,
            'show_ui' => true,
            'show_in_menu' => true,
            'query_var' => true,
            'rewrite' => array('slug' => 'portfolio'),
            'capability_type' => 'post',
            'has_archive' => true,
            'hierarchical' => false,
            'menu_position' => null,
            'supports' => array('title', 'editor', 'author', 'thumbnail',
'excerpt')
        );

        register_post_type('portfolio', $args);



Warm Regards.

**Comment by funkedgeek** [comment]
I can't duplicate your issue.  What plugins do you have installed.  Have you deactivated other plugins?

**Comment by santukhan** [comment]
okay. there are other plugins like visual composer, revolution slider etc
have installed on the system.
okay I will check the issue only in a fresh wordpress. thanks for your
review.

**Comment by santukhan** [comment]
Hello Manny,

We got issue with radium demo importer library. It has a filter over post
metadata which was affecting during saving values from post edit page. I
put that under filter under a condition and it has solved the issue from my
end. Sorry to bother you.

Warm Regards.
