### ISSUE TITLE
Cloning fields not working in frontend submission

### ISSUE THREAD

**Issue by visaals** [rilwis/meta-box#1137]
Cloning works in the backend, but not in the frontend. 

I click the "+Add More" button in the frontend, and it scrolls me up to the top of the page and appends a "#" to the url. 

Here's the form code:
`function new_member_meta_box( $meta_boxes ) {
	$prefix = 'new_member_';

	$meta_boxes[] = array(
		'id' => 'obh_member_form',
		'title' => esc_html__( 'New Member', $prefix ),
		'post_types' => array( 'obh_member', 'post'),
		'context' => 'normal',
		'priority' => 'high',
		'autosave' => false,
		'fields' => array(
			array(
				'id' => $prefix . 'first_name',
				'type' => 'text',
				'name' => esc_html__( 'First Name', $prefix ),
				'clone' => true,
			),
			array(
				'id' => $prefix . 'last_name',
				'type' => 'text',
				'name' => esc_html__( 'Last Name', $prefix ),
			),
			array(
				'id' => $prefix . 'email',
				'name' => esc_html__( 'Email', $prefix ),
				'type' => 'email',
			),
		),
	);

	return $meta_boxes;
}
add_filter( 'rwmb_meta_boxes', 'new_member_meta_box' );`

Here's the frontend code:
```
<div class="note-main-content">
		<h2 class="obh_archive_header">New Member</h2>
			<?php //place form shortcode here 
				 $form = '[mb_frontend_form id="obh_member_form"]';
				 echo do_shortcode( $form );

			?>
		<br>
		<br>
</div>
````

Here's the screenshot:

![screen shot 2017-06-23 at 11 02 01 am](https://user-images.githubusercontent.com/19598277/27490330-78965714-5803-11e7-8e12-08522b9659ff.png)

**Comment by truongwp** [comment]
I have just tested it but can't find the error you meet. Please make sure that you are using latest version of meta box and its extensions. If the error still occurs, please give me the error message in browser's Console
