### ISSUE TITLE
Group Title from multiple fields

### ISSUE THREAD

**Issue by wgstjf** [rilwis/meta-box#1140]
Hi,

Quick one for you (hopefully)... :-)

I have a custom page-builder built using Meta Box.  There is a cloneable, sortable group that enables the user to add/edit panels that appear on the page.  It looks like this:

![image](https://user-images.githubusercontent.com/3740694/27580873-eadc3550-5b23-11e7-9f2f-8a4fd7eea1e5.png)

The group is setup as follows:

```php
// Group
array(
  'id' =>  'page_panels',
  'type' => 'group',
  'clone' => true,
  'sort_clone' => true,
	'collapsible' =>  true,
	'save_state' =>  true,
	'group_title' =>  array( 'field' => 'page_type'),
	'columns' => '12',
  'add_button' => __( '+ Add another panel', 'meta-box' ),
  // List of sub-fields
  'fields' => array(
    // SELECT BOX - Panel Type
		array(
			'name'        => __( 'Panel Type', 'indigo-metaboxes' ),
			'id'          => 'page_type',
			'type'        => 'select',
			'class'        => 'inline',
			'options'     => array(
				'text-image' => __( 'Text & Image Panel', 'indigo-metaboxes' ),
				'promo-panel' => __( 'Promo Panel', 'indigo-metaboxes' ),
				'callout-panel' => __( 'Callout Panel', 'indigo-metaboxes' ),
				'testimonial-panel' => __( 'Testimonial Panel', 'indigo-metaboxes' ),
				'product-categories-panel' => __( 'Product Categories Panel', 'indigo-metaboxes' ),
			),
			'multiple'    => false,
			'placeholder'         => 'Choose Panel Type...',
      'columns'   =>  '2',
		),
....and so on
```

The group_title is currently set to 'page_type' field.  What I am trying to do is create a group_title that shows the 'page_type' followed by the 'panel_title' if it exists.  So in effect something like this

**"Text & Image Panel: A really great panel title"**

It is worth mentioning that the Panel Title is a sub-field of a nested group called 'page_textimage'

So the questions are as follows:

1. Can the group_title be a merging of two fields?
2. How do you reference in the group_title variable a field that is a sub-field of a nested group

Thanks in advance,

Will

**Comment by rilwis** [comment]
Hi Will,

1. Currently merging 2 fields is not possible yet. I will try to work on that.
1. We use a selector like `$field = $group.find( ':input[name*="[' + fieldId + ']"]' );`, so it doesn't matter where the field is located (direct sub-field or inside a nested group).

**Comment by rilwis** [comment]
I've just made an improvement to new version 1.2.6, which supports multiple sub-fields in the group title.

Now you can use `'group_title' => array( 'field' => 'sub1, sub2', 'separator' => ' ' )`, e.g. separate sub-fields by commas and optionally set the separator (default is a space).

Happy developing :)

**Comment by wgstjf** [comment]
That's amazing and works perfectly!!  Thanks so much.

Cheers,

Will
