### ISSUE TITLE
Modify value of other fields using js

### ISSUE THREAD

**Issue by satyagupta** [rilwis/meta-box#1142]
Here is what i want to do 

Total cost: (A) + (B)
Actual cost: (A)
Tax: (B)

I will provide the data in total cost field and depending on the value in the total cost, fields A and B will get calculated Automatically. 

This i know can be done using js which is why i want to know how can we add custom js? 

TIA

**Comment by truongwp** [comment]
The easiest way is use jQuery  like this:
```
$('field-a, field-b').on('change', function() {
    $('fieldc').val($('field-a').val() + $('field-b').val());
});
```

You can use `wp_enqueue_script()` to enqueue the custom js file.
