### ISSUE TITLE
Update Breaks Page

### ISSUE THREAD

**Issue by bulldogmeta** [rilwis/meta-box#1144]
Update from 4.11.3 breaks the homepage of our site. Background and text vanishes.

I didn't build the site, only maintain. So, I'm not sure if I should be posting this here, but if anyone wants further info please contact me.

Sight back to normal now:

http://newwayacademy.org

**Comment by truongwp** [comment]
Hi @bulldogmeta,
We have just updated Meta Box to version 4.12.1 which fixed this issue. Thank you for your report.
