### ISSUE TITLE
Mime type frontend validation for file type advanced

### ISSUE THREAD

**Issue by MihaiCraciun** [rilwis/meta-box#1146]
Hello,

I've used the online generator to create a field for an advanced file upload that should only accept audio files.
```
	'fields' => array(
			array(
				'id' => $prefix . 'file_advanced_1',
				'type' => 'file_advanced',
				'name' => esc_html__( 'File Advanced', 'metabox-online-generator' ),
				'mime_type' => 'audio/mpeg',
				'max_file_uploads' => 1,
				'max_status' => true,
			),
		),
	);
```
My question : is there any validation done ? When I go to the file upload dialog i can select any file and hit save (tested with a jpeg file). The file shows up in the metabox but disappears after i update the post. 
On the first save, the variable returns the path to the jpeg and the field is cleared in the admin. On a second update of the post  (with the field cleared) it returns `array(0) { }` as it should.
Is there a way to block the upload of unwanted mime types and allow only specified type ?

Thanks,

**Comment by funkedgeek** [comment]
Weird, because it filters as intended when I try it.  No non-audio files show up in the modal.  What version of the plugin are you using?

**Comment by MihaiCraciun** [comment]
Filtering works. Only existing audio files show up but if I go to upload I can select any file and it gets uploaded and I am able to hit save and the file shows up in the place where the add media button was.

**Comment by MihaiCraciun** [comment]
If anybody comes across this issue, you can use `wp_check_filetype()` to make sure you're getting the MIME type you're expecting.
