### ISSUE TITLE
Validation issue on hidden metabox

### ISSUE THREAD

**Issue by wgstjf** [rilwis/meta-box#1149]
Hi guys,

Quick one for you.  I have a set of metaboxes (that are hidden on the homepage template) that contain a required field.  The logic I need is that if the metaboxes are visible then the field is required, if hidden then not.  Is this possible?

The relevant code is as follows:

```php
'validation' => array(
'rules'    => array(
$prefix.'header_title' => array(
    'required'  => true,
    //'minlength' => 7,
    // More rules here
),
// Rules for other fields here
),
),
'hidden' => array( 'page_template', 'in', array('page_templates/template-homepage.php') ),
'fields' => array(

// HEADING
array(
'type' => 'heading',
'name' => 'Header options for this page.  The header image is added to the right in the \'Header Image\' area.',
'id'   => 'fake_id', // Not used but needed for plugin
'columns'   => '12',
'tab'  => 'general-header',
),
// Text - Page Subtitle
array(
'name'  => __( 'Header Title', 'indigo-metaboxes' ),
'desc' => 'A header title for the page which sits on top of the header image.  Keep it short!',
'class'    => 'big-text',
'id'    => $prefix . 'header_title',
'type'  => 'text',
'std'   => '',
'clone' => false,
'columns'   => '8',
'add_to_wpseo_analysis' => true,
'tab'  => 'general-header',
),
```

Cheers,

Will

**Comment by rilwis** [comment]
Hi Will,

I think you can solve this problem by using HTML5 `required` attribute with a custom JS code to add/remove it when the page template is changed.

Using validation library forces using JS to validate, thus can't be changed :(.

**Comment by wgstjf** [comment]
Thanks for coming back to me on that.  Will consider the HTML5 route and also look into extending the validation to allow for conditional requirement.

Cheers,

Will
