### ISSUE TITLE
default field (std) is not working. I am using 

### ISSUE THREAD

**Issue by markupdaddy** [rilwis/meta-box#1153]
default field (std) is not working. I am using Version: 4.12.2.

**Comment by rilwis** [comment]
Is the field clonable?

I found the 'std' doesn't work with cloneable fields and am working on them.

**Comment by markupdaddy** [comment]
Thanks for the reply. It is working if I am using clone = false.

**Comment by rilwis** [comment]
I just got to this issue. In case you set `clone = true`, the `std` should be **array of default values**. Like this:

```php
array(
    'type' => 'text',
    'id' => 'test',
    'clone' => true,
    'std' => array( 'Default 1', 'Default 2 ),
),
```

**Comment by newmon102** [comment]
It doesn't work for me either :( When it has value, it displays properly. But when I delete the value, the std value doesn't display as expected.
`<?php
/**
 * Register Settings Pages
 */
add_filter( 'mb_settings_pages', 'prefix_options_pages' );
function prefix_options_pages( $settings_pages ) {
	$settings_pages[] = array(
		'id'            => 'my-options',
		'option_name'   => 'my_options',
		'menu_title'    => __( 'Theme Options', 'textdomain' ),
		'submenu_title' => __( 'General', 'textdomain' ),
	);
}

/**
 * Register Fields
 */
add_filter( 'rwmb_meta_boxes', 'prefix_options_meta_boxes' );
function prefix_options_meta_boxes( $meta_boxes ) {
	$meta_boxes[] = array(
		'id'             => 'general', // Metabox ID
		'title'          => __( 'General', 'textdomain' ), // Metabox Title
		'settings_pages' => 'my-options', // Settings Page ID
		'fields'         => array(
			array(
				'id'   => 'test', // Field ID
				'name' => __( 'Test', 'liberstart' ), // Field Name
				'type' => 'text', // Field Type
				'std'  => 'std test',
			),
		),
	);
}
`

**Comment by rilwis** [comment]
@newmon102 The `std` value shows up only when you haven't saved the post yet. If you save the post, that means you want to save an empty value and the plugin respects that. Showing `std` value in this case actually confuses users, cause they can't save the empty value (if they want).
