### ISSUE TITLE
Removing Cloned Group Leaves Button 

### ISSUE THREAD

**Issue by acafourek** [rilwis/meta-box#1154]
Did a search through issues and didn't see any for this scenario.

When cloning a group on a settings page, the fields are added as expected (though it is creating additional "Add more buttons") . When the cloned groups are removed, the input fields are removed but the "Add more" button(s) are left. It is also then possible to remove all of the input fields and be cloning an empty group.

GIF of the behavior:
![meta_box_demo](https://user-images.githubusercontent.com/5088983/28643436-d8385a5c-7223-11e7-979e-f1e5ac862fc3.gif)

Code being used to generate:
```
$meta_boxes[] = array(
	'id'             => 'as_af_network_membership_settings_fields',
	'title'          => 'Membership Choices',
	'settings_pages' => 'as_af_network_settings',
	'fields'         => array(
		array(
			'name'    => 'Available Membership Options',
			'id'      => 'as_af_network_memberships',
			'type'    => 'group',
			'clone' => true,
			'fields' => array(
				array(
					'name'    => 'Label',
					'id'      => 'as_af_network_membership_label',
					'type'    => 'text',
					'columns' => 6,
					'size'		=> 50,
				),
				array(
					'name'    => 'Price',
					'id'      => 'as_af_network_membership_price',
					'type'    => 'text',
					'class' => 'pricing',
					'columns' => 4
				) //end price
			)//end group fields
		) //end group
	) //end meta box fields
);//end meta box
```

**Comment by rilwis** [comment]
I see you're using Columns extension. Can you try updating it to the latest version?

Or set the columns number to correct ones: 6+6 in stead of 6+4.

The latest version of Columns has a check if total columns is less than 12, which prevents the bug like yours.

**Comment by acafourek** [comment]
@rilwis Updating plugin versions (a couple of my extensions were behind the latest) and adjusting column count fixed it! Thanks for the quick guidance, should have thought of that myself but we never think of the simplest solutions first.

![giphy](https://user-images.githubusercontent.com/5088983/28650517-57743de2-724a-11e7-81b9-f1a0eda37bc8.gif)
