### ISSUE TITLE
Unable to Deactivate or Remove Meta-Box Plugin

### ISSUE THREAD

**Issue by TheArtBeacon** [rilwis/meta-box#1161]
There is no option to deactivate or delete. Do I need to go into my files and remove it manually or is there some trick?

![metabox](https://user-images.githubusercontent.com/30913508/29227278-e9b424b8-7e9a-11e7-9ba7-4cf2c2293fc1.png)

**Comment by truongwp** [comment]
Are there any extensions from Meta Box is active?

**Comment by TheArtBeacon** [comment]
Thank you for responding. No extensions. I added it, then realized it was too advanced for what I needed and now I can't delete it.

**Comment by rilwis** [comment]
Hi,

Please check [this docs on wp-config.php](https://codex.wordpress.org/Editing_wp-config.php#Disable_the_Plugin_and_Theme_Editor).

I think your host might disable some permissions, so WordPress can't remove the plugin. It happens to all plugins, not just Meta Box.

This problem might be hosting/chmod or WordPress issue. So I'll close it. Feel free to re-open it if you find anything.
