### ISSUE TITLE
Save WYSIWYG content as post content

### ISSUE THREAD

**Issue by RichDonnellan** [rilwis/meta-box#1163]
I tried using this [example code](https://metabox.io/docs/save-wysiwyg-content-post-content/), but setting `id => 'content'` saves the field data to the `wp_postmeta` table, not `wp_posts`. 

Is this tutorial up-to-date, or am I missing something here? Using version `4.12.2` on WordPress `4.8.1`.

```php
'fields' => array(
    array(
      'id'    => 'content',
      'type'  => 'wysiwyg',
      'raw'   => TRUE,
      'std'   => $default_content,
    ),
```

**Comment by rilwis** [comment]
Hi Rich,

I've just tested with the code in the example and here is how I get:

![save-as-content](https://user-images.githubusercontent.com/668274/29502336-5fb951d6-8659-11e7-8b30-6877882e8d73.gif)

**Comment by RichDonnellan** [comment]
Thanks for testing and confirming. I haven't tried since you recently added the `rwmb_content_value` filter to the docs. In the meantime, I ended up using something else, but I appreciate you looking into this.
