### ISSUE TITLE
WYSIWYG not working properly

### ISSUE THREAD

**Issue by lord-enzo** [rilwis/meta-box#1166]
Hello, 

I've been trying to search through my code, in order to find what could be missing, but I cannot find anything... 

When adding a WYSIWYG field, it does not work properly in the backend. The buttons from the editor are shown _outside_ the field, and if I change its position, the buttons are fixed in its original location. Also, when changing into "Visual" mode, everything gets messed up. 

Here it is:
![screen shot 2017-08-28 at 17 12 10](https://user-images.githubusercontent.com/3686028/29779857-1d3ad0ee-8c14-11e7-8d3f-b4b9a2ddb0f8.png)

And then, when clicking "Visual" tab:
![screen shot 2017-08-28 at 17 12 23](https://user-images.githubusercontent.com/3686028/29779869-2554afca-8c14-11e7-82ee-4491fe40d178.png)

What could be happening?

**Comment by funkedgeek** [comment]
Can you give the code you are using to create the meta box?

**Comment by lord-enzo** [comment]
Thanks @funkedgeek! There was the problem, I had written incorrectly the parameters...
