### ISSUE TITLE
Image Upload PHP Warning

### ISSUE THREAD

**Issue by peterdarthur** [rilwis/meta-box#1168]
Hi, 

I love the potential for this plugin, but I am unable to use the image select option in a custom Meta box. I generated the code for a new meta box from the online generator, and the text input area (in the same meta box) works fine, but the image upload button is not there. (see attached image)

<img width="317" alt="screen shot 2017-09-22 at 10 20 49 am" src="https://user-images.githubusercontent.com/16738218/30756551-00cff0b8-9f80-11e7-912f-d6e24007e276.png">

I'm running WP v.4.8.2
Here's the warning (discovered via the Query Monitor plugin):
`Warning: Invalid argument supplied for foreach() in wp-content/plugins/meta-box/inc/fields/image-select.php on line 32`

Here's the code I used from the Online generator: 

```
	function team_custom_meta_box( $meta_boxes ) {
		$prefix = '';

		$meta_boxes[] = array(
			'id' => 'team-information',
			'title' => esc_html__( 'Team Information', 'team' ),
			'post_types' => array( 'post', 'page' ),
			'context' => 'side',
			'priority' => 'high',
			'autosave' => true,
			'fields' => array(
				array(
					'id' => $prefix . 'team_photo_select',
					'type' => 'image_select',
					'name' => esc_html__( 'Team Photo', 'team' ),
					'force_delete' => false,
					'max_file_uploads' => '4',
				),
				array(
					'id' => $prefix . 'coach_name',
					'type' => 'text',
					'name' => esc_html__( 'Coach Name', 'team' ),
				),
			),
		);

		return $meta_boxes;
	}
	add_filter( 'rwmb_meta_boxes', 'team_custom_meta_box' );
```

In case it's useful, here's the HTML for the meta box on my post.php page:

```
<div id="team-information" class="postbox ">
<button type="button" class="handlediv" aria-expanded="true"><span class="screen-reader-text">Toggle panel: Team Information</span><span class="toggle-indicator" aria-hidden="true"></span></button><h2 class="hndle ui-sortable-handle"><span>Team Information</span></h2>
<div class="inside">
<div class="rwmb-meta-box" data-autosave="true" data-object-type="post"><input type="hidden" id="nonce_team-information" name="nonce_team-information" value="7549b3a460"><input type="hidden" name="_wp_http_referer" value="/wp-admin/post.php?post=1&amp;action=edit"><div class="rwmb-field rwmb-image_select-wrapper"><div class="rwmb-label">
					<label for="team_photo_select">Team Photo</label>
					
				</div><div class="rwmb-input"></div></div><div class="rwmb-field rwmb-text-wrapper"><div class="rwmb-label">
					<label for="coach_name">Coach Name</label>
					
				</div><div class="rwmb-input"><input size="30" type="text" id="coach_name" class="rwmb-text " name="coach_name"></div></div></div></div>
</div>
```

Please let me know if there's anything I should do to facilitate fixing this. I am wary about cusomizing plugin files.

**Comment by funkedgeek** [comment]
You want to use image_advanced instead of image_select

**Comment by funkedgeek** [comment]
Did my last comment resolve the issue?  image_select requires you give an array of image url's that the user selects from.  You probably want image_advanced

**Comment by peterdarthur** [comment]
Yes, thank you! image_advanced gave me what I needed. Great plugin with
great support!
