### ISSUE TITLE
Javascript error in revslider plugin

### ISSUE THREAD

**Issue by Elisalu** [rilwis/meta-box#1169]
Hi :)
I installed the Betheme theme in my wordpress, plugin revslider is include in pack, but I have some issue.

I turned on script_debugging and found in a browser console that I get a javascript error from a revslider file. The error is: 

tinymce-shortcode-script.js:105 Uncaught TypeError: undefined is not a function

The offending javascript file is located in /wp-content/plugins/revslider/admin/assets/js. Looking inte the file the error is in this function: 
104		jQuery(document).ready(function(){
105			jQuery('.rs-mod-slides-wrapper').sortable();
106		});

The error seems to stop the rest of the page to load properly. 

Error show in console:
Uncaught TypeError: jQuery(...).sortable is not a function

Can you help me, please?
I don't have idea what to do!

Thanks :)
Elisa

**Comment by funkedgeek** [comment]
Sorry but we don't provide support for revslider.  Are you having an issue with out plugin?

**Comment by Elisalu** [comment]
No, I solved the problem by changing the plugin. Now it all ok :)

Thanks
