### ISSUE TITLE
Increase priority of 'register_meta_boxes'

### ISSUE THREAD

**Issue by vladimirdulov** [rilwis/meta-box#1176]
Related to  https://github.com/rilwis/mb-custom-taxonomy/issues/2

Some of custom port types registered using the default priority (10)  are not shown in metaboxes.
I suggest increasing 'register_meta_boxes' action priority say to 20 in RWMB_Core::init() in wp-content/plugins/meta-box/inc/core.php
It will fix issues with custom post types registered using the default priority by 3rd party plugins.

```
--- wp-content/plugins/meta-box/inc/core.php.orig	2017-10-11 10:06:01.000000000 +0400
+++ wp-content/plugins/meta-box/inc/core.php	2017-10-11 10:05:28.000000000 +0400
@@ -18,7 +18,7 @@
 		load_plugin_textdomain( 'meta-box', false, plugin_basename( RWMB_DIR ) . '/languages/' );
 
 		add_filter( 'plugin_action_links_meta-box/meta-box.php', array( $this, 'plugin_links' ) );
-		add_action( 'init', array( $this, 'register_meta_boxes' ) );
+		add_action( 'init', array( $this, 'register_meta_boxes' ), 20 );
 		add_action( 'edit_page_form', array( $this, 'fix_page_template' ) );
 	}
```

**Comment by rilwis** [comment]
Thanks for your feedback. I've just fixed it.

**Comment by alex-solovyev** [comment]
Thank you very much Ahn, do you have a release date for this fix?

**Comment by rilwis** [comment]
Probably next week. We're finalizing some things in the code :)
