### ISSUE TITLE
Single image in image_advanced?

### ISSUE THREAD

**Issue by bitorbit** [rilwis/meta-box#1177]
Is there a way to limit image_advanced to single image (I want to allow selection of only one image)?

Thanks!

**Comment by rilwis** [comment]
You can set:

```
'max_file_uploads' => 1,
'max_status' => false,
```

**Comment by bitorbit** [comment]
Thanks for your answer, but this is not working for me - I am still able to select more than one image from Media Library.

**Comment by funkedgeek** [comment]
Can you post your complete code and the version of the plugin you are using?  The following works the way you want:

```
array(
	'id' =>'funk_imgs',
	'type' => 'image_advanced',
	'max_file_uploads' => 1,
	'max_status' => false,
),
```

**Comment by bitorbit** [comment]
After further testing, I can confirm that original solution by rilwis is working. The problem was related to our proxy function which we are using to create meta boxes.
