### ISSUE TITLE
field type "number" doesn't accept a standard value

### ISSUE THREAD

**Issue by flowdee** [rilwis/meta-box#1179]
I would like to define a standard value for number fields, but unfortunately `std` doesn't have any affect. Tried multiple ways:

```
array(
        'name'  => __( 'Unique Visitors per Month', 'nsm' ),
        'id'    => '_listing_visitors_month',
        'type' => 'number',
        'min'  => 0,
        'step' => 1,
        'std' => 0,
        'required' => false
    );
```

```
array(
        'name'  => __( 'Unique Visitors per Month', 'nsm' ),
        'id'    => '_listing_visitors_month',
        'type' => 'number',
        'min'  => 0,
        'step' => 1,
        'std' => '0',
        'required' => false
    );
```
The input field is empty when viewing it the first time on backend, as well as on the frontend submission addon.

Only `placeholder` works but of course it's not the same.

**Comment by funkedgeek** [comment]
`std` works for new posts that have never been saved.  Tried your code and it works as intended.

**Comment by flowdee** [comment]
Absolutely right @funkedgeek. 

I assume I previously saved an empty field. Sorry for the issue 😄
