### ISSUE TITLE
Mutliple fields clone

### ISSUE THREAD

**Issue by ther12k** [rilwis/meta-box#145]
Is it possible to create mutiple fields clone? I have tried to make it with creating new type of field (combine two fields), but offcourse it has problem with saved value

**Comment by rilwis** [comment]
Hi again, group of fields (which can be cloned) now supported officially by [Meta Box Group extension](http://metabox.io/plugins/meta-box-group/). Please take a look. Any feedback is welcomed.

Thanks.
