### ISSUE TITLE
rwmb_meta returns single value for select field with multiple values

### ISSUE THREAD

**Issue by alimony** [rilwis/meta-box#209]
The function `rwmb_meta()` always returns a single value for select type fields, even if it's set to multiple and has multiple values set. (The meta box itself saves the multiple values correctly.)

A workaround is to set the type to `checkbox_list` when fetching the value.

It seems like the multiple flag is based solely on the type: https://github.com/rilwis/meta-box/blob/master/inc/helpers.php#L127

This would have to be changed so that the multiple flag on select fields was checked too.

**Comment by funkedgeek** [comment]
Currently supported
