### ISSUE TITLE
Add subtitle option

### ISSUE THREAD

**Issue by djevrek** [rilwis/meta-box#268]
Maybe we can add subtitle option in this metabox. It will be great if we have this. 
![screenshot-1](https://f.cloud.github.com/assets/412686/322212/17adb584-9a32-11e2-86b2-c9c5c65ea90b.png)

This is from this repo https://github.com/helgatheviking/KIA-Subtitle

**Comment by funkedgeek** [comment]
That involves editing the theme you're working on
