### ISSUE TITLE
using select2 for creating a new feature

### ISSUE THREAD

**Issue by jjhesk** [rilwis/meta-box#291]
I am trying to create a new meta-box type like
"mutiplestep"

This type will allow you to pull out the custom post type titles with its ID in the select value

array(
"type"=>"mutiplestep",
"options"=>array(
"step_data_1"=>array(
"options"=>array(
"mycustomtype_select_1",
"mycustomtype_select_2",
"mycustomtype_select_3",),

"step_data_2"=>array(
"posttype_options"=>array(
"mycustomtype1","mycustomtype2","mycustomtype3")
)
)
)

please help me to improve this structure

**Comment by funkedgeek** [comment]
The post field should do this.
