### ISSUE TITLE
Save field content as single value

### ISSUE THREAD

**Issue by franz-josef-kaiser** [rilwis/meta-box#32]
Currently `do_field_class_actions` always saves an `array`, due to `$args[] = $field`. This is a little bit annoying, as it successfully prevents meta queries. We need to add a `single_value` argument.

**Comment by rilwis** [comment]
I think this issue can be closed. For reference, this is how we do with saving fields with "multiple" option:

- If field is "multiple" and **not** clone: each value is saved as a row in database
- If field is "multiple" and "clone": field value will be saved as a single row in database (in form of an array)
