### ISSUE TITLE
text_list doesn't save datas

### ISSUE THREAD

**Issue by inkcreativ** [rilwis/meta-box#323]
Is it the same for you .. or maybe i did a bad setup.

thxs  :)

**Comment by rilwis** [comment]
Hi, I think the problem stays here for a long time. In the latest version 4.4.2, I've fixed a bug #547 and I think it relates with this bug. From my test, the `text_list` field now works correctly, so I'll close this issue now. If you still see the problem, please re-open it.

Thank you.
