### ISSUE TITLE
map: resizeMap(m) needed

### ISSUE THREAD

**Issue by DreamsEngine** [rilwis/meta-box#346]
to simplify the problem: :P

http://stackoverflow.com/questions/9458215/google-maps-not-working-in-jquery-tabs

and an example

http://sabormexicano.com/tlaloc  //in #contact tab

thanks!

PS : maybe some indentation to beautify the code could be nice.. /n :P

**Comment by funkedgeek** [comment]
`refresh` function in map code should have fixed this.  Use this function with the `load` event in jQuery tabs.
