### ISSUE TITLE
Duplicates post_meta values when using 'wp_insert_post' action in creating attachment or custom post types

### ISSUE THREAD

**Issue by Defrothew** [rilwis/meta-box#372]
I've found unusual behavior when hooking an action in creating an attachment and a custom post type post.

Scenario:
1. Use this plugin and register your own post meta.
2. Create an action hook 'wp_insert_post' and make an attachment or custom post type post inside your action.
3. Create a new post where you used this plugin. Enter any value on those boxes.
4. Search the value on your database or look for that value on your custom post type that you placed on your action hook in no. 2. You will see duplicated post meta values.

function sample_insert_post( $post_id, $post ) {
// create an attachment and linked in to $post_id or create a new custom post type here to replicate this
}
add_action( 'wp_insert_post', 'sample_insert_post' );

**Comment by funkedgeek** [comment]
The plugin does better with saving meta of specific post types, so this issue should be resloved.  See https://github.com/rilwis/meta-box/commit/1445633f619219178bd78e8e184d140703e24024
