### ISSUE TITLE
meta boxes for options page

### ISSUE THREAD

**Issue by patrickf0** [rilwis/meta-box#378]
your plugin is very nice, great thing would be to add meta boxes also to options pages!

**Comment by apintocr** [comment]
Is this possible?

**Comment by flowdee** [comment]
+1

**Comment by funkedgeek** [comment]
I think this goes beyond the scope of the plugin.  If WordPress adds this in the core, then it'd be easy to extend.  Otherwise we'd have to create plugin code from scratch
