### ISSUE TITLE
Pulling in Dynamic data to Select/Checkboxes

### ISSUE THREAD

**Issue by dusted** [rilwis/meta-box#383]
I have a CPT called People and a CPT called testimonials, in testimonials I want to pull through a list of the different people so that a testimonial can be assigned to that person.

I'm just wondering if this is possible in Meta Box or if I would have to create my own metabox for this case?

Thanks
Dan

**Comment by funkedgeek** [comment]
You can do something like this with the posts field.  See the demo for post for more information: https://github.com/rilwis/meta-box/blob/master/demo/post.php
