### ISSUE TITLE
WP Views plugin breaks Meta Box plugin

### ISSUE THREAD

**Issue by stl99** [rilwis/meta-box#390]
Hi there,

After activating the WP Views plugin (http://wp-types.com/home/views-create-elegant-displays-for-your-content/) the Meta Box functionalities on my edit post page break: The fields created by the Meta Box plugin change their layout and using them doesn't work anymore (basically trying to insert something in one of these fields makes most of the WordPress edit post functions "un-selectable").

I attached two screenshots to demonstrate the issue:

WP Views activated

![wp views activated](https://f.cloud.github.com/assets/5437447/1750135/74c74a42-656f-11e3-94c0-132092d46b93.png)

WP Views deactivated

![wp views deactivated](https://f.cloud.github.com/assets/5437447/1750136/74c8a18a-656f-11e3-8e0b-6ecc96590d3c.png)

I notified the WP Views support as well.

Cheers,
Thomas

**Comment by funkedgeek** [comment]
Has this ever been resolved?

**Comment by funkedgeek** [comment]
Probably related to and fixed in https://github.com/rilwis/meta-box/issues/771
