### ISSUE TITLE
slider + text box field type

### ISSUE THREAD

**Issue by dazzlesoftware** [rilwis/meta-box#392]
Hello is it possible to create slider and textbox that clones as I have this working using my theme framework but trying to do the same with meta-box as its reviews system that you input the name and score for example graphics as text and slider to 70% and you clone to add more as I tried the group but does not create same effect as need them group together not having the boxes separate that clones

Stephen

**Comment by funkedgeek** [comment]
Duplicate of https://github.com/rilwis/meta-box/issues/394
