### ISSUE TITLE
Feature Request: Field Dependencies

### ISSUE THREAD

**Issue by onlysli** [rilwis/meta-box#398]
It would be nice to set dependencies for form elements.

For example, some fields should be visible only if a checkbox is checked.

**Comment by philburton** [comment]
+1

**Comment by rilwis** [comment]
The [Meta Box Show/Hide](https://metabox.io/plugins/meta-box-show-hide/) extension and the more powerful [Meta Box Conditional Logic](https://metabox.io/plugins/meta-box-conditional-logic/) now can do the job well.
