### ISSUE TITLE
Not doing the wp_set_object_terms => taxonomies not associated

### ISSUE THREAD

**Issue by xavsio4** [rilwis/meta-box#416]
(WP 3.8.1, MB 4.3.8) Everything is perfect with this plugin but one thing I can't do : I've removed the WP default metaboxes for taxonomies and i've used the one of the plugin. So far so good. Then I select a taxonomy value  "type => select" and update my custom post and the value is not selected...nothing happen for the taxonomies. The association with the CPT is not done. If I don't use the meta boxes of the plugin and use the default wp one...it works.  Any idea ?

**Comment by funkedgeek** [comment]
Closing this issue.  If you still need help, feel free to re-open.
