### ISSUE TITLE
Video Field

### ISSUE THREAD

**Issue by Abu-Taymiyyah** [rilwis/meta-box#426]
Hello,

Can you add the feautuere to it that one can also uploads/add videos for a gallery for example.

**Comment by funkedgeek** [comment]
You can upload videos using any of the file based fields, though displaying those videos isn't supported yet.  Stay tuned.

**Comment by Wolverin89** [comment]
hello! in continue of the theme about video...just cant find it in documentation...i have multiple video url (from you-tube) by Oembed meta-field. And i have the list of the video as output. That right! but this is wrap in ul > li tag and i see the dots (list style css)..My question is how can i remove it (change class..) i know that 'list-style:none' is help to me, but how i know that's the class for oembed?

**Comment by funkedgeek** [comment]
Video field now added
