### ISSUE TITLE
Taxonomy category creating conflict with post categories

### ISSUE THREAD

**Issue by alvaro0555** [rilwis/meta-box#434]
I am adding a metabox with a field of taxonomy-category (just copy-pasted the field from the demo.php file).
In my posts I see the default categories meta box (All Categories|Most used|Add new category) and the new created with checkbox.
This new created metabox controls the default categories one. I'm not sure if this is the default behaviour, so I cant have different values in both.
In case this is the default behaviour, I can tell that it still affects other metaboxes. I have a metabox that applies to my-custom-post-type and includes the taxonomy field. I have a second and different metabox that doesn't include the taxonomy field for normal posts. In normal posts I can't select categories in the default WordPress metabox (I assume that the conflict affects it also,although there is no new metabox taxonomy field).

Thanks

**Comment by funkedgeek** [comment]
Basically, if you have multiple fields effecting the same taxonomy or meta, the last one that is saved will overwrite any of the previous ones.  That's just how forms work.
