### ISSUE TITLE
map support issue

### ISSUE THREAD

**Issue by jjhesk** [rilwis/meta-box#448]
Please take a look of metabox google map. When I set the size of the map like so:

```
 array(
            'id' => METAPREFIX . 'reference_loc',
            'name' => _x('Map Search', 'google map', HKM_LANGUAGE_PACK),
            'type' => 'text',
            'std' => _x('Buda, Hong Kong', 'google map', HKM_LANGUAGE_PACK),
        ),

        array(
            'id' => METAPREFIX . 'location',
            'name' => _x('Google Pin', 'google map', HKM_LANGUAGE_PACK),
            'type' => 'map',
            'std' => '22.25,114.1667,15', // 'latitude,longitude[,zoom]' (zoom is optional)
            'style' => 'width: 100%; height: 500px',
            'address_field' => METAPREFIX . 'reference_loc', // Name of text field where address is entered. Can be list of text fields, separated by commas (for ex. city, state)
            'desc' => 'Choose One District in Hong Kong <strong style="color:red">(*)</strong> is required. It needs to be selected in order to be seen on the website.',

        ),
``` 

notice that the width is 100%.
when I drag and drop the metabox into another location or open close the metabox. The canvas of the google map did not adjust canvas size and it makes looked bad.

Please fix it. 
Many thanks

**Comment by Frenddy** [comment]
Hello, they have no idea how to change the style of the map? Https: //developers.google.com/maps/documentation/javascript/styling, I am also placing this
$ Args = array (
    'Type' => 'map'
    'Width' => 'auto', // Map width, default is 640px. Can be '%' or 'px'
    'Height' => '480px' height // Map, default is 480px. Can be '%' or 'px'
    'Zoom' => 5 // Map zoom, default value is the admin in September, and if it's omitted - 14
    'Marker' => true, // Display marker? Default is 'true',
    'Marker_title' => 'dfffd' When hover // Marker title
    'Marker_settings' => array (// Use your own marker for maps
        'Url' => get_template_directory_uri (). '/images/icon-map.png', // Give an image With the map
        'Size' => '42 75.60 '
    )
    'Info_window' => '<h3> Info Window Title </ h3> Info window content. HTML <strong> allowed </ strong> ', // Info window content, can be anything. HTML allowed.
    'Js_options' => array (
    'MapTypeId' => 'ROADMAP'
    'Scrollwheel' => false,
    'ZoomControl' => true,
    )
    
);

and it does not work.

**Comment by rilwis** [comment]
Hi @jjhesk, I've just added a fix for refresh map when drag and drop meta boxes. We also had a fix for refresh map when toggle meta boxes.
