### ISSUE TITLE
visual editor not working when cloning wysiwyg editor in 4.3.9

### ISSUE THREAD

**Issue by tobyhage** [rilwis/meta-box#473]
Visual editor is not working when cloning wysiwyg editor in version 4.3.9 meta box plugin.
When i remove the brackets in the field-name on line 71 in field.php, then the visual editor is working.

Hopefully you can fix this.

**Comment by tobyhage** [comment]
On this moment version 4.4.1 and this is still not working. Probably this is not used very much.
I can't figure out why this is not working, else i would fix this.

Is there somebody which has this functionality working?

**Comment by funkedgeek** [comment]
The visual editor is not designed for cloning.  We're working on a solution

**Comment by funkedgeek** [comment]
Fixed in https://github.com/rilwis/meta-box/commit/f8bbf528d14222c66d650888d169f321b6ee8a26
