### ISSUE TITLE
Trying to retrieve a list of available Layersliders in a select field

### ISSUE THREAD

**Issue by MargieinAZ** [rilwis/meta-box#477]
For the life of me, I can't figure out how to do this.
I'm able to populate the dropdown menu that the select field generates with "Array" "Array" "Array", etc.
But it's not passing the data of the layerslider name or id.

Here's the link to the deveoper doc's for Layerslider:
http://blaszok.mpcreation.net/docs/layer-slider-documentation/developers.html#sliders-class

I'm a relative newbie at php programming, and am really stuck here. 

Any help would be sooooo appreciated. I've wasted a ton of time trying to figure this out, and I'm no further than when I started. 

I'd be willing to pay a small fee to someone to hand-hold me and get it working correctly.

Thanks!

**Comment by funkedgeek** [comment]
Has this been resolved?  We need to see your code to know whats going on
