### ISSUE TITLE
Saving post metadate into 1 row of post meta

### ISSUE THREAD

**Issue by Jamarolex** [rilwis/meta-box#499]
Hi, in the first, i must to say a very big thaks 4 metaboxes, your awesome. And now about issue, How i can save all metadate, from 1 post into 1 row, seems like array.

Thank you. Sorry 4 ma bad inglish, i using a google translate.

Best regards Jamal Sultanov.

**Comment by rilwis** [comment]
This is now can be done with [Meta Box Group](http://metabox.io/plugins/meta-box-group/) extension. You can create a group which contains all fields you need. When saving in the database, it will create only 1 row for that group. Each field will be an element of group value (array).

You can find more information about this extension at [its page](http://metabox.io/plugins/meta-box-group/) or [its documentation page](http://metabox.io/docs/meta-box-group/)
