### ISSUE TITLE
oEmbed not working inside wysiwyg meta-box -(front end)

### ISSUE THREAD

**Issue by rrafekaj** [rilwis/meta-box#511]
I have a post type with an extra wysiwyg made using meta-box underneath the standard wysiwyg. When I paste a youtube link into my wysiwyg it works okay on the admin side - the video shows after url is pasted into my custom wysiwyg metabox, but the url only shows as text when i go to view my post.

The standard wordpress post wysiwyg oembed works fine - both admin and front end

Does anyone have any suggestions?

**Comment by eriktdesign** [comment]
You can run your content through WordPress' `the_content` filter to run shortcodes, do embeds, as well as auto-paragraph etc.

`echo apply_filters(` 'the_content', $whatever_content );`
