### ISSUE TITLE
Image_advanced undefined issue

### ISSUE THREAD

**Issue by HIENAworld** [rilwis/meta-box#512]
I created some custom meta boxes which were work fine couple of days ago. I uploaded every image what I wanted but now I'd like to change one of them. Since that time I did not update anything, and today I got undefined error when I tried to remove the image. So in this case I have no chance to upload a new one for this image_advanced metabox. I created a new image_advanced metabox and cannot upload nor use existing image from wordpress. There is no any console error. I hope there is any solutions to make it work. Thanks

**Comment by rfearing** [comment]
Hi, 

I'm sorry. I'm having the same issue. 

What I've tried: 
<ol>
<li> Deactivating/ Reactivating </li>
<li> Uninstalling/ Reinstalling </li>
<li> Making sure I have the latest version </li> 
<li> Deactivating other plugins I thought might be causing issues </li>
</ol> 

Sinusite (What conflicted with ajax?) Maybe I have something doing the same. 

Any advice?

**Comment by Sinusite** [comment]
Hi,
it was just my custom dev...which interfered with the include of meta_box
something like
function RDV_register_meta_boxes($meta_boxes) {		
...
if ( !in_array($typenow, $slug_array ) ) return $meta_boxes;
...
$meta_boxes['box_rdv'] = array(
....
}
So If you have custom code lines  i suggest you try to comment them and see...
++
