### ISSUE TITLE
Can we customize the 8 default colors in the color-picker?

### ISSUE THREAD

**Issue by wgdes** [rilwis/meta-box#516]
The default colors are black, white, red, orange, yellow, green, blue, and purple. I was wondering if we can somehow replace some or all of these with custom theme-related colors, and if so, how.

Thanks!

**Comment by funkedgeek** [comment]
Just now added this feature using `js_options` like our other JavaScript enhanced fields  Added in https://github.com/rilwis/meta-box/commit/bd2b2cc5f64d4143cc29ee26d8d1af831fe288d3
