### ISSUE TITLE
The New 'autocomplete' Field

### ISSUE THREAD

**Issue by chrisxclash** [rilwis/meta-box#523]
So I saw the new autocomplete that I was hoping to use, but I realized that users are only allowed to select something you define in the options array. Wouldn't it make more sense to have the autocomplete list be more of a suggestion of things you can enter rather than the only list of available options?

Or this could also be another setting for the field such as 'required' where users can only use what's in the list (like it is now).

For example, I was hoping to allow a user to enter their own values into it, and then when a post was published I would then take the options a user has entered and save them for later. This way the next time the autocomplete field is used I could use previously saved options in the dropdown for quick access.

This could also work with the text field by having an 'options' setting under text that would allow it to suggest a list of quick options. Just my two cents, but it made more sense to me that this field would allow you to suggest things rather than require them, otherwise a select box would make more sense.

**Comment by funkedgeek** [comment]
Technically, using a text field with a datalist does exactly this.
