### ISSUE TITLE
show taxonomy value

### ISSUE THREAD

**Issue by mukiwu** [rilwis/meta-box#532]
here is my sample code:
```
array(
				'name'    => __( 'category', 'meta-box' ),
				'id'      => "client_cat",
				'type'    => 'taxonomy',
				'options' => array(
					'taxonomy' => 'category',
					'type' => 'checkbox_list',
					'args' => array(
						'orderby' => 'id',
						'child_of' => 11,
						'depth' => -1,
					),
				),
			),
```

But when I use ```var_dump(rwmb_meta('client_cat'));``` , it returns null ..

how can I call those selected value ?

**Comment by rilwis** [comment]
You should add `type=taxonomy` in `rwmb_meta` to let the function know about the type of field, e.g. `rwmb_meta( 'client_cat', 'type=taxonomy' ) )`.
