### ISSUE TITLE
How to check plugin is active

### ISSUE THREAD

**Issue by krishna19** [rilwis/meta-box#533]
i include the metabox as plugin and i need help to check the plugin is active or not. 
Now i use like this
<pre>
if ( class_exists( 'RW_Meta_Box' ) )
	include 'demo/demo.php';
}
</pre>
is it correct ?

Thanks

**Comment by rilwis** [comment]
Hi, yes, using `class_exists` is good. Although it's not recommended to include the plugin inside themes or plugins. You should use something like [TGM Activation Class](http://tgmpluginactivation.com) to do that.

Please see [documentation](http://metabox.io/docs/include-meta-box-plugin-themes/).

**Comment by krishna19** [comment]
Hi, after install using TGM Activation class, how to include sample config file only when plugin is active. please help me. thanks
