### ISSUE TITLE
Add Custom fields to User Meta

### ISSUE THREAD

**Issue by ochoarobert1** [rilwis/meta-box#536]
I've read that is possible to add some fields in the user edit page, i'm trying to do the exact formula:

add_filter( 'rwmb_meta_boxes', 'n24_register_meta_boxes' );

function n24_register_meta_boxes( $meta_boxes )
{
    $prefix = 'n24_';
	
	// THIS IS THE METABOX WITH THE USER META	
    $meta_boxes[] = array(
        'title'    => 'Redes Sociales',
        'pages'    => array( 'user' ),
        'context'  => 'normal',
        'priority' => 'high',

        'fields' => array(
            array(
                'name'  => 'Perfil Twitter',
                'desc'  => 'Introduzca el username de twitter. E.G.: @username',
                'id'    => $prefix . 'twitter',
                'type'  => 'text',
				
            ),
        )
    );

    return $meta_boxes;
}

But nothing is showed :(

**Comment by rilwis** [comment]
Hi, it's not possible at the moment. Right now the plugin supports adding custom fields to post add new / edit page only.
