### ISSUE TITLE
ability to pass array variable as options to select field.

### ISSUE THREAD

**Issue by jlsodai** [rilwis/meta-box#537]
This is what I would like to achieve:
<pre>array(
            'name'    => 'Select',
            'id'      => 'select',
            'type'    => 'select',
            'options' => array(  // Array of value => label pairs for radio options
                'value1' => 'Label 1',
                'value2' => 'Label 2'
            ),
),
</pre>
Can't seem to pass a variable as options values. Example.

<pre>
$myarray = array('value1' => 'Label 1', 'value2' => 'Label 2')
array(
            'name'    => 'Select',
            'id'      => 'select',
            'type'    => 'select',
            'options' => $myarray,
),
</pre>

Select dropdown shows empty.

**Comment by ThemePlugger** [comment]
There shouldn't be any problem passing a variable to 'options' parameter. Are you sure you are passing the right variable with the right data to it?

**Comment by rilwis** [comment]
Like @ThemePlugger said, it would not be a problem, everything should work.
