### ISSUE TITLE
When i adding fields from foreach loop, the values not saving

### ISSUE THREAD

**Issue by alijmlzd** [rilwis/meta-box#538]
Hi.
i want to add some fields per current post's terms and i done this job like this:

```php
$persons = getPersonsInAdmin($postID);
$persons_fields = array();

foreach ($persons as $person) {

    $roles = getPersonRolesInAdmin($person->term_id);

    $field = array(
        'name'        => $person->name,
        'id'          => "{$prefix}person_roles_{$person->term_id}",
        'type'        => 'select_advanced',
        'multiple'    => true,
        'placeholder' => "choose person's roles for this event",
        'options'     => $roles,
    );

    array_push($persons_fields, $field);

}

$meta_boxes[] = array(
    'id'         => 'specify_persons_roles',
    'title'      => 'Select persons roles',
    'post_types' => getJaajimTypes(),
    'context'    => 'normal',
    'priority'   => 'high',
    'fields'     => $persons_fields,
);


return $meta_boxes;
```
everything is ok but the fields values not saving.
any idea?

**Comment by rilwis** [comment]
I think the logic is ok. I just wonder when the meta box saves post meta, your functions are not available. Can you check when functions like `getPersonsInAdmin`, `getPersonRolesInAdmin`, etc. available? Do you define them in some conditions, something like this:

```
if ( conditions )
{
    require 'functions.php';
}

// In functions.php
function getPersonsInAdmin()
{
}
```

**Comment by alijmlzd** [comment]
no, there is no conditions that prevent availability of my functions. but for more certainty, i've tried to add the fields by my hands in a variable and my functions are not involved in it and of course, it works and saves the values:
```php
$persons_fields = array(
    array(
        'name'        => 'Field 1',
        'id'          => "{$prefix}person_roles_1",
        'type'        => 'select_advanced',
        'multiple'    => true,
        'placeholder' => "choose person's roles for this event",
        'options'     => array(
            'value1' => 'label1',
            'value2' => 'label2',
            'value3' => 'label3',
        ),
    ),
    array(
        'name'        => 'Field 2',
        'id'          => "{$prefix}person_roles_2",
        'type'        => 'select_advanced',
        'multiple'    => true,
        'placeholder' => "choose person's roles for this event",
        'options'     => array(
            'value1' => 'label1',
            'value2' => 'label2',
        ),
    ),
);

$meta_boxes[] = array(
    'id'         => 'specify_persons_roles',
    'title'      => 'Select persons roles',
    'post_types' => getJaajimTypes(),
    'context'    => 'normal',
    'priority'   => 'high',
    'fields'     => $persons_fields,
);
```
by more reviews, now i'm sure the problem is about my `getPersonsInAdmin($postID)` function. it loads in wordpress's `init` action and it should be available when i call it, but it's not.
so, any consultation can help me.

thank you
Ali

**Comment by alijmlzd** [comment]
ok, everything is specified. actually i using `$_GET['post']` to getting current post id that it's not available when saving post meta. so how can i access to current post id in `rwmb_meta_boxes` filter? i've googled, googled, googled and tried various methods and i didn't succeed.

Ali

**Comment by alijmlzd** [comment]
it works, yay :d
you've made me happy. thank you.

Ali
