### ISSUE TITLE
Function to add meta boxes to other areas? Like user profiles and Options pages??

### ISSUE THREAD

**Issue by wgdes** [rilwis/meta-box#539]
Does anyone know if there is a function (or snippet) somewhere that can be used to add meta boxes to options pages and/or to users? Preferably the image meta boxes...

If not, then does anyone have any ideas for going about it?

**Comment by rilwis** [comment]
Hi,

Currently there's no ways to do that. This plugin works only for posts (and custom post types). I'll think more about this :).
