### ISSUE TITLE
Improve Metabox creation using Builder Pattern

### ISSUE THREAD

**Issue by DavidWiesner** [rilwis/meta-box#542]
Hi,

at first thank you for this great plugin!

For a Project i have create class that will make the creation of a metabox much easier. In addition i add a easier way to get the meta data from a post.

Here is the Gist with this class and two files showing the usage of the `Metabox_Builder`

https://gist.github.com/DavidWiesner/a9447fe2be95cefd2ba8 

Here is a really short example for creating a Metabox with the `Metabox_Builder`:
```php
// init builder with prefix, title and post_type
$PersonMetaBuilder = new Metabox_Builder('Person_Prefix_', __('Personinformation', 'rwmb'), 
                                            array( 'person_post_type' ));
// add two fields
$PersonMetaBuilder->new_field('homepage', __('Homepage', 'rwmb'), 'url')->set_required();
	->new_field('twins', __('Twins', 'rwmb'), 'number')->with_option('step', 2);

// create and register
$PersonsMeta = $PersonMetaBuilder->create();
```

This is much easier than the complex nested array stuff.

For later use `create` return an Object that allow an easy access to the post metadata. 
For example in a page template.

```php
<p><?php $PersonsMeta->echo_homepage(); ?></p>
<p><?php if($PersonsMeta->get_twins()) echo('Twins: '.$PersonsMeta->get_twins()); ?></p>
```  

This class was just a fast hack so there is still room for improvements.

Feel free to use this class in your plugin.

regards,
David

**Comment by rilwis** [comment]
This is great! Thanks for sharing. I'll look at that :)
