### ISSUE TITLE
select field value 0

### ISSUE THREAD

**Issue by inspiraaz** [rilwis/meta-box#543]
I need a select field with 0, 1 and a default empty value to override some global settings

with this code...

```php
array(
            'name' => 'TEST',
            'id'   =>  'test',
            'options' => array(
                1 => 'Yes',
                0 => 'No',
            ),
            'std' => '',
            'type'  => 'select',
            'multiple' => false,
            'placeholder' =>  'Select value',
        )
```

all options are ignored and value 0 is always selected.

Is there any way this can be done with select field ?

**Comment by sodbileg** [comment]
Exactly the same situation. Have you managed this issue?

**Comment by sodbileg** [comment]
Okay, I've managed the issue by setting `std` as `null` like `'std' => null`.
