### ISSUE TITLE
Add meta box to custom post type

### ISSUE THREAD

**Issue by MagnusKallgard** [rilwis/meta-box#546]
Hey!

I'm really new to custom post types and meta boxes and im trying to implement meta boxes to my custom post type.

This is the custom post type that I have:

		function products_post_type() {

		$labels = array(
			'name'                => _x( 'Products', 'Post Type General Name', 'text_domain' ),
			'singular_name'       => _x( 'Product', 'Post Type Singular Name', 'text_domain' ),
			'menu_name'           => __( 'Product', 'text_domain' ),
			'parent_item_colon'   => __( 'Parent Product:', 'text_domain' ),
			'all_items'           => __( 'All Products', 'text_domain' ),
			'view_item'           => __( 'View Product', 'text_domain' ),
			'add_new_item'        => __( 'Add New Product', 'text_domain' ),
			'add_new'             => __( 'New Product', 'text_domain' ),
			'edit_item'           => __( 'Edit Product', 'text_domain' ),
			'update_item'         => __( 'Update Product', 'text_domain' ),
			'search_items'        => __( 'Search products', 'text_domain' ),
			'not_found'           => __( 'No products found', 'text_domain' ),
			'not_found_in_trash'  => __( 'No products found in Trash', 'text_domain' ),
		);
		$args = array(
			'label'               => __( 'product', 'text_domain' ),
			'description'         => __( 'Product information pages', 'text_domain' ),
			'labels'              => $labels,
			'supports'            => array( 'title', 'editor', 'excerpt', 'author', 'thumbnail', 'comments', 'custom-fields', ),
			'taxonomies'          => array( 'category', 'post_tag' ),
			'hierarchical'        => false,
			'public'              => true,
			'show_ui'             => true,
			'show_in_menu'        => true,
			'show_in_nav_menus'   => true,
			'show_in_admin_bar'   => true,
			'menu_position'       => 5,
			'can_export'          => true,
			'has_archive'         => true,
			'exclude_from_search' => false,
			'publicly_queryable'  => true,
			'capability_type'     => 'page',
		);
		register_post_type( 'product', $args );

		}

		// Hook into the 'init' action
		add_action( 'init', 'products_post_type', 0 );

		include 'demo.php';

I've tried to do like this in the demo.php file:

			function your_prefix_register_meta_boxes( $meta_boxes )
			{
				/**
				 * prefix of meta keys (optional)
				 * Use underscore (_) at the beginning to make keys hidden
				 * Alt.: You also can make prefix empty to disable it
				 */
				// Better has an underscore as last sign
				$prefix = 'your_prefix_';
				// 1st meta box
				$meta_boxes[] = array(
					// Meta box id, UNIQUE per meta box. Optional since 4.1.5
					'id'         => 'standard',
					// Meta box title - Will appear at the drag and drop handle bar. Required.
					'title'      => __( 'Standard Fields', 'meta-box' ),
					// Post types, accept custom post types as well - DEFAULT is 'post'. Can be array (multiple post types) or string (1 post type). Optional.
					'post_types' => array( 'post', 'page', 'products_post_type' ),
					// Where the meta box appear: normal (default), advanced, side. Optional.
					'context'    => 'normal',
					// Order of meta box: high (default), low. Optional.
					'priority'   => 'high',
					// Auto save: true, false (default). Optional.
					'autosave'   => true,
					// List of meta fields
					'fields'     => array(

I tried to add products_post_type to the demo.php file.

Does anyone know how to fix this or how to make it work?

Thanks!

**Comment by DavidWiesner** [comment]
In your first code sample register a new custom posttype `product` with `register_post_type( 'product', $args );`. This id should also be use in the metaboxes array like `'post_types' => array( 'post', 'page', 'products' ),`

**Comment by MagnusKallgard** [comment]
I've tried to do that. My new row looks like yours but nothing happens in my Add new product page. Do I need to do anything else in the demo.php in order to make it work?

**Comment by DavidWiesner** [comment]
You must also tell wordpress to call your `your_prefix_register_meta_boxes` function:
```
add_filter( 'rwmb_meta_boxes', 'your_prefix_register_meta_boxes' );
```

**Comment by MagnusKallgard** [comment]
Oh okey! Where do I add that line? Im just started learning, sorry!

**Comment by DavidWiesner** [comment]
at the begin of your `demo.php` see: http://metabox.io/docs/registering-meta-boxes/

**Comment by MagnusKallgard** [comment]
I already have that at the beginning of my demo.php. I can see the meta boxes at my normal post page but not in my custom post type..

**Comment by rilwis** [comment]
I see you register post type `product`, but in your code you use `products_post_type`, is that the mistake? Can you change to `product` to check if it works?

**Comment by MagnusKallgard** [comment]
It worked!:) Thank you very much for the help!
