### ISSUE TITLE
Text_list field doesn't show his values when editing

### ISSUE THREAD

**Issue by NicolasCambas** [rilwis/meta-box#547]
Hi,

I have created a `text_list` field like this : 
```
array(
	'name'			=> __( 'Custom Specification', 'meta-box' ),
	'id'			=> "{$prefix}product_custom_spec",
	'type'			=> 'text_list',
	'clone'			=> true,
	'options'		=> array(
						'spec_label' => __( 'Label', 'meta-box' ),
						'spec_value' => __( 'Value', 'meta-box' )
					)
),
```
I can put my values in it, clone it, even display the data on the front site, no problem. But when I want to edit the post, the fields have wrong values.
They display en `A` in the first field and a `r` in the second. I believe that it displaying the letters `Array`... one for each field.

Every other fields type works fine, I can't figure out where's the mystake, maybe somebody have a clue or an alternative?

Thank's!

**Comment by clmnsbzy** [comment]
same here

**Comment by rilwis** [comment]
Just fixed this. Please check.

**Comment by NicolasCambas** [comment]
Works like a charm! Thanks a lot!
