### ISSUE TITLE
Cannot Clone taxonomy

### ISSUE THREAD

**Issue by bigandy** [rilwis/meta-box#549]
<pre><code>
'fields' => array(
	array(
		'name'		=> 'Authors',
		'options'  => array(
			'taxonomy' 	=> 'authors',
			'type' 		=> 'select',
		),
		'id'		=> $prefix . 'post_authors_order',
		'clone'		=> true,
		'type'		=> 'taxonomy',
	),
)</code></pre>

When I have clone set to true the select box disappears. I have also tried this with select_tree.

**Comment by bigandy** [comment]
``'fields' => array(
	array(
		'name'		=> 'Authors',
		'options'  => array(
			'taxonomy' 	=> 'authors',
			'type' 		=> 'select',
		),
		'id'		=> $prefix . 'post_authors_order',
		'clone'		=> true,
		'type'		=> 'taxonomy',
	),
)
``

**Comment by funkedgeek** [comment]
Cloning of taxonomy terms isn't supported because of the way WP saves terms on posts.
