### ISSUE TITLE
file restriction doesn't work?

### ISSUE THREAD

**Issue by senlin** [rilwis/meta-box#551]
I'm trying to use the advanced file upload and want to restrict file upload for PDF only.

I have tried both `'mime_type' => 'pdf'` and `'mime_type' => 'application/pdf'`, but the metabox still lets me upload other file types.

How to make this work properly?

**Comment by rilwis** [comment]
The correct param is `mime_type`, but it restricts the Media files shown in the popup, not for uploading :(. I will try to find a solution for this.

**Comment by senlin** [comment]
The files also show on the front end, would be great if you can find a solution for it!

**Comment by rilwis** [comment]
Yes, the problem is WP still allows to upload file. It just doesn't show the file in the Media list (because of the `mime_type` filter). So file is uploaded and displayed in the frontend.

**Comment by senlin** [comment]
The file also shows in the media list...

**Comment by rilwis** [comment]
Yes, because file is uploaded.

**Comment by senlin** [comment]
It is a very weird issue, I will try to look into it too, but for now I think it is safe to say that files format cannot be restricted in any way...

**Comment by rilwis** [comment]
Agree.

**Comment by senlin** [comment]
:+1:

**Comment by senlin** [comment]
just checking in, still no solution for this?

**Comment by rilwis** [comment]
Unfortunately no :(. I think WP uploader doesn't have ability to restrict all file type, but only images afaik.

**Comment by senlin** [comment]
Ah well, okay let's leave it at this then :)
