### ISSUE TITLE
FIXED - 'Create your own field type' example throws error. 

### ISSUE THREAD

**Issue by ryanlabelle** [rilwis/meta-box#555]
Awesome script, thanks! Just a note on your example to "Create your own field type":
http://metabox.io/docs/create-field-type/#section-define-a-new-field-class

I think you want
```add_action( 'admin_init', 'prefix_load_phone_type', 1 );```

vs.

```add_action( 'init', 'prefix_load_phone_type', 1 );```

I could be misinterpreting but it threw an error and that's how I fixed it. Cheers!

ref:
http://codex.wordpress.org/Plugin_API/Action_Reference/admin_init

**Comment by rilwis** [comment]
Hi, thanks for your comment. I've tried again with `init` hook and it works as expected. I think `init` is more general than `admin_init` which fires only in admin area. Ideally both of them should work :)

What was the error you saw? Did you try with custom code or the same code as in the documentation?

Thanks

**Comment by ryanlabelle** [comment]
Hi, I was getting a class not found. So if my class was called RWMB_Sortable_Field which extends RWMB_Field, I would get a RWMB_Field class not found. I just wrapped the class declaration in a class_exists('RWMB_Field') if statement.

```
if (class_exists('RWMB_Field') ){
    class RWMB_[name_of_custom_field]_Field extends RWMB_Field
     {
     // do something
     }
}```

**Comment by rilwis** [comment]
Thanks, I've just updated [the docs](http://metabox.io/docs/create-field-type/). I'm not sure 100% why `init` not working for you, but it's fine (maybe better) to use `admin_init` hook.
