### ISSUE TITLE
Table metabox

### ISSUE THREAD

**Issue by Mariyo** [rilwis/meta-box#556]
Do you have in your roadmap plan to develop "Table" metabox?

**Comment by rilwis** [comment]
Hi, what do you mean "table" meta boxes?

**Comment by Mariyo** [comment]
It will be metabox, where you can define rows and columns of <table> in at least "text" type.

**Comment by Mariyo** [comment]
Column 1 | Column 2 | + add column
------------ | ------------- | ------------- 
cell 1 | cell 1.2 ||
cell 1 | cell 1.2 ||
+ add row|||

**Comment by rilwis** [comment]
I understand. I developed an extension for this purpose, please check it here: http://metabox.io/plugins/meta-box-columns/

**Comment by Mariyo** [comment]
Looks good, but can I add as many columns and rows, as I need? Its not clear for me from screnshots.. Or its staticly defined in metabox definition on init?

**Comment by rilwis** [comment]
The number of rows and columns are defined statically in the meta box's code.

Do you want to add columns and rows dynamically? Is that similar to cloning feature? Have you checked this extension: http://metabox.io/plugins/meta-box-group/. It works with Columns extension.

**Comment by Mariyo** [comment]
Yes, its simillar. I've already bought meta-box-group extension and I am about to test it.

**Comment by Mariyo** [comment]
I am getting this fatal error when installing plugin:

*Fatal error: Class 'RWMB_Field' not found in \wp-content\plugins\meta-box-group\group.php on line 8*

**Comment by rilwis** [comment]
It's a dummy question but have you activated Meta Box extension yet?

**Comment by Mariyo** [comment]
Sorry, this was just my mistake :)
