### ISSUE TITLE
metabox typography

### ISSUE THREAD

**Issue by WPThemer** [rilwis/meta-box#557]
hi all - am I missing something. is there any typography field e.g.

Font Size (1...X), Font Style (Normal, SemiBold, Itlalic etc), Font Color

as I can see this is not available, has anyone created this so far ? it will save me sometime..

thanks

**Comment by rilwis** [comment]
Hi, there is no typography fields now. It would be great if you can develop that field and share with everyone :)

**Comment by funkedgeek** [comment]
You can easily create select fields that let you select those options and putr them in a group
