### ISSUE TITLE
$field['std'] not wordk!

### ISSUE THREAD

**Issue by ahmadazimi** [rilwis/meta-box#558]
I found that `$saved` is always true in `static function meta( $post_id, $saved, $field )` [inc/field.php] so MetaBox never use my **std**.

Can anyone help me?

**Comment by rilwis** [comment]
The variable `$saved` is set in [`has_been_saved`](https://github.com/rilwis/meta-box/blob/master/inc/meta-box.php#L446) function, which checks all custom fields of a meta box: if none of them has value then it will be `true`, else `false`.

**Comment by ahmadazimi** [comment]
I'm confused! So how can I use `std` for my fields?

**Comment by rilwis** [comment]
Just set 'std' value for your fields, or am I misunderstanding something?

**Comment by ahmadazimi** [comment]
I set `std` value for my field, but when I create a new post, which still has no meta saved, `std` not shown for that field.

In the first comment, I mentioned that at the position you set up `$meta` for a field, `$saved` never be false: `inc/field.php:258` even the first time I run! So the `std` value never shown for field.

// Use $field['std'] only when the meta box hasn't been saved (i.e. the first time we run)
$meta = ( ! $saved && '' === $meta || array() === $meta ) ? $field['std'] : $meta;

**Comment by rilwis** [comment]
Can you post your code to register meta box?

**Comment by ahmadazimi** [comment]
I really confused!
Because of when I use your default code (http://metabox.io/docs/registering-meta-boxes/) I can see std value, but in my own code I can't. My code depends on a complicated template engine which I wrote for Wordpress, and creation of meta boxes for custom post types is automated in it.
Please let me debug my code again and then I will be back here.

**Comment by rilwis** [comment]
No problem, I'm here for help, anytime :)

**Comment by ahmadazimi** [comment]
Thank you buddy :-)
