### ISSUE TITLE
Extension License for Commercial Themes.

### ISSUE THREAD

**Issue by ryanlabelle** [rilwis/meta-box#559]
I've read up on your GPL license for Meta Box but I wasn't sure if the Extensions are included in that. Do we purchase and continue renewing a copy of the Extension we would like to include in our commercial product? We are interested in the Meta Box Tabs Extension.

Thanks so much for your contribution, it's been a refreshing script to use.

Cheers!

**Comment by rilwis** [comment]
Hi,

This is a great question! All the extensions are under GPL license, too. You can use it in multiple commercial products. The expiry date only used to provide support and updates.

For more details, please read the FAQ here: http://metabox.io/faq/

**Comment by ryanlabelle** [comment]
That's great. Thank you.
