### ISSUE TITLE
placeholder not works for post

### ISSUE THREAD

**Issue by ahmadazimi** [rilwis/meta-box#560]
I've add a field of type `post` with `field_type = select` in the parameters.
I've already assign `placeholder` for my field. But I see an empty option element as the first element in my select.

I investigated the code and I found a bug in `inc/select.php:130`

`if ( $field['placeholder'] )` you never check `'post' == $field['type']`

Is it true?

**Comment by rilwis** [comment]
Thanks, just fixed it.

**Comment by ahmadazimi** [comment]
You're welcome.
Tanx
