### ISSUE TITLE
Save meta box data via AJAX, has this been done before?

### ISSUE THREAD

**Issue by ryanlabelle** [rilwis/meta-box#561]
I had a search and I haven't seen it mentioned before but has anyone experimented with saving meta box data via ajax call? 

On a page with many meta boxes this could save on server resources by making a quick save request vs posting and reloading the whole page.

If this hasn't been done before how difficult do you think it would be to use the button field to trigger a ajax call which could save the meta box data without reloading the page?

Is this crazy talk?

**Comment by rilwis** [comment]
Hi, actually this is already implemented in the plugin by using the WordPress autosave feature. When defining a meta box, just set autosave = true, then its fields will be saved automatically without reloading whole page.

**Comment by ryanlabelle** [comment]
Very nice. Is there a way to force a save via onclick handler? I have several meta boxes on one page so I'm thinking of putting a 'save changes' button on every meta box. Being able to save changes without reloading would be awesome. I'll look into this.

Thanks so much for the quick response.

**Comment by rilwis** [comment]
Currently there's no way to 'trigger' saving process via a onclick event. I think we can mimic the autosave feature somehow to achieve that, but I haven't tried.

**Comment by ryanlabelle** [comment]
I haven't found anything yet that I can easily implement. Saving post meta data via ajax appears to be more complicated than I thought. 

I'm really looking to improve overall performance. We have a lot of meta boxes on each page and it takes some time to load and then render. I think it's simply the large amount of markup / DOM loading.

I'll keep looking for a solution and post back. If you have any suggestions please let me know.

Cheers!

**Comment by funkedgeek** [comment]
Currently autosaves happen ever 60 seconds so if you set your meta box to `autosave = true`, your meta will be saved every 60 seconds.
