### ISSUE TITLE
How to save advanced checkbox list

### ISSUE THREAD

**Issue by brehouse** [rilwis/meta-box#562]
First - I recognize this is a simple issue, but I just can't figure it out. 

The only thing I want to do is when checking the checkbox, have that save once I update the page - but it always comes back unchecked. I've read all of the documentation but not sure what I'm missing. Here is my code: 

functions.php:
 
    add_filter( 'rwmb_meta_boxes', 'prefix_register_meta_boxes' );

    function prefix_register_meta_boxes( $meta_boxes )
	{
	    $prefix = 'rw_';

	    // 1st meta box
	    $meta_boxes[] = array(
	        'id'       => 'clients',
	        'title'    => 'Clients',
	        'pages'    => array( 'page' ),
	        'context'  => 'normal',
	        'priority' => 'high',

	        'fields' => array(

	        	array(
				'name' => __( 'Display Clients?', 'meta-box' ),
				'id'   => $prefix . 'checkbox_list',
				'type' => 'checkbox_list',
				// Value can be 0 or 1

				$clients = '<div class=\'clients\'>Clients block of text...</div>',

				'options' => array(
					$clients => __( '', 'meta-box' ),
					),
				)
			)
	    );

	    return $meta_boxes;
	}

content.php:

    <?php echo rwmb_meta( 'rw_checkbox_list' ); ?>

Thanks for your help in advance!

**Comment by dacmail** [comment]
How do you fix it?
