### ISSUE TITLE
Metabox Group Clone: File upload + WYSIWYG support

### ISSUE THREAD

**Issue by Mariyo** [rilwis/meta-box#563]
Hello,
do you have plans to add "clone" support to at least one file upload and WYSIWYG editor? It would be really great and will make from the extension "must-have". We will really appreciate it...

Thx

**Comment by rilwis** [comment]
Hi Mariyo,

Yes, absolutely. That’s what I’m trying to do and that was the reason I delay releasing the Group extension (I completed it in half a year ago).

For now, you can try it with `file_input` for file upload, it works for 1 file upload.

**Comment by Mariyo** [comment]
Hi Rilwis,
that sounds great! 

Can I ask how far you are or when do you expect new release with clone support?

Thx

**Comment by rilwis** [comment]
I'm afraid I can't say exactly when. But in the next week, I'll try my best to locate the problem and fix it.

**Comment by Mariyo** [comment]
Thx, hope you will be lucky :)

Let me know if you needed any help with testing or other..

**Comment by Mariyo** [comment]
Hi Rilwis,

do you have any update on this issue?

**Comment by rilwis** [comment]
Not yet, the wysiwyg is quite complicated to handle. I'm trying to work with it.

**Comment by Pistil-Studio** [comment]
Hi, i'm waiting for this update with impatience :)

**Comment by vekexasia** [comment]
me too.. I also paid the group clone but without checking it before. this is quite unusable right now!

**Comment by skelly-jbfc** [comment]
Any insight on getting a group containing a WYSIWYG editor to be cloneable? I don't mind hacking it myself, just not really sure where to start.

**Comment by kdemi** [comment]
Cloneable wysiwyg would be phenomenal.

**Comment by funkedgeek** [comment]
The file_advanced field will support cloning in the next version.

**Comment by joshuagarity** [comment]
Any update on this? It's almost a year old now and not being able to support cloned groups that contain a WYSIWYG is a major issue.

**Comment by rilwis** [comment]
We've solved the clone problem with file and image fields (it works in the latest version of Meta Box). We're working on WYSIWYG field. We have a basic solution (for old version of MB) and we are revamping the code to make it works with latest version.

**Comment by spagi** [comment]
Hi Rilwis, any update? I really need this feature :)

**Comment by rilwis** [comment]
I've just made a commit fafe8825e244a4f8b5cb49a9d176e9b00aff9ff8, which allows you to clone WYSIWYG fields. It hasn't work for group yet. It works as a standalone field only. I will keep working on that.

Can you please help me to check it? It's in the `clone-wysiwyg` branch:

https://github.com/rilwis/meta-box/tree/clone-wysiwyg

**Comment by rilwis** [comment]
The new [version 4.8.3 now supports cloning WYSIWYG field](https://metabox.io/cloning-wysiwyg-supported/).
