### ISSUE TITLE
call_user_func() expects parameter 1 to be a valid callback (/inc/meta-box.php)

### ISSUE THREAD

**Issue by rolandinsh** [rilwis/meta-box#564]
call_user_func() expects parameter 1 to be a valid callback, first array member is not a valid class name or object 
`…func called at /.../wp-content/plugins/meta-box/inc/meta-box.php (80)`
`…onstruct called at /.../wp-content/plugins/meta-box/inc/init.php (19)`
`in rwmb_register_meta_boxes called at ? (?)`

PHP 5.5.9 / Ubuntu 14 / Apache 2.4

**Comment by rilwis** [comment]
I got this bug sometimes and after checking I found that I forgot to set field type somewhere. Can you please check all fields for that?

**Comment by rolandinsh** [comment]
look like You were right. I had old workaround for older meta-box versions when there was no 'post','taxonomy','attachemt' support. 

If someone get same error, check: 
https://github.com/rilwis/meta-box/blob/master/demo/demo.php#L310 
https://github.com/rilwis/meta-box/blob/master/demo/demo.php#L324
