### ISSUE TITLE
I can get the medium thumb with the image_advanced

### ISSUE THREAD

**Issue by jgldev** [rilwis/meta-box#568]
There's a way to get a not crop medium thumbnail from the image advanced metabox? I just can get a thumbnail 150x150 cropped.

**Comment by rilwis** [comment]
Is there a good reason that you use a custom thumbnail size in the admin area?

Because we think that in the admin area, there's no need to display full size or custom size of images which reduces loading time and they're not used to display to users like in the frontend.

**Comment by jgldev** [comment]
thanks for your soon answer, I just checked in the forums and solved my problem. I was trying to get the medium size thumbnail in the front end, I just found the answer here. https://wordpress.org/support/topic/define-image-sizes-with-plupload

Thanks anyway, I really love this plugin.
