### ISSUE TITLE
Pulling Images into shortcode

### ISSUE THREAD

**Issue by Paulbarrera12** [rilwis/meta-box#569]
I'm having an issue pulling Images into shortcode and im not sure which code to use.

I used the 'Get custom field value and display in the frontend' as the 'get_post_meta' does not work
`$images = rwmb_meta( 'ch_box_image', 'type=image' );`
`foreach ( $images as $image ) {`
    `$output .= "<img src='{$image['url']}' width='{$image['width']}' height='{$image['height']}' alt='{$image['alt']}' />";}`

The text and select fields are working 
`$hb_link = get_post_meta( $post->ID,'ch_link',true );`
`$hb_image = get_post_meta( $post->ID,'ch_box_image',true );	`	
`$output .= '<a class="fourcolcell" id="'.$hb_color.'" href="'. site_url($hb_link).'">';`

**Comment by rilwis** [comment]
Hi,

I'm not sure I understand 100%, can you give me more details about what you have and what you want to output?

**Comment by Paulbarrera12** [comment]
I needed to use 
`$hb_images = get_post_meta($post->ID,'ch_box_image',true);`
`$image_attributes = wp_get_attachment_image_src($hb_images, 'full');`
`$output .= $image_attributes[0];`
to display the image url.

This was a wordpress code issue, i thought I needed to include the function from the plugin to work. Thanks!
