### ISSUE TITLE
Meta Box Show Hide (Javascript)

### ISSUE THREAD

**Issue by krishna19** [rilwis/meta-box#579]
I want to purchase the plugin. before that i want to know, is it possible to show/hide metabox by using the value from custom made metabox ?
Example: if i select right sidebar layout, then the metabox for right sidebar only shown others are hide

**Comment by rilwis** [comment]
Hi @krishna19,

Unfortunately this is not supported by the extension. It supports show/hide by taxonomy, page ID, page template,..., e.g. info related to the post. In the next version, I will add feature to check by value of a selector (by `#id` or `.class` or `input[name]`).

**Comment by krishna19** [comment]
@rilwis now its possible or not ?

**Comment by rilwis** [comment]
Hi @krishna19 ,

Yes, it's possible now. Please update to version 0.2 and check out [the documentation](http://metabox.io/docs/meta-box-show-hide-javascript/).
