### ISSUE TITLE
Video Tutorials

### ISSUE THREAD

**Issue by nomansbeauty** [rilwis/meta-box#580]
Metabox latest version is awesome, great work! Are there any video tutorials available Paid / Free?
I am asking because you may know if someone has produced such training stuff? Please let me know.

Thanks.

**Comment by rilwis** [comment]
Hi, there's no video tutorials at the moment :). Do you need them to start using the plugin or for your clients?

**Comment by nomansbeauty** [comment]
Oh that's sad to hear. We need it for developers. A complete training for all the major features that will speed up learning process of using Metabox plugin for any new WP developer.

This is just my idea, I was really sad to find that there is NO such training available anywhere. So you can take it as suggestion :)
Thank you

**Comment by rilwis** [comment]
Thank you, I will think about it. (We just have few core members and the features demand are huge, we just don't have enough time to make videos). Have you looked at the [documentation](http://metabox.io/docs)? I think it's a good start for developers.

**Comment by nomansbeauty** [comment]
Okay, yes I am aware of the fact that we have docs. A separate question I had is regard Meta Box Builder. We are considering to buy this but need some clarifications:

1. The metaboxes that this extension builds will work after we remove this extension or it must be kept always? (I am asking from Premium Themes point of view).

2. The code / structure this extension builds is exactly same as the original metabox plugin or API itself or are there any kind of code-level adjustments?

Thanks for quick response.

**Comment by rilwis** [comment]
1. We need to keep the Builder plugin activated to have meta boxes. After "build", the plugin needs to register meta boxes for us to use, without the plugin, there's no way to register what we built since the Meta Box plugin doesn't read from database.
1. The code which plugin generates is exactly the same as PHP code (it's an array and stored in post content and post excerpt of the "meta box post type"). The purpose of the extension is creating a GUI for users only.

**Comment by nomansbeauty** [comment]
ok thanks, so the extension must always be activated to see its metaboxes. And we cannot use this extension to bundle in a WP Theme, is it correct or we need to get an extended license?

**Comment by rilwis** [comment]
There's no extended license for extensions :). They are all released under GPL, so you can bundle in a WP theme.

We're building import/export feature for it which I think will help a lot when bundle in a theme (so users don't need to create meta boxes manually again).

**Comment by nomansbeauty** [comment]
oh that's so cool :) We will wait for the new features :+1:
