### ISSUE TITLE
post fieldtype generates warning when defining multiple post types

### ISSUE THREAD

**Issue by jorisvm** [rilwis/meta-box#581]
Since I upgraded tot WordPress 4.2 I get a php error wich seems to have  something to do with the metabox plugin. This is the error.

Warning Illegal offset type in isset or empty in path/to/wp-includes/post.php on line 1160

I tested my code and it seems to be come down to the a piece of code in the rwmb_meta_boxes filter. To be more specific: It has some thing to do with regsitering a field type: 'post' . This my field declaration:

```
array(
	'name'        => 'Landingspagina',
	'id'          => "{$prefix}page",
	'type'        => 'post',
	// Post type
	'post_type'   => array('page', 'product'),
	'field_type'  => 'select_advanced',
	'placeholder' => 'Kies een pagina',
	// Query arguments (optional). No settings means get all published posts
	'query_args'  => array(
	    'post_status'    => 'publish',
	    'posts_per_page' => - 1,
        )
)
```
As you may notice I have specified two post types using an array. This works perfectly, but seems to be the source of the waring I mentioned above. I am using WordPress 4.2 and metabox plugin version 4.5. I hope you can fix this with information I provided.

**Comment by rilwis** [comment]
The latest commit fixes this problem :)

**Comment by tanerozturk** [comment]
Can we use some ordering(drag and drop) functionality for posts which are selected (specially when using 'field_type'  => 'select_advanced')?
