### ISSUE TITLE
Updating to 4.5 broke website!

### ISSUE THREAD

**Issue by ahmadazimi** [rilwis/meta-box#583]
Before I update this plugin to the latest version, everything work fine. as you see below, I use this method to get meta value and it returns full info about that image:

```php
$value = rwmb_meta('image', array('type'=>'image_advanced'), 15);
```

But after updating, it returns only **attachment id**! I also tried **rwmb_get_field** and always it returns false!

Can you help me please.

**Comment by streetyingyang** [comment]
I have a production site that had the same problem. Rolled back to 4.4.3. Using WP 4.2.1.

Fields for PDF and image uploads appeared to be populated, but it didn't matter if they had a file associated with them or not. Clicking Edit on an image thumbnail would take you to the image editor if the image existed or to the post in a new tab/window if there was no image.

PDF file would take on the name of the post.

![edit post development environment wordpress](https://cloud.githubusercontent.com/assets/12172433/7394572/66b37822-ee62-11e4-9b9a-508767231c08.png)

Reverting to 4.4.3 of Meta Box resolved the issue.

**Comment by rilwis** [comment]
@streetyingyang your issue is similar to #584 and is fixed. Update will available on wp.org soon :)

**Comment by rilwis** [comment]
@ahmadazimi I've just tested with `rwmb_meta` and `rwmb_get_field` and couldn't replicate the problem. Both functions return full info of the image:

http://prntscr.com/6zrneh

Can you please check again? (Maybe re-install the plugin from wp.org)

**Comment by ahmadazimi** [comment]
Thank you @rilwis for reply and checking.
I updated it again via wp.org but after updating **rwmb_meta** returns only **id**.
I'm really confused and I don't know what should I do. I drilled into your code and couldn't find any reason for this. Just found that ** rwmb_get_field** method return false in my case.
Rollin back to 4.4.3 fix the problem again for me.

Output before update:
![screen shot 1394-02-10 at 9 01 20](https://cloud.githubusercontent.com/assets/1847191/7406458/768f26fe-ef18-11e4-8645-a770d940d5ef.png)

Output after update (without any changes in code):
![screen shot 1394-02-10 at 9 01 52](https://cloud.githubusercontent.com/assets/1847191/7406479/95838cb2-ef18-11e4-8760-93e34273f3a1.png)

**Comment by streetyingyang** [comment]
@rilwis Thanks so much! :-)

**Comment by rilwis** [comment]
@ahmadazimi hmm, can you try:

```php
$images = rwmb_meta( 'image', 'type=image&multiple=1', 15 );
```

FYI: `rwmb_get_field` returns `false` when it can't find ID of that field in registered meta boxes. Can you please check field ID again?

**Comment by ahmadazimi** [comment]
Thank you @rilwis for helping me :)

I tried things you mentioned but nothing different happened. As I mentioned before, everything is okay with 4.4.3 but after I upgrade it to 4.5.1 (without any changes in my code) **rwmb_meta** function returns  only attachment id.

After reviewing your code, I found the problem ;-)
In many cases when multiple parameter is false, **get_post_meta** returns the attachment id and it is correct!

on version 4.4.3 in **helper.php** at line **170** before you check ```is_array( $meta )```, you make a query and change the ```$meta``` variable:

```php
$meta = $wpdb->get_col( $wpdb->prepare( "
	SELECT meta_value FROM $wpdb->postmeta
	WHERE post_id = %d AND meta_key = '%s'
	ORDER BY meta_id ASC
", $post_id, $key ) );
```

This query fetch meta data from DB and results is an array not attachment id.

But on version 4.5.1 in **helper.php** at line **90** you remove this section of code ( ```$wpdb->get_col``` ).
I copy and paste this part from 4.3.1 to 4.51 and the problem solved.

Can you please review your helper.php line **90**? I think you must return back that piece of code to 4.5.1

**Comment by ahmadazimi** [comment]
BTW: all this thing happened on front-end, however I've tested issue on admin area, but problem is exist there too.

**Comment by rilwis** [comment]
I just checked your screenshots above and I see you set `multiple=false`, I think it's the problem.

The piece of code to get meta value using `$wpdb` is too old, and it's basically the same as `get_post_meta`. The reason here I think is you set `multiple=false` somehow.

**Comment by ahmadazimi** [comment]
Yes!!!
That is the problem! 
I've changed the ```multiple=false``` to ```multiple=true``` and now the results is correct. But with this change I have to change all of my previous codes to work correctly. I believe it is better to add some backward compatibility to this section. Because according to documentation, we can pass ```multiple=false``` parameter. And now we should always get multiple and using ```reset()``` for example function to obtain desired value.

**Comment by rilwis** [comment]
I've just added code to force `multiple=true` for those field types. Please try :)

**Comment by ahmadazimi** [comment]
Thank you @rilwis , It seems the problem fixed :)
