### ISSUE TITLE
Image default thumbnail broken

### ISSUE THREAD

**Issue by pacikav** [rilwis/meta-box#585]
Hi 
Just installed Meta Box on two different servers and both has default thumbnail broken
http://clip2net.com/s/3gXnR7R

Here is code of metabox 
http://clip2net.com/s/3gXo8Xt

WP version is 4.2.1
Plugin version 4.5

**Comment by rilwis** [comment]
The latest commit d076fbf0c03e8746cdafb7ac0050c728c233d654 has fix for this. Plugin will be updated soon.
