### ISSUE TITLE
meta-box-group add_clone_button() missing $field param on line 143

### ISSUE THREAD

**Issue by JeppeSigaard** [rilwis/meta-box#586]
Installing and activating meta-box-group from zip in WP version 4.2.1 throws error:
> Strict Standards :  Declaration of RWMB_Group_Field::add_clone_button() should be compatible with RWMB_Field::add_clone_button($field) in --/meta-box-group/group.php on line 8

Changing line 143 to:
`static function add_clone_button($field)`
fixes the issue

**Comment by rilwis** [comment]
Hi, the latest version of Meta Box Group already has this fix. Please update the extension and Meta Box plugin.

**Comment by JeppeSigaard** [comment]
Update zip, maybe?

Issue happened on meta-box-group version 1.0 bought via metabox.io // Gumroad and installed on WP 4.2.1 yesterday, on april 29th.

Is there a newer version?

**Comment by rilwis** [comment]
Oh, sorry, I forgot to update on Gumroad. Just did it. Please upload again. Latest version is 1.0.1.

Thanks.
