### ISSUE TITLE
The map shows gray frame and doesn't work

### ISSUE THREAD

**Issue by fahidjavid** [rilwis/meta-box#587]
By default the Google Map works fine for the custom post type Metabox. 

But, When I use paid extension <strong>Meta Box Columns</strong> the Google Map doesn't work and it shows gray frame only on exploring it.

Screenshot: http://screencast.com/t/H84Whw6jgeYY

Please help to get that issue fixed.

Regards,

Fahid

**Comment by rilwis** [comment]
Hi Fahid, we've updated the JS for the map field. Please let us know if you still see the bug.

**Comment by fahidjavid** [comment]
Yes, it has been fixed.
