### ISSUE TITLE
'clone' text field broken in 4.5.1

### ISSUE THREAD

**Issue by keeth** [rilwis/meta-box#588]
Hello,

I have a field definition like the following:

            [
                'name'  => 'Need To Know',
                'id'    => 'need_to_know',
                'type'  => 'text',
                'class' => 'need-to-know',
                'clone' => true,
                'size' => 60,
            ],

On a new post, where's what I see in 4.4.1:

![screen shot 2015-05-01 at 3 10 12 pm](https://cloud.githubusercontent.com/assets/239868/7438142/3caa2d7e-f014-11e4-9cfc-dc0c3dcd4a2a.png)

On a new post, here's what I see in 4.5.1:

![screen shot 2015-05-01 at 3 00 13 pm](https://cloud.githubusercontent.com/assets/239868/7438153/5f332972-f014-11e4-81f0-019ff51d9958.png)

The input field is missing, and the 'Add' button does nothing.

Thanks!

**Comment by justinfriebel** [comment]
I think this might be with all fields. If I add clone to my URL field it does the same.

**Comment by NicolasCambas** [comment]
Same here, all my cloned fields are broken. I have a lot of them, and no one is spared!

**Comment by myprivatesandbox** [comment]
rilwis, the fix you've made introduced a new bug in "image_advanced" and "file_advanced" since they get 'multiple=true' by default. Your fix forces meta to be an array which shows a fake file or image when field is shown.

**Comment by cdlewis** [comment]
+1 All my cloned field are broken.

**Comment by rilwis** [comment]
I hope latest commit fixes the bug!

**Comment by NicolasCambas** [comment]
It's seems to work! Thank you a lot! :+1:

**Comment by hassanrazmy** [comment]
Hi Rilwis,

When it is going to be fixed on WordPress plugin directory?

Regards.

**Comment by rilwis** [comment]
Just now :). Please update!

**Comment by gguynn** [comment]
I just came here to say Thank You!

**Comment by senlin** [comment]
Thanks for the fix Rilwis!

**Comment by hassanrazmy** [comment]
Thank you Rilwis!
