### ISSUE TITLE
Is it safe to use RWMB_Image_Field::file_info?

### ISSUE THREAD

**Issue by ahmadazimi** [rilwis/meta-box#592]
Hi,

I was using ```RWMB_Helper::image_info```in my custom framework, but after updating to 4.5.2, I found that method was removed from ```RWMB_Helper``` class.
Now I wanna use ```RWMB_Image_Field::file_info``` instead of that.
Is it safe to use this method? Or maybe it will removed in the future?

**Comment by rilwis** [comment]
This is the helper method and meant to be used internally. The reason I moved this function is letting each field handles its own way to get/set value. You still can use this function in your project, I think it won't change for a long time :)

**Comment by ahmadazimi** [comment]
I got it. Thank you.

I have a plan to write some free modules for MetaBox, so I need to know about backward compatibilities in your code.

It's better if you have a long plan for MetaBox and don't remove public methods without thinking about backward compatibility ;-)

**Comment by rilwis** [comment]
I'm very carefully about backward compatibility and try to keep it as much as possible. Public functions are always backward compatible. The only thing that I change is internal functions, where file_info is one of them.

But I think it's good now and not going to be changed for years :)

By the way, hope to see your modules soon!
