### ISSUE TITLE
clone oembed field broken

### ISSUE THREAD

**Issue by senlin** [rilwis/meta-box#600]
This issue is related to [all](https://github.com/rilwis/meta-box/issues/594) the other [issues](https://github.com/rilwis/meta-box/issues/598) that deal with the latest updated breaking the clone field.

This time it is the oembed field that causes problems.

I have tried to add a similar solution as @samford has done in his PR, but the oembed field seems a bit more complicated?

**Comment by rilwis** [comment]
Looks like the `esc_meta` function doesn't work as expected, due to `array_walk_recusive` function. I will look at that.

**Comment by senlin** [comment]
As far as I can see the [oembed file](https://github.com/rilwis/meta-box/blob/master/inc/fields/oembed.php) doesn't use the `esc_meta`function...

**Comment by rilwis** [comment]
It does, as well as other fields. The `esc_meta` is called in [parent class](https://github.com/rilwis/meta-box/blob/master/inc/field.php#L270).

**Comment by rilwis** [comment]
I think it's fixed in a1f74c6b5fb58356fafc88

**Comment by senlin** [comment]
I can give this a go if you want, but I'm wondering whether you're now not double escaping?

On line 301 you add the `esc_meta` function to `$meta`(`$meta = array_map( array( __CLASS__, 'esc_meta' ), $meta );`)
And then on line 304 you escape that again with `return esc_attr( $meta );`
That seems double, no?

**Comment by rilwis** [comment]
No, it checks for `is_array`: if is array -> run function for each element of the array via `array_map`, otherwise run `esc_attr`.

**Comment by senlin** [comment]
ah ok, well then the fix works :)
