### ISSUE TITLE
Change Clone button text (group)

### ISSUE THREAD

**Issue by thatvideowebguy** [rilwis/meta-box#601]
Hi I tried to change the clone text button with 

```php
add_filter( 'rwmb_group_add_clone_button_text', 'prefix_group_add_clone_button_text', 10, 2 );
function prefix_group_add_clone_button_text( $text, $field )
{
    return __( '+ Ajouter', 'textdomain' );
    // If you want to change text by field, you can do something like this
    // if ( 'group_id' == $field['id'] )
    // {
    //     $text = __( '+ Add more chapter', 'textdomain' );
    // }
    // return $text;
}
;
```

But didn't work, any idea ?

thanks

**Comment by rilwis** [comment]
I'm wondering where do you place this code? It just works to me.

**Comment by thatvideowebguy** [comment]
on functions.php ?

Aurélien Bonsignore
That Video / web Guy

www.thatvideoguy.be <http://www.thatvideoguy.be/>
www.thatwebguy.be <http://www.thatwebguy.be/>
aurelien.bonsignore@gmail.com <mailto:aurelien.bonsignore@gmail.com>
Tel: 0032(0)474 586 513
TVA: BE 0845878897

**Comment by thatvideowebguy** [comment]
@rilwis can you explain please ? what am i doing wrong ?
Have i to change prefix or group ?

**Comment by rilwis** [comment]
Can you please tell me if it worked again? I've updated the Group extension several times.
