### ISSUE TITLE
'clone' => true doesn't work

### ISSUE THREAD

**Issue by Jelena1** [rilwis/meta-box#602]
field doesn't work and I get this error "Array to string conversion in C:...\meta-box\inc\fields\text.php on line 28, metabox plugin is included in theme.

**Comment by rilwis** [comment]
This bug is fixed by this commit a1f74c6b5fb58356fafc88

**Comment by Jelena1** [comment]
Unfortunately still the same error.

**Comment by rilwis** [comment]
Can you please share the code you use to register meta box and fields?

**Comment by Jelena1** [comment]
registered metabox:

$prefix = 'prefixa_';

$meta_boxes[] = array(
'id' => "{$prefix}icon",
'title' => __( 'Icon', 'text' ),
'post_types' => array( 'typeone' ),
'context' => 'normal',
'priority' => 'high',
'autosave' => true,
'fields' => array(

  // Text
  array(
  // Field name - Will be used as label
  'name' => __( 'Icon', 'text' ),
  // Field ID, i.e. the meta key
  'id' => "{$prefix}icon",
  // Field description (optional)
  'desc' => __( 'description', 'text' ),
  'type' => 'text',
  // Default value (optional)
   'std' => __( 'example', 'text' ),
  // CLONES: Add to make the field cloneable (i.e. have multiple value)
  'clone' => true
  ),

)
);

in custom post type: 

<?php 
$icon = rwmb_meta('prefixa_icon'); 
if ($icon) {
  echo $icon;
}
?>

**Comment by Jelena1** [comment]
If clone is false it works ok, if clone is true field can't be copied (plus button doesn't work).

**Comment by rilwis** [comment]
Did you created the field with `clone=false` first, then added value, then converted to `true`? From the error above, I think the value is saved before (string) cannot be converted to array for clone.

**Comment by Jelena1** [comment]
Yes but I tried again with new post for that custom post type and error is the same. Maybe it is js error? Because "plus" button simply does nothing on click.

**Comment by funkedgeek** [comment]
I can't replicate this in the latest version.  Closing this for now, please update if it's still broken for you
