### ISSUE TITLE
meta-box-group premium plugins installation problem.

### ISSUE THREAD

**Issue by anik4e** [rilwis/meta-box#603]
hi, i recently buy your plugins meta-box-group. When i active this plugins then meta-box-group plugins show a error message.

Strict Standards: Declaration of RWMB_Group_Field::add_clone_button() should be compatible with RWMB_Field::add_clone_button() in /Applications/MAMP/htdocs/wordpress/soccer/wp-content/plugins/meta-box-group/class-rwmb-group-field.php on line 145

What can i do?

Is it possible to integrate this plugins with theme. If possible then how?

Thanks.

**Comment by rilwis** [comment]
Hi,

Can you please re-download the plugin? I already fixed this bug weeks ago. Can you tell me which payment gateway you used so I can check again?

If you want to integrate the plugin with theme, please use [TGM Activation Class](http://tgmpluginactivation.com/)
