### ISSUE TITLE
Using Select2 'maximumSelectionLength' for taxonomy select_advanced

### ISSUE THREAD

**Issue by brehouse** [rilwis/meta-box#604]
I am trying to create a select_advanced dropdown that allows the user to select 3 categories at most out of a larger list. I have tried several approaches (this, checkbox_list, altering the js for both) and nothing seems to work (user can choose as many as they want). 

In the documentation for select_advanced (http://metabox.io/docs/define-fields/#section-select-advanced) it states that we can use the options that Select2 offers. I've tried using 'maximumSelectionLength' from https://select2.github.io/examples.html but it is not working. 

Is this option not available? If not, is there an alternative solution for this problem using either checkbox or multi select? JS has not worked for either.

**Comment by rilwis** [comment]
Hello,

The current version of select2 included in the plugin is 3.5.2, where the option name is `maximumSelectionSize`. Can you please try this option?

I will update select2 to latest version 4.0.0 as it's stable now. Then you can use `maximumSelectionLength` parameter.

**Comment by brehouse** [comment]
Thanks, that worked great!

When will you be adding that so I know when to change the name?

**Comment by rilwis** [comment]
In next couples of days I will release new version. I'm fixing other bugs as well. I suggest you use both parameters in the code, so when new version is released, you don't have to change your code :)
