### ISSUE TITLE
metabox's data are all blank in admin panel

### ISSUE THREAD

**Issue by mukiwu** [rilwis/meta-box#605]
I use metabox for many post type and pages / post  ... etc.
but when I want to update my message, I found that meta box don't save data in admin panel.

this is my front website page screenshot:
![2015-05-19 11 51 14](https://cloud.githubusercontent.com/assets/3794103/7695118/3e31e454-fe1d-11e4-9f53-c38353231997.png)

but in my admin panel, it show blank for me:
![2015-05-19 11 51 57](https://cloud.githubusercontent.com/assets/3794103/7695128/57034126-fe1d-11e4-8e66-c7a46660ff07.png)

I can't update, because if I update my post, my data will be deleted in page, ( I've try before ..., actually my data was 30+ before, and they all disappear because I update the post : \ )

not only this case, many of my metabox setting has same problem: it all blank in admin panel 

here is my code snippet

```
<?php

add_filter( 'rwmb_meta_boxes', 'meta_resource' );

function meta_resource($meta_boxes) {
	$prefix = 'resource';

	$meta_boxes[] = array(
		'title'    => '資源收集',
		'pages'    => array('page'),
		'autosave' => true,
		'only_on'  => array(
			'template'    => array('resource.php'),
			'id'          => array(210),
		),
		'context'  => 'normal',
		'priority' => 'high',

		'fields' => array(
			array(
				'id'     => 'resource',
				'clone'  => true,
				'type'   => 'group',
				'fields' => array(
					array(
						'name' => '標題',
						'id'   => "title",
						'type' => 'text',
					),
					array(
					'name' => '連結',
					'id'   => "link",
					'type' => 'text',
					),
					array(
						'name' => '簡單介紹',
						'id'   => "introduce",
						'type' => 'textarea',
						'cols' => 20,
						'rows' => 6,
					),
				),
			),
		),
	);

	return $meta_boxes;

	add_action( 'admin_init', 'meta_resource');
}
?>
```

**Comment by rilwis** [comment]
I think the way you register meta boxes is wrong. There's no `admin_init` hook here.

Also from what I see, `only_on` seems to be similar to the demo file. If you want to use that, please use the similar code on demo, not using filter `rwmb_meta_boxes`.
