### ISSUE TITLE
Outside plugin directory JS problem

### ISSUE THREAD

**Issue by ippiel** [rilwis/meta-box#607]
Hello,

Is it possible to add this plugin outside the plugin directory?
In my theme directory i have a folder named 'Admin', in this folder i wan't to place the Meta-Box plugin folders and files.

Everything works fine until the Javascript files, it's look like the JS files won't be registered. 

How is it possible to register the JS files?

**Comment by rilwis** [comment]
You need to define 2 constants to make Meta Box works:

```php
define( 'RWMB_URL', $url );
define( 'RWMB_DIR', $dir );
```
