### ISSUE TITLE
Image list works only on first post

### ISSUE THREAD

**Issue by eyalbin** [rilwis/meta-box#608]
I created a multi image uploader meta-box for a custom post type, but it works and display selected images only for the first post.

This is the code I am using:

for the function - 
function register_meta_boxes( $meta_boxes )
{
	
	$meta_boxes[] = array(
		'pages'    => array( 'date_info' ),
		'title'  => __( 'Upload images', 'your-prefix' ),
		'fields' => array(
			// HEADING
			array(
				'type' => 'Select images for the product gallery (max. 5 images per product)',
				'name' => __( 'Heading', 'your-prefix' ),
				'id'   => 'fake_id', // Not used but needed for plugin
				'desc' => __( 'Select images for the product gallery', 'your-prefix' ),
			),
			array(
				'name'             => __( 'Image Advanced Upload', 'your-prefix' ),
				'id'               => "imgadv",
				'type'             => 'image_advanced',
				'max_file_uploads' => 5,
			),
		)
	);
	return $meta_boxes;

The script in the post template page - 

      $images = rwmb_meta( 'imgadv', 'type=image_advanced&size=full' );
                foreach ( $images as $image ) { 
                    $imagePath = "{$image['url']}"; 
                    ?>
                    <li><img src="<?php echo $imagePath; ?>" /></li>
                    <?php
                }  wp_reset_postdata(); 

As I wrote, it works, but only for the first post created.

**Comment by rilwis** [comment]
I think you should pass the post ID into `rwmb_meta` function as the third parameter.

**Comment by eyalbin** [comment]
I tried passing the ID, still no success :(.

Code:

$post_id = get_the_ID();
$images = rwmb_meta( 'imgadv', 'type=image_advanced&size=full', $post_id );
                foreach ( $images as $image ) {
                    $imagePath = "{$image['url']}"; 
                    ?>
                    <li><img src="<?php echo $imagePath; ?>" /></li>
                    <?php
                }   

I t

**Comment by eyalbin** [comment]
I found a solution.

proper way to get the post id is:

$post = $wp_query->post;
$post_id = $post->ID;

Then put in the function:

$images = rwmb_meta( 'imgadv', 'type=image_advanced&size=full', $post_id );
