### ISSUE TITLE
Feature Request: Make Post Relations Possible

### ISSUE THREAD

**Issue by kkeiper1103** [rilwis/meta-box#610]
Maybe this is outside the scope of the plugin, but it would be incredibly useful if post type relations were possible using metabox. I realize that there is a "post" type of metabox, but this simply sets an id within the post_meta; if I go to the related post, I cannot tell that it's inversely related. 

Would it be possible to implement real relations?

**Comment by funkedgeek** [comment]
Currently not possible without building a separate table.  There are other plugins like [Posts 2 Posts](https://wordpress.org/plugins/posts-to-posts/) that handle this
