### ISSUE TITLE
Datepicker not adding ID

### ISSUE THREAD

**Issue by AlexElric** [rilwis/meta-box#611]
I've been using your metaboxes for a while and I have to say that you are amazing, thank you very much. But something happened with the datepicker, it was working days ago but yesterday I realized that it wasn't adding the id, is just in blank. Do you have any idea why can this be ?
Everything seems to be fine when I add the field in the backend.
![screen shot 2015-05-27 at 10 32 07 am](https://cloud.githubusercontent.com/assets/12629034/7840186/bd0760d0-045b-11e5-97e2-b3bda415b8c5.png)

**Comment by thaoha** [comment]
The id will be set by js function when this function called: datetimepicker( options ). Did you use any option in js_options attribute of metabox. Please turn on browser console to check js error and show me the code you used.
