### ISSUE TITLE
add Metabox fields to WordPress SEO Content Analysis

### ISSUE THREAD

**Issue by senlin** [rilwis/meta-box#612]
A [topic](https://www.facebook.com/groups/advancedwp/permalink/960441190684762/) on one of the WP related FB groups introduced a [premium plugin](http://neversettle.it/buy/wordpress-plugins/ns-automation-for-wordpress-seo/) that lets you include custom fields in the Yoast WordPress SEO keyword analysis.

One of the commenters found the price of the plugin too high and decided to code something together and make it available via a [Gist](https://gist.github.com/JeroenSormani/41cffb09a79578aafff6).

The Gist focuses on ACF, but I think this should be quite easy to adapt for the Meta Box plugin.

Two questions:
* Is it indeed fairly easy to change the snippet for Meta Box?
* Do you think it is it a useful addition?

**Comment by rilwis** [comment]
Hi @senlin , this is a great idea.

After seeing the demo video and the Gist, I think it's easy to adapt the Gist for Meta Box: just adding a new parameter for fields and use it to check when include in the analyzed content.

Maybe a free extension?

**Comment by senlin** [comment]
Glad you like it :)

Yes, I think a free extension should do it.

**Comment by rilwis** [comment]
Hi @senlin , the extension is available on [Github now](https://github.com/rilwis/mb-wordpress-seo). I'm submitting to wordpress.org, hope it will be available there soon :)

**Comment by senlin** [comment]
Hey @rilwis that's awesome! And great idea to just make it as an additional parameter, that way it is the most flexible to setup! Can you please update this thread once wordpress.org has approved the plugin?
Cheers,
Piet

**Comment by rilwis** [comment]
Absolutely. I sumitted and also make it available on [metabox.io](https://metabox.io/plugins/meta-box-yoast-seo/). I will update here when it's approved on wordpress.org.

**Comment by senlin** [comment]
:+1:

**Comment by rilwis** [comment]
The plugin is available on [wordpress.org](https://wordpress.org/plugins/meta-box-yoast-seo/), enjoy!

**Comment by senlin** [comment]
Yay!

**Comment by senlin** [comment]
Just noticed [this post](https://yoast.com/yoast-seo-breaking-api-changes/) over at yoast.com.

From that post:

> The most important filter, that most plugins and themes use, is `wpseo_pre_analysis_post_content`. If you use that filter, you will need to make changes as that filter is going away entirely.

You still have some time though, as they will be releasing this update on November 2nd, 2015

**Comment by rilwis** [comment]
Just close this issue as the extension has a fix for the update from Yoast.
