### ISSUE TITLE
Clone-able Text Field inside Group

### ISSUE THREAD

**Issue by josh-rathke** [rilwis/meta-box#614]
Is there any chance this will be added in a future release? Currently this error appears when you try to insert a clone-able text field into a group.

```Warning: Invalid argument supplied for foreach() in /Applications/MAMP/htdocs/development.ywammontana.org/watertower-content/plugins/meta-box/inc/field.php on line 74```

**Comment by josh-rathke** [comment]
I had some time to fiddle with the plugin. It looks like the base Meta-Box plugin handles the "clone" function, which includes "Groups". The tricky part is stopping the group from cloning, "Cloned" text fields. I would imagine the more common use case will be for someone to want to have a "Group" that contains a text field that is clone-able, but that's where they'll want the "Group" cloning to stop. For instance I am trying to develop a "mock weekly schedule" app for a small college and it would be awesome to have a group of fields like Day and Schedule Blocks, where Schedule Items is clone-able to accommodate for multiple Schedule Items per day and each day may have a different number of Items.

**Comment by rilwis** [comment]
I've just released a new version for Group extension which allows us to clone text fields in a group. But either the group or the sub-field is non-cloneable, e.g. not both of them are cloneable.

**Comment by rilwis** [comment]
The new version 1.1 of the Group extension now supports this :). Please update the extension (and use with latest version on Github).
