### ISSUE TITLE
Get error ( http:// wrapper is disabled in the server configuration by allow_url_include=0 )

### ISSUE THREAD

**Issue by hamdan-mahran** [rilwis/meta-box#617]
Hello rilwis meta-box Team,

Thanks very much for this awesome plugin :)

I face this error when i trying to include the plugin in my theme http://awesomescreenshot.com/00f4ytiwa7

<pre>

Warning: require_once(): http:// wrapper is disabled in the server configuration by allow_url_include=0 in D:\xampp\htdocs\hamdan-wp\wp-content\themes\hamdan\theme-admin\metaboxes\meta-box.php on line 31

Warning: require_once(http://localhost/hamdan-wp/wp-content/themes/hamdan/theme-admin/metaboxes/inc/common.php): failed to open stream: no suitable wrapper could be found in D:\xampp\htdocs\hamdan-wp\wp-content\themes\hamdan\theme-admin\metaboxes\meta-box.php on line 31

Fatal error: require_once(): Failed opening required 'http://localhost/hamdan-wp/wp-content/themes/hamdan/theme-admin/metaboxes/inc/common.php' (include_path='.;\xampp\php\PEAR') in D:\xampp\htdocs\hamdan-wp\wp-content\themes\hamdan\theme-admin\metaboxes\meta-box.php on line 31
</pre>

I hope to tell me how to fix this error.

Thanks!

**Comment by hamdan-mahran** [comment]
i Edit the php.ini and enable the following 2 settings.

allow_url_fopen = On
allow_url_include = On

The previous error is gone, but i get other error 
<pre>
 Fatal error: Call to undefined function add_action() in D:\xampp\htdocs\hamdan-wp\wp-content\themes\hamdan\theme-admin\metaboxes\inc\init.php on line 2
</pre>

**Comment by hamdan-mahran** [comment]
There are no support yet !!

**Comment by tanng** [comment]
Can you show me the way you include this plugin on theme?

Btw, I'd recommend that you install Meta Box plugin and register meta box in your theme, not include this plugin into your theme. Then you can update plugin easily without error.

Please follow this guide: http://metabox.io/docs/registering-meta-boxes/

**Comment by sundarrinsa** [comment]
<!DOCTYPE html>
<html>
<body>

<h1>Welcome to my home page!</h1>
<?php 
//include 'https://www.w3schools.com/php/demo_include3.php';

require_once dirname( __FILE__ ) . 'https://www.w3schools.com/php/demo_include3.php'

  //require_once(www.w3schools.com/php/demo_include3.php)
  
//include($_SERVER['DOCUMENT_ROOT']."w3schools.com/php/demo_include3.php");

//echo "I have a $color $car.";

?>

</body>
</html>
