### ISSUE TITLE
taxonomy term splitting an issue?

### ISSUE THREAD

**Issue by senlin** [rilwis/meta-box#619]
I'm not entirely sure whether or not this affects Meta Box, but I see ACF and Types in the list, so I thought to post it here. Please close it if this is a non-issue.

Via [make.wordpress.org/core](https://make.wordpress.org/core/2015/02/16/taxonomy-term-splitting-in-4-2-a-developer-guide/) comes the final call for plugin developers to make them aware of this "issue".

**Comment by rilwis** [comment]
After 2 versions of WordPress (since 4.2), I think this problem don't affect too much to Meta Box :)
