### ISSUE TITLE
rwmbSelect is not defined

### ISSUE THREAD

**Issue by ryanlabelle** [rilwis/meta-box#620]
Any one else getting the "rwmbSelect is not defined" JS error on the new 4.5.4 ?

**Comment by ryanlabelle** [comment]
Chrome devtools:

http://new.tinygrab.com/6407caa59e4af0b8195edc2dba08ee1c407b99544f.png

http://new.tinygrab.com/6407caa59e1168c4caa179022047e5daef8409362e.png

Thanks.

**Comment by trofimov-aleks** [comment]
I have the same error (v4.5.4)..

**Comment by thaoha** [comment]
Thanks, I fixed it.
https://github.com/rilwis/meta-box/commit/7b880dbab11e4760807faac032b58058a09f7eff

**Comment by ryanlabelle** [comment]
Awesome, thanks! Any idea when this fix will be pushed out to the WP Plugin repository? We have a theme that bundles the plugin and it's breaking the page builder. We are using tgm plugin activation to bundle / update. Cheers!

**Comment by rilwis** [comment]
I will update the plugin today. Please wait!

**Comment by ryanlabelle** [comment]
No worries. I didn't mean to sound pushy, I was just looking for an eta so I could alert those having issues. I'll try and do some more beta testing so I can get ahead of the updates / releases. Thanks again for all your hard work. Please let us know how we can contribute. I've already purchased a few extensions but happy to support in other ways too.

**Comment by rilwis** [comment]
It's fine :). I also want to release the fix as soon as possible. I'm fixing this bug #621 and when I'm done, I'll upload both fixes to wp.org.

You can contribute to the plugin by fork this repo, make patches and create pull requests. Github wrote a detailed guide [here](https://guides.github.com/activities/contributing-to-open-source/) and you can follow it.

Regarding the premium extensions, we have private repos at bitbucket.org. You can help us by opening a topic in our [support forum](http://metabox.io/support/) (maybe include code). We will merge the code.

**Comment by rilwis** [comment]
FYI, the version 4.5.5 is available on wp.org. Please update :)
