### ISSUE TITLE
Taxonomy select box problem

### ISSUE THREAD

**Issue by tinyHacker** [rilwis/meta-box#624]
Hello, i'm very thanful for your work on such a plugin, it really saved me.

I'm facing a problem with the taxomony select box, it is not saving the metadata to the post, and not loading it, while all other field types are working fine, but the taxomony one using the select_advanced style is not creating a new metadata field or load it.

here is the code:
```
array(
        'name' => __( 'البلد:', $prefix_translation ),
        'id' => "{$prefix_translation}country",
        'type' => 'taxonomy',
        'options' => array(
          'taxonomy' => 'category',
          'type' => 'select_advanced',
          'args' => array('hide_empty'=>false, 'child_of'=>12)
        ),
        'placeholder' => __( 'اختر من القائمة..', $prefix_belief ),
),
```
+ i'm using the latest version of wordpress and meta-box.

thanks for helping :)

**Comment by rilwis** [comment]
Hi, the `taxonomy` field doesn't add meta data for posts. Instead of that, it will set terms for posts, similarly when you select terms from default WP meta boxes. In short, it just provide another UI to set taxonomy terms.

**Comment by funkedgeek** [comment]
When you save the file, does the field update with the selected taxonomy term?

**Comment by funkedgeek** [comment]
Closing this as taxonomy is working the way it should work.
