### ISSUE TITLE
Timestamp warning message

### ISSUE THREAD

**Issue by zabestof** [rilwis/meta-box#626]
Hey,

When using the datetime option and set the timestamp option to true I always get this warning:

Warning: date() expects parameter 2 to be long, string given ..inc\fields\datetime.php on line 98

If I select a date and time and hit save the warning disappears.

The problem appears on the demo fields too when enabling timestamp.

Cheers!
Chris

**Comment by rilwis** [comment]
Thanks for reporting. It's just fixed now!
