### ISSUE TITLE
Color picker small issue

### ISSUE THREAD

**Issue by trofimov-aleks** [rilwis/meta-box#627]
Hello!

I have a small problem with the Color picker:

![color_z_index](https://cloud.githubusercontent.com/assets/7106468/8375057/380398d2-1c0b-11e5-8bca-03f87c5614c6.png)

It seems that this problem is easily solved by adding "z-index: 1;" to the ".rwmb-color-wrapper .wp-picker-holder" (/meta-box/css/color.css):

![color_z_index_2](https://cloud.githubusercontent.com/assets/7106468/8375071/4dd6ae7e-1c0b-11e5-9be1-73e76de154f9.png)

It would be great if you add this to the new version of the plugin :)

Thank you very much for your work! You are the best!
Best regards, Alexey

**Comment by rilwis** [comment]
Done! Thanks for your suggestion :)
