### ISSUE TITLE
Post field type ordering

### ISSUE THREAD

**Issue by tanerozturk** [rilwis/meta-box#628]
Can we use some ordering(drag and drop) functionality for posts which are selected (specially when using 'field_type' => 'select_advanced')?

**Comment by funkedgeek** [comment]
Limitations for this are limitations for the select_advanced field.  If the code source for that field gets updated to include this, we'll add it.

**Comment by rilwis** [comment]
I think we already can sort selected posts if we setup the field with `'multiple' => true` and `'clone' => false`, can't we?
