### ISSUE TITLE
Multiple color pickers

### ISSUE THREAD

**Issue by p2or** [rilwis/meta-box#629]
Hi,

when implementing **multiple color pickers**, it results in a css z-index display error:

![screenshot](https://cloud.githubusercontent.com/assets/512368/8496186/73854366-2173-11e5-994c-aba9f4811d48.png)

_I think this is a very special case. Editing the color works fine, so this is more like a feature request._

**Comment by funkedgeek** [comment]
Weird, not replicating this.

**Comment by rilwis** [comment]
I think I resolved this problem in #627

**Comment by p2or** [comment]
Thanks! Now, it's working as expected.
