### ISSUE TITLE
Getting custom fields to WP-API

### ISSUE THREAD

**Issue by martinsookael** [rilwis/meta-box#631]
How can I get WP-API to retrieve also the custom fields set by metabox?

**Comment by rilwis** [comment]
Hi, the custom fields set by Meta Box plugin are mostly saved in the DB as typical fields. For more information, please [read this documentation](https://metabox.io/docs/how-post-meta-is-saved-in-the-database/).

For more information about using WP-API to retrieve post meta, please follow [this instruction](http://wp-api.org/#posts_retrieve-meta-for-a-post)

**Comment by jackyon** [comment]
@rilwis, looks like wp rest api v2 have removed the this doc. I can't find it on http://v2.wp-api.org/

**Comment by eeynard** [comment]
Hi,

Here is how i do it :
```php
function add_myCPT_metabox_to_json($data, $post, $request) {
    $custom_meta = array();
    $prefix = 'myCPT_';

    $response_data = $data->get_data();
    if ($request['context'] !== 'view' || is_wp_error($data)) {
        return $data;
    }

    $authorized_metadata = array(
        'meta1',
        'meta2'
    );

    $authorized_serialized_metadata = array(
        'multipleMeta1',
        'multipleMeta2'
    );

    foreach (get_post_meta($post->ID, '', false ) as $key => $value) {
        $sliced_key = str_replace($prefix, '', $key);

        if (count($value) != 0 && in_array($sliced_key, $authorized_metadata)) {
            $custom_meta[$sliced_key] = count($value) === 1 ? $value[0] : $value;
        } else if (count($value) != 0 && in_array($sliced_key, $authorized_serialized_metadata)) {
            $custom_meta[$sliced_key] = unserialize($value[0]);
        }
    }

    $response_data['custom_meta'] = $custom_meta;
    $data->set_data($response_data );

    return $data;
}
add_filter('rest_prepare_myCPT', 'add_myCPT_metabox_to_json', 10, 3);
```
I just added a hook to WP-API response. 

- myCPT is the name of your custom_post_type
- authorized_metadata contain ids (without prefix) of single result metaboxes
- authorized_serialized_metadata contain ids (without prefix) of multiple result metaboxes

Exemple of registered metabox:
```php
$prefix = 'myCPT_';

$meta_boxes[] = array(
    'title'      => __('Metaboxes', 'myCPT'),
    'post_types' => 'custom_layer',
    'fields'     => array(
        array(
            'id'   => $prefix . 'meta1',
            'name' => __('Text field', 'myCPT'),
            'type' => 'text'
        ),
        ...
)
```

After adding this hook you should see a new object in your json output named custom_meta containing all your instantiated metaboxes :)

**Comment by jackyon** [comment]
@eeynard ,
wow, nice solution! love it!
thx for your solutions!
I will tried that later ;)

**Comment by rilwis** [comment]
This is done as a standalone plugin here https://github.com/rilwis/mb-rest-api. Will be soon available on WordPress.org.
