### ISSUE TITLE
image advanced unique filter

### ISSUE THREAD

**Issue by Lugat** [rilwis/meta-box#634]
Hey there,

for the first time, we had the case, that it should be able to upload/select multiple times the same image. Sadly the image advanced field removes images which are not unique. The only way to make this possible at the moment is to use the normal image field, which will upload each image to the media library.
It would be great to provide an option, if the images should be made unique or not.

Greetings,
Lukas

**Comment by rilwis** [comment]
Thanks, I will add this option :)

**Comment by funkedgeek** [comment]
So you want or don't want duplicates?

**Comment by rilwis** [comment]
@funkedgeek he wants an option so he can turn on/off duplicates.

**Comment by funkedgeek** [comment]
All the new media fields use Backbone collections, which does not support duplicates ie you can't select an uploaded file multiple times.  You can upload a file multiple times in the uploader that is in the media modal, however.
