### ISSUE TITLE
Updated from 4.5.3 to 4.5.5 and it exploded!!!

### ISSUE THREAD

**Issue by tony23456** [rilwis/meta-box#635]
After updating, it broke my access to the dashboard. It produced a warning that goes like this:

Warning: require_once(…/includes/metaboxes/inc/field-multiple-values.php) [function.require-once]: failed to open stream: No such file or directory in …/wp-content/plugins/meta-box/meta-box.php on line 33

Trying to locate 4.5.3 to re-upload.

**Comment by rilwis** [comment]
Can you check files on your server when upload? In [version 4.5.3](https://github.com/rilwis/meta-box/tree/4.5.3/inc), the file `field-multiple-values.php` exists.
