### ISSUE TITLE
Conditional logic on cloned group

### ISSUE THREAD

**Issue by nkrambo** [rilwis/meta-box#636]
Is it possible to show and hide subfields of group fields using the conditional logic extension? They are also set 'clone' => true. I have the conditional logic working for non-grouped fields, however, when I try on the subfield for group fields it won't work. It's not throwing any console errors.

I'm trying to show and hide fields based on the the 'slide_type' selected with a radio input.

```php
  // Meta Box
	$meta_boxes[] = array(
		'title'  => __( 'Slideshow', 'ep' ),
    'pages'    => array('page'),
    'include' => array(
      'template' => array( 'homepage.php')
    ),

		'fields' => array(
			array(
				'id'     => 'slides',
				'name'   => __( 'Slides', 'ep' ),
				'type'   => 'group',
        'max_clone' => 3,
        'sort_clone' => true,
				'clone'  => true,

				// List of child fields
				'fields' => array(
					array(
						'name'    => __( 'Sub Title', 'ep' ),
						'id'      => $prefix . 'sub_title',
						'type'    => 'text',
					),
					array(
						'name'    => __( 'Main Title', 'ep' ),
						'id'      => $prefix . 'main_title',
						'type'    => 'text',
					),
          array(
    				'name'             => __( 'Slide Image', 'ep' ),
    				'id'               => $prefix . 'image',
    				'type'             => 'file_input',
    				'max_file_uploads' => 1,
    			),
          array(
            'name'             => __( 'Slide Type', 'ep' ),
    				'id'	             => $prefix . 'slide_type',
    				'type'	           => 'radio',
    				'options'           => array(
    					'Action' 		=> 'Action',
    					'Video' 		=> 'Video'
    				)
    			),
          array(
    				'name' => __( 'oEmbed', 'ep' ),
    				'id'   => $prefix . 'oembed',
            'type' => 'oembed',
            'visible' => array($prefix . 'slide_type', 'Video')
    			),
				),
			),
		),
	);
```

**Comment by tanng** [comment]
Hi nkrambo,

Thanks for reporting, we're working with this bug and have a release before 28th.

Best regards.

**Comment by bucketpress** [comment]
Hi tanng, I am having the issues as nkrambo - just checking if there a fix for this yet? Thanks!

**Comment by skelly-jbfc** [comment]
It looks like this was fixed in the latest version, but I'm not sure if it's been updated in the Core Extensions Bundle files - I just downloaded, and it doesn't seem to be working. There's also no available update for the extension in my Wordpress plugins menu.

**Comment by rilwis** [comment]
Hi @skelly-jbfc and @bucketpress , I've updated the .zip files in the Core Extensions Bundle. Please update and let us know.

Thanks.

**Comment by bucketpress** [comment]
Hi @rilwis, I didn't purchase the Core Extensions Bundle, I had purchased a few extensions on their own. I've followed the download link that was sent to my email after the purchase, and downloaded from gumtree again, and got v1.03 which doesn't seem to be the latest - I believe the latest update is v1.04?

**Comment by rilwis** [comment]
Hi @bucketpress, you can go to your profile page and download the latest
version. I've just also updated files on Gumroad (the developer just
released the new version this morning).

**Comment by bucketpress** [comment]
@rilwis Thanks, working good on my side now. I guess we can close this issue. @nkrambo , is your use case for this solved with this update?
