### ISSUE TITLE
Video details

### ISSUE THREAD

**Issue by pixedelic** [rilwis/meta-box#638]
Great work here.

Is there any way to use the "video details" UI when the user upload a MP4 video to offer OGG and WEBM versions as well? Any plan to allow that in the near future?

TIA

**Comment by funkedgeek** [comment]
What video details UI?

**Comment by funkedgeek** [comment]
Can you explain what video details UI?

**Comment by funkedgeek** [comment]
Closing this for now.  Please explain what video details ui.

**Comment by funkedgeek** [comment]
This feature added in latest update
