### ISSUE TITLE
Map documentation

### ISSUE THREAD

**Issue by pixedelic** [rilwis/meta-box#639]
If I'm not wrong, there is an error in the documentation of the maps and something has been omitted: `zoom`must be passed using `js_options` argument and it can be passed `mapTypeId` as well

```php
$args = array(
    'type'         => 'map',
    'width'        => '1640px', // Map width, default is 640px. You can use '%' or 'px'
    'height'       => '480px', // Map height, default is 480px. You can use '%' or 'px'
    'marker'       => true, // Display marker? Default is 'true',
    'marker_title' => '', // Marker title when hover
	'js_options'   => array(
		'zoom'         => 14, //default value
		'mapTypeId'	   => 'ROADMAP' //select among ROADMAP, SATELLITE, HYBRID and TERRAIN
	),
);

$map = rwmb_meta( 'pix_title_map_bg', $args, $post_id );
```

Am I right? Thank you.

**Comment by rilwis** [comment]
Thanks for your comment. You're right, you can pass more parameters using `js_options` like zoom, map type, etc. However, to keep backward compatibility, you still can use `zoom` directly.

I will update the documentation for this.
