### ISSUE TITLE
Extend file_input to have image_input

### ISSUE THREAD

**Issue by bucketpress** [rilwis/meta-box#641]
Since cloning image fields is a problem, and in the support documents, it is suggested that users use file_input to insert images as URL in order to be able to clone the field. But the problem is that no preview is available. Why not have an image_input that works exactly as file_input but something that shows the image right below the field like how oembed shows the embedded html?

**Comment by rilwis** [comment]
This is a good idea!

**Comment by funkedgeek** [comment]
Cloning image_advanced is now possible.

**Comment by spendavis** [comment]
I've just purchased the metabox group extension and I'm having considerable trouble trying to render images in the frontend using image_advanced.

Do you have any example code that I might be able to try using?
