### ISSUE TITLE
how to use Update_post_meta with select_advanced

### ISSUE THREAD

**Issue by CRTIVO** [rilwis/meta-box#643]
i'm trying to post from the front-end , the value of "select_advanced" meta box and 'multiple'    => true, , doesn't work fine with me, 
i'm trying to save it's option using update_post_meta , any ideas ?

**Comment by CRTIVO** [comment]
foreach($checkboxs as $checkbox) {
                 add_post_meta( $pid, $metabox , $checkbox );
}

it work , but is there is any better way ?

**Comment by rilwis** [comment]
Yes, that the correct way to do :)
