### ISSUE TITLE
Update Select2 4.0 jQuery

### ISSUE THREAD

**Issue by Sinusite** [rilwis/meta-box#645]
Hi,
It would be nice to upgrade Select2 LIbrary 3.5.1 ==> 4.0  ( https://select2.github.io/ )

Really more powerful, extensible and clean ( No more hidden input tags )
See : https://select2.github.io/announcements-4.0.html

But yes, it is an important update... :)
Thank you.

**Comment by funkedgeek** [comment]
I'm looking into it @Sinusite.  Thanks for the heads up.

**Comment by funkedgeek** [comment]
Trying the new version and some of the WP styles mess with the select2 styles.  Trying to work up a solution

**Comment by Sinusite** [comment]
You rock :)

**Comment by funkedgeek** [comment]
Select2 4.0 is really buggy for some reason when used in WP.

**Comment by Sinusite** [comment]
Hi! any chance with the v4.0.1 ?

**Comment by Sinusite** [comment]
You guys Roxx :)
