### ISSUE TITLE
add New

### ISSUE THREAD

**Issue by kanawanzx** [rilwis/meta-box#648]
i want add new option select, then how to made

**Comment by p2or** [comment]
Hi kanawanzx,

Please provide more context to get a solid answer. First take a look into the [docs](https://metabox.io/docs/) and [templates](https://github.com/rilwis/meta-box/tree/master/demo). 

Basic option select for a custom post type called 'Author':

      array(
          'name' => __( 'Author', 'rwmb' ),
          'id' => "{$prefix}author",
          'type' => 'post',

          // Set the post type
          'post_type' => 'authors',

          // Placeholder
          'placeholder' => __( 'Choose an Author', 'rwmb' ),

          // Field type, either 'select' or 'select_advanced' (default)
          'field_type' => 'select_advanced',
      ),

*Note: Please consider that you should report issues for developers here. Might be better to ask on stackoverflow instead.*

**Comment by rilwis** [comment]
Thanks @p2or !

**Comment by kanawanzx** [comment]
thanks..... for support
