### ISSUE TITLE
Image uploads not visible after adding them, on save/reload page they are

### ISSUE THREAD

**Issue by MikevHoenselaar** [rilwis/meta-box#649]
When I upload an image a red box will show with a loading animation. After that is done it dissapears but doesnt show the image I just uploaded. When I save the post and scroll down to the Image upload section the image I just uploaded is visible. When I upload a new image (second one) the same applies.
See video of what I mean.
https://monosnap.com/file/WpWhNSo55Olr8icvhn0xYYQ9YVeU67

Previously this was working perfectly. We updated Metabox plugin (dont know from which version) and updated server. We are running the website on HipHop (HVVM) now. Maybe that is the problem?

**Comment by funkedgeek** [comment]
Looks like it gets sent to the server but something prevents the js from putting up the image.  Have you tried one of the other image fields like `image_advanced`?

**Comment by funkedgeek** [comment]
Another question: got to the console and do it again.  Do any errors pop up?

**Comment by MikevHoenselaar** [comment]
Nope, thats the strange part, no errors in Console.

**Comment by rosswintle** [comment]
Don't know if this is related. I'm having an issue with a file upload (type => 'file'). After much debugging I discovered that meta values within the same meta_box as my file upload were being attached to the post_id of the file attachment post.

The diagnosis of this involved hooking into the added_post_meta option and doing:

`error_log("DOING: $object_id $meta_key = $meta_value \n", 3, '/home/something/public_html/wp-content/errors.txt');`

This printed the following:

```
DOING: 8019 _edit_lock = 1439308388:1 
DOING: 8019 _edit_last = 1 
DOING: 8019 _edit_lock = 1439308404:1 
DOING: 8019 _edit_lock = 1439308418:1 
DOING: 8021 _wp_attached_file = 2015/08/test.pdf 
DOING: 8021 _csc_author = bbrg 
DOING: 8021 _csc_year = 2014 
DOING: 8021 _csc_hub = rl 
DOING: 8021 _csc_featured = 0 
DOING: 8019 _csc_resource_file = 8021 
DOING: 8019 _csc_resource_thumb = test.jpg
DOING: 8019 _csc_external = 0 
DOING: 8019 _csc_disable_preview = 0 
DOING: 8019 _edit_lock = 1439308423:1 
DOING: 8019 _edit_lock = 1439308424:1 
```

You can see that the author, year, hub and features meta are saved to post ID 8021, which is the attachment created by the file upload.

The rest of the meta is added to post ID 8019, which is the actual post that I'm saving.

I've had a quick look at file.php in your source code, but can't find anything odd in there.

Here's my meta box fields definition:

```
// List of meta fields
		'fields' => array(
			// FILE UPLOAD
			array(
				'name' => 'Upload a resource file',
				'desc' => 'Upload a resource file here',
				'id'   => $prefix . 'resource_file',
				'type' => 'file',
			),			
			array(
				'name' => 'Resource URL (optional)',
				'id' => $prefix . 'resource_URL',
				'desc' => 'The URL of an external resource (will not be used if a file is uploaded)',
				'type'  => 'text',
				'std' => '',
			),
			array(
				'name' => 'Resource Thumbnail URL (optional)',
				'id' => $prefix . 'resource_thumb',
				'desc' => 'The URL of a thumbnail (automatically generated from uploaded PDFs)',
				'type'  => 'text',
				'std' => '',
			),
			array(
				'name' => 'External/subscription resource',
				'id' => $prefix . 'external',
				'desc' => 'Select "Yes" to mark the resource as an external or subscription resource. Such resources do not appear in initial search results and have to be requested to be shown.',
				'type'  => 'select',
				'options' => array(
								'0' => 'No',
								'1' => 'Yes',
					),
				'std' => '0',
			),
			array(
				'name' => 'Disable Google Docs Preview',
				'id' => $prefix . 'disable_preview',
				'desc' => 'Check this to disable Google Docs preview of the resource - note that the preview only works for certain document types anyway (PDF, DOC, DOCX)',
				'type'  => 'checkbox',
				'std' => '',
			),
		)
```

My hook to do the debug looks like this:

```
add_action( "updated_post_meta", "debug_upload", 10, 4 );
add_action( "added_post_meta", "debug_upload", 10, 4 );

function debug_upload( $meta_id, $object_id, $meta_key, $meta_value ) {
	error_log("DOING: $object_id $meta_key = $meta_value \n", 3, '/home/name/public_html/wp-content/errors.txt');
}
```

Is this likely to be related to Mike's issue?

**Comment by rosswintle** [comment]
I should add that this bug is present in meta box v4.5.5 and v4.5.6. I did have a dev environment with an install of v4.3.x (I think) that seemed to be OK. When I updated from v4.3.x to v4.5.6 this bug started to happen.

**Comment by rosswintle** [comment]
OK - I just watched Mike's video and this is a different issue. I'll log it separately.

**Comment by MikevHoenselaar** [comment]
Reverted back to as far as Metabox 4.4.2. Still the same effect when uploading an image.
So it could be a WP or HVVM thing.
Anyone running their WP site on HVVM (HipHop) by any chance?
This is not funny :(

**Comment by MikevHoenselaar** [comment]
There is a new version of Metabox now, but no mention of a fix :(
Anyone experienced the same when running on HVVM?

**Comment by funkedgeek** [comment]
Has this been resolved yet?  We rewrote the way file_advanced works so I'm hoping your problem should be resolved
