### ISSUE TITLE
Meta in a meta box with a file upload is saving to the wrong post ID

### ISSUE THREAD

**Issue by rosswintle** [rilwis/meta-box#650]
I'm having an issue with a file upload (type => 'file'). After much debugging I discovered that meta values within the same meta_box as my file upload were being attached to the post_id of the uploaded file attachment post, not to the post ID of the post.

The diagnosis of this involved hooking into the added_post_meta option and doing:

`error_log("DOING: $object_id $meta_key = $meta_value \n", 3, '/home/something/public_html/wp-content/errors.txt');`

This printed the following:

```
DOING: 8019 _edit_lock = 1439308388:1 
DOING: 8019 _edit_last = 1 
DOING: 8019 _edit_lock = 1439308404:1 
DOING: 8019 _edit_lock = 1439308418:1 
DOING: 8021 _wp_attached_file = 2015/08/test.pdf 
DOING: 8021 _csc_author = bbrg 
DOING: 8021 _csc_year = 2014 
DOING: 8021 _csc_hub = rl 
DOING: 8021 _csc_featured = 0 
DOING: 8019 _csc_resource_file = 8021 
DOING: 8019 _csc_resource_thumb = test.jpg
DOING: 8019 _csc_external = 0 
DOING: 8019 _csc_disable_preview = 0 
DOING: 8019 _edit_lock = 1439308423:1 
DOING: 8019 _edit_lock = 1439308424:1 
```

You can see that the author, year, hub and features meta are saved to post ID 8021, which is the attachment created by the file upload.

The rest of the meta is added to post ID 8019, which is the actual post that I'm saving.

I've confirmed that this is happening in the database.

I've had a quick look at file.php in your source code, but can't find anything odd in there.

Here's my meta box fields definition:

```
// List of meta fields
		'fields' => array(
			// FILE UPLOAD
			array(
				'name' => 'Upload a resource file',
				'desc' => 'Upload a resource file here',
				'id'   => $prefix . 'resource_file',
				'type' => 'file',
			),			
			array(
				'name' => 'Resource URL (optional)',
				'id' => $prefix . 'resource_URL',
				'desc' => 'The URL of an external resource (will not be used if a file is uploaded)',
				'type'  => 'text',
				'std' => '',
			),
			array(
				'name' => 'Resource Thumbnail URL (optional)',
				'id' => $prefix . 'resource_thumb',
				'desc' => 'The URL of a thumbnail (automatically generated from uploaded PDFs)',
				'type'  => 'text',
				'std' => '',
			),
			array(
				'name' => 'External/subscription resource',
				'id' => $prefix . 'external',
				'desc' => 'Select "Yes" to mark the resource as an external or subscription resource. Such resources do not appear in initial search results and have to be requested to be shown.',
				'type'  => 'select',
				'options' => array(
								'0' => 'No',
								'1' => 'Yes',
					),
				'std' => '0',
			),
			array(
				'name' => 'Disable Google Docs Preview',
				'id' => $prefix . 'disable_preview',
				'desc' => 'Check this to disable Google Docs preview of the resource - note that the preview only works for certain document types anyway (PDF, DOC, DOCX)',
				'type'  => 'checkbox',
				'std' => '',
			),
		)
```

My hook to do the debug looks like this:

```
add_action( "updated_post_meta", "debug_upload", 10, 4 );
add_action( "added_post_meta", "debug_upload", 10, 4 );

function debug_upload( $meta_id, $object_id, $meta_key, $meta_value ) {
	error_log("DOING: $object_id $meta_key = $meta_value \n", 3, '/home/name/public_html/wp-content/errors.txt');
}
```

**Comment by rosswintle** [comment]
It's worth nothing that my code does all sorts of other weird stuff. I've not created a minimal replication of this yet. I'll try to do that later. In the meantime any insight you can have into this would be appreciated. I'll keep digging myself too.

**Comment by rosswintle** [comment]
OK. I have some minimum code to replicate this.  You need to have TWO meta boxes on a custom post type with a file field in the first meta box.

I've used a (relatively but not entirely) clean install of WordPress with meta_box version 4.5.6.

I'm using the twenty-fifteen theme and I've added the following code to the bottom of the functions.php of 
the theme:

```
add_filter( 'rwmb_meta_boxes', 'YOURPREFIX_register_meta_boxes' );
function YOURPREFIX_register_meta_boxes( $meta_boxes )
{
    $prefix = 'rw_';
    // 1st meta box
    $meta_boxes[] = array(
        'id'       => 'personal',
        'title'    => 'Personal Information',
        'pages'    => array( 'post' ),
        'context'  => 'normal',
        'priority' => 'high',
        'fields' => array(
            array(
                'name'  => 'File',
                'desc'  => 'A file',
                'id'    => $prefix . 'file',
                'type'  => 'file',
            ),
            array(
                'name'  => 'Text',
                'desc'  => 'Some text',
                'id'    => $prefix . 'text',
                'type'  => 'text',
            ),
        )
    );
    $meta_boxes[] = array(
        'id'       => 'More',
        'title'    => 'More Information',
        'pages'    => array( 'post' ),
        'context'  => 'normal',
        'priority' => 'high',
        'fields' => array(
            array(
                'name'  => 'More Text',
                'desc'  => 'Some more text',
                'id'    => $prefix . 'more_text',
                'type'  => 'text',
            ),
        )
    );
    return $meta_boxes;
}

add_action( "updated_post_meta", "csc_generate_resource_thumb", 10, 4 );
add_action( "added_post_meta", "csc_generate_resource_thumb", 10, 4 );

function csc_generate_resource_thumb( $meta_id, $object_id, $meta_key, $meta_value ) {
	$uploads = wp_upload_dir();
	$error_file = trailingslashit($uploads['path']) . 'errors.txt';

	error_log("DOING: $object_id $meta_key = $meta_value \n", 3, $error_file);

}

```

With this in place, if I create a new post, upload a file to the file meta, and populate both of the text boxes, the SECOND text box (meta key 'rw_more_text') is assigned to the uploaded file's attachment.

I think that I've tracked this down to the fact that you don't check the post type when saving meta.

inc/meta-box.php contains the save_post() method, which is attached to the save_post hook. The save_post() method calls the save() method for each field in the meta_box

At no point during save_post() is the type of the post being saved checked.

So the following happens:

- The post (post_type: post) is saved
- This triggers the save_post hook and the RW_Meta_Box->save_post() method for each meta box in turn
- This runs for the first meta box. It sets the $saved property to true so that this meta_box is not processed again
- The first field is the file field. It gets the upload, and creates an attachment
- Creating an attachment triggers the save_post hook and the RW_Meta_Box->save_post() method for each meta box (again)
- save_post() runs for the first meta box, but $saved was set to true earlier so nothing happens
- save_post() runs for the second meta box - it sets its own $saved property and proceeds to save all of its meta data using the post_id of the attachment that was created for the file
- that's all the meta_boxes for the attachment done, the process backs up
- save_post() now fires for the second meta_box but with the original post_id - but this now has $saved set to true, so it bails out

Solutions:

I'm not quite sure how you solve this in the general case.

My initial thought was that you just need to check the post_type of the post_id against the list of post_types that this meta_box is configured for and bail out if it doesn't match.

This would catch most cases, but you could potentially have a case where a user has created a hook that, when you save post A, created post B and as that has the same post type you'd get the bug.

Another option is to ignore saving meta if the post_id is of an attachment. Are there any cases where users might want to attach meta to an attachment? I'm not sure.

I've implemented the "bail out if the post type is an attachment" rule by adding this line to the top of the RW_Meta_Box::save_post() method:

```
if (get_post_type($post_id) == 'attachment') return;
```

That works for me, but as I say, it may not be what you want for the general case.

Hope that all made sense!

**Comment by funkedgeek** [comment]
Thank you for the research. I think we can find a solution using the specific `save_post_{post_type}` hooks instead of the generic one.  That'd make more sense to me, imho.  I'll work up a fix.

**Comment by rosswintle** [comment]
Yeah, that's a neat idea. So the RW_Meta_Box constructor would hook to 'save_post_{post_type}' for each of the configured post_types, instead of just to 'save_post'.

That works unless, as I say, the user or a plugin is doing something really weird creating another post on the save_post hook.

**Comment by funkedgeek** [comment]
Okay, change is made.  Feel free to test it to make sure the bug went away

**Comment by funkedgeek** [comment]
Okay, tested it and I think it's fixed.  Haven't been able to replicate your issue.  Let me know if its fixed for you.

**Comment by funkedgeek** [comment]
Fixed a typo that broke everything

**Comment by rilwis** [comment]
Thank you guys @rosswintle and @funkedgeek !

**Comment by funkedgeek** [comment]
@rosswintle Has the commit fixed your problem?

**Comment by rosswintle** [comment]
I've not had time to test it I'm afraid and I have my own solution in place. I'll try to test it at some point.

Were you unable to replicate?

**Comment by funkedgeek** [comment]
Not able to replicate after the fix

**Comment by funkedgeek** [comment]
Closing this as fixed
