### ISSUE TITLE
meta boxes in front end

### ISSUE THREAD

**Issue by khodorhammoud** [rilwis/meta-box#651]
I'm working on a theme that enables users to publish custom post types from the front end, and some of the content they can include in the post are images and map locations,.
So is there a way to display meta boxes in front end?
I am not looking for a way to display the meta box content in front end, but the actual meta box.
Thank you in advance

**Comment by funkedgeek** [comment]
This is more or a question to ask the WordPress developers.  This goes beyond the scope of this plugin.
