### ISSUE TITLE
Wrong images when duplicate post to another language in WPML

### ISSUE THREAD

**Issue by uiliw** [rilwis/meta-box#652]
I have an advanced image input that has a bunch of images, and when i duplicate this post to translate it for another language with WPML, those images are all the same from the first image from the gallery... any clue how to fix this?

1. image galery
<img width="1265" alt="captura de tela 2015-08-18 as 21 00 16" src="https://cloud.githubusercontent.com/assets/4606715/9345887/0a663442-45ec-11e5-956e-5d5989202232.png">

2. ready to duplicate for other languages
<img width="1254" alt="captura de tela 2015-08-18 as 21 00 30" src="https://cloud.githubusercontent.com/assets/4606715/9345896/1572c86e-45ec-11e5-9fb8-125c36583128.png">

3. in other language the images are all the same from the first onte
<img width="1262" alt="captura de tela 2015-08-18 as 21 01 17" src="https://cloud.githubusercontent.com/assets/4606715/9345905/24c8464a-45ec-11e5-9c41-14883cbb9530.png">

**Comment by funkedgeek** [comment]
Not sure how to replicate this.

**Comment by senlin** [comment]
@uiliw Have you installed **and set up** the WPML Media addon?

**Comment by funkedgeek** [comment]
This bug might be resolved in the next version of MB.  The new image advanced fields will use new code that might help with the trade off that the field won't be saved by ajax anymore; you would have to update the page to save the images.

**Comment by funkedgeek** [comment]
The new version of image_advanced came out a few weeks ago with a new codebase.  Does the problem still persist?

**Comment by funkedgeek** [comment]
I'm closing this issue.  Please reopen if you are still having issues
