### ISSUE TITLE
Oembed not showing on frontend

### ISSUE THREAD

**Issue by joesalowitz** [rilwis/meta-box#653]
Hi,

Oembed is not displaying as an embed on the frontend, but is simply outputting the URL text. Help?

Functions.php code: 

    // Register Metabox Video Embed box
    
    add_filter( 'rwmb_meta_boxes', 'rw_video_url_register_meta_boxes' );
    function rw_video_url_register_meta_boxes( $meta_boxes )
    {
        $prefix = 'rw_';
        // Behind the scenes Video Meta box
        $meta_boxes[] = array(
            'title'    => 'Behind the Scenes Video',
            'pages'    => array( 'portfolio_page' ),
            'fields' => array(
                array(
                    'name' => 'URL',
                    'id'   => $prefix . 'video_url',
                    'type' => 'oembed',
                ),
            )
        );
        return $meta_boxes;
    }

Template.php code: 

    <?php $btsvideoembed = rwmb_meta ( 'rw_video_url');
    
    if (empty($btsvideoembed)) { 
    // do nothing
    } else { ?>
    
    <?php echo do_shortcode( $btsvideoembed ) ?>

    <?php } ?>

Page:

http://voyagepictures.co/portfolio_page/stockholm-fashion-destination/

**Comment by funkedgeek** [comment]
Added `oembed` compatibility in `rwmb_meta`.  When using `rwmb_meta` with `oembed`, do the following:

```
$btsvideoembed = rwmb_meta ( 'rw_video_url', array( 'type' => 'oembed') );
```

**Comment by senlin** [comment]
@funkedgeek your sample still seems to output only the url and not the video.

**Comment by funkedgeek** [comment]
I updated the code of the plugin.  Have you re-downloaded it?

**Comment by senlin** [comment]
just did, still URL output only

**Comment by senlin** [comment]
the preview in the backend shows perfectly, just the frontend only shows the URL...

**Comment by funkedgeek** [comment]
Where are you putting the code?

**Comment by senlin** [comment]
in my template file

**Comment by funkedgeek** [comment]
Weird.  It works when I pasted it in a template file as well.  Can you post the code to the file?

**Comment by senlin** [comment]
hmmm very strange, I got rid of the `if ( ! empty( $btsvideoembed ) )` condition and now it all of a sudden works, sorry, seems you can close this after all then.

**Comment by Akrasnovskis** [comment]
hey people, I use this code, but only what it shows that Embed HTML not available. What I'm doing wrong


$video_url = rwmb_meta ( 'video_url', array( 'type' => 'oembed' ) );
{ echo $video_url; }

**Comment by rilwis** [comment]
HI @Akrasnovskis , I've just tested the code and it works. Are you using the latest version of the plugin?

If so, you might want to try this code:

```php
$video_url = rwmb_meta ( 'oembed' );
echo $video_url;
```

Or simpler:

```php
rwmb_the_value( 'oembed' ):
```

For more info, please see [this docs](https://docs.metabox.io/fields/oembed/#template-usage) and [this docs](https://docs.metabox.io/rwmb-the-value/).

**Comment by Akrasnovskis** [comment]
Hey rilwis,

Thanks for your reply, well, I tried your way and still not working, do not know why. See below how my meta box looks like, pretty much simple as per example really.

On website backend, it appears without any problem as it should be, but when I try to display on the front-end, nothing, that div is empty. So that's why I confused really, let me know if I do something wrong.

```
// Video Post Format
	$meta_boxes[] = array(
		'id' => 'video',
		'title' => 'Video Settings',
		'pages' => array( 'post' ),
		'context' => 'normal',
		'priority' => 'high',
	
		// List of meta fields
		'fields' => array(
			
			array(
				'id'	=> $prefix . 'video_url',
				'desc'	=> 'Enter the embed link from Youtube.',
				'name'	=> 'URL',
				'type'  => 'oembed',
				'clone'	=> false,
				'size'  => 30,
				
			),
		)
	);

<div class="entry-video">
	   <?php $video_url = rwmb_meta ( 'oembed' ); echo $video_url; ?>
    </div>

```

**Comment by rilwis** [comment]
Hi, can you send the full code that registers meta box? And what is the video URL?

**Comment by Akrasnovskis** [comment]
Hi, finally I managed it work, thank you for your help anyway, was tiny mistake which cause the issue
