### ISSUE TITLE
File Advanced Upload - Existing media already in library not attaching to post 

### ISSUE THREAD

**Issue by kijo-creative** [rilwis/meta-box#654]
```
    $meta_boxes[] = array(
		'title' => __( 'Attach Files', 'meta-box' ),
		'pages' => array('post','company','department','people','sites','bonus','feedback'),
		'priority' => 'high',
		'fields' => array(

			array(
				'name' => __( 'Attach File', 'meta-box' ),
				'desc' => "Attach files to the page (PDFs load in PDF viewer)",
				'id'   => "dbt_file_advanced",
				'type' => 'file_advanced',
				'max_file_uploads' => 10,
			),

		)
	);
```

I am able to retrieve the file paths using the rwmb_meta function and display the files that way. However only first time uploads through the meta box actually become post attachments. If you try to attach an existing file already in the Wordpress media library this does not register as a post attachment. Therefore using the Wordpress code to display attachments, which was previously built into the theme doesn't work. 

In addition the meta box cannot display previous post attachments but i'm assuming this is not a bug and has just not been implemented.

**Comment by funkedgeek** [comment]
The field isn't designed to attach to posts; it just saves ids of files as meta.  It doesn't mess with what posts/pages/etc the files are actually attached to.

**Comment by kijo-creative** [comment]
If using the meta box you upload a file from your computer that hasn't been uploaded before the plugins adds the file as a post attachment.

**Comment by funkedgeek** [comment]
That's only because of how the WordPress media modal works in general.  It attaches the uploaded file  to the post page its on at the time.  It has nothing specific to do with our code, however.  All our code does is select media and save the IDs as meta.  It doesn't attach or unattach files from posts on its own.

**Comment by funkedgeek** [comment]
As this isn't part of this field's features, I'm closing this issue.
