### ISSUE TITLE
Display list of terms (taxonomy type): Error

### ISSUE THREAD

**Issue by wasantec** [rilwis/meta-box#655]
Examples Error 
Catchable fatal error: Object of class WP_Error could not be converted to string in

>>> Code config <<<<

array(
				'name'    => __( 'category', 'your-prefix' ),
				'id'      => "thaitheme_meta_cat",
				'placeholder' => __( 'category', 'your-prefix' ),
				'type'    => 'taxonomy',
				'options' => array(
					'taxonomy' => 'category',
					'type'     => 'select_advanced',
					'args'     => array()
				),
			),	 

--------------------------------------

>>> Use Display <<<< Examples  https://metabox.io/docs/get-meta-value/

  $terms = rwmb_meta( 'thaitheme_meta_cat', 'type=taxonomy&taxonomy=tax_slug' );
    $content = '<ul>';
    foreach ( $terms as $term )
    {
        $content .= sprintf(
            '<li><a href="%s" title="%s">%s</a></li>',
            get_term_link( $term, 'tax_slug' ),
            $term->name,
            $term->name
        );
    }
    $content .= '</ul>';
    echo $content;

--------------------------

Help me

**Comment by funkedgeek** [comment]
In the metabox you are usingthe taxonomy `category` but you are using `tax_slug` with `rwmb_meta`.  it should be:

```
 rwmb_meta( 'thaitheme_meta_cat', 'type=taxonomy&taxonomy=category' );

```

**Comment by funkedgeek** [comment]
Here is what the complete  example should look like for you:
```
$terms = rwmb_meta( '', 'type=taxonomy&taxonomy=category' );
$content = '<ul>';
foreach ( $terms as $term )
{
    $content .= sprintf(
        '<li><a href="%s" title="%s">%s</a></li>',
        get_term_link( $term, 'category' ),
        $term->name,
        $term->name
    );
}
$content .= '</ul>';
echo $content
```

**Comment by funkedgeek** [comment]
Closing this issue.
