### ISSUE TITLE
Dynamically update file_advanced attachment

### ISSUE THREAD

**Issue by gnikolopoulos** [rilwis/meta-box#656]
Hi all,

I made a simple plugin that besides other stuff, lets me add custom post type entries from the front end. Since I also use a file_advanced field, I would like to know if it's possible to update the file_advanced field value with the correct file, uploaded by the user from the front end...

Thanks!

**Comment by rilwis** [comment]
Hi,

`file` field (and all other extended fields, including `image`, `file_advanced`, ...) saves attachment ID in the post meta table. If users uploaded multiple files, then each attachment ID of the uploaded files is saved as a single row in post meta title.

I also wrote a [documentation](https://metabox.io/docs/how-post-meta-is-saved-in-the-database/) on this topic.
