### ISSUE TITLE
Conditional logic plugin does not hide group clone "add more button"

### ISSUE THREAD

**Issue by leeroyrose** [rilwis/meta-box#659]
When using the conditional logic plugin on a group field, the sub fields get hidden but the "add more" button is persistence. 

Code:

		array(
			'id'   => $prefix.'one_pager_content_tabs',
			'type' => 'group',
			'fields' => array(
				array(
					'name'  => __( 'Title:', 'meta-box' ),
					'id'    => $prefix.'one_pager_content_tab_title',
					'type'  => 'text',
				),
				array(
					'name'    => __( 'Content:', 'meta-box' ),
					'id'      => $prefix.'one_pager_content_tab_content',
					'type'    => 'textarea',
				),
				// Other sub-fields here
			),
			'clone' => true,
			'visible' => array( $prefix.'one_pager_content_provider', '=', 'content_tab' ),
		),

Outputs:

<img width="726" alt="screen shot 2015-09-08 at 11 16 21" src="https://cloud.githubusercontent.com/assets/3706842/9732342/17c0b826-561b-11e5-8f32-53a525a29827.png">

The fields hide, but the "Add More" button stays!

**Comment by tanng** [comment]
Hi leeroyrose,

The `+ Add more` button is visible when you set `'clone' => true`, you can only hide it when you remove clone from your meta box.

Btw,
`
'visible' => array( $prefix.'one_pager_content_provider', 'content_tab' ),
`
Actually, you don't have to use equal sign to define conditional logic :)

**Comment by leeroyrose** [comment]
Hi tangg,

Yes that's right, in terms of cloning, everything is working fine. But, I want the add more button to hide unless the visible condition is met. Currently, the text and textarea fields are doing exactly that, but the add more button remains there. I only want it to show when the text and textarea fields are being shown.

Ah I will remove the conditional. Thanks! :)

**Comment by tanng** [comment]
Hi @leeroyrose 

Unfortunately, current version doesn't support hide Clone button, we'll add it on the next major update :)

**Comment by Kuuak** [comment]
Hello,
@leeroyrose I encounter the same issue as you, which is that the hidden condition is not applied on the group (wrapper) but on the fields inside the group. 
This behavior makes the layout a bit weird as the fields are hidden but not the group title & clone button.

Anyway I found a way to fix that with a simple modification by adding the group id 
to the wrapper via the `rwmb_{$field_type}_outer_html` filter.

Here if the my code, which I'm sure can be optimised. 

```
add_filter( 'rwmb_group_outer_html', 'bvt_group_wrapper', 10, 2);
function bvt_group_wrapper( $html, $field ) {
    $pos = strpos( $html, 'class=');
    return substr($html, 0, $pos) . "id='".$field['id']."' ". substr($html, $pos);
}
```

Hope this will be helpfull
Cheers!

**Comment by tanng** [comment]
Hi mates,

I've just update Meta Box Conditional Logic, it works with Group out of the box from now. Feel free to update.

Cheers
