### ISSUE TITLE
Conditional Logic Edit Post Issue

### ISSUE THREAD

**Issue by wgstjf** [rilwis/meta-box#660]
Firstly, loving the conditional logic plugin, I can finally do away with my custom admin js that tried achieved the same job but less efficiently!

I have a problem though and am trying to track down where it is coming from... When Conditional Logic is enabled whenever I try and edit a post/page or Custom Post item the edit screen that I get taken to is the one for the first Post.  The URL is correct, ie. the correct ID is showing in the URL but the content of the edit screen (both Title and Body Content) is that of the first Post and not that of the item I clicked on.

This issue does not occur if there are no Posts in the database or if the plugin is disabled.  

I have tried disabling all other plugins but find that the issue remains.  We are using a custom theme so there may be a conflict there but initial attempts to locate the issue have failed.  Any ideas?

All the best,

Will

Using WP 4.3.1 with custom theme

**Comment by rilwis** [comment]
@tanng Can you please look at this bug?

**Comment by wgstjf** [comment]
Has there been any progress on this?  The site I am building needs to go-live soon.

Cheers,

Will

**Comment by rilwis** [comment]
Hi Will,

Did you add any rule with Conditional Logic? Or just activated it?

I didn't add any rule, only activated the extension and it works without any issue.

**Comment by wgstjf** [comment]
That's a good question.  Pretty sure there were rules in my custom metaboxes file from the beginning...would have to check when back at work on Monday.
Also have a number of the other premium metabox plugins installed as well so maybe there is a conflict in there somewhere... 

Cheers
Will





On Sat, Oct 3, 2015 at 6:40 AM -0700, "Tran Ngoc Tuan Anh" <notifications@github.com> wrote:












Hi Will,



Did you add any rule with Conditional Logic? Or just activated it?



I didn't add any rule, only activated the extension and it works without any issue.

**Comment by wgstjf** [comment]
Ok...done some further investigation into this and have found the problem.  We use queries to build custom select lists and it is these additional queries that are causing the problem.  

Below is a test example of the code in question that is generating the issue.  I would really appreciate any help you might be able to suggest to enable us to keep the same capabilites but also be able to use the conditional logic plugin:

```php
add_filter( 'rwmb_meta_boxes', 'post_type_meta_boxes' );

function getThePosts() {
	$args = array(
		'posts_per_page'   => -1,
		'post_type'        => 'post', //Usually a custom post type
		'orderby' => 'title',
		'order' => 'ASC',

	       );

	$thePosts = new WP_Query( $args);
	wp_reset_postdata();

	$posts_menu = array();
	while ( $thePosts->have_posts() ) {
		$thePosts->the_post();
		$t = get_the_title();
		$i = get_the_ID();
		$posts_menu[$i] = $t;
	}
	return $posts_menu;
}

function post_type_meta_boxes() {

	//Page Metaboxes
	$prefix = 'page_';
	$meta_boxes[] = array(
		'id'       => 'page',
		'title'    => 'Page Details',
		'pages'    => array( 'page'),
		'context'  => 'normal',
	  'priority' => 'low',
		'fields' => array(

    // SELECT - Testing
    array(
			'name'  => 'Post select list',
			'id'    => $prefix . 'subtitle',
			'type'  => 'select',
			'options' => getThePosts(),
			'std'   => '',
			'clone' => false,
		),

return $meta_boxes;

}
```

Cheers,

Will

**Comment by wgstjf** [comment]
Ok, have figured out a work-around in case it is of use to anyone else. @rilwis if you know of a better way do jump in...

The key here is not to call the_post(), the work around therefore is:

```php

function getThePosts() {
    $args = array(
        'posts_per_page'   => -1,
        'post_type'        => 'post', //Usually a custom post type
        'orderby' => 'title',
        'order' => 'ASC',
    );

    $thePosts = new WP_Query( $args);
    wp_reset_query();
    $posts_menu = array();
    if (count($thePosts->posts)>0) {
      foreach ( $thePosts->posts as $thePost) {
          $t = get_the_title($thePost);
          $i = $thePost->ID;
          $posts_menu[$i] = $t;
      }
    }
    return $posts_menu;
}

```

Hope that helps someone :-)

Cheers,

Will

**Comment by rilwis** [comment]
I see. I guess `the_post` changes the current post object, which make WP confuses because it's using it for editing.

By the way, why don't you just use `post` field? It's exactly what you want :)

**Comment by wgstjf** [comment]
It's just strange that it only happens if Conditional Logic is activated, no issue if not (even with loads of your other Metabox plugins installed and active).

The reason I don't use the post field is that we customise the resulting list more than just including the title, sometimes we need to show other custom meta data in the option label as well so useful to be able to build our own options list :-)

Thanks as always,

Will

**Comment by funkedgeek** [comment]
We could adapt the post field with a filter So that it can display whatever
you want.  Wouldn't be that hard.  I can have a patch up later today.

**Comment by funkedgeek** [comment]
Added two new filters.  @rilwis might want to look over it to see if I missed anything or if he wants to rename the filters: https://github.com/rilwis/meta-box/commit/fc84ec0e2a751e6e4bce5ca4ceb975cbea022a94

**Comment by tanng** [comment]
Hi @wgstjf 

Did you get Meta Box Builder installed on your site? I think the problem is generated by Meta Box Builder, not Meta Box Conditional Logic, and I have fixed it already.

**Comment by wgstjf** [comment]
@rilwis  - I don't use Builder so I don't think that can be the cause of the issue in this case. I prefer to build manually via a metaboxes.php file

@funkedgeek - good idea!

Cheers,

Will
