### ISSUE TITLE
Standard value overrides stored meta data when using hidden

### ISSUE THREAD

**Issue by ryanlabelle** [rilwis/meta-box#662]
My apologizes if I double posted, I left a comment here:

https://github.com/rilwis/meta-box/commit/03f1ee6559f894dc519ec05f7860d9cf1fe0faa6

Not sure if this is the same as posting an issue, it is causing an issue for my script.

Thank you very much.

**Comment by rilwis** [comment]
I also commented in the commit. I will quote here for discussion as well:

> The hidden field doesn't have input for users, so its value should not be changed by users. That's why its value is always constant (`$field['std']`).

Do you use Javascript to change the value of the hidden field? That makes sense.

**Comment by ryanlabelle** [comment]
Thanks. Yes I use JavaScript to set but I would like to pull the last saved value from the database and didn't have to use std before on the sever side but I suppose I can . It was automaticity pulled from the meta value . I could be off in my logic but I'm sure I can make it work both ways .

**Comment by ryanlabelle** [comment]
Please correct me if I"m wrong but now if I want to use a hidden field to store a hidden value for a metabox and allow javascript to update the value I have to rely on the std attribute to set the value when I define the field. So a call to get_post_meta as I define the field because otherwise it will never retrieve what's been saved in the database. 

I think I'll end up using a text field and then just hide it with CSS. Seems like a simpler solution. 

So I get what you mean when you say that is should be a constant because it doesn't allow for user input but when using java script it sort of does allow user input because the javascript is now inputting on behalf of the user. Just a thought. This is how I have it working right now in my script.

Thanks for making such a great script. It's been very helpful for us. How can I contribute?

**Comment by rilwis** [comment]
I think you're right in this case. Users are able to change the value of the hidden field. Otherwise it would be useless. I've just reverted the code to keep this logic. Also this logic is consistent with other field as well.

Regarding contributing, please fork this repo, then make any change to your code. After that, create a pull request and I will merge them into the core. Here is the [complete guide](https://guides.github.com/activities/contributing-to-open-source/index.html) that you can follow.

**Comment by ryanlabelle** [comment]
Sounds great! We did a work around but this would still be great. 

Thanks, I'm still getting my head around git / github but I would love to contribute. I'll check that out. Cheers.
