### ISSUE TITLE
color picker buggy when used with Group extension

### ISSUE THREAD

**Issue by senlin** [rilwis/meta-box#664]
I have never used the color picker before, so I don't know if the bugs are exclusive when using the Groups extension.

There are several issues.
One is alignment of the picker itself; it moves to the bottom of the group and to the left
Another is that it seems there can be only 1 color picker per group, so making something such as buttons with a background color and a text color is impossible.

![screenshot of left alignment](https://dl.dropboxusercontent.com/u/63708053/color-picker-wrong-aligned.png)

![screenshot of bottom placement](https://dl.dropboxusercontent.com/u/63708053/color-field-mess.png)

**Comment by rilwis** [comment]
I already answered your question in support forum for premium extension. Let me close this issue.
