### ISSUE TITLE
rwmb_meta breaks for cloneable group IDs beginning with an underscore

### ISSUE THREAD

**Issue by jkruger** [rilwis/meta-box#666]
I have a cloneable group that contains a text field. Values are being stored fine in the admin, but I'm having problems displaying them on the front.

Did a few tests, as per this documentation:

```
$group_values = rwmb_meta( 'group_id' );
foreach ( $group_values as $group_value )
{
    $value = isset( $group_value[$sub_field_key] ) ? $group_value[$sub_field_key] : '';
    echo $value; // Display sub-field value
}
```

If group_id = aci_slides, everything works fine.
If group_id = _aci_slides, I get "invalid argument supplied for foreach()"

This behavior is inconsistent for rwmb_meta, as I can return values for non-group meta boxes that begin with an underscore just fine.

**Comment by rilwis** [comment]
Hmm, I think the "Invalid argument supplied for foreach()" error occurs when there is no value for groups. Please try this:

```
$group_values = rwmb_meta( 'group_id' );
if ( ! empty( $group_values ) )
{
    foreach ( $group_values as $group_value )
    {
        $value = isset( $group_value[$sub_field_key] ) ? $group_value[$sub_field_key] : '';
        echo $value; // Display sub-field value
    }
}
```

**Comment by jkruger** [comment]
The problem is, those groups had values, but the helper function didn't
find them when the group ID began with an underscore. So, that code snippet
would not even get to the for loop.

On Thu, Oct 1, 2015 at 9:57 PM, Tran Ngoc Tuan Anh <notifications@github.com

**Comment by funkedgeek** [comment]
Does or does not the meta start with an underscore?

**Comment by rilwis** [comment]
Hi @jkruger,

I've just tested again with group id begins with an underscore.  Here is my code:

```php
add_filter( 'rwmb_meta_boxes', function ( $meta_boxes )
{
	$meta_boxes[] = array(
		'title'  => 'Test group with underscore',
		'fields' => array(
			array(
				'name'   => 'Group',
				'id'     => '_group',
				'type'   => 'group',
				'clone'  => true,
				'fields' => array(
					array(
						'name' => 'Text',
						'id'   => 'text',
						'type' => 'textarea',
					),
				),
			),
		),
	);
	return $meta_boxes;
} );
add_filter( 'the_content', function ( $content )
{
	$items = rwmb_meta( '_group' );
	ob_start();
	var_dump( $items );
	return $content . ob_get_clean();
} );
```

Here is how it looks:

http://prntscr.com/b5dfpo

Can you please try again with the latest version of both Meta Box and Group and let me know if you still see the bug? Thanks!
