### ISSUE TITLE
image_advanced default showing a blank thumbnail?

### ISSUE THREAD

**Issue by ryanlabelle** [rilwis/meta-box#668]
Is any one else seeing a blank thumbnail when using image_advanced field? 

I don't think it was always like this but now when I add a new image_advanced or thickbox I get a black thumbnail that looks like this: http://new.tinygrab.com/6407caa59e372418cb2573718c456c9146f0c5facd.png

and if you click on edit, it take me to the edit page for the post I'm on. If I remove using the X, then the upload button shows up and the blank thumb is removed. 

I"ve tried using std => false but it still persists. Not a critical issue but something I've noticed. 

Cheers!

**Comment by funkedgeek** [comment]
Really weird.  image_advanced is getting a code overhaul next version to support cloning and so far I haven't seen this bug.  I am seeing it with plupload, however.

**Comment by ryanlabelle** [comment]
Thanks @funkedgeek - I guess I'll see if the next updates fixes this issue. Cheers!

**Comment by funkedgeek** [comment]
The updated code is on github.  Fair warning: in order to make it cloneable, image_advanced now saves like any other field

**Comment by ryanlabelle** [comment]
Thanks. I'll test this out.

**Comment by ryanlabelle** [comment]
@funkedgeek Looks and works great. Haven't tested cloning but the issue I was seeing appears to be gone. Nice work!

**Comment by funkedgeek** [comment]
I'm going to rewrite plupload image so that it fixes the same issue and gets the same cloning benifits
