### ISSUE TITLE
Priority / Positioning after title

### ISSUE THREAD

**Issue by flowdee** [rilwis/meta-box#670]
Is there a way to move a meta-box under the title? ACF for example can handle this too.

**Comment by funkedgeek** [comment]
We use the standard positioning locations that WP uses.  Positioning a box under the title would involve overriding WP's code in some way, which maybe out of the scope of this plugin.  I'll let @rilwis decide if this is feasible or not

**Comment by funkedgeek** [comment]
This could help: http://wordpress.stackexchange.com/questions/36600/how-can-i-put-a-custom-meta-box-above-the-editor-but-below-the-title-section-on
