### ISSUE TITLE
Composer autoload error

### ISSUE THREAD

**Issue by sondoha** [rilwis/meta-box#672]
Hi,

Thank you for your awesome classes :)

I got this error when installing meta-box using Composer.

`/vendor/rilwis/meta-box/meta-box-loader.php): failed to open stream: No such file or directory`

I saw that there is no file named `meta-box-loader.php` but `meta-box.php`

Can you please fix?

Cheers,
Son

**Comment by rilwis** [comment]
That's strange cause the file is [here](https://github.com/rilwis/meta-box/blob/master/meta-box-loader.php)

**Comment by sondoha** [comment]
I'm not sure... Here is what I see in my installed.json file:
```
{
        "name": "rilwis/meta-box",
        "version": "4.5.7",
        "version_normalized": "4.5.7.0",
        "source": {
            "type": "git",
            "url": "https://github.com/rilwis/meta-box.git",
            "reference": "a448208f304ff39959d5a2dc53275200740f575e"
        },
        "dist": {
            "type": "zip",
            "url": "https://api.github.com/repos/rilwis/meta-box/zipball/a448208f304ff39959d5a2dc53275200740f575e",
            "reference": "a448208f304ff39959d5a2dc53275200740f575e",
            "shasum": ""
        },
        "time": "2015-09-17 01:58:42",
        "type": "library",
        "installation-source": "dist",
        "autoload": {
            "files": [
                "meta-box-loader.php"
            ],
            "classmap": [
                "inc/fields",
                "inc/common.php",
                "inc/field.php",
                "inc/helpers.php",
                "inc/meta-box.php"
            ]
        },
```
This file has been generated by composer when I use `composer require rilwis/meta-box`

**Comment by rilwis** [comment]
Hmm, I will take a look at that.

**Comment by sondoha** [comment]
Thank you! Looking forward your information. I really love your works :)

**Comment by rilwis** [comment]
Hi again,

Can you please check with the latest commit? I added an loader class and change the composer config file. Hope it works.
