### ISSUE TITLE
Metabox Groups - id issue

### ISSUE THREAD

**Issue by wgstjf** [rilwis/meta-box#677]
Hi guys,

Any chance we could have the defined 'id' for a group being added as an attribute to the .rwmb-group-wrapper div?  For example the following:

```// Group
          array(
              'name' => 'Sidebar Options:',
              'type' => 'group',
              'id' =>  'panel_sidebar',
              ....and so on...```

Would result in something like

```
<div id="panel_sidebar" class="rwmb-field rwmb-group-wrapper togglediv rwmb-column rwmb-column-12 rwmb-column-first rwmb-column-last">....and so on...</div>
```

I am working on the ability to show/hide groups and need to be able to target a specific group wrapper?

Cheers,

Will

**Comment by rilwis** [comment]
Hi, I will add `id` for the wrapper div for all kinds of fields.

**Comment by wgstjf** [comment]
A great plan, thanks.  Any idea when this might be done? :-)

**Comment by rilwis** [comment]
Ah, I just found that we still can do the job **without** adding `id` attribute to the wrapper. Each field (including `group`) has an attribute `class`, where you can specify a special class for the group and then you can use it in your JS, like this:

```php
array(
    'type' => 'group',
    'id' => 'group_id',
    'class' => 'custom-css-class',
),
```

If you don't want custom CSS class, you can use `before` and `after` to create another wrapper div for the group, like this:

```php
array(
    'type' => 'group',
    'id' => 'group_id',
    'before' => '<div id="panel_sidebar">',
    'after' => '</div>',
),
```

**Comment by wgstjf** [comment]
Thanks for those suggestions.  I have managed to achieve the necessary by wrapping them as suggested using the 'before' and 'after' solution.  The other solution would not work as I need to be able to get a single unique reference for the group in question and adding a class (whilst unique) would return a large number of other classes as well.

It would be great if, in time, a group's id would be assigned to its wrapper by default to avoid this slightly more long winded approach though.

Thanks for all the help,  I now have collapsible groups with the ability for the site to remember their visibility status via a cookie... :-)

Will
