### ISSUE TITLE
file_advanced and image_advanced on 4.6

### ISSUE THREAD

**Issue by karissademi** [rilwis/meta-box#678]
When a new file (or files) are uploaded, they do not appear in the media library pane. I'm seeing this with both the file_advanced and image_advanced metaboxes. The files do get uploaded to the media library and refreshing the page will display them as expected. 

<img width="1086" alt="uploader" src="https://cloud.githubusercontent.com/assets/479028/10737107/ce63611e-7be6-11e5-8b46-aee7a641ad14.png">

**Comment by funkedgeek** [comment]
Just noticed that myself a few days ago.  Looking into how to fix this.  Stay tuned

**Comment by funkedgeek** [comment]
Alright, uploading should now work in the modal.  The reason it wasn't working right is a bug in the media modal.  When the modal is created, I filtered out media that was already selected in the field.  This, unfortunately, prevented uploads from showing up in the modal browser.  With this fix, files selected will show up in the modal, though the current code will prevent those files from being inserted multiple times.

**Comment by funkedgeek** [comment]
Closing this as it fixes the main issue, which is uploads in the modal.

**Comment by karissademi** [comment]
Awesome. You all rock. Any eta on an official WP release with this included?
