### ISSUE TITLE
Notice appearing on URL fields, version 4.6

### ISSUE THREAD

**Issue by karissademi** [rilwis/meta-box#679]
On development environments, with wp_debug set to true, the following notice appears on URL fields: 
`Notice: Undefined index: pattern in /wp-content/plugins/meta-box/inc/fields/url.php on line 29`

This does not affect functionality, but it would be nice to correct. :)

**Comment by rilwis** [comment]
Just fixed it. Thanks for reporting :)

**Comment by karissademi** [comment]
Awesome! Love this plugin, by the way. If you ever need someone to test a release I'm really good a finding things.
