### ISSUE TITLE
Create a loader file for Meta Box

### ISSUE THREAD

**Issue by rilwis** [rilwis/meta-box#680]
As the plugin can be used as a standalone plugin (highly recommended) or a module (with Composer or inside themes/plugins), it's better to write a loader for the plugin. This loader should check if the standalone plugin is installed: yes - use the standalone plugin, no - load the plugin.

This way users can always use the latest version of the plugin while still keep it not broken when include in themes/plugins.

**Comment by funkedgeek** [comment]
Closing this since we have a loader file now.  Thanks @rilwis
