### ISSUE TITLE
Notice: Undefined index: pattern

### ISSUE THREAD

**Issue by giovanicrim** [rilwis/meta-box#681]
Hi,

with last update, now i find this notice in my custom post type new&edit page:
Notice: Undefined index: pattern in /home/lnw174/public_html/wp-content/plugins/meta-box/inc/fields/url.php on line 29

How solve?

**Comment by p2or** [comment]
Same here :) This seems to be a [new feature of 4.6](https://github.com/rilwis/meta-box#changelog) For now you can fix it by adding an empty `pattern` 'attribute' to the array:

```php

// URL
array(
	'name'  => __( 'URL:', 'rwmb' ),
	'id'    => "{$prefix}url",
	'desc'  => __( 'http://www.google.com', 'rwmb' ),
	'type'  => 'url',
        'std'   => 'http://www.google.com',
	'pattern' => ''
	
),
```

**Comment by giovanicrim** [comment]
Yes!

**Comment by p2or** [comment]
@rilwis Is there any reason why this is not optional?

**Comment by funkedgeek** [comment]
This was fixed in the last commit on github.  https://github.com/rilwis/meta-box/commit/9407832544e6ca9283f520be6314d288cd0bc1db.  Please update your code from github for now.  The fix will be available when we update the plugin next
