### ISSUE TITLE
Notice: Undefined index: pattern in /path/wp-content/plugins/meta-box/inc/fields/url.php on line 29

### ISSUE THREAD

**Issue by senlin** [rilwis/meta-box#683]
As per title. 

After latest update when using the URL field this Notice shows in the backend.

**Comment by funkedgeek** [comment]
Fixed in https://github.com/rilwis/meta-box/commit/9407832544e6ca9283f520be6314d288cd0bc1db.  See https://github.com/rilwis/meta-box/issues/679
