### ISSUE TITLE
Meta Box Conditional Logic is not working

### ISSUE THREAD

**Issue by anhntbk08** [rilwis/meta-box#684]
Hi Tan,

I can't make Conditional Logic work. Here my code (a part)

	$meta_boxes[0] = array(
		'id' => '{$prefix}_settings_metabox',
		'title' => __('Project basic settings', '{$prefix}_settings'),
		'post_types' => array('bf-projects'),
		'context' => 'normal',
		'priority' => 'high',
		'autosave' => true,
		'fields' => array(
			// Type
			array(
				'type' => 'image_select',
				'id' => '{$prefix}_type',
				'name' => __('Project Type', BF_PLG_NAME),
				'desc' => __('Choose a type for your Project', BF_PLG_NAME),
				'options' => array(
					'image' => BF_URL . 'assets/img/image.png',
					'gallery' => BF_URL . 'assets/img/gallery.png',
					'video' => BF_URL . 'assets/img/video.png',
					'code' => BF_URL . 'assets/img/code.png',
				),
				'std' => 'image',
			),

			// Image
			array(
				'type' => 'image',
				'id' => '{$prefix}_image',
				'title' => __('Image', BF_PLG_NAME),
				'hidden ' => array('{$prefix}_type', '=', 'image'),
			),

I'm using version 1.0.7 and metabox version 4.6.
Thanks.

**Comment by tanng** [comment]
Hi Anh,

You can't put variable in single quote, so please change single quotes to double quotes,  for example: `'{$prefix}_type'` to `"{$prefix}_type"`

**Comment by anhntbk08** [comment]
My bad.
I found the issue, 'hidden '  --> there is a redundant space.

Thanks
