### ISSUE TITLE
DVWA :  function allow_url_include: Disabled 

### ISSUE THREAD

**Issue by mudx** [rilwis/meta-box#685]
Hi to all, i am new on this and my English isn't good, i need some help with my DVWA setup. I have searched a lot on google and could not find an answer to this. The first time i tried to install dvwa on Kali linux 2.0 amd64 i got problems with opening the setup , i got all times the 404 not found error, so y follow all steps to install dvwa on my OS, and still got that error. After that i reinstall kali linux and tried to install again dvwa and got no error, but some functions were disabled. I fixed some errors i got on the setup page but i still cant fix that : 

Setup Check
Operating system: *nix
Backend database: MySQL
PHP version: 5.6.14-0+deb8u1

Web Server SERVER_NAME: 127.0.0.1

PHP function display_errors: Disabled
PHP function safe_mode: Disabled
PHP function allow_url_include: Disabled  <-- that one is driving me crazy

i have changed the values into the php.ini on my dvwa folder, changed the values of php.ini on the PHP5 folder, gave the folder the right permissions and still cant not see that function on GREEN.  did a lot of researching and found nothing so i registered here to try to get some help of you guys.

Greetz Alejandro

**Comment by rilwis** [comment]
Hi, I'm not sure if this is related to the Meta Box plugin. I will close this issue.
