### ISSUE TITLE
image_advanced upload not visible

### ISSUE THREAD

**Issue by Maaark** [rilwis/meta-box#688]
Hello,

The image_advanced type has a bug, when you click add menu there is a popup with the media in WP, when you upload a new one to this the media list isn't updating and not showing your newly uploaded image.

**Comment by jonwatson87** [comment]
+1 - same thing here! 

I commented on the WordPress support forum the other day about it. No reply as yet.

**Comment by rilwis** [comment]
Thanks for reporting. This issue is duplicated with #678 . I will close this.
