### ISSUE TITLE
Default map coordinates = blank map

### ISSUE THREAD

**Issue by jonwatson87** [rilwis/meta-box#689]
I'm having a problem with the std map coordinates. 

If the address field isn't changed when an event is created then the map on the front end fails to appear. All I get is a blank grey box... 

When the field is updated to something else, via the WordPress Admin Panel it works perfectly. It's just the std/default map that's failing to load.

I've checked and triple-checked the coordinates, and have tested them (and the address) via Google Maps directly. 

I've also changed the coordinates to alternative locations. 

Still just the grey box.

Default and non-default images below: 

<img width="351" alt="screenshot 2015-11-03 20 57 57" src="https://cloud.githubusercontent.com/assets/7596221/10921499/bdb4fb2e-826d-11e5-8299-1981702aa09c.png">
<img width="350" alt="screenshot 2015-11-03 20 58 45" src="https://cloud.githubusercontent.com/assets/7596221/10921500/bdb79a14-826d-11e5-885e-299ab8fdcfbb.png">

**Comment by funkedgeek** [comment]
Can you post your meta box code so we can test it out?

**Comment by jonwatson87** [comment]
function cf_events_register_meta_boxes( $meta_boxes ) {
    $prefix = 'cf_';

    //Map
        $meta_boxes[] = array(
        'title'      => __( 'Location'),
        'post_types' => 'events',
        'priority'   => 'high',
        'fields'     => array(

            // Map requires at least one address field (with type = text)

            array(
                'id'   => 'address',
                'name' => __( 'Address' ),
                'type' => 'text',
                'std'  => __( 'CentreForum, 27 Queen Anne\'s Gate, Westminster, London SW1H 9BU, UK' ),
            ),

            array(
                'id'            => 'map',
                'name'          => __( 'Map' ),
                'type'          => 'map',

                // Default location: 'latitude,longitude[,zoom]' (zoom is optional)

                'std'           => '51.500275,-0.1359987,15',

                // Name of text field where address is entered. Can be list of text fields, separated by commas (for ex. city, state)
                
                'address_field' => 'address',
            ),
        ),
    );

    return $meta_boxes;

    }

    add_filter( 'rwmb_meta_boxes', 'cf_events_register_meta_boxes' );


Then to call the data: 

    $args = array(
        'type'         => 'map',
        'width'        => '340px', // Map width, default is 640px. You can use '%' or 'px'
        'height'       => '280px', // Map height, default is 480px. You can use '%' or 'px'
        'zoom'         => 20,  // Map zoom, default is the value set in admin, and if it's omitted - 14
        'marker'       => true, // Display marker? Default is 'true',
        'info_window'  => $theaddress . $getdirections,
    );

    echo rwmb_meta( 'map', $args );

**Comment by funkedgeek** [comment]
It's actually doing what it's supposed to be doing, sort  a location, you get the blank box.  of.  `std` is designed right now to only on a new, unsaved post.  If the post/event is saved and you haven't saved.

The solution you should use is the `sanitize_post_meta_{meta_key}` filter.  It will allow you to filter out any empty meta values and substitute them with your own:

```
function sanitize_map( $value )
{
	return empty( $value ) : '51.500275,-0.1359987,15' : $value;
}

add_filter( 'sanitize_post_meta_map', 'sanitize_map' );
```

**Comment by rilwis** [comment]
I think the problem happens when you haven't saved the post => no value is saved in the database. Saving the post fixes it (we always have to save the post to show it in the front end, right? In case you edit an existing post, just update it).

By the way, we also updated our `rwmb_meta` to make sure it doesn't output anything if there's no value. So if you haven't saved the post => nothing is shown instead of the gray box. I think it's better than showing something error.

**Comment by haphuoctuyen1997** [comment]
hi @rilwis  ! 
I fixed the problem! but I want to ask another question, I can't search for a location, instead I use 'osm type', it is completely okay. But I want to find exactly 1 location with "type map". For example: '58 Quoc Tu Giam, Hanoi '. So what should I do to fix it? Look forward to your help, thanks!
