### ISSUE TITLE
Default maxlength added

### ISSUE THREAD

**Issue by eriktdesign** [rilwis/meta-box#694]
On updating to 4.7, I found a default maxlength of 30 added to many of my existing inputs. This broke the backend interface for my clients, not allowing them to save posts without cutting down the length of headlines etc.

**Comment by ryanlabelle** [comment]
I'm experiencing the same issue. We can we do to help get this updated as soon as possible?

I'll investigate as well.

Thanks guys.

**Comment by ryanlabelle** [comment]
So it looks like with 4.7 various default attributes values were added to help normalize fields / inputs.

https://github.com/rilwis/meta-box/commit/0cfb20b023d770b873adb242942cf38f2785896b
https://github.com/rilwis/meta-box/blob/73190f2338e5ddc352643dd6eb47a3aa91c09a4f/readme.md

This is now inherited from abstract input field. So I"m looking for a bit of assistance accomplishing two things:

1) Set the default maxlength in this new abstract input field. Sounds like a master setting somewhere?
2) What's the best way to set something like maxlength for all text fields or all url fields?

I'm assuming to change it for one specific instance of a url field, it's as easy as:

```
'name' =>  'Social Media Links',
'id'   => "social_links",
'desc' =>  'Click plus button to add a link for each or your social media icons',
'type' => 'url',
'placeholder' =>  'http://facebook.com',
'clone' => true,
'maxlength'=>30
 ```

Thanks for your assistance guys :)

**Comment by funkedgeek** [comment]
Correct, you can set the max length of individual fields, either by
maxlength as a field argument or as part of the attributes argument. Sorry,
wasn't anticipating these issues. For the time being, please explicitly set
maxlength.

**Comment by funkedgeek** [comment]
I  will probably set the maxlength to false to remove this issue. Solution
will be up by 700 cst on github

**Comment by ryanlabelle** [comment]
Awesome! Thanks. 

What's your policy on pushing to the WordPress plugin repo? That's probably the quickest way to roll this temp fix. Otherwise we need to package our our theme files and push ourselves.

Is there also an elegant way to prevent auto updating from the WP repo in the future? Just so we can test future versions before sending it out to our 1200 customers.

Thanks for the speedy replies.

**Comment by rilwis** [comment]
Just pushed the new version on .org. Please update now.

Sorry for this bug and the inconvenience.

I think the auto update can be disabled using a plugin like this:

https://wordpress.org/plugins/disable-automatic-updates/

**Comment by ryanlabelle** [comment]
Thanks guys! I'll let our team know. Thanks for the plugin recommendation as well.  :)

**Comment by funkedgeek** [comment]
Pull request
