### ISSUE TITLE
Breakage of Media Library and Notice

### ISSUE THREAD

**Issue by bigandy** [rilwis/meta-box#697]
Using latest version of plugin 4.7.1 and WordPress 4.3.1 and PHP 5.5.3 

Updated and when I navigate to Media Library I get a spinning icon and nothing else. 

When looked at debug_log I get this 

PHP Notice:  Undefined index: attributes in /wp-content/plugins/meta-box/inc/fields/time.php on line 67

**Comment by Grumbkow** [comment]
Same issue with different PHP notice:
Notice: Undefined index: attributes in /home/lomans/domains/lomans.nl/public_html/wp-content/plugins/meta-box/inc/fields/date.php on line 66

Plugin WP and PHP are the same versions.

**Comment by funkedgeek** [comment]
Moved some code in `date` and `time` so that `attributes` is always present.

**Comment by Grumbkow** [comment]
Thanks! I was in a hurry so didn't look for an actual solution as opposed to the quickfix

**Comment by funkedgeek** [comment]
They won't.  The original `field` class creates the `attributes` index and I made sure that it's present in time for all the descendents
