### ISSUE TITLE
image_advanced still not showing up - breaks one of my plugins

### ISSUE THREAD

**Issue by senlin** [rilwis/meta-box#698]
Just updated to latest (4.7.1). In the changelog of 4.7 it says that something has been fixed for `image_advanced`, however, on  WP 4.4-beta4 using [my simple gallery plugin](https://github.com/senlin/so-simple-gallery) nothing shows in the meta box.

**Comment by funkedgeek** [comment]
Can you be more specific?  What is not working for you?

**Comment by senlin** [comment]
please see the attached screenshot and have a look at the top-most screenshot in the Repo for what there should be: https://wordpress.org/plugins/so-simple-gallery/screenshots/

<img width="1098" alt="image-advanced-fail" src="https://cloud.githubusercontent.com/assets/650066/11270167/87d5635e-8ef7-11e5-8286-afc0fe487b28.png">

**Comment by funkedgeek** [comment]
Are you using our plugin to display those images?

**Comment by funkedgeek** [comment]
Just installed your plugin and it works for me just fine.  Are you getting any error messages in the console?  
![sogallery](https://cloud.githubusercontent.com/assets/1159774/11270479/09bf93b2-8e85-11e5-86ad-1b67de82b96d.jpg)

**Comment by senlin** [comment]
Manny, the difference between your install and mine is the WP version. As you can see from my screenshot earlier, there is no "Add Media" button showing. On WP 4.3.1 that button is showing.

So for the next 19 days, things are fine, but after that everything will sadly fall apart.

As I received the notice of WP today to make sure my plugins are compatible with WP 4.4, I started checking everything more thoroughly and I discovered this.

**Comment by funkedgeek** [comment]
I'm running the 4.4 Beta, so I'm up to date.  Something else is going on.  I suggest deactivating all your plugins except meta box and your plugin, see if it works and them start activating each one individually to see if one is breaking it.  Also, check your JavaScript console to see if any errors are popping up.  Something tells me the JavaScript that renders them image_advanced field is being blocked somehow.

**Comment by senlin** [comment]
I'm sorry Manny, you're right.

In the meantime I found the culprit: Yoast SEO...

following scripts cause issues:

* wordpress-seo/js/wp-seo-post-scraper.min.js?ver=3.0.1
* wordpress-seo/js/dist/yoast-seo/yoast-seo.min.js?ver=3.0.1

It seems team Yoast is doing an attempt to break the world record of getting the most 1 star reviews in 1 day...

Apologies again for wasting your time.

**Comment by funkedgeek** [comment]
Are there specific line numbers in those files that are causing issues?

**Comment by senlin** [comment]
The scripts are minified, all is line 1 :(

**Comment by funkedgeek** [comment]
Yoast is patching up their plugin, so I'm considering this closed
