### ISSUE TITLE
Fire `change` event when `image_advanced` or `file_advanced` changed

### ISSUE THREAD

**Issue by tanng** [rilwis/meta-box#700]
Currently, we save `image_advanced` or `file_advanced` in hidden field. It's hard for users to listen to hidden field `on change` event. So we have to trigger `change` event when hidden field values changed then other plugins can listening to change event.

**Comment by funkedgeek** [comment]
Just added in https://github.com/rilwis/meta-box/commit/0054dce58a359d71058c057190965afc62da1631.  Enjoy

**Comment by rilwis** [comment]
Some how the commit 684d4e61c0b0e868ff5199ccda60c98eec175ff3 removed this event. @funkedgeek can you please readd it?

Thanks
