### ISSUE TITLE
Insert String of PHP into Meta Box

### ISSUE THREAD

**Issue by veitmehler** [rilwis/meta-box#701]
Hi guys,

I want to be able to insert a string of PHP or a WP Short-Code into a Metabox on a per post basis to publish a specific slider for the posts.

How can I best do that?

When I use the "Text" type, I only get an "Array" published on the front-end.

Any advice?

Thanks!!

**Comment by rilwis** [comment]
If you use a text type, just paste the shortcode into the input box. In the frontend, you can use this code to render the shortcode:

```php
$value = rwmb_meta( $field_id );
echo do_shortcode( $value );
```

Make sure the text field is not cloned. In case of clone, you should change the code to:

```php
$values = rwmb_meta( $field_id );
foreach ( $values as $value )
{
    echo do_shortcode( $value );
}
```
