### ISSUE TITLE
NOTICE: Undefined index: attributes

### ISSUE THREAD

**Issue by the-specialist2005** [rilwis/meta-box#702]
NOTICE: wp-content/plugins/meta-box/inc/fields/date.php:66 - Undefined index: attributes
require_once('wp-admin/admin.php'), do_action('admin_init'), call_user_func_array, rwmb_register_meta_boxes, RW_Meta_Box->__construct, RW_Meta_Box::normalize, RW_Meta_Box::normalize_fields, call_user_func, RWMB_Date_Field::normalize_field

**Comment by rilwis** [comment]
Please update the plugin to latest version, it's already fixed.

**Comment by the-specialist2005** [comment]
Thanks
