### ISSUE TITLE
Group input fields not being saved

### ISSUE THREAD

**Issue by Kuuak** [rilwis/meta-box#705]
Hello,

Working on a new project with the latest version of Metabox & Metabox Group extension, I hit an issue width input field inside a group.
I noticed that the "standard" fields didn't had the correct name which lead them not being saved.

**My clonable metabox group with three inputs (text, url & file_input)**
![01-metabox-group](https://cloud.githubusercontent.com/assets/6989959/11340701/7bb968e4-91ff-11e5-8ca9-0d63fc01ba03.jpg)

**When the post is saved.**
You can see that `title`& `link` fieldd havn't the correct name, compared to `img` which have the group name in his name.
![02-metabox-group-save-post](https://cloud.githubusercontent.com/assets/6989959/11340930/87e11fa8-9200-11e5-8c03-07af516e8849.jpg)

**Here is my metabox register**
```php
$mb_extras = array(
	'id'		=> $prefix .'extras',
	'title'		=> __( "Liens internes", 'bvt-domain' ),
	'pages'		=> array( 'my-taxonomy' ),
	'fields'	=> array(
		array( 'name'	=> __( '', 'bvt-domain' ),
			'id'		=> $prefix .'extras_links',
			'type'		=> 'group',
			'clone'		=> true,
			'fields'	=> array(
				array( 'name'		=> __( 'Titre', 'bvt-domain' ),
					'id'			=> 'title',
					'type'			=> 'text',
					'columns'		=> 6,
				),
				array( 'name'		=> __( 'Lien', 'bvt-domain' ),
					'id'			=> 'link',
					'type'			=> 'url',
					'columns'		=> 6,
				),
				array( 'name'		=> __( 'Image', 'bvt-domain' ),
					'id'			=> 'img',
					'type'			=> 'file_input',
					'columns'		=> 12,
				),
			),
		),
	),
);
new RW_Meta_Box( $mb_extras );
```
After some research about why `file_input` is being saved but not `text` nor `url` I found that after commit [0cfb20b](https://github.com/rilwis/meta-box/commit/0cfb20b023d770b873adb242942cf38f2785896b#diff-fd5d65e4f9c091e09009b2cba78f4a87) where the function html was kind of edited to call `self::render_attributes` which uses the `attributes` field to populate the `<input>` attributes instead of using `$field['field_name']`.

To overcome the issue I edited line 41 in file `class-rwmb-group-field.php` to set both `$chield_field['field_name']` & `$chield_field['attributes']['name']` with the correct name.

**Replaced line 41**
```php 
$child_field['field_name'] = self::child_field_name( $field['field_name'], $child_field['field_name'] );
```
**By this one**
```php 
$child_field['field_name'] = $child_field['attributes']['name'] = self::child_field_name( $field['field_name'], $child_field['field_name'] );
```

Thanks

**Comment by rilwis** [comment]
Hi, please update the Group extension to 1.0.3 (the latest version). It has a fix for this.

The problem happens because of the new way to output inputs in Meta Box 4.7, using the custom attributes.
