### ISSUE TITLE
Group fields naming issue in 4.7...

### ISSUE THREAD

**Issue by wgstjf** [rilwis/meta-box#707]
Hi guys,

I am working on a development site and updated the base metabox plugin this morning from 4.6 to 4.7.2 and it has caused an issue with some of my grouped fields. 

The issue is the the fields (currently aware this affects a text field and a radio field) do not get their group prefix.  In my example a field that has the ID of 'thetitle' is part of a group that has the ID 'panel_sidebar'.  The field should therefore, in the post edit screen' have the name 'panel_sidebar[thetitle]' and in 4.6 it does.  If I update the plugin (and I cannot be sure whether the problem was introduced with 4.7, 4.7.1, or 4.7.2), and refresh the edit post page the field's name now becomes 'thetitle', ie. missing its group prefix.  This is obviously preventing the field value from saving.

I cannot provide all the code from my metaboxes.php file as it is rather large(!!) but here is an excerpt.

```php
// Group
          array(
              'name' => 'Sidebar Options:', // Optional
              'type' => 'group',
              'id' =>  $prefix .'sidebar',
              'class' =>  'togglediv',
              'before' => '<div class="toggle-parent" id="sidebar-options">',
              'after' => '</div>',
              'clone' => false,
              'columns'     => '12',
              // List of sub-fields
              'fields' => array(
                  // SELECT - Sidebar Content Type
                  array(
            				'name'  => 'Sidebar Content Type',
            				'desc' => 'What content, if any, do you want to show in the sidebar?',
            				'id'    => 'content_type',
            				'type'  => 'select',
                    'options' => $sidebar_options_array,
            				'std'   => 'no',
            				'clone' => false,
                    'columns'   => '3',
            			),

                // Stuff removed from here to keep it short....

               // Group
          array(
              'name' => 'Sidebar Options:', // Optional
              'type' => 'group',
              'id' =>  $prefix .'sidebar',
              'class' =>  'togglediv',
              'before' => '<div class="toggle-parent" id="sidebar-options">',
              'after' => '</div>',
              'clone' => false,
              'columns'     => '12',
              // List of sub-fields
              'fields' => array(

              // Stuff removed from here to keep it short....

                // TEXT - Panel Title
                array(
                  'name'  => 'Sidebar Title',
                  'desc'  => 'Enter a title for the sidebar (optional)',
                  'id'    => 'thetitle',
                  'type'  => 'text',
                  'std'   => '',
                  'columns'     => '12',
                  'clone' => false,
                  'hidden' => array( 'panel_sidebar[content_type]', 'not in', array('services','products','features','support-pin') ),
                  //'add_to_wpseo_analysis' => true,
                ),

               // File continues here...

```

Can you take a look into it as I cannot update the metabox plugin until this has been fixed.  Thanks for all the great work though...LOVE your range of plugins, they are the first ones installed on any of our projects.

Cheers,

Will

**Comment by rilwis** [comment]
Hi, are you using old version of Group? The version 1.0.3 has a fix for this issue. Please update.

**Comment by wgstjf** [comment]
Thanks, will give that a go and report back. :-)

**Comment by wgstjf** [comment]
All fixed, thanks for the suggestion! :-)
