### ISSUE TITLE
Conditional Logic (v.1.0.8) - Image_advanced hidden

### ISSUE THREAD

**Issue by wgstjf** [rilwis/meta-box#708]
Hi guys,

I have updated my metabox plugins today as advised in a previous post (which fixed that post's issue) and now seem to have a problem in that the image_advanced field shown in the example below is being hidden by the conditional logic plugin although it has not been configured to do so...

Metabox: 4.7.2
Conditional Logic: 1.0.8
Group: 1.0.3

```php

//Post Metaboxes
	$prefix = 'post_';
	$meta_boxes[] = array(
		'id'       => 'post',
		'title'    => 'Post Setup',
		'pages'    => array( 'post' ),
		'context'  => 'normal',
		'priority' => 'high',
		'fields' => array(

      // IMAGE ADVANCED - Additional Images
      array(
        'name'  => 'Additional Images',
        'desc'  => 'Add any additional images you require  <b>Min dimensions 1000px wide</b>',
        'id'    => $prefix.'additional_images',
        'type'  => 'image_advanced',
        'std'   => '',
        'max_file_uploads' => 8,
        'columns'     => '12',
        'clone' => false,
      ),

      // TEXT - Youtube video URL
        array(
          'name'  => 'YouTube/Vimeo video URL',
          'desc' => 'Enter a link to a YouTube/Vimeo video. <b>Copy and Paste the URL from the YouTube/Vimeo page</b>',
          'id'    => $prefix . 'video',
          'type'  => 'text',
          'std'   => '',
          'clone' => false,
          'columns'   => '8',
        ),

      // TEXT - Author Override
          array(
      'name'  => 'Author Override (optional)',
      'desc' => 'If you want this post\'s author to be someone other than yourself then enter their name',
      'id'    => $prefix . 'author_override_indigo',
      'type'  => 'text',
      'std'   => '',
      'clone' => false,
      'columns'   => '4',
    ),


		)
	);
```

Any thoughts?  Can you replicate this at your end?

Cheers,

Will

**Comment by tanng** [comment]
Hi Will,

Since Meta Box 4.7, we updated the template for Image Advanced and File Advanced, the next version of Meta Box will have [a patch](https://github.com/rilwis/meta-box/issues/700) for that. If you want to workaround immediately, just replace this file in Meta Box plugin

https://github.com/rilwis/meta-box/blob/0054dce58a359d71058c057190965afc62da1631/js/media.js

**Comment by wgstjf** [comment]
Thanks for the quick reply.  I have replaced the file, as you suggest, but no improvement.

This is what I am seeing with Conditional Logic enabled
![screenshot-1](https://cloud.githubusercontent.com/assets/3740694/11567715/3c5eb918-99e0-11e5-8d25-beeb1754ed40.jpg)

and this is what I see (what I should see!) when I disable CL
![screenshot-2](https://cloud.githubusercontent.com/assets/3740694/11567714/3c56f8d6-99e0-11e5-8801-d5cfc2eb73f3.JPG)

Cheers,

Will

**Comment by tanng** [comment]
Hi Will, I have checked and it works on my PC. Do you have live site so I can check? Or did you see something on Console?

**Comment by wgstjf** [comment]
Ok, I have figured it out.

The issue seems to have come from another image_advanced field that was configured in another part of my metaboxes.php file.  This field has conditional logic applied to it and it seems to be affecting the other one mentioned above.  If I comment out the 'hidden' line then the 'Additional Images' field above does show, if I do not then it gets hidden.  

```php

// IMAGE - Sidebar Image
                array(
                  'name'  => 'Sidebar Image',
                  'desc'  => 'Add image you wish to show.  <b>Min dimensions 1000x1000px advised</b>',
                  'id'    => 'image',
                  'type'  => 'image_advanced',
                  'std'   => '',
                  'max_file_uploads' => 1,
                  'columns'     => '12',
                  'clone' => false,
                  'hidden' => array( 'panel_sidebar[content_type]', 'not in', array('image','image-video') ),
                ),
```

I have fixed the issue by adding the $prefix to the id making it now $prefix.'image'.  My confusion is why this field with a different ID to the 'Additional Images' one is affecting its visibility.  Is this a bug or just a case of me not assigning the prefix to the ID??

Thanks in advance,

Will

**Comment by tanng** [comment]
Hi Will, this happen when you have a field in Group and conditional logic try to find group fields by match with [name*=$value] attribute, so it will match with both `image`, and `additional_images`. I'm thinking a way to fix this. Maybe change the pattern to match :)

Thanks for letting me know that bug

**Comment by tanng** [comment]
Hi Will,

Version 1.2 also fixed this bug. Can you please check with your site?

Cheers

**Comment by funkedgeek** [comment]
@tanng has this been fixed?

**Comment by tanng** [comment]
Yeah
