### ISSUE TITLE
Metabox Tabs Help

### ISSUE THREAD

**Issue by krishna19** [rilwis/meta-box#709]
Hi,

Is it possible to hide particular tab on custom post types ?

Thanks
krishna

**Comment by rilwis** [comment]
Hi Krishna,

I think you can do that with PHP by creating 2 meta boxes: 1 for all post types and 1 (duplicated) for the specific one, something like:

```
// This is for all post type A, B, C
$meta_box_1 = array(
    // your definition is here
)

// This is for D
$meta_box_2 = $meta_box_1;
$meta_box_2['post_type'] = 'D';
$meta_box_2['tabs'] = array( 'new_tab' => 'New Tab' );
$meta_box_2['fields'][] = array(
    'id' => 'new_field',
    'type' => 'text',
    'name' => 'New Field',
    'tab' => 'new_tab',
);
// Add more fields to new tab here

// Return meta boxes
$meta_boxes[] = $meta_box_1;
$meta_boxes[] = $meta_box_2;
```

**Comment by krishna19** [comment]
@rilwis thanks for you reply. Is there any documentation regarding this ? Can you provide me full code ? Please
![tab](https://cloud.githubusercontent.com/assets/4782674/11677136/781d1006-9e60-11e5-9ede-e015db9da4bc.jpg)

**Comment by krishna19** [comment]
is it possible using Meta Box COnditional Logic ?

**Comment by tanng** [comment]
Yes, please update to latest version (1.1) and follow this guide

https://metabox.io/docs/hide-meta-box-tabs-conditional-logic/

**Comment by krishna19** [comment]
what is the parameter for post types ?
<pre>'hidden' => array('post_types', array( 'contact', 'about' ))</pre>

**Comment by tanng** [comment]
```
'hidden' => ['post_type', 'in', ['contact', 'about']]
```

**Comment by krishna19** [comment]
this not works.
<pre>
add_filter( 'rwmb_outside_conditions', function( $conditions )
{
    $conditions['.rwmb-tab-page'] = array(
        'hidden' => ['post_type', 'in', ['page']]
    );
    return $conditions;
} );
</pre>

**Comment by tanng** [comment]
I've tested and it works. Please check conditional logic version and PHP version. If your PHP version is lower than 5.5. Please change 
```
'hidden' => ['post_type', 'in', ['contact', 'about']]
```
to 
```
'hidden' => array('post_type', 'in', array('contact', 'about'))
```

This is my code
```
add_filter( 'rwmb_meta_boxes', function($meta_boxes)
{
	$meta_boxes[] = array(
		'title'     => __( 'Meta Box Tabs 2', 'rwmb' ),
		'tabs'      => array(
			'bio'      => __( 'Biography', 'rwmb' ),
			'interest' => __( 'Interest', 'rwmb' ),
		),
		'pages' => ['post', 'page'],
		'tab_style' => 'box',
		'fields'    => array(

			array(
				'name' => __( 'Bio', 'rwmb' ),
				'id'   => 'bio',
				'type' => 'textarea',
				'tab'  => 'bio',
			),
			array(
				'name' => __( 'Interest', 'rwmb' ),
				'id'   => 'interest',
				'type' => 'textarea',
				'tab'  => 'interest',
			),
		),
	);

	return $meta_boxes;
});

add_filter( 'rwmb_outside_conditions', function( $conditions )
{
    $conditions['.rwmb-tab-interest'] = [
        'hidden' => ['post_type', 'in', ['page']]
    ];
    
    return $conditions;
} );
```

**Comment by krishna19** [comment]
@tanng Thanks. Now it works
