### ISSUE TITLE
Clean include of the Core Extension Bundle into a theme

### ISSUE THREAD

**Issue by tinabillinger** [rilwis/meta-box#711]
Hello,

I love this plugin, have been using it in a ton of projects so far.
What always bugged me, is that the main plugin has a 'developer approved' way of including it into a theme, but the premium extensions don't.
We currently purchased the Core Extension Bundle which contains 9 separate plugins.
If included into a theme, all the plugin related code, like `plugins_url()` has to be modified manually.

Are there any plans of creating separate 'non plugin' versions of the extensions, 
or at least one plugin that combines them all?

Cheers

**Comment by rilwis** [comment]
Hi,

Actually you should not include extensions directly into your theme. The
reason is the same as for main plugin and you can see it here:

https://metabox.io/docs/include-meta-box-plugin-themes/

The recommended way is load them via TGM Activation class. This library has
an option for you to install the extensions from .zip files inside your
theme (if they have not been installed before). It's easier and cleaner to
do than modifying these plugins :)

**Comment by tinabillinger** [comment]
Hey,

thanks for the quick response.
Ok then, gonna have to do it the plugin-way to be save.

Cheers
