### ISSUE TITLE
retrieve type post with clone option enabled

### ISSUE THREAD

**Issue by mbtocalli** [rilwis/meta-box#712]
I have set a metabox with the following options:
'type'        => 'post',
'post_type'   => 'custom post type name',
'field_type'  => 'select_advanced',
'clone' => true,

but I just don't know how to retrieve the selected post titles in the front end.

**Comment by funkedgeek** [comment]
The ids of the posts you selected are saved as the meta data, I recommend using `get_the_title` to retrieve the title: https://codex.wordpress.org/Function_Reference/get_the_title

**Comment by funkedgeek** [comment]
Did my last comment help at all?  I'm closing this but if you're still having issues please comment
