### ISSUE TITLE
Conditional Logic on Tabs

### ISSUE THREAD

**Issue by pseudonymus** [rilwis/meta-box#713]
Not sure if this question`s place is here, but it possible to hide a Tabs section, conditioned by a checkbox? For example, I want to enable a section based on Tabs by selecting a checkbox. And another one, Could I use both "fields" and "tabs" attributes for a $meta_boxes[] array?

Thanks!

**Comment by tanng** [comment]
Hi @pseudonymus 

Current Meta Box version doesn't support hide tabs but I'm ready to add this feature in the next release this week. I'll let you know when I finish :)

Regards

**Comment by pseudonymus** [comment]
That`s great to hear! Looking forward for it!

Cheers!

**Comment by tanng** [comment]
Btw, I've just bumped version 1.1. You can put any selector now instead of only ID selector for `rwmb_outside_conditions` filter. Of course, it can hide tabs also:

For example:

```
add_filter( 'rwmb_meta_boxes', function($meta_boxes)
{
	$meta_boxes[] = array(
		'title'     => __( 'Meta Box Tabs 2', 'rwmb' ),
		'tabs'      => array(
			'bio'      => __( 'Biography', 'rwmb' ),
			'interest' => __( 'Interest', 'rwmb' ),
		),
		'tab_style' => 'box',
		'fields'    => array(
			array(
				'name' => __( 'Bio', 'rwmb' ),
				'id'   => 'bio',
				'type' => 'textarea',
				'tab'  => 'bio',
			),
			array(
				'name' => __( 'Interest', 'rwmb' ),
				'id'   => 'interest',
				'type' => 'textarea',
				'tab'  => 'interest',
			),
		),
	);

	return $meta_boxes;
});
```
You can hide a tab by using this snippet

```
add_filter( 'rwmb_outside_conditions', function( $conditions )
{
    // `Interest` tab is hidden when post format is aside
    $conditions['.rwmb-tab-interest'] = [
        'hidden' => ['post_format', 'aside']
    ];
    
    return $conditions;
} );
```

Regards

**Comment by pseudonymus** [comment]
Hey, thanks for the fast action! 

This feature looks promising, however, this is not covering my question. I was wondering if I can show/hide an entire Tabs section, not just one tab, by selecting/deselecting a checkbox field. Both the field and the tabs should be located in the same meta box. Here's an example that I quickly made for you: http://i.giphy.com/xTka04lRI8skPVQSaI.gif

Thanks!

**Comment by tanng** [comment]
Not sure how you can you create a checkbox field outside tabs section. But if you did it. You can obviously toggle that tabs. For example, with above meta box, and you've created additional checkbox field with id `enable_tabs`. Just define condition like so:

```
add_filter( 'rwmb_outside_conditions', function( $conditions )
{
    $conditions['#meta-box-tabs-2.rwmb-tabs'] = [
        'hidden' => ['enable_tabs', 1]
    ];
    
    return $conditions;
} );
```

**Comment by pseudonymus** [comment]
@tanng  I couldn`t create a checkbox field outside the tabs section, but in the same meta box and from your reply, I understand that I can't do that. I'll check out your code and see how it goes. 

Thanks!
