### ISSUE TITLE
Zoom In Map Field

### ISSUE THREAD

**Issue by javierencalada** [rilwis/meta-box#714]
Hi! thank you for your great plugin!, i have one question:

Is there a possibility to extract the zoom value when im using the next code?

```php
array(
                'name' => 'Mapa',
                'id'   => $prefix.'ubicacion_gmap',
                'type' => 'map',
				'style' => 'width: 100%; height: 400px',
				'std' => '-33.54776138318351,-70.55199980735779,17',
				'address_field' => $prefix.'ubicacion',
            ),
```
Front end:

```php
$proyecto_ubicacion = rwmb_meta('ubicacion_gmap', '');
$proyecto_coords = explode(',', $proyecto_ubicacion);
```
In my case i'm extracting the zoom value separately in an input text field because im using some extra codes like: custom markers, custom events on JS, etc.

Thank you!

**Comment by rilwis** [comment]
Hi,

This commit 4f0a7351447e653f2a8a276533c75557d9917fe3 adds support for saving `zoom` in the meta value. So you can get zoom using this code:

`$proyecto_coords = explode(',', $proyecto_ubicacion);
echo $proyecto_coords[2];`
