### ISSUE TITLE
Issue Adding MetaBox In WP Comments

### ISSUE THREAD

**Issue by technofreaky** [rilwis/meta-box#715]
I am trying to add a metabox in wpcomments. but i get the error in the image below
Error 1 : http://prntscr.com/9cs3df
Error 2 : http://prntscr.com/9cs3fx

**Comment by rilwis** [comment]
How did you add to wp comments? Because the plugin support custom post types, not comments.

**Comment by technofreaky** [comment]
i added like this
```php
'post_types' => array('comment','post')
```

Please check here : https://codex.wordpress.org/Function_Reference/add_meta_box

**Comment by rilwis** [comment]
Sorry, `comment` is not a post type and not supported.

**Comment by technofreaky** [comment]
Hi,

Why dont you add support for adding metabox for Comment ?

**Comment by funkedgeek** [comment]
Meta boxes aren't supported for comments

**Comment by technofreaky** [comment]
No.

Adding metabox in comment is possible checkout this :)

http://prntscr.com/9dvsb2

**Comment by funkedgeek** [comment]
Okay, stand corrected.  That aside, the current code is written assuming its for posts and custom post types

**Comment by technofreaky** [comment]
@funkedgeek . yes i know. but this is a plugin which can generate metabox. with custom html support. so why we add support for comments ?

**Comment by funkedgeek** [comment]
Currently not the scope if this project.

**Comment by technofreaky** [comment]
Ho Nice :)
Thanks for your reply. :)
