### ISSUE TITLE
Supporting custom fields in REST API

### ISSUE THREAD

**Issue by rilwis** [rilwis/meta-box#716]
We can add an option to return data of custom fields for requests made with REST API. Similar to this plugin:

https://wordpress.org/plugins/acf-to-wp-api/

**Comment by karissademi** [comment]
:+1:

**Comment by jackyon** [comment]
hi @rilwis, 

totally need this feature, when will this feature released?

plz advise.

thx.

**Comment by eriktdesign** [comment]
In the meantime, you should be able to use a filter like this:

`function yourslug_rest_add_data( $data, $post, $request ) {
	$_data = $data->data;

	// Populate the array with your data
	// you should probably do some error checking before assigning
	$_data['your_field_name'] = rwmb_meta('your_field');

	$data->data = $_data;
	return $data;
}
add_filter( 'rest_prepare_post', 'yourslug_rest_add_data', 10, 3 );`

**Comment by jackyon** [comment]
thx! I already did that.

**Comment by rilwis** [comment]
This is done as a standalone plugin here https://github.com/rilwis/mb-rest-api. Will be soon available on WordPress.org.
