### ISSUE TITLE
Metabox Tabs CSS Not Works

### ISSUE THREAD

**Issue by krishna19** [rilwis/meta-box#717]
Hi,

I include the meta box tabs and conditional logic folder into my theme. And call from functions.php like this

require_once( RWMB_DIR . 'meta-box-conditional-logic/meta-box-conditional-logic.php' );
require_once( RWMB_DIR . 'meta-box-tabs/meta-box-tabs.php' );

But the CSS & JS files not loaded.

Please help

**Comment by pseudonymus** [comment]
The scripts are called using the plugin path:

```
wp_enqueue_style( 'rwmb-tabs', plugins_url( 'tabs.css', __FILE__ ) );
```

Since you`re loading the files from the theme folder, use the get_template_directory_uri() to retrieve the path to the file:

```
wp_enqueue_style( 'rwmb-tabs', get_template_directory_uri().'/framework/meta-box/meta-box-extensions/meta-box-tabs/tabs.css');
```

Cheers!

**Comment by krishna19** [comment]
@pseudonymus Thanks for your reply. I made the following changes if I done anything wrong please reply me.

For Tabs, I replace the following
<pre>
wp_enqueue_style( 'rwmb-tabs', plugins_url( 'tabs.css', __FILE__ ) );
wp_enqueue_script( 'rwmb-tabs', plugins_url( 'tabs.js', __FILE__ ), array( 'jquery' ), '0.1', true );
</pre>
with
<pre>
wp_enqueue_style( 'rwmb-tabs', get_template_directory_uri() . '/framework/meta-box/meta-box-tabs/tabs.css' );
wp_enqueue_script( 'rwmb-tabs', get_template_directory_uri() . '/framework/meta-box/meta-box-tabs/tabs.js', array( 'jquery' ), '0.1', true );
</pre>

And For Conditional Logic, I add the following codes in functions.php
<pre>
define( 'MBC_URL', trailingslashit( get_template_directory_uri() . '/framework/meta-box/meta-box-conditional-logic/' ) );
define( 'MBC_DIR', trailingslashit( get_template_directory() . '/framework/meta-box/meta-box-conditional-logic/' ) );
</pre>

Thanks

**Comment by pseudonymus** [comment]
As long as your files are at the specified location, things should be fine. 

Regarding the conditional Logic paths, they seem to go to nowhere. You should check that.

**Comment by tanng** [comment]
Hi @krishna19 

I wouldn't recommend you use conditional logic on your theme but I can make sure that it works. This is my "quick" snippet on Twenty Fifteen.

`
define('MBC_URL',  get_template_directory_uri() . '/meta-box-conditional-logic/');
define('MBC_DIR',  get_template_directory() . '/meta-box-conditional-logic/');
require get_template_directory() . '/meta-box-conditional-logic/meta-box-conditional-logic.php';
`

Regards

**Comment by krishna19** [comment]
@pseudonymus @tanng Thanks
