### ISSUE TITLE
Text field not recording

### ISSUE THREAD

**Issue by vwpowergtsr** [rilwis/meta-box#718]
I upload the plugin when the website was on a demo path. After I change the location then the text field is not working. I ad any text and is not showing and is not recording. When I reload the page the field is missing. What can be the problem?

**Comment by funkedgeek** [comment]
Can you post the code you are using?

**Comment by funkedgeek** [comment]
Most likely the files aren't being found because you moved the folder.

**Comment by rilwis** [comment]
I think the problem is you moved the file that registers meta boxes and custom fields. That's why the field isn't showing in the back end. Please check the log to make sure you include the correct file.
