### ISSUE TITLE
Can I create a select_advanced in this way?.

### ISSUE THREAD

**Issue by YeltsinReyes** [rilwis/meta-box#719]
'options'  => array(
array('value1', 'value2') => 'Label1',
array('value3', 'value4') => 'Label2',
),

**Comment by rilwis** [comment]
No, each option should be in formar value => Label.

**Comment by YeltsinReyes** [comment]
Can each option only have 1 value?

**Comment by funkedgeek** [comment]
Yes, Each option can only have 1 value.  That's how select work
