### ISSUE TITLE
After upgrade to Metabox 4.7.3 MetaBox Group throws Fatal Error

### ISSUE THREAD

**Issue by karissademi** [rilwis/meta-box#722]
`Fatal error: Call to undefined method RW_Meta_Box::has_been_saved() in /home/ubuntu/mysite/wp/wp-content/plugins/meta-box-group/meta-box-group.php on line 64`

On any admin pages that contain regular 'ol metaboxes, or group metaboxes.

**Comment by karissademi** [comment]
Not a WP Core problem as I originally thought.

**Comment by funkedgeek** [comment]
Sorry.  Rilwias changed a function name and it looks like group meta box is looking and failing to find the old function.  I'll let him know and we'll put a patch up soon

**Comment by rilwis** [comment]
Please update Meta Box Group to latest version 1.0.4, it has a fix for that.

PS: I sent a newsletter yesterday annoucing this issue :)

**Comment by karissademi** [comment]
Welp, I guess I should read my newsletters! ;)

Thanks!
