### ISSUE TITLE
Meta box conditional logic issue

### ISSUE THREAD

**Issue by m2experts** [rilwis/meta-box#724]
I have purchase bundle package in Metabox.io with mariamiralles78@gmail.com this morning
Meta box conditional logic issue not supported for Meta box group field type
It not hide Meta box group field type

![untitled](https://cloud.githubusercontent.com/assets/16174505/11806415/801c07be-a345-11e5-9cef-4d4da07eecee.png)

**Comment by rilwis** [comment]
This probably is the same as [here](https://github.com/rilwis/meta-box/issues/682#issuecomment-152245359) and #708

**Comment by tanng** [comment]
Hi @m2experts 

I have updated documentation, please follow this guide

https://metabox.io/docs/hide-group-conditional-logic/

Regards
