### ISSUE TITLE
Taxonomy Problem

### ISSUE THREAD

**Issue by hirooapps** [rilwis/meta-box#726]
I can't display taxonomy with code:
<?php
   $terms = rwmb_meta( '', 'type=taxonomy&taxonomy=photo-category' );
   var_dump($terms);
?>
Display error:
Notice: Trying to get property of non-object in ../wp-includes/category-template.php on line 1153

Notice: Trying to get property of non-object in ../wp-includes/category-template.php on line 1153

Warning: array_map(): Argument #2 should be an array in ../wp-includes/category-template.php on line 1158
bool(false)

Please, fix this problem guys. Thanks!

**Comment by funkedgeek** [comment]
Where is the function being called?  In a template if so which?  Also which version of WP are you running?

**Comment by hirooapps** [comment]
I'm running wordpress version 4.4, using the plugin 'MB Custom Taxonomy' and 'MB Custom Post Type'. But, I got a problem with display taxonomy in front end. Thanks

**Comment by funkedgeek** [comment]
How were you able to fix this?
