### ISSUE TITLE
Range: Adding preview & unit

### ISSUE THREAD

**Issue by flowdee** [rilwis/meta-box#727]
Would be very helpful to add a preview of the current value by default and when moving the range slide.

![range](https://cloud.githubusercontent.com/assets/2278756/11962136/c77ac5b2-a8dd-11e5-901a-d9a4d7a3ce8b.png)

Additionally print out a label (or unit) for this value would be great.

```
array(
                'name' => __( 'Breakpoint', 'your-prefix' ),
                'id'   => 'navigation_breakpoint',
                'type' => 'range',
                'desc' => __( 'Define ...', 'your-prefix' ),
                'min'  => 768,
                'max'  => 1255,
                'step' => 25,
                'unit' => 'px',
            ),
```

**Comment by bentzibentz** [comment]
:+1:
