### ISSUE TITLE
Geocode stripping out dash in longitude?

### ISSUE THREAD

**Issue by chromeo** [rilwis/meta-box#728]
In the admin area, preview maps are often centered in China, when they should be centered in Seattle. When I inspect the generated html, the default location is printed correctly, but the meta value is missing the dash:

    <div class="rwmb-map-canvas" data-default-loc="47.6064,-122.3316,15" style="position: relative; overflow: hidden; transform: translateZ(0px); background-color: rgb(229, 227, 223);">...</div>
        <input type="hidden" name="sg_gmap_url" class="rwmb-map-coordinate" value="47.6097,122.3331,15">

Is this something that is getting stripped out after the geocoding?

**Comment by rilwis** [comment]
I've just tested with the default location `47.6064,-122.3316` and it shows the center in Seattle. Please let me know if you still see the bug.
