### ISSUE TITLE
Metabox Tabs Conflict with Conditional Logic

### ISSUE THREAD

**Issue by krishna19** [rilwis/meta-box#730]
Hi,
I want to show the first tab only in "Post". And i hide the first tab for other post types using Conditional Logic.

Only the tab title was hide, the content are still displayed. If I change the position of the first tab to third or some other position, it works fine.

I hide the first tab using this
<pre>
add_filter( 'rwmb_outside_conditions', function( $conditions )
{
    $conditions['.rwmb-tab-post'] = [
        'visible' => ['post_type', 'in', ['post']]
    ];

    return $conditions;
} );
</pre>

Thanks

**Comment by tanng** [comment]
Hi @krishna19,

Thanks for create that issue, I have updated [a documentation](https://metabox.io/docs/hide-meta-box-tabs-conditional-logic/#section-hide-the-first-tab) related to this.
