### ISSUE TITLE
Got a error message in 4.7.3

### ISSUE THREAD

**Issue by krishna19** [rilwis/meta-box#731]
I'm using version 4.7.2 it works fine. If I update to version 4.7.3 I got a error message in botttom of "Add New Page".

Wordpress Version: 4.4
And use the latest version of Metabox tabs & Conditional Logic

<code>Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'fix_page_template' not found or invalid function name in /Applications/MAMP/htdocs/new_theme/wp-includes/plugin.php on line 525</code>

**Comment by rilwis** [comment]
Just pushed a fix for this. Are you using Github version? Cause the .org version [it's fine](https://plugins.trac.wordpress.org/browser/meta-box/trunk/inc/init.php).

**Comment by krishna19** [comment]
Yes, I'm using github version. And I directly integrate into the theme.

And i need help on this #730

**Comment by rilwis** [comment]
I think this is done :)

**Comment by krishna19** [comment]
@rilwis thanks
