### ISSUE TITLE
Broken radio button when key of options array is string '0'

### ISSUE THREAD

**Issue by Jordi-m** [rilwis/meta-box#732]
Since about 1 or 2 months ago my meta-box configuration seems to be broken for a specific radio option. Before I explain the issue, let me show you the fields configuration:

	...
	'fields' => array(
		array(
			'name'		=> 'Website',
			'id'		=> "{$prefix}video_site",
			'type'		=> 'radio',
			'options'	=> array(
				'0'		=> 'YouTube',
				'1'		=> 'Vimeo'
			),
			'multiple'	=> false,
			'desc'		=> 'Selecteer de video-website'
		)
	)
	...

![youtube_video_site_selection](https://cloud.githubusercontent.com/assets/4034848/12056616/9f02bb56-af38-11e5-9d1e-6c2499ae8046.jpg)

_I'm using Meta-Box Version 4.7.3 with Wordpress 4.3 [due to a yet-to-be-fixed bug in 4.4]_

The issue here seems to be related to option '0' => YouTube. When I select this option in the admin front-end and save it, it is stored in the database (and I can query it in the website front-end), but after the publish/update page refresh, the radio button for 'YouTube' is no longer selected. So if you do another update, you've basically undone your previous YouTube selection without really knowing about it (took a while to figure out what was going on...).

I'd expect the YouTube option to be selected after page reload/publish/update etc.

Another thing I noticed a few weeks ago: Instead of the DB stored value being the key '0' (0 as string), I've found out meta-box(?) now stores the string 'on' instead of the previously expected '0'. Is this intentional, or also related to the issue from above?

I'll try my best to provide any further requested information if needed.

**Comment by funkedgeek** [comment]
I would choose an option other than 0.  0 is typically considered as empty to the code, so it won't be saved properly.

**Comment by Jordi-m** [comment]
@funkedgeek Ofcourse thats valid, however I'm not sure if it would be backwards compatible (since it did work fine for two years). If I change the key now in the fields config, all existing post meta data will be 'broken' for sure, correct?

**Comment by funkedgeek** [comment]
You would have to run some code that would change the meta of that name to the new value.  Probably can be done in MySQL to find all the meta of video_site and change the ones that are 0 to the new value (I'd choose youtube).

**Comment by funkedgeek** [comment]
Okay, try the latest version.  Thanks for the fix Rilwis.  Didn't think of that

**Comment by rilwis** [comment]
@funkedgeek you're welcome :)

**Comment by Jordi-m** [comment]
@funkedgeek @rilwis Awesome. Thanks for the help guys. Did a quick test with this commit diff, but I'm wondering:

If the previous statement before that commit was:

    if( $value )

Shouldnt it now be:

    if ( false !== $value && '' !== $value )

Instead of the current comit:

    if ( false === $value || '' === $value )

Seems like that with this fix no attributes are set at all. Or did I miss something else?
