### ISSUE TITLE
Got Notice When Define Variables

### ISSUE THREAD

**Issue by krishna19** [rilwis/meta-box#733]
I include the metabox directly, based on your documentation i include the metabox into my theme.
Whenever I update to version 4.7.3, I got a notification when defining variables like this
<pre>
define( 'RWMB_URL', trailingslashit( get_template_directory_uri() . '/framework/meta-box/' ) );
define( 'RWMB_DIR', trailingslashit( get_template_directory() . '/framework/meta-box/' ) );
define( 'MBC_URL', trailingslashit( get_template_directory_uri() . '/framework/meta-box/meta-box-conditional-logic/' ) );
define( 'MBC_DIR', trailingslashit( get_template_directory() . '/framework/meta-box/meta-box-conditional-logic/' ) );
require_once( RWMB_DIR . 'meta-box.php' );
require_once( RWMB_DIR . 'meta-box-conditional-logic/meta-box-conditional-logic.php' );
require_once( RWMB_DIR . 'meta-box-tabs/meta-box-tabs.php' );
require_once( get_template_directory() . '/framework/meta-boxes.php' );
</pre>
Error Message:
<pre>
Notice: Constant RWMB_URL already defined in /Applications/MAMP/htdocs/new_theme/wp-content/themes/new_theme/framework/meta-box/inc/loader.php on line 36

Notice: Constant RWMB_DIR already defined in /Applications/MAMP/htdocs/new_theme/wp-content/themes/new_theme/framework/meta-box/inc/loader.php on line 41
</pre>

**Comment by rilwis** [comment]
If you use the latest version on Github, all you need to do is `require path/to/meta-box.php' :)

**Comment by krishna19** [comment]
For Conditional logic & Tabs, i use like this
<pre>
define( 'TPMB_DIR', trailingslashit( get_template_directory() . '/framework/meta-box/' ) );
define( 'MBC_URL', trailingslashit( get_template_directory_uri() . '/framework/meta-box/meta-box-conditional-logic/' ) );
define( 'MBC_DIR', trailingslashit( get_template_directory() . '/framework/meta-box/meta-box-conditional-logic/' ) );
require_once( MYMB_DIR . 'meta-box-conditional-logic/meta-box-conditional-logic.php' );
require_once( MYMB_DIR . 'meta-box-tabs/meta-box-tabs.php' );
</pre>
is it correct ?

**Comment by rilwis** [comment]
Yes, but I'm not sure if JS/CSS files are loaded correctly because we just finished fixing the loading issue for the main plugin only (e.g., including directly in themes). I will work on other extensions later.

**Comment by krishna19** [comment]
ok @rilwis... Thanks for your reply
