### ISSUE TITLE
Taxonomy Advanced throwing warning 

### ISSUE THREAD

**Issue by bjlatta** [rilwis/meta-box#734]
Warning: array_unique() expects parameter 1 to be array, string given in /html/wp-content/plugins/meta-box/inc/fields/taxonomy-advanced.php on line 24
and
Warning: implode(): Invalid arguments passed in /html/wp-content/mu-plugins/meta-box/inc/fields/taxonomy-advanced.php on line 24

                  /**
		 * Get meta values to save
		 * Save terms in custom field, no more by setting post terms
		 * Save in form of comma-separated IDs
		 *
		 * @param mixed $new
		 * @param mixed $old
		 * @param int   $post_id
		 * @param array $field
		 *
		 * @return string
		 */
		static function value( $new, $old, $post_id, $field )
		{
				return implode(',', array_unique($new));
		}

fixed the problem by changing to:
static function value($new, $old, $post_id, $field)
{
          if(!empty($new) && is_array($new)
                       {
			 return implode(',', array_unique($new));
			}
			else return $new;
}

**Comment by tanng** [comment]
I'd like without else statement

```
if ( empty( $new ) || ! is_array( $new ) )
    return $new;

return implode(',', array_unique($new));
```
