### ISSUE TITLE
Should this be saving as an array? type => post, multiple => true?

### ISSUE THREAD

**Issue by ckbedwell** [rilwis/meta-box#735]
Hi guys,

Had a look back to see if anybody has had this issue and nothing that I can see; I think I've found a problem when 'type' => 'post', and 'multiple' => 'true'. 

```php
	add_filter( 'rwmb_meta_boxes', 'pg_register_post_meta_boxes' );
	function pg_register_post_meta_boxes( $meta_boxes ) {

			$meta_boxes[] = array(
				'title'    => 'Page Information',
				'pages'    => array( 'post' ),
				'priority' => 'high',
				'autosave' => true,
				'context' => 'side',
				'fields' => array(


					array(
						'name'    => __( 'What tents are mentioned in this post?', 'rwmb' ),
						'id'      => "specific-tents",
						'type'    => 'post',
						'post_type' => 'tent',
						'field_type' => 'select_advanced',
						'multiple' => 'true',
						'placeholder' => __( 'Select an Item', 'rwmb' ),
						'query_args' => array(
							'post_status' => 'publish',
							'posts_per_page' => '-1',
							),
						),
				),
			);	

		return $meta_boxes;
	}
```
I can select multiple posts in Wordpress's post admin screen and save them, but when I try to retrieve the IDs in the php template, they don't seem to be saved as an array but only the first post which was selected is saved as a string. 

I've tried a foreach loop to display all the IDs but it comes back as invalid and when I've done a var_dump of the rwmb_meta ( 'specific-tents') it just returns:

```php
string(3) "281" 
```

I have triple-checked and I have definitely selected and saved multiple posts in Wordpress's admin in the correct field. That ID being displayed is only ever the first post which is selected in the select advanced field. 
 
Am I missing something to display all the IDs selected or is this an issue that needs fixing?

Happy to supply any additional information / screenshots if this isn't clear.

**Comment by funkedgeek** [comment]
when using rwmb_meta with a field that is multiple, you have to specify that's its multiple:
`rwmb_meta ( 'specific-tents', array( 'multiple' => true ) )`

otherwise, it'll just return the first one saved.

**Comment by ckbedwell** [comment]
Perfect, thank you!
