### ISSUE TITLE
Metabox Tabs Conflict with Conditional Logic

### ISSUE THREAD

**Issue by krishna19** [rilwis/meta-box#736]
Hi,
I want to show the first tab only in "Post". And i hide the first tab for other post types using Conditional Logic.

Only the tab title was hide, the content are still displayed.

Already I ask about this issue here #730. But the snippet was not works

Here's the code

First  Tab - __Post__
Second Tab - __Layout__

<pre>
add_filter( 'rwmb_outside_conditions', function( $conditions )
{
    $conditions['.rwmb-tab-post, .rwmb-tab-panel-post'] = array(
        'hidden' => ['post_type', 'not in', ['post']]
    );

    $conditions['.rwmb-tab-panel-layout'] = array(
        'visible' => ['post_type', 'not in', ['post']]
    );

    return $conditions;
} );
</pre>

Thanks

**Comment by tanng** [comment]
Hi @krishna19 

Can you please inspect element these tabs and give us the rendered html or screenshot?

**Comment by krishna19** [comment]
@tanng thanks for the reply.

Video: https://youtu.be/OgWJz6gPhTE

Code For Metabox
<pre>
add_filter( 'rwmb_meta_boxes', 'krish_register_meta_boxes' );

if( ! function_exists( 'krish_register_meta_boxes' ) ) {
	function krish_register_meta_boxes( $meta_boxes )
	{
		/**
		 * prefix of meta keys (optional)
		 * Use underscore (_) at the beginning to make keys hidden
		 * Alt.: You also can make prefix empty to disable it
		 */
		// Better has an underscore as last sign
		$prefix = 'krish_';

		// Background Options
		$meta_boxes[] = array(
			'id'			=> 'rwmb_general_options',
			'title'			=> __( 'General Options', 'rwmb' ),
			'post_types'	=> array( 'post', 'page' ),
			'context'		=> 'normal',
			'priority'		=> 'high',
			'autosave'		=> true,

			'tabs'			=> array(
				'post'				=> __( 'Post', 'rwmb' ),
				'layout'			=> __( 'Layout', 'rwmb' ),
				'header'			=> __( 'Header', 'rwmb' ),
			),
			'tab_style'		=> 'box',
			'tab_wrapper'	=> true,

			'fields'     => array(
				
				array(
					'name'				=> __( 'Text', 'rwmb' ),
					'id'				=> "{$prefix}post_text",
					'desc'				=> __( 'Test Box', 'rwmb' ),
					'type'				=> 'text',
					'clone'				=> false,
					'std'				=> '',
					'tab'				=> 'post',
				),
				
				array(
					'name'				=> __( 'Select', 'rwmb' ),
					'id'				=> "{$prefix}select_box",
					'type'				=> 'select',
					'options'			=> array(
						'default'		=> __( 'Default', 'rwmb' ),
						'option_1'			=> __( 'Option 1', 'rwmb' ),
						'option_2'			=> __( 'Option 2', 'rwmb' ),
					),
					'multiple'			=> false,
					'std'				=> 'default',
					'tab'				=> 'layout',
				),
				
				array(
					'name'				=> __( 'Select', 'rwmb' ),
					'id'				=> "{$prefix}select_box_1",
					'type'				=> 'select',
					'options'			=> array(
						'default'		=> __( 'Default', 'rwmb' ),
						'option_1'			=> __( 'Option 1', 'rwmb' ),
						'option_2'			=> __( 'Option 2', 'rwmb' ),
					),
					'multiple'			=> false,
					'std'				=> 'default',
					'tab'				=> 'header',
				),
			)
		);

		return $meta_boxes;
	}
}

add_filter( 'rwmb_outside_conditions', function( $conditions )
{
    $conditions['.rwmb-tab-post, .rwmb-tab-panel-post'] = array(
        'hidden' => ['post_type', 'not in', ['post']]
    );

    $conditions['.rwmb-tab-panel-layout'] = array(
        'visible' => ['post_type', 'not in', ['post']]
    );

    return $conditions;
} );
</pre>

Rendered Html - Post
<pre>
&lt;div class=&quot;rwmb-tabs rwmb-tabs-box&quot;&gt;
	&lt;ul class=&quot;rwmb-tab-nav&quot;&gt;
		&lt;li data-panel=&quot;post&quot; class=&quot;rwmb-tab-post rwmb-tab-active&quot;&gt;&lt;a href=&quot;#&quot;&gt;Post&lt;/a&gt;&lt;/li&gt;
		&lt;li data-panel=&quot;layout&quot; class=&quot;rwmb-tab-layout&quot;&gt;&lt;a href=&quot;#&quot;&gt;Layout&lt;/a&gt;&lt;/li&gt;
		&lt;li data-panel=&quot;header&quot; class=&quot;rwmb-tab-header&quot;&gt;&lt;a href=&quot;#&quot;&gt;Header&lt;/a&gt;&lt;/li&gt;
	&lt;/ul&gt;
	&lt;div class=&quot;rwmb-tab-panels&quot;&gt;
		&lt;div class=&quot;rwmb-tab-panel rwmb-tab-panel-post&quot; style=&quot;display: block;&quot;&gt;
			&lt;div class=&quot;rwmb-field rwmb-text-wrapper&quot;&gt;
				&lt;div class=&quot;rwmb-label&quot;&gt;&lt;label for=&quot;krish_post_text&quot;&gt;Text&lt;/label&gt;&lt;/div&gt;
				&lt;div class=&quot;rwmb-input&quot;&gt;
					&lt;input type=&quot;text&quot; name=&quot;krish_post_text&quot; id=&quot;krish_post_text&quot; class=&quot;rwmb-text&quot; size=&quot;30&quot;&gt;
					&lt;p class=&quot;description&quot; id=&quot;krish_post_text_description&quot;&gt;Test Box&lt;/p&gt;
				&lt;/div&gt;
			&lt;/div&gt;
		&lt;/div&gt;
		&lt;div class=&quot;rwmb-tab-panel rwmb-tab-panel-layout&quot; style=&quot;display: none;&quot;&gt;
			&lt;div class=&quot;rwmb-field rwmb-select-wrapper&quot;&gt;
				&lt;div class=&quot;rwmb-label&quot;&gt;&lt;label for=&quot;krish_select_box&quot;&gt;Select&lt;/label&gt;&lt;/div&gt;
				&lt;div class=&quot;rwmb-input&quot;&gt;
					&lt;select name=&quot;krish_select_box&quot; id=&quot;krish_select_box&quot; class=&quot;rwmb-select&quot; size=&quot;0&quot;&gt;
						&lt;option selected=&quot;selected&quot; value=&quot;default&quot;&gt;Default&lt;/option&gt;
						&lt;option value=&quot;option_1&quot;&gt;Option 1&lt;/option&gt;
						&lt;option value=&quot;option_2&quot;&gt;Option 2&lt;/option&gt;
					&lt;/select&gt;
				&lt;/div&gt;
			&lt;/div&gt;
		&lt;/div&gt;
		&lt;div class=&quot;rwmb-tab-panel rwmb-tab-panel-header&quot; style=&quot;display: none;&quot;&gt;
			&lt;div class=&quot;rwmb-field rwmb-select-wrapper&quot;&gt;
				&lt;div class=&quot;rwmb-label&quot;&gt;&lt;label for=&quot;krish_select_box_1&quot;&gt;Select&lt;/label&gt;&lt;/div&gt;
				&lt;div class=&quot;rwmb-input&quot;&gt;
					&lt;select name=&quot;krish_select_box_1&quot; id=&quot;krish_select_box_1&quot; class=&quot;rwmb-select&quot; size=&quot;0&quot;&gt;
						&lt;option selected=&quot;selected&quot; value=&quot;default&quot;&gt;Default&lt;/option&gt;
						&lt;option value=&quot;option_1&quot;&gt;Option 1&lt;/option&gt;
						&lt;option value=&quot;option_2&quot;&gt;Option 2&lt;/option&gt;
					&lt;/select&gt;
				&lt;/div&gt;
			&lt;/div&gt;
		&lt;/div&gt;
	&lt;/div&gt;
&lt;/div&gt;
</pre>

Rendered Html - Page
<pre>
&lt;div class=&quot;rwmb-tabs rwmb-tabs-box&quot;&gt;
	&lt;ul class=&quot;rwmb-tab-nav&quot;&gt;
		&lt;li data-panel=&quot;post&quot; class=&quot;rwmb-tab-post rwmb-tab-active&quot; style=&quot;display: none;&quot;&gt;&lt;a href=&quot;#&quot;&gt;Post&lt;/a&gt;&lt;/li&gt;
		&lt;li data-panel=&quot;layout&quot; class=&quot;rwmb-tab-layout&quot;&gt;&lt;a href=&quot;#&quot;&gt;Layout&lt;/a&gt;&lt;/li&gt;
		&lt;li data-panel=&quot;header&quot; class=&quot;rwmb-tab-header&quot;&gt;&lt;a href=&quot;#&quot;&gt;Header&lt;/a&gt;&lt;/li&gt;
	&lt;/ul&gt;
	&lt;div class=&quot;rwmb-tab-panels&quot;&gt;
		&lt;div class=&quot;rwmb-tab-panel rwmb-tab-panel-post&quot; style=&quot;display: block;&quot;&gt;
			&lt;div class=&quot;rwmb-field rwmb-text-wrapper&quot;&gt;
				&lt;div class=&quot;rwmb-label&quot;&gt;&lt;label for=&quot;krish_post_text&quot;&gt;Text&lt;/label&gt;&lt;/div&gt;
				&lt;div class=&quot;rwmb-input&quot;&gt;
					&lt;input type=&quot;text&quot; name=&quot;krish_post_text&quot; id=&quot;krish_post_text&quot; class=&quot;rwmb-text&quot; size=&quot;30&quot;&gt;
					&lt;p class=&quot;description&quot; id=&quot;krish_post_text_description&quot;&gt;Test Box&lt;/p&gt;
				&lt;/div&gt;
			&lt;/div&gt;
		&lt;/div&gt;
		&lt;div class=&quot;rwmb-tab-panel rwmb-tab-panel-layout&quot; style=&quot;display: none;&quot;&gt;
			&lt;div class=&quot;rwmb-field rwmb-select-wrapper&quot;&gt;
			&lt;div class=&quot;rwmb-label&quot;&gt;&lt;label for=&quot;krish_select_box&quot;&gt;Select&lt;/label&gt;&lt;/div&gt;
				&lt;div class=&quot;rwmb-input&quot;&gt;
					&lt;select name=&quot;krish_select_box&quot; id=&quot;krish_select_box&quot; class=&quot;rwmb-select&quot; size=&quot;0&quot;&gt;
						&lt;option selected=&quot;selected&quot; value=&quot;default&quot;&gt;Default&lt;/option&gt;
						&lt;option value=&quot;option_1&quot;&gt;Option 1&lt;/option&gt;
						&lt;option value=&quot;option_2&quot;&gt;Option 2&lt;/option&gt;
					&lt;/select&gt;
				&lt;/div&gt;
			&lt;/div&gt;
		&lt;/div&gt;
		&lt;div class=&quot;rwmb-tab-panel rwmb-tab-panel-header&quot; style=&quot;display: none;&quot;&gt;
			&lt;div class=&quot;rwmb-field rwmb-select-wrapper&quot;&gt;
				&lt;div class=&quot;rwmb-label&quot;&gt;&lt;label for=&quot;krish_select_box_1&quot;&gt;Select&lt;/label&gt;&lt;/div&gt;
				&lt;div class=&quot;rwmb-input&quot;&gt;
					&lt;select name=&quot;krish_select_box_1&quot; id=&quot;krish_select_box_1&quot; class=&quot;rwmb-select&quot; size=&quot;0&quot;&gt;
						&lt;option selected=&quot;selected&quot; value=&quot;default&quot;&gt;Default&lt;/option&gt;
						&lt;option value=&quot;option_1&quot;&gt;Option 1&lt;/option&gt;
						&lt;option value=&quot;option_2&quot;&gt;Option 2&lt;/option&gt;
					&lt;/select&gt;
				&lt;/div&gt;
			&lt;/div&gt;
		&lt;/div&gt;
	&lt;/div&gt;
&lt;/div&gt;
</pre>

**Comment by tanng** [comment]
Hi @krishna19 

I have checked with your code, it works as expected. Can you please check your PHP version? If < 5.6, please change your filter to:

```
add_filter( 'rwmb_outside_conditions', function( $conditions )
{
    $conditions['.rwmb-tab-post, .rwmb-tab-panel-post'] = array(
        'hidden' => array('post_type', 'not in', array('post'))
    );

    $conditions['.rwmb-tab-panel-layout'] = array(
        'visible' => array('post_type', 'not in', array('post'))
    );

    return $conditions;
} );

```

Regards

**Comment by krishna19** [comment]
Hi,

My Php version : 5.6.7
Wordpress Version : 4.4.1

And please check the rendered html for page version.
The first tab panel is in Display: block and second is in Display: none

<pre>&lt;div class="rwmb-tabs rwmb-tabs-box"&gt;
    &lt;ul class="rwmb-tab-nav"&gt;
        &lt;li data-panel="post" class="rwmb-tab-post rwmb-tab-active" style="display: none;"&gt;&lt;a href="#"&gt;Post&lt;/a&gt;&lt;/li&gt;
        &lt;li data-panel="layout" class="rwmb-tab-layout"&gt;&lt;a href="#"&gt;Layout&lt;/a&gt;&lt;/li&gt;
        &lt;li data-panel="header" class="rwmb-tab-header"&gt;&lt;a href="#"&gt;Header&lt;/a&gt;&lt;/li&gt;
    &lt;/ul&gt;
    &lt;div class="rwmb-tab-panels"&gt;
        <strong>&lt;div class="rwmb-tab-panel rwmb-tab-panel-post" style="display: block;"&gt;</strong>
            &lt;div class="rwmb-field rwmb-text-wrapper"&gt;
                &lt;div class="rwmb-label"&gt;&lt;label for="krish_post_text"&gt;Text&lt;/label&gt;&lt;/div&gt;
                &lt;div class="rwmb-input"&gt;
                    &lt;input type="text" name="krish_post_text" id="krish_post_text" class="rwmb-text" size="30"&gt;
                    &lt;p class="description" id="krish_post_text_description"&gt;Test Box&lt;/p&gt;
                &lt;/div&gt;
            &lt;/div&gt;
        &lt;/div&gt;
        <strong>&lt;div class="rwmb-tab-panel rwmb-tab-panel-layout" style="display: none;"&gt;</strong>
            &lt;div class="rwmb-field rwmb-select-wrapper"&gt;
            &lt;div class="rwmb-label"&gt;&lt;label for="krish_select_box"&gt;Select&lt;/label&gt;&lt;/div&gt;
                &lt;div class="rwmb-input"&gt;
                    &lt;select name="krish_select_box" id="krish_select_box" class="rwmb-select" size="0"&gt;
                        &lt;option selected="selected" value="default"&gt;Default&lt;/option&gt;
                        &lt;option value="option_1"&gt;Option 1&lt;/option&gt;
                        &lt;option value="option_2"&gt;Option 2&lt;/option&gt;
                    &lt;/select&gt;
                &lt;/div&gt;
            &lt;/div&gt;
        &lt;/div&gt;
        &lt;div class="rwmb-tab-panel rwmb-tab-panel-header" style="display: none;"&gt;
            &lt;div class="rwmb-field rwmb-select-wrapper"&gt;
                &lt;div class="rwmb-label"&gt;&lt;label for="krish_select_box_1"&gt;Select&lt;/label&gt;&lt;/div&gt;
                &lt;div class="rwmb-input"&gt;
                    &lt;select name="krish_select_box_1" id="krish_select_box_1" class="rwmb-select" size="0"&gt;
                        &lt;option selected="selected" value="default"&gt;Default&lt;/option&gt;
                        &lt;option value="option_1"&gt;Option 1&lt;/option&gt;
                        &lt;option value="option_2"&gt;Option 2&lt;/option&gt;
                    &lt;/select&gt;
                &lt;/div&gt;
            &lt;/div&gt;
        &lt;/div&gt;
    &lt;/div&gt;
&lt;/div&gt;
</pre>

Another problem, just now I update to latest version after that Conditional Logic not works. Please help

Thanks

**Comment by tanng** [comment]
Can you please give me your FTP / Website Credentials so I can login and check?

Btw, this is my screenshot:

http://prntscr.com/9ocke8

**Comment by krishna19** [comment]
Hi @tanng,
I work on localhost. And in your screenshot also the same error was happen please check.
Instead of select box the text box from "POST" tab was displayed.
Actually the Layout Tab has Select Box. please check the code
<pre>
                array(
                    'name'              => __( 'Select', 'rwmb' ),
                    'id'                => "{$prefix}select_box",
                    'type'              => 'select',
                    'options'           => array(
                        'default'       => __( 'Default', 'rwmb' ),
                        'option_1'          => __( 'Option 1', 'rwmb' ),
                        'option_2'          => __( 'Option 2', 'rwmb' ),
                    ),
                    'multiple'          => false,
                    'std'               => 'default',
                    'tab'               => 'layout',
                ),
</pre>
![meta_page](https://cloud.githubusercontent.com/assets/4782674/12222430/2c662030-b7e2-11e5-9e7e-9f5a681e040a.jpg)
![meta_post](https://cloud.githubusercontent.com/assets/4782674/12222432/381bd85c-b7e2-11e5-8fda-42f3c0c8e5f5.jpg)


Thanks

**Comment by tanng** [comment]
Hi @krishna19,

Thanks for your patience, I have just updated Meta Box Tabs to 0.1.7 which better compatibility with Meta Box Conditional Logic and fixed all these issues. Please download and try.

Cheers!

**Comment by krishna19** [comment]
Hi @tanng,

Now it works fine.

Thanks
