### ISSUE TITLE
Clonable Date Field Throwing JS Error

### ISSUE THREAD

**Issue by baden03** [rilwis/meta-box#737]
In version 4.7.3, the date field, when clone is set to true, is no longer working.
The datepicker will display, however if a date is selected, or the month is changed the following JS error is being thrown:
```
Uncaught Missing instance data for this datepicker
```
This issue seems to be specific to the date field, as there the problem does not occure if the date field is changed to time or datetime.

**Comment by funkedgeek** [comment]
Can you post your code because I can't replicate this.  I have a date field, set clone to true but I'm not seeing this error in the console.

**Comment by baden03** [comment]
I have a class:
```
class tminus_Meta_Boxes{
    static function build( &$meta_boxes, $prefix ){
        $meta_boxes[] = array(
            'id' => 'launch_schedule',
            'title' => __('Recurring Launch Schedule','tminus'),
            'pages' => array('t-countdown'),
            'context' => 'normal',
            'priority' => 'default',

            'fields' => array(
                array(
                    'name' => __('Exclude Dates','tminus'),
                    'desc' => __('Dates to exclude from the schedule','tminus'),
                    'id' => $prefix . 'exclude_dates',
                    'type' => 'date',
                    'clone' => true,
                    'js_options' => array(
                            'autoSize'        => true,
                            'buttonText'      => __( 'Select Date', 'rwmb' ),
                            'dateFormat'      => 'yy-mm-dd',
                            'numberOfMonths'  => 2,
                            'showButtonPanel' => true,
                    )
                )
            )
        );
    }       
}
```
and call it like so:

```
$meta_boxes = array();
if ( ! class_exists( 'tminus_Meta_Boxes' ) )
	include_once 'admin/scripts/config-meta-boxes.php';
tminus_Meta_Boxes::build( $meta_boxes, 'tminus_' );
```

**Comment by funkedgeek** [comment]
Weird.  Can't replicate this.  Where is the code being called: in a plugin or in a theme?

**Comment by baden03** [comment]
After further testing it seems this is only an issue when there is already a non-clonable date field defined in a separate $meta_boxes[] array.  This should replicate the issue:
```
add_filter( 'rwmb_meta_boxes', 'my_register_meta_boxes' );
function my_register_meta_boxes( $meta_boxes ){
    $prefix = 'my_';
    $meta_boxes[] = array(
		'id' => 'block_one',
		'title' => __('First Block', 'my_domain'),
		'pages' => array('t-countdown'),
		'context' => 'normal',
		'priority' => 'high',
		'fields' => array(
             array(
				'name' => __('Date', 'my_domain'),
				'desc' => __('Normal DatePicker.','my_domain'),
				'id' => $prefix . 'simple_date',
				'type' => 'date',
				'js_options' => array(
					'autoSize'        => true,
					'buttonText'      => __( 'Select Date', 'rwmb' ),
					'dateFormat'      => 'yy-mm-dd',
					'numberOfMonths'  => 2,
					'showButtonPanel' => true,
				)
			)
        )
	);

    $meta_boxes[] = array(
		'id' => 'block_two',
		'title' => __('Second Block', 'my_domain'),
		'pages' => array('t-countdown'),
		'context' => 'normal',
		'priority' => 'high',
		'fields' => array(
             array(
				'name' => __('Clone Date', 'my_domain'),
				'desc' => __('Clone DatePicker.','my_domain'),
				'id' => $prefix . 'clone_date',
				'type' => 'date',
                'clone' => true,
				'js_options' => array(
					'autoSize'        => true,
					'buttonText'      => __( 'Select Date', 'rwmb' ),
					'dateFormat'      => 'yy-mm-dd',
					'numberOfMonths'  => 2,
					'showButtonPanel' => true,
				)
			)
        )
	);

    return $meta_boxes;
}
```

**Comment by funkedgeek** [comment]
Okay, replicated it.  Weirdly, it only gives that error to the second clone.

**Comment by funkedgeek** [comment]
Okay @rilwis @baden03 I found the problem.  So in the current code when we clone inputs, our reset code is changing the id, which messes with datepicker because it can't find the input it was attached to because the id has been changed.  I suggest we change this because cloneable inputs aren't given ids anyway unless code from something like datepicker give them ids.

**Comment by rilwis** [comment]
The fix is not ideal, because it will make all the cloned inputs have the same ID (it's not too important, but having same IDs on the same page doesn't look right). In this case the fix works. So I guess we should make a full test for other fields as well.

**Comment by funkedgeek** [comment]
Then we can give new clones ids using underscore's uniqueId.  Changing all of the ids every time we clone messes things up so why not just give ids to the new clones?

**Comment by funkedgeek** [comment]
New addition https://github.com/rilwis/meta-box/commit/82d6215eed8e96f08334554f15b272e03bb01df0

**Comment by funkedgeek** [comment]
I would like to know what fields rely on the id so we can formulate a more precise solution.

**Comment by funkedgeek** [comment]
Alright, got a solution that will solve multiple problems:

For ids created on the server side, I created `get_unique_id`, which guarantees all inputs will have unique ids, especially fields that have multiple inputs like checkbox and radio.  It uses a static variable that increments at every call.  It can be seen in this commit: https://github.com/rilwis/meta-box/commit/85bbf57cba796d998d43b4c2d2a308933a229180

For clones that are created on the client, I do something similar: I give them an id using Underscorejs's uniqueId function: https://github.com/rilwis/meta-box/commit/82d6215eed8e96f08334554f15b272e03bb01df0.  Same reasoning as before: fields that have multiple inputs will no longer share ids like before.  This way, inputs' ids aren't changed every time a clone is created like with the old code, and we won't break `date`, `datetime` and `time` fields.  The new ids are just `rwmb-clone-{number}` but we can change it to something else; I just didn't want to create id collisions with the pre-existing ids.

**Comment by funkedgeek** [comment]
Rewrote the code so auto increment ids for new clones.

**Comment by rilwis** [comment]
The idea behind `id` is simple: keep them unique for all inputs (making HTML valid) and make fields work.

The `cloneIndex.reset` was born for this exact purpose. I think the bug happened because the order of calls: reset should be called **before** trigger clone, so fields are re-rendered only **after** ids are reset.

I will refactor the code a little. I think it's too complicated now and not clear.

**Comment by rilwis** [comment]
The latest JS code works for me. Basically: I removed the code that might call reset index multiple times: 7b1245137c3ac421220b973c3b02a2f76bb2e3bc, and revert the simple code before: 3474d3d7b69911ab88abd318aa2dbf4c007e293f.

I will check if we need unique id function for PHP. What do you think @funkedgeek ?

**Comment by funkedgeek** [comment]
Re-opening this bug as there are still issues with sort.  Sorting changes the ids, which messes up the datepicker.

**Comment by funkedgeek** [comment]
It makes little sense to keep changing the ids and names for clones; makes more sense to make sure the name and id for any new clones are unique.  Hence https://github.com/rilwis/meta-box/commit/34b466fd4a33065a22af047debd9f23495319dbd.  Date works fine, names and ids aren't changed constantly and are always unique, sorting clones works as intended.
