### ISSUE TITLE
Datepicker field : inline mode

### ISSUE THREAD

**Issue by Sinusite** [rilwis/meta-box#738]
Is there a short way (an option) to make the datepicker field inline ?
See https://jqueryui.com/datepicker/#inline

Thanks.!

**Comment by funkedgeek** [comment]
Inline datepicker won't save anything

**Comment by Sinusite** [comment]
Thanks
But please see "With inline mode using altField:" in [Examples]  tab here : http://trentrichardson.com/examples/timepicker/

**Comment by funkedgeek** [comment]
Still the same issue.  altfield field shows the time/date but if you load up an already saved date, the inline datepicker won't remember

**Comment by Sinusite** [comment]
Indeed... i will check for an alternative like http://demos.jquerymobile.com/1.4.5/datepicker/ .... or not :)
Thanks!

**Comment by funkedgeek** [comment]
I have a branch which has this functionality: https://github.com/rilwis/meta-box/commit/3d81b04794cb113729315c70c24f4269cb042ddb.  Feel free to test it out

**Comment by funkedgeek** [comment]
So if the datepicker is inline, should we hide the text box?

**Comment by Sinusite** [comment]
cool! I will test that over the next couple of days.
Mmmm by default yes ? but maybe we could  have the choice to hide or not the text box ? :p (for web accessibility it's better...)
