### ISSUE TITLE
Tool to export, problems with attached files

### ISSUE THREAD

**Issue by Infolu** [rilwis/meta-box#739]
Hello I have a problem when using the tool to export and import my post type that has the metabox.

when using metabox the xml file that the tools / export creates is as follows.

WRONG
<wp: postmeta>
<wp: meta_key> <! [CDATA [nfe_issued_mb_pdf_file]]> </ wp: meta_key>
<wp: meta_value> <! [CDATA [11]]> </ wp: meta_value>
</ wp: postmeta>

as would be the right meta_volue have the way of attachment as below.

<wp: postmeta>
<wp: meta_key> <! [CDATA [_wp_attached_file]]> </ wp: meta_key>
<wp: meta_value> <! [CDATA [2015/12 / CODE-OF-THE-ENVIRONMENT-IPI.pdf]]> </ wp: meta_value>
</ wp: postmeta>

ie to import the xml it does not indicate to me the attached file via metabox

Somebody help me, please?

**Comment by funkedgeek** [comment]
The meta for media fields stores the id of the files, not the files themselves
