### ISSUE TITLE
PHP Field Type

### ISSUE THREAD

**Issue by ahmadawais** [rilwis/meta-box#742]
Is there a possibility to have a `php` field type just like the one we have for `html`?

**Comment by rilwis** [comment]
I think we can do that.

**Comment by ahmadawais** [comment]
Looking forward!

**Comment by rilwis** [comment]
I've just started working on this and I found that we can achieve the result without creating more field types. The field `custom_html` can do this in a simple (and safe) way:

```php
array(
    'type' => 'custom_html',
    'callback' => 'prefix_function_name', // callback function that returns the output
),

// And function
function prefix_function_name( $meta, $field ) {
    $output = '//code goes here';
    return $output;
}
```

**Comment by ahmadawais** [comment]
Yes, I have been doing that for a while now. :)

**Comment by rilwis** [comment]
Great that you found that :)
