### ISSUE TITLE
std not working

### ISSUE THREAD

**Issue by rafasegat** [rilwis/meta-box#743]
Hi,

std value is not working for me. In all fields, the default value is not working.

Is there a documentation about it?

Thanks

**Comment by funkedgeek** [comment]
I think std only works if the post is new and hasn't been saved before.

**Comment by WEBIDIA** [comment]
I believe what @funkedgeek is true, however i'm not able to get std to work at all for the field type select_advanced

**Comment by funkedgeek** [comment]
How are you trying to use std @WEBIDIA ?

**Comment by rilwis** [comment]
I've just pushed a fix 4309e6e0282bd9679e890c13d0c8704b1f30819a, hope it fixes the bug.
