### ISSUE TITLE
Fatal Error after upgrade !!! Please help !

### ISSUE THREAD

**Issue by VictorConstruct** [rilwis/meta-box#744]
Hy there,
i am using Real Homes 2.3.0 and after updating to Meta Box 3.7.3 in Addd new property I’m reciving this error
“Fatal error: Call to undefined method RW_Meta_Box::has_been_saved() in /home/victor/public_html/wp-content/themes/realhomes/framework/meta-box/extensions/meta-box-group/meta-box-group.php on line 70”
please someone could help me and tell me what is to e done ???
I should say that after I disable meta box … everything works fine but i don’t have my field in Add New Property
tahnks !!! :) I am new in WordPress and Php !

**Comment by funkedgeek** [comment]
You're getting the error because meta box group hasn't been updated as well
