### ISSUE TITLE
Add timestamp support for date field

### ISSUE THREAD

**Issue by rilwis** [rilwis/meta-box#746]
And also refactor date + datetime fields to use the same codebase to convert date, time.

**Comment by funkedgeek** [comment]
Refactoring done but not sure how you want timestamp to work

**Comment by rilwis** [comment]
I think we should make it simple: if `'timestamp' => true`, then store timestamp in the meta field instead of date. But output the date in the field for user to choose.

**Comment by funkedgeek** [comment]
So the current time and date every time the meta is saved?

**Comment by rilwis** [comment]
No.

If user selects date = 12/3/2016, then the value save is timestamp('12/3/2016').

**Comment by funkedgeek** [comment]
Sorry, not understanding the difference

**Comment by rilwis** [comment]
For example:

We have a date field with format "yyyy-mm-dd". When user clicks on that field, he can choose any date, like "1/1/2017".

When we save the field, we will convert "1/1/2017" to timestamp and save that timestamp into the custom field.

Here we don't save the current time or something. We save timestamp of the selected date.

**Comment by funkedgeek** [comment]
Just not understanding what you mean by timestamp.  Is that a specific
format?

**Comment by rilwis** [comment]
Ah, it's the Unix timestamp. See here https://en.wikipedia.org/wiki/Unix_time

**Comment by rilwis** [comment]
Similar to what we get from `time()`

**Comment by funkedgeek** [comment]
Okay, you already have it like that.

**Comment by funkedgeek** [comment]
Can you double check the date refactoring branch?  Seems to work for both single and clone for all 3 date fields

**Comment by rilwis** [comment]
I will check it later today. Thanks for the great work!
