### ISSUE TITLE
Metabox Tabs Issue

### ISSUE THREAD

**Issue by krishna19** [rilwis/meta-box#747]
Hi,

I have updated my metabox plugins yesterday as advised in a previous post #736 (which fixed that issue) but now if I try to select the fields in second tab, the field was hide and the fields from the first tab was displayed.

https://www.youtube.com/watch?v=0-t-N3Js6hk

Please check the firebug changes

Metabox: 4.7.3
Conditional Logic: 1.2
Tabs: 0.1.7

Code:
<pre>
add_filter( 'rwmb_meta_boxes', 'krish_register_meta_boxes' );

if( ! function_exists( 'krish_register_meta_boxes' ) ) {
    function krish_register_meta_boxes( $meta_boxes )
    {
        /**
         * prefix of meta keys (optional)
         * Use underscore (_) at the beginning to make keys hidden
         * Alt.: You also can make prefix empty to disable it
         */
        // Better has an underscore as last sign
        $prefix = 'krish_';

        $meta_boxes[] = array(
            'id'            => 'rwmb_general_options',
            'title'         => __( 'General Options', 'rwmb' ),
            'post_types'    => array( 'post', 'page' ),
            'context'       => 'normal',
            'priority'      => 'high',
            'autosave'      => true,

            'tabs'          => array(
                'post'              => __( 'Post', 'rwmb' ),
                'layout'            => __( 'Layout', 'rwmb' ),
                'header'            => __( 'Header', 'rwmb' ),
            ),
            'tab_style'     => 'box',
            'tab_wrapper'   => true,

            'fields'     => array(
                
                array(
                    'name'              => __( 'Post - Text Box', 'rwmb' ),
                    'id'                => "{$prefix}post_text",
                    'desc'              => __( 'Test Box', 'rwmb' ),
                    'type'              => 'text',
                    'clone'             => false,
                    'std'               => '',
                    'tab'               => 'post',
                ),
                
                array(
                    'name'              => __( 'Layout - Select Box', 'rwmb' ),
                    'id'                => "{$prefix}layout_select_box",
                    'type'              => 'select',
                    'options'           => array(
                        'default'       => __( 'Default', 'rwmb' ),
                        'option_1'          => __( 'Option 1', 'rwmb' ),
                        'option_2'          => __( 'Option 2', 'rwmb' ),
                    ),
                    'multiple'          => false,
                    'std'               => 'default',
                    'tab'               => 'layout',
                ),
                
                array(
                    'name'              => __( 'Layout - Text Box 2', 'rwmb' ),
                    'id'                => "{$prefix}layout_text",
                    'desc'              => __( 'Test Box', 'rwmb' ),
                    'type'              => 'text',
                    'clone'             => false,
                    'std'               => '',
                    'tab'               => 'layout',
                    'visible'			=> array( 'krish_layout_select_box', '=', 'option_1' ),
                ),
                
                array(
                    'name'              => __( 'Layout - Select Box 2', 'rwmb' ),
                    'id'                => "{$prefix}layout_select_box_2",
                    'type'              => 'select',
                    'options'           => array(
                        'default'       => __( 'Default', 'rwmb' ),
                        'option_1'          => __( 'Option 1', 'rwmb' ),
                        'option_2'          => __( 'Option 2', 'rwmb' ),
                    ),
                    'multiple'          => false,
                    'std'               => 'default',
                    'tab'               => 'layout',
                    'visible'			=> array( 'krish_layout_select_box', '=', 'option_1' ),
                ),
                
                array(
                    'name'              => __( 'Header - Select Box', 'rwmb' ),
                    'id'                => "{$prefix}header_select_box",
                    'type'              => 'select',
                    'options'           => array(
                        'default'       => __( 'Default', 'rwmb' ),
                        'option_1'          => __( 'Option 1', 'rwmb' ),
                        'option_2'          => __( 'Option 2', 'rwmb' ),
                    ),
                    'multiple'          => false,
                    'std'               => 'default',
                    'tab'               => 'header',
                ),
            )
        );

        return $meta_boxes;
    }
}

add_filter( 'rwmb_outside_conditions', function( $conditions )
{
    $conditions['.rwmb-tab-post, .rwmb-tab-panel-post'] = array(
        'hidden' => ['post_type', 'not in', ['post']]
    );

    $conditions['.rwmb-tab-panel-layout'] = array(
        'visible' => ['post_type', 'not in', ['post']]
    );

    return $conditions;
} );
</pre>

Thanks

**Comment by tanng** [comment]
Thanks @krishna19  for reporting this bug.

Hmm, the problem is when this conditional logic applies for pages it will works but not for posts because the tab panel layout only visible when post type not in post. I'm thinking a way to fix this.

There is a workaround for you at this time, just ignore conditions if current post type is `post`. Btw, I have changed the `not in` operator to `!=` because you're compare with only one value, not an array:

```
add_filter( 'rwmb_outside_conditions', function( $conditions )
{
	global $post;
	
	if ( $post->post_type === 'post' )
		return $conditions;

    $conditions['.rwmb-tab-post, .rwmb-tab-panel-post'] = [
        'hidden' => ['post_type', '!=', 'post']
    ];

    $conditions['.rwmb-tab-panel-layout'] = [
        'visible' => ['post_type', '!=', 'post']
    ];

    return $conditions;
} );
```

Best regards

**Comment by krishna19** [comment]
@tanng For Post it works fine. But for Page the problem is not solved. Please help

**Comment by tanng** [comment]
I have tested with both Post and Page and it works. Can you please post your full code if something changed?

**Comment by krishna19** [comment]
@tanng All tabs works fine in **Post**. In **Pages** Layout Tab Works fine, But in other tabs whenever I try to select the field which uses the conditional logic, The layout tab was duplicated. Please check the video.

https://www.youtube.com/watch?v=RsAZmxBusgk

Here's the full code
<pre>
add_filter( 'rwmb_meta_boxes', 'krish_register_meta_boxes' );

if( ! function_exists( 'krish_register_meta_boxes' ) ) {
    function krish_register_meta_boxes( $meta_boxes )
    {
        /**
         * prefix of meta keys (optional)
         * Use underscore (_) at the beginning to make keys hidden
         * Alt.: You also can make prefix empty to disable it
         */
        // Better has an underscore as last sign
        $prefix = 'krish_';

        // Background Options
        $meta_boxes[] = array(
            'id'            => 'rwmb_general_options',
            'title'         => __( 'General Options', 'rwmb' ),
            'post_types'    => array( 'post', 'page' ),
            'context'       => 'normal',
            'priority'      => 'high',
            'autosave'      => true,

            'tabs'          => array(
                'post'              => __( 'Post', 'rwmb' ),
                'layout'            => __( 'Layout', 'rwmb' ),
                'header'            => __( 'Header', 'rwmb' ),
            ),
            'tab_style'     => 'box',
            'tab_wrapper'   => true,

            'fields'     => array(
                
                array(
                    'name'              => __( 'Select Box', 'rwmb' ),
                    'id'                => "{$prefix}post_select_1",
                    'type'              => 'select',
                    'options'           => array(
                        ''              => __( 'Select Option', 'rwmb' ),
                        'opt_1'         => __( 'Option 1', 'rwmb' ),
                        'opt_2'         => __( 'Option 2', 'rwmb' ),
                    ),
                    'multiple'          => false,
                    'std'               => '',
                    'tab'               => 'post',
                ),
                
                array(
                    'name'              => __( 'Post Text Box', 'rwmb' ),
                    'id'                => "{$prefix}post_text_1",
                    'type'              => 'text',
                    'clone'             => false,
                    'std'               => '',
                    'tab'               => 'post',
                    'visible'           => array( 'krish_post_select_1', '=', 'opt_1' ),
                ),
                
                array(
                    'name'              => __( 'Select Box 2', 'rwmb' ),
                    'id'                => "{$prefix}layout_select_1",
                    'type'              => 'select',
                    'options'           => array(
                        ''              => __( 'Select Option', 'rwmb' ),
                        'opt_1'         => __( 'Option 1', 'rwmb' ),
                        'opt_2'         => __( 'Option 2', 'rwmb' ),
                    ),
                    'multiple'          => false,
                    'std'               => '',
                    'tab'               => 'layout',
                ),
                
                array(
                    'name'              => __( 'Text Box 2', 'rwmb' ),
                    'id'                => "{$prefix}layout_text_1",
                    'type'              => 'text',
                    'clone'             => false,
                    'std'               => '',
                    'tab'               => 'layout',
                    'visible'           => array( 'krish_layout_select_1', '=', 'opt_1' ),
                ),
                
                array(
                    'name'              => __( 'Select Box 3', 'rwmb' ),
                    'id'                => "{$prefix}header_select_1",
                    'type'              => 'select',
                    'options'           => array(
                        ''              => __( 'Select Option', 'rwmb' ),
                        'opt_1'         => __( 'Option 1', 'rwmb' ),
                        'opt_2'         => __( 'Option 2', 'rwmb' ),
                    ),
                    'multiple'          => false,
                    'std'               => '',
                    'tab'               => 'header',
                ),
                
                array(
                    'name'              => __( 'Text Box 3', 'rwmb' ),
                    'id'                => "{$prefix}header_text_1",
                    'type'              => 'text',
                    'clone'             => false,
                    'std'               => '',
                    'tab'               => 'header',
                    'visible'           => array( 'krish_header_select_1', '=', 'opt_1' ),
                ),
            )
        );

        return $meta_boxes;
    }
}

add_filter( 'rwmb_outside_conditions', function( $conditions )
{
    global $post;

    if ( $post->post_type === 'post' )
        return $conditions;

    $conditions['.rwmb-tab-post, .rwmb-tab-panel-post'] = [
        'hidden' => ['post_type', '!=', 'post']
    ];

    $conditions['.rwmb-tab-panel-layout'] = [
        'visible' => ['post_type', '!=', 'post']
    ];

    return $conditions;
} );
</pre>

**Comment by tanng** [comment]
Hi @krishna19 

Post type is never change since the page load, so isn't necessary to apply conditional logic to these tabs. I have modified your code like so:

This create a meta box for post and another only for page but still keep your code clean and easy to update.

```php
<?php
add_filter( 'rwmb_meta_boxes', 'krish_register_meta_boxes' );

if( ! function_exists( 'krish_register_meta_boxes' ) ) {
    function krish_register_meta_boxes( $meta_boxes )
    {
        /**
         * prefix of meta keys (optional)
         * Use underscore (_) at the beginning to make keys hidden
         * Alt.: You also can make prefix empty to disable it
         */
        // Better has an underscore as last sign
        $prefix = 'krish_';

        // Background Options
        
        // Create a Meta Box for Post. Note that I've removed `post_types`
        $meta_box = array(
            'id'            => 'rwmb_general_options',
            'title'         => __( 'General Options', 'rwmb' ),
            'context'       => 'normal',
            'priority'      => 'high',
            'autosave'      => true,
            'tabs'          => array(
                'post'              => __( 'Post', 'rwmb' ),
                'layout'            => __( 'Layout', 'rwmb' ),
                'header'            => __( 'Header', 'rwmb' ),
            ),
            'tab_style'     => 'box',
            'tab_wrapper'   => true,

            'fields'     => array(
                
                array(
                    'name'              => __( 'Select Box', 'rwmb' ),
                    'id'                => "{$prefix}post_select_1",
                    'type'              => 'select',
                    'options'           => array(
                        ''              => __( 'Select Option', 'rwmb' ),
                        'opt_1'         => __( 'Option 1', 'rwmb' ),
                        'opt_2'         => __( 'Option 2', 'rwmb' ),
                    ),
                    'multiple'          => false,
                    'std'               => '',
                    'tab'               => 'post',
                ),
                
                array(
                    'name'              => __( 'Post Text Box', 'rwmb' ),
                    'id'                => "{$prefix}post_text_1",
                    'type'              => 'text',
                    'clone'             => false,
                    'std'               => '',
                    'tab'               => 'post',
                    'visible'           => array( 'krish_post_select_1', '=', 'opt_1' ),
                ),
                
                array(
                    'name'              => __( 'Select Box 2', 'rwmb' ),
                    'id'                => "{$prefix}layout_select_1",
                    'type'              => 'select',
                    'options'           => array(
                        ''              => __( 'Select Option', 'rwmb' ),
                        'opt_1'         => __( 'Option 1', 'rwmb' ),
                        'opt_2'         => __( 'Option 2', 'rwmb' ),
                    ),
                    'multiple'          => false,
                    'std'               => '',
                    'tab'               => 'layout',
                ),
                
                array(
                    'name'              => __( 'Text Box 2', 'rwmb' ),
                    'id'                => "{$prefix}layout_text_1",
                    'type'              => 'text',
                    'clone'             => false,
                    'std'               => '',
                    'tab'               => 'layout',
                    'visible'           => array( 'krish_layout_select_1', '=', 'opt_1' ),
                ),
                
                array(
                    'name'              => __( 'Select Box 3', 'rwmb' ),
                    'id'                => "{$prefix}header_select_1",
                    'type'              => 'select',
                    'options'           => array(
                        ''              => __( 'Select Option', 'rwmb' ),
                        'opt_1'         => __( 'Option 1', 'rwmb' ),
                        'opt_2'         => __( 'Option 2', 'rwmb' ),
                    ),
                    'multiple'          => false,
                    'std'               => '',
                    'tab'               => 'header',
                ),
                
                array(
                    'name'              => __( 'Text Box 3', 'rwmb' ),
                    'id'                => "{$prefix}header_text_1",
                    'type'              => 'text',
                    'clone'             => false,
                    'std'               => '',
                    'tab'               => 'header',
                    'visible'           => array( 'krish_header_select_1', '=', 'opt_1' ),
                ),
            )
        );
		
		// Create a meta box for pages which similar to above meta box but removed first tab
		$meta_box_page = $meta_box;
		$meta_box_page['post_types'] = 'page';
		$meta_box_page['tabs'] = [
            'layout'  => __( 'Layout', 'rwmb' ),
            'header'  => __( 'Header', 'rwmb' ),
		];

		// Register two meta boxes above
		$meta_boxes[] = $meta_box;
		$meta_boxes[] = $meta_box_page;

        return $meta_boxes;
    }
}
```

**Comment by krishna19** [comment]
@tanng Thanks. Now everything works fine. If I don't add post types, metaboxes are not displayed on pages and other post types. So I change like this
<pre>
&lt;?php
add_filter( 'rwmb_meta_boxes', 'krish_register_meta_boxes' );

if( ! function_exists( 'krish_register_meta_boxes' ) ) {
    function krish_register_meta_boxes( $meta_boxes )
    {
        $prefix = 'krish_';
        <strong>$post_types = get_post_types();</strong>

        // Remove the Post Tab
        $meta_box = array(
            'id'            => 'rwmb_general_options',
            'title'         => __( 'General Options', 'rwmb' ),
            <strong>'post_types'    => $post_types,</strong>
            'context'       => 'normal',
            'priority'      => 'high',
            'autosave'      => true,
            'tabs'          => array(
                'layout'            => __( 'Layout', 'rwmb' ),
                'header'            => __( 'Header', 'rwmb' ),
            ),
            'tab_style'     => 'box',
            'tab_wrapper'   => true,
            'fields'     => array()
        );
        
        $meta_box_post = $meta_box;
        $meta_box_post['post_types'] = 'post';
        $meta_box_post['tabs'] = [
            <strong>'post'              => __( 'Post', 'rwmb' ),</strong>
            'layout'            => __( 'Layout', 'rwmb' ),
            'header'            => __( 'Header', 'rwmb' ),
        ];

        // Register Metaboxes
        $meta_boxes[] = $meta_box;
        $meta_boxes[] = $meta_box_post;

        return $meta_boxes;
    }
}
</pre>

**Comment by tanng** [comment]
Awesome man :+1:
