### ISSUE TITLE
Uncaught ReferenceError: rwmbFile is not defined

### ISSUE THREAD

**Issue by rhino88** [rilwis/meta-box#753]
When I click the "Add Image" button I see the error coming from this line:

`msg = maxFileUploads > 1 ? rwmbFile.maxFileUploadsPlural : rwmbFile.maxFileUploadsSingle;`

I'm also having an issue where the images saved on this field previously are no longer showing up. I am on the latest version of WP and this plugin.

Is there an older version of this plugin that I should revert to?

**Comment by funkedgeek** [comment]
What line number is this?

**Comment by rhino88** [comment]
https://github.com/rilwis/meta-box/blob/71dde7afb46a2799cb2c338b04264c10c6b7d12f/js/plupload-image.js#L41

It's a basic image field

**Comment by rhino88** [comment]
Let me know if you require any additional information

**Comment by funkedgeek** [comment]
Not getting this error.  Also, not seeing an `Add image` button, just `Select Files`.  The code you linked to is from plupload_image; are you using that or the image field?

**Comment by funkedgeek** [comment]
Are you on the latest version on WP.org or the latest from github?

**Comment by funkedgeek** [comment]
This should be fixed in the next version of the plugin.  Plupload_image now shares the same code as image_advanced.  Please try the github version

**Comment by funkedgeek** [comment]
This should be fixed since the code has been overhauled.  Please reopen if you are still running into issues
