### ISSUE TITLE
Detecting color picker changind

### ISSUE THREAD

**Issue by rafasegat** [rilwis/meta-box#758]
Hi

How can I detect when the user is changing the color picker?

While the user change the color picker bind a change..

Thanks 
Raf

**Comment by funkedgeek** [comment]
If you know the id of the color field, just bind to the change event:

```
jQuery( '#color_field' ).on( 'change', function( e ){
    //Do stuff.  Access the field using $( this )
}  )
```

**Comment by rafasegat** [comment]
Hii man, thanks

I already tried this. There is no way. Maybe im using the incorrect id.

**Comment by rafasegat** [comment]
<pre>
jQuery('#rfkt_preloader_color').on("propertychange change click keyup input paste", function() {
	  var preloader_color = jQuery(this).val();
	jQuery('.'+preloader).css({'background-color' : '#' + preloader_color});
	console.log(preloader); 
});
</pre>

**Comment by rafasegat** [comment]
I got it!!!

<pre>
function watchProperty(obj, name, handler) {
	    if ('watch' in obj) {
	        obj.watch(name, handler);
	    } else if ('onpropertychange' in obj) {
	        name= name.toLowerCase();
	        obj.onpropertychange= function() {
	            if (window.event.propertyName.toLowerCase()===name)
	                handler.call(obj);
	        };
	    } else {
	        var o= obj[name];
	        setInterval(function() {
	            var n= obj[name];
	            if (o!==n) {
	                o= n;
	                handler.call(obj);
	            }
	        }, 200);
	    }
	}

	watchProperty(document.getElementById('rfkt_preloader_color'), 'value', function(e) {
	    var preloader_color = jQuery(this).val();
	    console.log(preloader_color);
	});
</pre>

Fuck yeah! 1 day spent off to that :)

**Comment by funkedgeek** [comment]
Fixed in https://github.com/rilwis/meta-box/commit/69fc390c31d6acb2b0286806c2fed7220d07db89
