### ISSUE TITLE
master latest version triggers multiple warnings

### ISSUE THREAD

**Issue by TweetPressFr** [rilwis/meta-box#759]
Hi, I've checked the 4.7.3 tag and in meta-box-loader.php a "if ( ! class_exists( 'RWMB_Loader' ) ) {}" would sove error 500 in case we use your framework in a plugin while another plugin or a theme is using it.

What do you thing about it ? I also noticed you delete meta-box-loader.php in master ? why ?
Regards.

**Comment by rilwis** [comment]
Hi,

We have rewritten the mechanism of loading the plugin in the development version on Github. The new loading mechanism uses autoload which solves the problem if the plugin is already embed in a theme or plugin or already installed as a standalone version. It also works with Composer.

Please try it and let us know the result.
