### ISSUE TITLE
Post field query_args not applied

### ISSUE THREAD

**Issue by wgstjf** [rilwis/meta-box#765]
Hi guys,

Got a strange, hopefully quick, one here for you...

I am using the Post field to get a list of all the pages on the site.  Using the query_args I have defined the order to be 'menu_order' but it is not being applied.  All Pages are being returned in their default (ID) order...can you help?

``` php

// POST - Page
array(
	'name'        => __( 'Choose Page', 'indigo-options' ),
	'id'          => 'page',
	'type'        => 'post',
	'post_type'   => array('page' ),
	'field_type'  => 'select',
	'placeholder' => __( 'Select a page', 'indigo-options' ),
	'query_args'  => array(
		'post_status'    => 'publish',
		'posts_per_page' => - 1,
		'orderby' => 'menu_order',
	),
	'columns'   => '12',
	'visible' => array( 'type', '=', array('page') ),
),
```

Cheers,

Will

**Comment by funkedgeek** [comment]
What version of the plugin are you using?

**Comment by funkedgeek** [comment]
Okay just tested it out.  Menu order works fine with the current version of the plugin but it defaults at descending ie largest menu order first.  You might want to add `'order' => 'asc'` to make it work the way you want.  Also Are all those pages on the same level or are some of them children to other pages?

**Comment by wgstjf** [comment]
Perfect thanks...was missing the 'order' var.  Thanks!

Will
