### ISSUE TITLE
Metabox Columns / Conditional Logic feature request

### ISSUE THREAD

**Issue by wgstjf** [rilwis/meta-box#766]
Hi guys,

Another one from me.... :-)

I would love to be able to define fields that use columns, in combination with Conditional Logic's visibility, so that I can, for example have a select list with a column width of 4 and then 2 hidden fields each with a column width of 8.  Depending on which option is selected from the list this would then show the correct field with the remaining 8 column width.

The problem seems to be that the Metabox Columns plugin does not ignore columns with fields that are hidden and as such the layout gets messed up.  So the request is just that, can the Columns plugin be modified to ignore hidden field columns, thus enabling more than one field to show up in the same place (though obviously not at the same time).

Hopefully this makes sense...

Will

**Comment by tanng** [comment]
Hi Will, I've fixed in the latest release. Please check the latest version and tell me if you meet some problem. 

Thank you.
