### ISSUE TITLE
Call to undefined function wp_normalize_path() 

### ISSUE THREAD

**Issue by hamdan-mahran** [rilwis/meta-box#767]
Hi
Thank you so much for this awesome plugin!
I get this error inside ins/loader.php file:

<pre>
Fatal error: Call to undefined function wp_normalize_path() in /web/htdocs/www.studiotecnicobaldi.com/home/wp-content/themes/enar/theme-admin/metaboxes/inc/loader.php on line 72
</pre>

Important note: This issue not showing in my localhost 2 another domains.

Thanks!

**Comment by funkedgeek** [comment]
wp_normalize_path is a function baked into WordPress, so it sounds to me that the theme is calling meta box before WordPress is fully loaded

**Comment by hamdan-mahran** [comment]
Thank you so much for your reply @funkedgeek 
It's my theme, and it's works good for me and for about 28 other client!
I don't know how to fix it because i don't have experience in PHP.
What is your advice to fix it?
Thanks!

**Comment by funkedgeek** [comment]
How are you loading Meta Box in your theme?

**Comment by hamdan-mahran** [comment]
Here is my code inside functions.php
<pre>
if ( file_exists( ENAR_DIR . '/theme-admin/metaboxes/meta-box.php' ) ) {
	require_once( ENAR_DIR . '/theme-admin/metaboxes/meta-box.php' );
}
</pre>

Thanks again for your quick reply! :)

**Comment by funkedgeek** [comment]
Which version of WP are you using?

**Comment by hamdan-mahran** [comment]
I send this question to my client! to know which version he use.
Thank you so much mr @funkedgeek  :)

**Comment by funkedgeek** [comment]
From what I'm looking at, the function was added in WP 3.9, so if yor client is getting errors, its because he's running an old version of WP

**Comment by hamdan-mahran** [comment]
Yes mar @funkedgeek  i contact with my client, and he tell me that he use old WordPress version.
Now i know that we should update WordPress!
Thank you so much! :)
