### ISSUE TITLE
issue with Oembed field

### ISSUE THREAD

**Issue by thatvideowebguy** [rilwis/meta-box#770]
Button displays 30 and apercu (preview) outside of button

![cap](https://cloud.githubusercontent.com/assets/10667757/13116571/b48ced90-d59c-11e5-9988-82ae67a98b17.jpg)

**Comment by funkedgeek** [comment]
What is the code for the field you are using?

**Comment by funkedgeek** [comment]
Fixed in https://github.com/rilwis/meta-box/commit/0050a018233e482f0136580fd8f9cbd2123f5704.  Please update from github.  Update will come later from wordpress.org
