### ISSUE TITLE
custom metabox with custom html/php & js 

### ISSUE THREAD

**Issue by thatvideowebguy** [rilwis/meta-box#772]
Hi, 
Is there a way to create a custom metabox to display for example, 
a field where i can use drag and drop or other custom events (via JS script) 
(to create custom slides for a slider) ?
Thanks

**Comment by rilwis** [comment]
I think this is more complicated and you can use the `custom_html` field to output custom HTML code for the field, then enqueue JS to do your job. But as I said, it's very complicated and I'm not recommending.
