### ISSUE TITLE
Issues retrieving taxonomy data in 4.8.1 (and 4.8.0)

### ISSUE THREAD

**Issue by ckbedwell** [rilwis/meta-box#773]
Hey guys,

Just updated to 4.8.1 and now having an issue with retrieving taxonomy data from the taxonomy field type. I rolled back to 4.7.3 and have everything working again. I can see that in 4.8.0 there's a note saying taxonomy fields have been updated and I can't work out how I should be updating my code to play ball with them.

Registering the taxonomy field:
```php 
array(
'name'    => __( 'What type of tents?', 'rwmb' ),
'id'      => "type-of-tents",
'field_type' => 'select_advanced',
'multiple' => 'true',
'type'    => 'taxonomy',
'options' => array (
     'taxonomy' => 'tent_type',
     'placeholder' => __( 'Select an Item', 'rwmb' ),
     ),
),
```

This all works nicely in Wordpress' admin and I can see the taxonomy and select the terms I want.

Retrieving the taxonomy:

```php
$tent_types = rwmb_meta( 'type-of-tents', 'type=taxonomy&taxonomy=tent_type' );
foreach($tent_types as $tent_type) { 
// feeds a new wp_query depending on which taxonomies have been selected
}
```

So, in 4.7.3 this works perfectly and I have no issues. In 4.8.1 I'm now getting:
```html
Warning: Invalid argument supplied for foreach() .../my-templates/event-sub-page.php on line 161
```

I'm not sure if the documentation has been updated for 4.8.1 but I'm following the example here: https://metabox.io/docs/get-meta-value/#section-examples, and seem to be having no luck. 

How should I be changing the retrieval so it's getting the type-of-tents data? Is it possible to get the docs updated to reflect the new changes.

**Comment by funkedgeek** [comment]
This is most likely related to https://github.com/rilwis/meta-box/issues/768#issuecomment-185789798.  Basically if you are using the old way of loading the meta box plugin, it won't be seen on the front end and rwmb_meta doesn't work.

**Comment by ckbedwell** [comment]
Brilliant, thank you! Bit of tinkering but I've worked it all out now from that. Great work as always.
