### ISSUE TITLE
how do i solve this issue "Warning: call_user_func() expects parameter 1 to be a valid callback, class 'RWMB_Group_Field' not found in /home/name/public_html/wp-content/plugins/meta-box/inc/meta-box.php on line 353"

### ISSUE THREAD

**Issue by trenovaltd** [rilwis/meta-box#774]
how do i solve this issue "Warning: call_user_func() expects parameter 1 to be a valid callback, class 'RWMB_Group_Field' not found in /home/name/public_html/wp-content/plugins/meta-box/inc/meta-box.php on line 353" pls author assist me on that

**Comment by rilwis** [comment]
Hi, please update the Group extension to 1.0.5 to fix this.

Thanks

**Comment by trenovaltd** [comment]
how do i do the update i can not see it in my plugin

**Comment by rilwis** [comment]
Please login to the [support forum](https://metabox.io/support/) and go to **My Account** to download the update. If you haven't an account, please register a new one.

Another way is installing the [Updater extension](https://metabox.io/plugins/meta-box-updater/) which can auto update the extension.
