### ISSUE TITLE
rwmb_meta calls are very slow

### ISSUE THREAD

**Issue by bcheriaux** [rilwis/meta-box#775]
Hi,
I developped a WP website one year ago with Meta Box 4.4.2. I'm working on an upgrade of this website. I have updated Meta Box and Wordpress to their last releases (MB 4.8.1, WP 4.4.2).
I'm experiencing a serious slowdown on page generation each time the rwmb_meta() function is called.
For instance, without any rwmb_meta call, page is generated in 1.2s
- one call to rwmb_meta : 1.96s
- 2 calls to rwmb_meta : 2.55s
- 3 calls to rwmb_meta : 3.3s
- etc...

If I use the get_post_meta function instead, there is no slowdown. Am I doing something wrong ? Anyone experiencing the same issue ?
Thanks

**Comment by rilwis** [comment]
Hmm, I haven't thought about that. Can you share the way you test the run time? And how you define meta boxes and fields?

**Comment by funkedgeek** [comment]
It might be because every time you call rwmb_meta, it calls all the meta boxes and then searches each one for the right field.  Maybe we should do a hash table or something similar to prevent the search.

**Comment by bcheriaux** [comment]
Hi, 
Tx for replying so quickly.
It's complicated to share you my project, but I can say:
- I have created 6 custom post types (function.php)
- I have created 6 metaboxes (one for each custom post type) in function.php too
- I checked twice the way I created metaboxes (copying your demo.php file)
- My metaboxes have several fields : 
 - metabox #1 : 6 fields (text, text area, image_advanced)
 - metabox #2 : 38 fields (text, text area, file, image_advanced)
 - metabox #3 : 10 fields (heading, date, text, text area, file, image_advanced)
 - metabox #4 : 4 fields (text, url, image_advanced)
 - metabox #5 : 32 fields (heading, select, text, text area)
 - metabox #6 : 60 fields (heading, select, text, text area, taxonomy, image_advanced, color, radio)

As @finkedgeek said: if every time I call rwmb_meta, it loops through all the fields, it could be the reason of slowdown. 
The question is: "why it was working well with Meta Box 4.4.2?"

**Comment by funkedgeek** [comment]
My idea: when meta boxes are defined, take the normalized fields and add them in an indexed static array.  Instead of searching for the field, just use the field id to get the field.  It should speed up rwmb_meta significanlty

**Comment by rilwis** [comment]
@funkedgeek I think we have to do that. Also cache the result of `find_field` method so we don't have to apply filters anymore. Can you please implement that?

**Comment by rilwis** [comment]
I think the 4.8.2 is much faster now :)
