### ISSUE TITLE
Metabox plugin can't activate

### ISSUE THREAD

**Issue by Ninetheme** [rilwis/meta-box#776]
Hello Heros

Thank you so much firstly! and there is a problem about 4.8.1 version because our custoumers can't activate plugin after update.

And there is a way for plugin add tgmpa ? If you add metabox php codes in the themes and plugin not activated you see a undefined php problem etc.

**Comment by rilwis** [comment]
Could you please try remove the older version of the plugin and re-install the 4.8.1?

Regarding using the plugin inside a theme or plugin, please see [this documentation](https://metabox.io/docs/include-meta-box-plugin-themes/).

**Comment by Ninetheme** [comment]
Thanks Rilwis,

We already use this TGMPA and there is no problem on fresh theme installation, problem just about update plugin. When you update metabox you can't activate it.

1. Install 4.7.3 version of plugin
2. Update to 4.8.1
3. Refresh plugin page on WP

Please try it

**Comment by rilwis** [comment]
I tested with a fresh installation of WP and here is how I did:

http://recordit.co/Qwnex2Ed7h

Did you see any error appears when updating the plugin?

**Comment by Ninetheme** [comment]
Thank you but I'm not sure really, I don't see any error message. I will update TGMPA and let you know

**Comment by Ninetheme** [comment]
I found problem but still have problem :

We are using the some codes in the theme files likes this : 

`<?php
			$images = rwmb_meta( 'beard_gallery_image', 'type=image_advanced' );
			$beards_gallery_style = rwmb_meta('beard_gallery_style', 'type=select');
			
?>`

and we want to add plugin via TGMPA but when metabox not active theme showing undefined function rwmb...

any idea or solution please ?

**Comment by funkedgeek** [comment]
@Ninetheme Add an iff statement that checks for that function:
```
<?php
        if( function_exists( 'rwmb_meta' ) {
            $images = rwmb_meta( 'beard_gallery_image', 'type=image_advanced' );
            $beards_gallery_style = rwmb_meta('beard_gallery_style', 'type=select');
        }
?>
```

**Comment by Ninetheme** [comment]
Thank you Funkedgeek

but, there is a lot of lines in the theme files  : 


```
<article id="post-<?php the_ID(); ?>" <?php post_class(); ?>>
	<div class="blog-bg">
		<?php
			$images = rwmb_meta( 'beard_gallery_image', 'type=image_advanced' );
			$beards_gallery_style = rwmb_meta('beard_gallery_style', 'type=select');
			
		?>
		<?php if($beards_gallery_style == 'value1') : ?>
			<div class="flexslider">
				<ul class="slides">
					<?php
						foreach ( $images as $image ) {
							echo "<li><img src='{$image['full_url']}' alt='{$image['alt']}' /></li>";
						}
					?>
				</ul>
			</div>
		<?php else : ?>
		<?php
		wp_enqueue_script('swipebox');
		wp_enqueue_script('beard_ninetheme_custom_swipebox');
		?>
		<div class="entry-media">
			<div class="gallery-content clearfix">
				<ul class="row">
					<?php
						foreach ( $images as $image ) {
							echo "<li class='col-sm-4'><a class='swipebox'  href='{$image['full_url']}'><img src='{$image['full_url']}' alt='{$image['alt']}' /></a></li>";
						}
					?>
				</ul>
			</div>
		</div>
	    <?php endif; ?>
	</div><!-- Ends Post Media -->

	<div class="post-container">
		<div class="content-container">
			<?php $show_quote_meta = rwmb_meta('beard_post_content_heading', 'type=select'); ?>
			<?php if($show_quote_meta == 'value1') : ?>
			<div class="entry-header">
				<?php
					if ( is_single() ) :
						the_title( '<h2 class="entry-title all-caps">', '</h2>' );
					else :
						the_title( sprintf( '<h2 class="entry-title all-caps"><a href="%s" rel="bookmark">', esc_url( get_permalink() ) ), '</a></h2>' );
					endif;
				?>
			</div><!-- .entry-header -->
			<?php endif; ?>
		
			<?php $show_gallery_meta = rwmb_meta('beard_show_gallery_meta', 'type=select'); ?>
			<?php if($show_gallery_meta == 'value1') : ?>
			<ul class="entry-meta">
				<li> <?php the_time('F j, Y'); ?></li>
				<li>  <?php esc_html_e('in', 'beard'); ?>  <?php the_category(', '); ?></li>
				<li><?php the_author(); ?></li>
			</ul>
			<?php endif; ?>
		</div>
		
		<?php $show_quote_meta = rwmb_meta('beard_post_content', 'type=select'); ?>
		<?php if($show_quote_meta == 'value1') : ?>
		<div class="entry-content">
			<?php
			/* translators: %s: Name of current post */
			the_content( sprintf(
				esc_html__( 'Continue reading %s', 'beard' ),
				the_title( '<span class="screen-reader-text">', '</span>', false )
			) );
			?>
		</div><!-- .entry-content -->
		
		<?php if ( ! is_single() ) : ?>
		<a class="margin_30" href="<?php echo get_permalink(); ?>" role="button"><?php esc_html_e( 'Continue Reading', 'beard' ); ?></a>
		<?php endif; // is_single() ?>
		
		<?php endif; ?>
		
		<?php $show_gallery_social_icons = rwmb_meta('beard_show_gallery_social_icons', 'type=select'); ?>
		<?php if($show_gallery_social_icons == 'value1') : ?>
			<!-- I got these buttons from simplesharebuttons.com -->
			<div id="share-buttons">
			<a href="http://www.facebook.com/sharer.php?u=<?php echo get_permalink(); ?>" target="_blank"><i class="fa fa-facebook"></i></a>
			<a href="http://twitter.com/share?url=<?php echo get_permalink(); ?>&text=Simple Share Buttons&hashtags=simplesharebuttons" target="_blank"><i class="fa fa-twitter"></i></a>
			<a href="https://plus.google.com/share?url=<?php echo get_permalink(); ?>" target="_blank"><i class="fa fa-google-plus"></i></a>
			<a href="http://www.digg.com/submit?url=<?php echo get_permalink(); ?>" target="_blank"><i class="fa fa-digg"></i></a>
			<a href="http://reddit.com/submit?url=<?php echo get_permalink(); ?>&title=Simple Share Buttons" target="_blank"><i class="fa fa-reddit"></i></a>
			<a href="http://www.linkedin.com/shareArticle?mini=true&url=<?php echo get_permalink(); ?>" target="_blank"><i class="fa fa-linkedin"></i></a>
			<a href="javascript:void((function()%7Bvar%20e=document.createElement('script');e.setAttribute('type','text/javascript');e.setAttribute('charset','UTF-8');e.setAttribute('src','http://assets.pinterest.com/js/pinmarklet.js?r='+Math.random()*99999999);document.body.appendChild(e)%7D)());"><i class="fa fa-pinterest"></i></a>
			<a href="http://www.stumbleupon.com/submit?url=<?php echo get_permalink(); ?>&title=Simple Share Buttons" target="_blank"><i class="fa fa-stumbleupon"></i></a>
			<a href="mailto:?Subject=Simple Share Buttons&Body=I%20saw%20this%20and%20thought%20of%20you!%20 <?php echo get_template_directory_uri(); ?>"><i class="fa fa-envelope-o"></i></a>
		</div>
		<?php endif; ?>
	</div>
</article><!-- #post-## -->
```

**Comment by Ninetheme** [comment]
Is there any solution like temporary function ? 

<?php
        function rwmb_meta {
         more more
        }
?>

**Comment by funkedgeek** [comment]
```
<?php
if( ! function_exists( 'rwmb_meta' ) {
    function rwmb_meta {
        more more
    }
}
?>
```

**Comment by rilwis** [comment]
I think the best way is activating the plugin before using it in the frontend.

Otherwise, you should write a "wrapper" function to make the website not broken, like this:

```
<?php
if ( ! function_exists( 'rwmb_meta' ) ) {
    function rwmb_meta( $key, $args = '', $post_id = null ) {
        return false;
    }
}
?>
```

**Comment by Ninetheme** [comment]
Unfortunately, redeclare rwmb_meta error and you can't activate plugin again. 

Fatal error: Cannot redeclare rwmb_meta() (previously declared in C:\wamp\www\zzz-tester-for-all-themes\wp-content\plugins\meta-box\inc\functions.php:15

**Comment by funkedgeek** [comment]
Did you place it in an if checking if the function exists or not?

**Comment by Ninetheme** [comment]
I put it in the functions.php

<?php
if ( ! function_exists( 'rwmb_meta' ) ) {
    function rwmb_meta( $key, $args = '', $post_id = null ) {
        return false;
    }
}
?>

and this : 

<?php
if( ! function_exists( 'rwmb_meta' ) {
    function rwmb_meta {
        more more
    }
}
?>

**Comment by Ninetheme** [comment]
if ( !function_exists( 'rwmb_meta' ) ) {
	require_once get_template_directory() . '/includes/metaboxes/inc/helpers.php'; }
	


}

**Comment by Ninetheme** [comment]
Finally functions_exists not working on themes, you can't activate plugin when you put these codes in the functipns.php

You can try on any theme

**Comment by rilwis** [comment]
@Ninetheme You're right. I've just tested and added a fix for this. Now you can simply declare a fallback function to make it works:

```php
<?php
if ( ! function_exists( 'rwmb_meta' ) ) {
    function rwmb_meta( $key, $args = '', $post_id = null ) {
        return false;
    }
}
?>```

I'm checking other issues and will release a new version soon. In the meantime, please download the development version on Github and use it.

**Comment by Ninetheme** [comment]
Ok , waiting and please create a docs for this update. We will share metabox plugin on envato forum after this update.

Thank you so much.!

**Comment by rilwis** [comment]
The documentation is [updated](https://metabox.io/docs/get-meta-value/#section-prevent-undefined-function-rwmb_meta).

**Comment by Ninetheme** [comment]
Did you test in the functions.php ? 


if ( ! function_exists( 'rwmb_meta' ) ) {
    function rwmb_meta( $key, $args = '', $post_id = null ) {
        return false;
    }
}

I still see problem , try it : 1. add this code, 2. deactivate metabox, 3. try to activate. not working

**Comment by rilwis** [comment]
Did you use the development version on Github? The stable version doesn't has the fix yet.

**Comment by Ninetheme** [comment]
I found old version code in my file, fixed this problem now. But :

You need to add function_exists code when you use metabox code in the any file.

I will test development version but we have 3000 customer, we waiting stabil 4.8.2 version. Thank you so much!

**Comment by Ninetheme** [comment]
Working now, Thank you so much!

I found old version admin_init line in the our old metabox register file. 

**# 1-) Add functions.php : **

if ( ! function_exists( 'rwmb_meta' ) ) {
function rwmb_meta( $key, $args = '', $post_id = null ) {
return false;
}
}

**# 2-) Create register file :**

<?php

add_filter( 'rwmb_meta_boxes', 'yourprefix_register_page_meta_boxes' );

function yourprefix_register_page_meta_boxes( $meta_boxes ) {
	
$prefix = 'ninetheme_bovile_';
$meta_boxes = array();

... // codes here

 //end
 return $meta_boxes;
}
