### ISSUE TITLE
SelectJS 4.0.1  Localization / Translation (Tip)

### ISSUE THREAD

**Issue by Sinusite** [rilwis/meta-box#777]
For translation in user language, you can add in select-advanced.php after line 18 :

```
$locale     = substr(get_locale(), 0, 2); // Working for french :p
		wp_enqueue_script( 'rwmb-select2-lang', RWMB_JS_URL . 'select2/i18n/'.$locale.'.js', array(), '4.0.1', true );
```

And then copy the i18n directory from package : https://github.com/select2/select2/releases (in dist/js/) to meta-box/js/select2/

**Comment by Sinusite** [comment]
Note that Select2 debug tell me :

> select2.min.js?ver=4.0.1:2 Select2: The language file for "./i18n/fr-FR" could not be automatically loaded. A fallback will be used instead.

**Comment by funkedgeek** [comment]
probably because the locale is returned as uppercase, while the locale files are lowercase
