### ISSUE TITLE
If image_advanced is empty display featured image

### ISSUE THREAD

**Issue by jorrit91** [rilwis/meta-box#778]
Hi guys,

I'm currently developing a WP theme with the help of MetaBox. And this is freaking awesome, it helps me make everything easy for my clients.

I've ran into an issue though. I have created a Portfolio post type, and want my customers to be able to add a slider on a portfolio item. Every portfolio at least has a Featured image, I want the slider to display if the image_advanced field is used to upload slider images. If the image_advanced field has been left blank, I want to display the featured image. It should be just an if statement but I can't get it to work. Any help?

This is the code I use now, the slider works, the featured image works, but the if statement doesn't work properly. 

`<?php if (rwmb_meta('wpos_slider_images') == '0') { ?>

	<div class="project-img">

		<img src="<?php echo $src[0]; ?>" alt="<?php the_title();?>">

	</div> 

<?php } else { ?>
	<div class="flexslider">

	<ul class="slides">

		<?php $bg_img = rwmb_meta('wpos_slider_images' , 'type=image'); ?>

		<?php if (count('$bg_img') > '0' ){

			$slide_id = 1;

			foreach ($bg_img as $img) {

				$slider_img = "{$img['full_url']}";

				echo '<li>';

				echo '<img src="' . $slider_img .'" alt="Slide'. $slide_id.'">';

				echo '</li>';

				$slide_id++;

			}

		} else if (rwmb_meta('wpos_slider_images') == '') { ?>

			<div class="project-img">

				<img src="<?php echo $src[0]; ?>" alt="<?php the_title();?>">

			</div> 

		<?php } ?>

	</ul>

</div>

<?php } ?>`

This code displays the slider if the image_advanced contains images, but if it doesn't, it doesn't fall back to the featured image.

**Comment by d2roth** [comment]
You could try a var_dump(rwmb_meta('wpos_slider_images') ) right before the first if statement to see what the value is when there are no items. I am wondering though if changing the if statement to be if( empty( rwmb_meta( 'wpos_slider_images' ) ) ) would solve your issue.

**Comment by d2roth** [comment]
Sorry, I misunderstood your comment the first time I read it.

You have a syntax error:
`    <?php if (count('$bg_img') > '0' ){`
should be: (without quotes)
`    <?php if (count($bg_img) > 0 ){`

That should get you up and going.

Just an FYI when calling rwmb_meta() on a field that is an image_advanced the result is an array containing the elements or an empty array if there are no items added in the back end.
