### ISSUE TITLE
Urgent Meta Box 4.8.1 rwmb_meta issue 

### ISSUE THREAD

**Issue by wgstjf** [rilwis/meta-box#779]
Hi guys,

I have an issue having updated to 4.8.1 (and I have updated Groups to 1.0.5 as well).  I have the following code (which worked fine before the update):

```php
while ( $slide->have_posts() ) {
            $slide->the_post();
            $count++;
            $featuredimage = wp_get_attachment_image_src( get_post_thumbnail_id( get_the_ID()), 'full' );
            $slide_small_text = rwmb_meta('slide_small_text');
            etc etc...
```

This now returns no value for $slide_small_text.

If I modify the line to the following:

```php
$slide_small_text = rwmb_meta('slide_small_text',null,get_the_ID());
```

It returns the value.  I have numerous websites out there that utilise the fact that it is not a requirement to pass the post id when using rwmb_meta inside a loop so cannot update all references to rwmb_meta across all of them.  Can you, urgently, release a fix that addresses this issue please?

Cheers,

Will

**Comment by rilwis** [comment]
Can you send me the code to register meta boxes?

**Comment by wgstjf** [comment]
Thanks for the incredibly quick response :-)

The code for the metaboxes is very long (lots of meta boxes!) but here is a snippet including the add_filter bit...

```php
add_filter( 'rwmb_meta_boxes', 'post_type_meta_boxes' );
function post_type_meta_boxes() {

  // Lots before this...

    //Slide Metaboxes
	$prefix = 'slide_';
	$meta_boxes[] = array(
		'id'       => 'slide',
		'title'    => 'Slide Information',
		'pages'    => array( 'slide' ),
		'context'  => 'normal',
		'priority' => 'high',
		'fields' => array(

      array(
				'name'  => 'Slide Small Text',
				'desc'  => 'This is the smaller text underneath the slide title',
				'id'    => $prefix . 'small_text',
				'type'  => 'textarea',
				'std'   => '',
				'clone' => false,
        'columns' => 12,
				'type' => 'textarea',
				'cols' => 20,
				'rows' => 5,
        'limits' => array (
            'type'  => 'character',
            'limit'  => '200',
            'direction'  => 'down',
          //  'text-down'  => 'characters left',
        ),
			),

      array(
				'name'  => 'Button Text',
				'desc'  => 'Enter the text for the button, eg. Learn More',
				'id'    => $prefix . 'button_text',
				'type'  => 'text',
				'std'   => '',
        'columns'     => '4',
				'clone' => false,
			),


      array(
				'name'  => 'Button URL',
				'desc'  => 'Enter the web address the button should link to',
				'id'    => $prefix . 'button_url',
				'type'  => 'text',
				'std'   => '',
        'columns'     => '4',
				'clone' => false,
			),
       ),

  // More after this...

    );

return $meta_boxes;

}
```

Cheers,

Will

**Comment by rilwis** [comment]
Hmm, I tested your code and couldn't replicate the bug. I guess it must be somewhere in the frontend where the post object is changed. Can you please share the code for the frontend as well?

**Comment by wgstjf** [comment]
Just had a thought...

The code is being called from within a shortcode on a page.  There is therefore one loop for the page and another, separate one for the shortcode which is calling up information from other posts (in this case a CPT of slides to show on the homepage).  

I will try and get you some code but I cannot paste the whole thing, but maybe you could try and replicate the issue from within a shortcode function if you have a moment?

Cheers,

Will

**Comment by rilwis** [comment]
It might relate with the custom loop. I'm receiving another question with the loop https://wordpress.org/support/topic/array-shows-up-in-some-instance-empty-in-others?replies=2#post-8066628. I'm trying to figure it out.

**Comment by wgstjf** [comment]
Thanks for getting on this so quickly...have had to revert to previous version for now as the site in question is supposed to be going live today.

Standing by for updates :-)

**Comment by rilwis** [comment]
I've just update the plugin with the code for backward compatibility. Can you please check if it works for you?

**Comment by rilwis** [comment]
Can you please confirm the latest version fixes the bug?

**Comment by wgstjf** [comment]
Sorry for not getting back to you on this.  Yes, the latest version seems to have fixed it, thanks and well done!

Cheers,

Will

**Comment by rilwis** [comment]
That's fine :). Glad that it works!
