### ISSUE TITLE
RWMB_Group Error

### ISSUE THREAD

**Issue by ochoarobert1** [rilwis/meta-box#783]
I've bought the last metabox group and updated to 4.8.1 and this message started to appear everywhere:

Warning: call_user_func() expects parameter 1 to be a valid callback, class 'RWMB_Group_Field' not found in C:\xampp\htdocs\wp_lluvia\wp-content\plugins\meta-box\inc\meta-box.php on line 353

Warning: call_user_func() expects parameter 1 to be a valid callback, class 'RWMB__Field' not found in C:\xampp\htdocs\wp_lluvia\wp-content\plugins\meta-box\inc\meta-box.php on line 63

**Comment by ochoarobert1** [comment]
Just installed the metabox updater but i don't receive any update whatsoever. 

still have the error on my site: 

Warning: call_user_func() expects parameter 1 to be a valid callback, class 'RWMB_Group_Field' not found in /home/mattioli22/public_html/lluvia/wp-content/plugins/meta-box/inc/meta-box.php on line 353

**Comment by rilwis** [comment]
Hi, could you please log in to the support forum and re-download the group v1.0.5 in "My Account" section? It has the fix for this bug.

Also, please try the development version on Github. I've just pushed a fix for backward compatibility.
