### ISSUE TITLE
Select field (multiple) : how to not display All |None

### ISSUE THREAD

**Issue by Sinusite** [rilwis/meta-box#784]
Is there a way to have an option for select/advanced in order to not show the "All | None" ?

( In Select.php i have commented the line 38 $html .= self::get_select_all_html( $field['multiple'] ); )
Because i d'ont need this (and it's not translated as well).

Thanks

**Comment by rilwis** [comment]
Just added an option `select_all_none` with default value is `false`. So it's better for backward compatibility. You can turn it on/off by setting this to true/false.
