### ISSUE TITLE
4.8.2 not working with AJAX?

### ISSUE THREAD

**Issue by bitorbit** [rilwis/meta-box#786]
It looks like rwmb_meta is not working within AJAX functions any more.

**Comment by bitorbit** [comment]
Here is more details: Call to undefined function rwmb_meta() error within AJAX called function (calling RWMB_Helper::meta function instead works fine).

**Comment by bitorbit** [comment]
Is there any chance that this could be fixed with next update, we have hundreds of users who might be hit by this issue?

Thanks!

**Comment by rilwis** [comment]
Please try the latest commit.

**Comment by bitorbit** [comment]
Looks ok with latest commit!

Could you please let us know when you will publish update on wordpress.org?

Thank you!

**Comment by rilwis** [comment]
Great. I'm checking other issues and will release the new version soon.
