### ISSUE TITLE
Issue after installing metabox 4.8.2

### ISSUE THREAD

**Issue by VictorConstruct** [rilwis/meta-box#788]
Hello I am using Real Romes heme version 2.4.3 and after instalinng (upgrade) metabox to his newest version when i click "Activate" i receive this fatl error:
Fatal error: Class 'RWMB_Core' not found in /home/victor/public_html/wp-content/plugins/meta-box/inc/loader.php on line 125 !
Please help me.... what can i do to activate it again :( I am quite new in wordpress !
Thanks !!!

**Comment by rilwis** [comment]
Can you please re-download the plugin on the Github ([this link](https://github.com/rilwis/meta-box/archive/master.zip)), unzip and upload to your host?

**Comment by VictorConstruct** [comment]
Thanks I have tried ! but I have got some help from a friend who knows alittle css programming and now everything is fine

**Comment by rilwis** [comment]
Glad to see it's good for you :)
