### ISSUE TITLE
Call to undefined function rwmb_meta() in admin area

### ISSUE THREAD

**Issue by wgstjf** [rilwis/meta-box#790]
ver: 4.8.2

Hi, I have upgraded to 4.8.2 to get around the backwards compatibility issues but now am getting a "Call to undefined function rwmb_meta()" in the admin area.  

We over-ride the standard list view for Posts and Pages to provide a more informative set of columns and within the function called by the manage_edit-post-columns filter I call various bits of custom meta data like this:

```php
case 'post_subtitle' :
         $post_subtitle =  rwmb_meta( 'post_subtitle');
         //etc etc...
```

Since upgrading I am now getting the undefined function error.  Can you help please as this site is due to go live tomorrow so needs to be fixed asap?

Cheers,

Will

**Comment by rilwis** [comment]
I pushed a fix in this commit 2898d06c371581b0c86ad3884541a9adcd2f30d0

**Comment by wgstjf** [comment]
Thanks for the quick response but unfortunately this has not helped to solve the problem.  Any other ideas?

If it helps I have the following installed on a site running WP 4.4.2:

MB Settings Page – 1.0.1
Meta Box Columns – 0.1.1
Meta Box Conditional Logic – 1.2
Meta Box Group – 1.0.5
Meta Box Tabs – 0.1.6
Meta Box for Yoast Seo – 1.1.0
Meta Box	– 4.8.2

Cheers,

Will

**Comment by rilwis** [comment]
I mean I made a fix on Github. Can you please try the development version on Github?

**Comment by wgstjf** [comment]
Ah, my mistake.  I only updated the inc/functions/php file.  Updating the whole plugin has fixed it, thanks for the great support :-)
