### ISSUE TITLE
Documentation: Looping through one meta box's fields in the front end

### ISSUE THREAD

**Issue by nimmolo** [rilwis/meta-box#792]
Before 4.8, if you had _a lot of fields_ in the **same** meta box, you could loop through the `['fields']` keys of the global variable `$meta_boxes` for that post. 

Here is an example of the old way:

	global $meta_boxes;

	if( isset($meta_boxes['my_prefix']['fields']) ) 
	
	foreach ( ($meta_boxes['my_prefix']['fields'] ) as $key) {
			
			$value = rwmb_meta( $key['id'] );
      
			if ( ! empty($value) ) {
				
				echo '<label>' . $key['name'] . '</label> ' . $value;
				
			}
	}

This loop was very handy if your meta box has, say, 20 fields. 

Now that `$meta_boxes` is not used as a global variable for every post, it's still pretty easy to loop through the Meta-Box-only field keys, but i had to read through the plugin code to find the function that would return this. `RWMB_Core::get_meta_boxes();` does the trick. The rest of the loop is identical, but it would be nice to put this loop in the documentation.

New way, using `RWMB_Core` class:

        $meta_boxes = RWMB_Core::get_meta_boxes();

	if( isset($meta_boxes['my_prefix']['fields']) ) 
	
	foreach ( ($meta_boxes['my_prefix']['fields'] ) as $key) {
			
			$value = rwmb_meta( $key['id'] );
      
			if ( ! empty($value) ) {
				
				echo '<label>' . $key['name'] . '</label> ' . $value;
				
			}
	}

Note: Without this function you would be trying to loop through ALL postmeta, and there may be WordPress meta fields that are not part of your Meta Box, and you don't want those. Without the core function, to retrieve only the values for your meta box with `get_post_meta`, you would have to know and re-list all the field keys separately in your code.

**Comment by rilwis** [comment]
Thanks for your idea. I will add this to the documentation tonight :)

**Comment by nimmolo** [comment]
alright! :)

**Comment by nimmolo** [comment]
New site is pretty amazing, by the way. I had not checked it out in a long time.

**Comment by rilwis** [comment]
Thanks :)

The docs is added [here](https://metabox.io/docs/looping-meta-box-fields/). Thanks for your contribution :+1:
