### ISSUE TITLE
Warning on latest dev version

### ISSUE THREAD

**Issue by karissademi** [rilwis/meta-box#794]
Hi, Just wanted to give you a heads up that on the latest dev version I'm getting the following warning in the admin on newly created items (posts, pages, cpts) with at least one metabox. It does not appear to affect saving of any fields.

 `Invalid argument supplied for foreach() in /home/ubuntu/phila.gov/wp/wp-content/plugins/meta-box/inc/fields/file.php on line 302`

Thanks.

**Comment by rilwis** [comment]
Can you please post the code to register meta boxes?

**Comment by karissademi** [comment]
The simplest implementation I have: 

`add_filter( 'rwmb_meta_boxes', 'myprefix_register_meta_boxes' );`

```
function myprefix_register_meta_boxes($meta_boxes) {
   $prefix = 'myprefix_';

   ///a bunch of other metaboxes here, registered to other post types

   $meta_boxes[] = array(   
       'id'       => 'post-description',        
       'title'    => 'Post Summary',
       'pages'    => array( 'post' ),
       'context'  => 'normal',
       'priority' => 'high',

       'fields' => array(
         array(
          'name' => 'Summary',
          'id'   => $prefix . 'post_desc',
          'type' => 'textarea'
        ),
      ),
     );
    return $meta_boxes;
}

```
