### ISSUE TITLE
MB & Yoast SEO

### ISSUE THREAD

**Issue by wgstjf** [rilwis/meta-box#795]
Hi guys,

Does the Meta Box for Yoast SEO plugin work with the latest version of Yoast SEO (3.1)?  I have various metaboxes configured with the 'add_to_wpseo_analysis' => true parameter but Yoast is not adding this content to it's analysis...an example shown below

```php
	// TEXTAREA - Panel Text
	array(
		'name'    => __( 'Panel Text', 'indigo-options' ),
		'id'      => $prefix . 'text',
		'desc'  => 'Enter your text for this panel (excluding list of features!). Use <b>[header]Your Heading[/header]</b> to insert a header.',
		'type'  => 'textarea',
		'cols' => 10,
		'rows' => 6,
		'columns'   => '6',
		'visible' => array( $prefix.'type', '=', array('text-image') ),
		'add_to_wpseo_analysis' => true,
	),
```

The screenshot shows below shows that Yoast is seeing zero content (content editor empty for testing) even though there are a number of metabox fields with content that have analysis parameter set to 'true'

![image](https://cloud.githubusercontent.com/assets/3740694/13532833/84d527f8-e225-11e5-8057-581ebc1c6059.png)

Thanks in advance,

Will

**Comment by wgstjf** [comment]
Any thoughts on this? :-)

**Comment by rilwis** [comment]
Is the problem the same as described [here](https://github.com/rilwis/mb-yoast-seo/issues/1)? If yes, let's just continue discussing there :) If no, please just copy this ticket to that repo so we can manage it better.
