### ISSUE TITLE
Header and strpos bugs in 4.8.3

### ISSUE THREAD

**Issue by bitorbit** [rilwis/meta-box#798]
We have these issues reported by some of our users:

```
Warning: strpos() [function.strpos]: Empty needle in /wp-content/plugins/meta-box/inc/loader.php on line 61

Warning: Cannot modify header information - headers already sent by (output started at /wp-content/plugins/meta-box/inc/loader.php:61) in /wp-includes/option.php on line 820

Warning: Cannot modify header information - headers already sent by (output started at /wp-content/plugins/meta-box/inc/loader.php:61) in /wp-includes/option.php on line 821
```

**Comment by rilwis** [comment]
Hi,

Can you tell me how do you use the plugin? As a separated plugin or include into themes?

**Comment by bitorbit** [comment]
Hi,

It is separated (installed from wordpress.org using TGM plugin activation).

Also, when theme is switched, e.g. to twentysixteen the issue persists (with meta-box already installed and activated).

It looks that only some sites/servers are affected.

**Comment by rilwis** [comment]
Hmm, can you send me admin account and FTP info via contact form at https://metabox.io ? I need to look at that to see where the bug comes from.

**Comment by bitorbit** [comment]
The problem is that we could not reproduce this on our server, so we will ask our user for FTP access...

**Comment by bitorbit** [comment]
We have sent you WP and FTP credentials.

**Comment by rilwis** [comment]
Thanks. I just fixed it in the commit above. I will release a new version later for that.
