### ISSUE TITLE
Nested Cloneable Groups

### ISSUE THREAD

**Issue by sebng87** [rilwis/meta-box#799]
Hi guys, 

I've just started to use the new feature on cloneable wysiwyg which is working pretty well. However, is there a way to implement it in nested cloneable groups ? 

Thanks

**Comment by rilwis** [comment]
Hi, I have to say that the nested cloneable groups aren't supported yet. At the moment we can have only 1-level of nesting.

**Comment by sebng87** [comment]
Ok thank you I am looking forward to the release of this feature
