### ISSUE TITLE
Metabox error

### ISSUE THREAD

**Issue by Moni222** [rilwis/meta-box#800]
Class 'RWMB_Core' not found
Hi, I when I try to activate a number of plugins, I get the following error Class 'RWMB_Core' not found
Fatal error: Class 'RWMB_Core' not found in wp-content/plugins/meta-box/inc/loader.php on line 127

I have reinstalled meta-box 4.8.3 and also unzipped and uploaded the copy at github meta-box-master. Issue persists. Can anyone help please?

**Comment by rilwis** [comment]
Hi,

Can you please follow [these steps](https://metabox.io/steps-fix-problems-meta-box-4-8-0/) and tell me if it works?

**Comment by Moni222** [comment]
Hi, thank you for your response. I have updated to the latest meta-box, and having same issue..

**Comment by rilwis** [comment]
That not only updating the meta boxes. Did you check the syntax to register meta boxes? Also are you using a theme that includes Meta Box directly?

I've seen 1 theme that includes Meta Box directly but the way the theme includes the Meta Box is [incorrect](https://metabox.io/docs/include-meta-box-plugin-themes/) and the version included is outdated.

**Comment by rilwis** [comment]
Hi again, I've made a fix yesterday. Can you check the latest version on github?

**Comment by Nicholas-Cardot** [comment]
Rilwis,

I have this included in my plugin, and I have several customers who are expressing that they are seeing this same error.

Fatal error: Class 'RWMB_Core' not found in /home/nginx/blahblahblah/public/wp-content/plugins/blahblahblah/meta-box/inc/loader.php on line 122

I just pulled the most recent version of this plugin for inclusion about 2 days ago. Thanks!

**Comment by rilwis** [comment]
I will close this issue as it's resolved in #810
