### ISSUE TITLE
Default width for oembed previews

### ISSUE THREAD

**Issue by eriktdesign** [rilwis/meta-box#801]
I'm working on a responsive site where the design requires me to set the WordPress content width setting to a very high value. This causes the `oembed` field previews to be way too big to fit in the metabox. I'd suggest changing [oembed.php:42](https://github.com/rilwis/meta-box/blob/master/inc/fields/oembed.php#L42) to the following:

`$embed = wp_oembed_get( $url, array( 'width' => 360 ) );`

Where `360` is some sane value for the width. Thoughts?

**Comment by rilwis** [comment]
That makes sense. I've just tested with big `$content_width` and the iframe looks bad in the admin area.

I think your solution is a good one. However, I would like that to be implemented only in the admin area as `$content_width` is made for frontend. And frontend developers should use another technique to solve the responsiveness problem in the frontend, like FitVids.js. What do you think?

PS: `360` is a good value for admin area. As [the stats](https://www.w3counter.com/globalstats.php) shows, the screen sizes above 5% still includes 1024x768. And at that screen size, the width for oembed field input is `372px`.

**Comment by eriktdesign** [comment]
Yes, I was only referring to the admin side for this. Maybe you could also add `iframe { max-width: 100% }` to the CSS for the meta box?

**Comment by rilwis** [comment]
Just pushed a fix.

We already implemented CSS [here](https://github.com/rilwis/meta-box/blob/master/css/oembed.css#L9) but the height of the video doesn't change automatically like responsive image.
