### ISSUE TITLE
Admin page: Call to undefined function rwmb_meta()

### ISSUE THREAD

**Issue by ahmadazimi** [rilwis/meta-box#802]
Hi there,

I've update meta-box to the latest version, now I'm getting this error in the admin area of the Wordpress:
`Call to undefined function rwmb_meta()`

I've found that you checked `is_admin()` in the **loader.php** file.
Can you explain me why you remove functions.php from admin area? I need to extract some meta fields in the admin area to show admins.

**Comment by rilwis** [comment]
Hi, the version 4.8.3 removed the check `is_admin()`. Please just update the plugin.

**Comment by ahmadazimi** [comment]
:+1:
