### ISSUE TITLE
Get the post id from filters

### ISSUE THREAD

**Issue by sebng87** [rilwis/meta-box#806]
Hi guys, 

Do you know how I can get the post id inside the register metabox filter like so ?

```php
add_filter( 'rwmb_meta_boxes', 'prefix_register_meta_boxes' );
function prefix_register_meta_boxes() {
    // get the post id here...
} 
```

thank you

**Comment by funkedgeek** [comment]
I don't think the filter is designed to work like that, since I don't think a post id is even available when it is run.  What were you trying to do?

**Comment by sebng87** [comment]
Basically I need to have nested cloneable groups, but because at the moment the plugin only supports one level of nesting I'm working on a solution which consist to dynamically create multiple metaboxes with the a cloneable group in it from the admin panel

**Comment by rilwis** [comment]
I think you can get the ID for the current post via `$_GET['post']` like this:

```php
$post_id = false;
if ( isset( $_GET['post'] ) )
	$post_id = intval( $_GET['post'] );
elseif ( isset( $_POST['post_ID'] ) )
	$post_id = intval( $_POST['post_ID'] );
```

**Comment by sebng87** [comment]
it works fine thank you guys !
