### ISSUE TITLE
Wrong path for js/css file inclusion in loader.php

### ISSUE THREAD

**Issue by atomtigerzoo** [rilwis/meta-box#808]
Hi!
I'm having the problem that `$url` in [line 33 in loader.php](https://github.com/rilwis/meta-box/blob/master/inc/loader.php#L33) gets a wrong path on two of my systems. One is a debian wheezy, the other a Xubuntu inside a virtualbox, both running fine with nginx with latest php5. Also the paths were correct before version 4.8.x.

On both systems the value of `$url` contains a `/themes/`, hence all JS and CSS files in the backend are not loaded:

    string(64) "https://XXXXXX/wp-content/themes/plugins/meta-box/" 

When I save posts, the values of images/files get lost because of this.

The plugin is not installed inside themes, it's regular within the plugins folder.

I monkey-patched it over here for now with a simple str_replace, but there must be a) a better fix than this and b) the url-path has to be the same on all machines.

**Comment by atomtigerzoo** [comment]
Just looked up the list() method you are using - and found out that the behaviour will change with PHP7, so you might want to change it anyway? http://de2.php.net/manual/en/function.list.php#refsect1-function.list-notes

**Comment by krivinarius** [comment]
I'm having a problem with line 77 in loader.php 
`$url  = str_replace( wp_normalize_path( $content_dir ), $content_url, wp_normalize_path( $path ) );`
This solution is not working with WP installations that do not use 'wp-content' folder.
Why aren't you using plugins_url function https://codex.wordpress.org/Function_Reference/plugins_url

**Comment by rilwis** [comment]
Just pushed a fix. Can you please test with your install? @atomtigerzoo @krivinarius 
Thanks a lot!

**Comment by atomtigerzoo** [comment]
Great, works fine on both of my systems. Can be closed from my side of the issue.
Just FYI, your plugin was - in both cases - inside the normal plugin directory.

**Comment by krivinarius** [comment]
Thank you, that worked.
