### ISSUE TITLE
Taxonomy field with select_tree not displaying saved hierarchical values

### ISSUE THREAD

**Issue by maticomp** [rilwis/meta-box#814]
Hi guys!

I've encountered a problem I am almost sure worked quite a while ago, but I can't be sure anymore. I've been updating Metabox regularly for over a year, and lately have noticed this problem occurs.

We have a taxonomy field declared in a Metabox for our custom field type, that we register using `rwmb_meta_boxes` filter in our plugin like that.

```
array(
    'name' => 'City',
    'desc' => 'After selecting state you will be able to select city ',
    'id' => 'event_place_city',
    'type' => 'taxonomy',
    'options' => array(
        'type' => 'select_tree',
        'taxonomy' => 'event_city',
    ),
),
```

the field uses a hierarchical taxonomy `event_city` in which we have cities listed under their corresponding states. When not using `'type' => 'select_tree',` the list is rendered flat, and as such is very difficult to use. With `select_tree` we get a neat combo box for state, and then - after selecting one - another one with only those cities that are valid.

The problem happens after saving. The metabox, displaying an already saved entry (which is saved properly in the DB), does not show the current selection at all. The first state combo box is empty, and the second one for city is not displayed at all.

When we click on the correct state in the first combo, the second one appears with correct selection in it, but we can't get it to display all information on page render.

Are we doing something wrong, or is this a bug in `select_tree` renderer for hierarchical taxonomies?

**Comment by funkedgeek** [comment]
Does the taxonomy have the native meta box?  That might be interfering

**Comment by maticomp** [comment]
No, there is no native meta box for this taxonomy.

**Comment by funkedgeek** [comment]
Trying to figure this out because it works fine for me, albiet I'm using it with the built in categories.  Let me create a custom taxonomy and try it out

**Comment by funkedgeek** [comment]
Okay, not seeing the problem.  Created a new taxonomy, made some hierarchical terms and the field saves as fine.  I'm using the latest version of the plugin on github and no problems.  Can you show a video demonstrating the problem?

**Comment by maticomp** [comment]
Okay, sorry for the delay, we've been flooded with other work.

I'm looking through commits and can't see anything related, but I wanted to record the video sample for you today and I updated WP to 4.5 and Metabox to latest. The problem simply disappeared, it works like a charm.

I'm clueless what has changed, but since it works, there is nothing to do here. Thank you for your support!
