### ISSUE TITLE
Metabox include exclude function check_custom() only checks regular functions not class methods (has patch)

### ISSUE THREAD

**Issue by rlaan** [rilwis/meta-box#815]
Dear metabox crew,

I would like to suggest the following code for the include/exclude plugin check_custom() method:

```php
public static function check_custom( $func, $meta_box )
	{
		if ( is_array( $func ) ) {
			if ( ! method_exists( $func[0], $func[1] ) ) {
				return false;
			}
		}
		else {
			if ( ! function_exists( $func ) ) {
				return false;
			}
		}
		return call_user_func( $func, $meta_box );
	}
```

In this way a user can also use class methods as its custom method.

Thanks,
Ruud

**Comment by rilwis** [comment]
Thanks for your contribution.

I think it's better to check by [`is_callable`](http://php.net/manual/en/function.is-callable.php) instead of making 2 if.

**Comment by rilwis** [comment]
New version is just released :)

**Comment by rlaan** [comment]
Hi Rilwis,

Yes! excellent fix, didn't think of that.

Thanks for the quick turnaround
Ruud
