### ISSUE TITLE
Datepicker cut off by TinyMCE 

### ISSUE THREAD

**Issue by karissademi** [rilwis/meta-box#816]
A date field which should fall on top of the wysiwyg editor will get hidden behind it. 

It can be fixed by adjusting the z-index of `#ui-datepicker-div` but it would be nice if that was included in meta-box. 

<img width="690" alt="screen shot 2016-03-23 at 4 06 21 pm" src="https://cloud.githubusercontent.com/assets/479028/13999180/6697ca7a-f111-11e5-9e5f-3dfc03f8435e.png">

**Comment by rilwis** [comment]
Just pushed a fix. I couldn't replicate the bug with [this test](https://github.com/rilwis/meta-box/blob/master/tests/datetime.php). Hope the fix works in your case :)

**Comment by karissademi** [comment]
Thanks!
