### ISSUE TITLE
Error 500 after 4.8.4 update

### ISSUE THREAD

**Issue by lolametro** [rilwis/meta-box#817]
Hi,

since I installed version 4.8.4 of the plugin, my whole wp-admin directory responds an Error 500.
With 4.8.3, everything was fine. Newest WP version (4.4.2) installed. As far as I know, only the theme "Positivus" is using Meta Box functions on my site.
I don't know how to log the errors, so if you could say what I should do, I can give you more information.

Greetings

**Comment by rilwis** [comment]
Can you turn on the debug mode and see what outputs in the admin screen? Here is the instruction:

http://codex.wordpress.org/Debugging_in_WordPress

PS: Positivus is a premium theme, I couldn't check its source code :(. If you need to fix urgent, please send FTP info and admin account details via the [Contact form](https://metabox.io/contact)

**Comment by lolametro** [comment]
I've searched through the log and found this. Does this help you? If not, I will send you the theme.
`[29-Mar-2016 08:47:28 UTC] PHP Catchable fatal error:  Object of class WP_Post could not be converted to string in /var/www/virtual/awde/html/wp-content/plugins/meta-box/inc/fields/choice.php on line 56`

**Comment by rilwis** [comment]
@funkedgeek Can you please check this?

**Comment by funkedgeek** [comment]
Actually, the fix I added last night should fix the problem.  Please try the github version of the plugin

**Comment by lolametro** [comment]
Yes, this fixes it for me. Thanks for your help!
