### ISSUE TITLE
Support revision

### ISSUE THREAD

**Issue by rilwis** [rilwis/meta-box#822]
By default, WP doesn't support saving fields in revisions. That might cause users to be confused when editing posts.

These are some work around this problem:

Save/Restore meta value revision
https://wordpress.org/support/plugin/wp-post-meta-revisions

Show meta value revision data in revision screen
https://wordpress.org/support/topic/post-meta-revisions-added-to-database-but-not-showing-in-ui

If we can add support for revision, it would be great.

Similar to #354

**Comment by danielkun** [comment]
I'm setting up a new project which requires revisions. I really wanted to use Metabox but this time I will probably go with ACF instead (which supports revisions). Do you know when this might get implemented?

**Comment by couponscom** [comment]
What is the status of this? Will support for revisions ever be added to Metabox? I've got users complaining about the lack of revision history. Thanks!

**Comment by couponscom** [comment]
Hello? Will support for revisions ever be added to Metabox?

**Comment by Thanerik** [comment]
What is the status on this feature? I'm really missing this feature, because it's really hard to hardcode revisions to match MB, and to let it work together. Please take a look at it!

**Comment by rilwis** [comment]
Hey guys,

We've just completed this feature in the [MB Revision](https://metabox.io/plugins/mb-revision/) extension. Please use this extension. Any feedback is welcomed.

Thanks.
