### ISSUE TITLE
rwmb_meta for images no longer returning array after 4.8.4 update

### ISSUE THREAD

**Issue by baden03** [rilwis/meta-box#823]
Prior to the 4.8.4 update I would request an image value like so:
```
$images = rwmb_meta( 'my_image_id', 'size=full' );
```
and it would return an array as described in the documentation: https://metabox.io/docs/get-meta-value/#section-image
However, since 4.8.4, the same function is now only returning a string with the id of the image.
Since I am also using the meta-box-group plugin, i see this was also updated (10 days after my licence expired), so I purchased another licence (as I was unable to extend my licence) and updated the groups plugin to version 1.0.7, however this did not resolve the issue.

After further testing, removing the size=full argument DOES return the full array.
```
$images = rwmb_meta( 'my_image_id' );
```
Update:
The issue is ONLY when the argument is used in the form of: size=full.  However, when the size is included as an array like so:
```
$image_args = array('size' => 'full');
$images = rwmb_meta( 'my_image_id', $image_args );

or
$images = rwmb_meta( 'my_image_id', array('size' => 'full'));
```
Everything works correctly, so long as an array is used. This needs to be addressed in the documentation.

Can anyone else verify that the rwbm_meta function for images and image-advance field types when using a non-associative array as an argument is no longer returning a full array, but only the media element ID.

Very frustrating, and hard to develop with meta-box with so many surprises not being documented in the change log.

**Comment by rilwis** [comment]
Hi,

This is unexpected behaviour. We used `wp_parse_args` function which accepts both string and array for the arguments. Let me check again.

Thanks for letting me know.

**Comment by funkedgeek** [comment]
Does `$images = rwmb_meta( 'my_image_id', array('size'=>'full' );` work?

**Comment by baden03** [comment]
yes, as this is using an inline associative array, rather than first defining it as a variable.

**Comment by baden03** [comment]
Has anyone been able to recreate the issue?

**Comment by rilwis** [comment]
I made a simple test like this:

```php
add_filter( 'rwmb_meta_boxes', 'your_prefix_image_demo' );
function your_prefix_image_demo( $meta_boxes )
{
	$meta_boxes[] = array(
		'title'  => __( 'Image Upload Demo', 'your-prefix' ),
		'fields' => array(
			array(
				'id'   => 'image_advanced',
				'name' => __( 'Image Advanced', 'your-prefix' ),
				'type' => 'image_advanced',
			),
			array(
				'id'   => 'group',
				'name' => __( 'Group', 'your-prefix' ),
				'type' => 'group',
				'fields' => array(
					array(
						'id'   => 'image_advanced',
						'name' => __( 'Image Advanced', 'your-prefix' ),
						'type' => 'image_advanced',
					),
				),
			),
		),
	);
	return $meta_boxes;
}

add_filter( 'the_content', function ( $content )
{
	$images = rwmb_meta( 'image_advanced', 'size=full' );
	$group = rwmb_meta( 'group', 'size=full' );
	$content .= '<pre>' . print_r( $images, true ) . '</pre>';
	$content .= '<pre>' . print_r( $group, true ) . '</pre>';
	return $content;
} );
```

And here is the result:

![result](http://i.prntscr.com/fe1c6fb21b0f42879d56afd96d46c602.png)

Can you post your code so we can test together?

**Comment by zabestof** [comment]
Hey,

I've encountered this problem too after updating from 4.8.3 to 4.8.5 but the thing is on my localhost it is working fine while on a client's website it returns the image id. And I'm using just the metabox plugin without any extensions.

**Comment by rilwis** [comment]
@baden03 @zabestof Could you please send us the full code to test? As I said in the previous comment, it worked for me. So I need more description on the error to track it and fix.

Thanks a lot.

**Comment by zabestof** [comment]
I have also tried with the code you've pasted above and it has the same result. On my localhost and on my vps server it is working fine. On 3 of my clients (there are 3 now) I need to use the code like this to pull the images:

`$image = rwmb_meta( 'my_image', array( 'size' => 'full' ) );`

Otherwise it just returns the id of the image.

Unfortunately I don't have too much access on their servers so I can't get inside their logs.

Cheers!

**Comment by rilwis** [comment]
Thanks a lot for your feedback.

Can you please post full code you use on clients' servers? And some info about their servers like: OS, WordPress version?

**Comment by sodbileg** [comment]
I'm also having same issue. It's working fine on the localhost, however, returning only IDs on the server.

WP Version: 4.5.2
Server OS: Ubuntu 12.04.5 LTS
RWMB Version: 4.8.6

```
// Here is the config
array(
    'name'             => __( 'Gallery Images', 'test' ),
    'id'               => "{$prefix}pf_gallery_data",
    'type'             => 'image_advanced',
    'max_file_uploads' => 10,
),

// Here is the data
$images = rwmb_meta( 'test_pf_gallery_data', 'multiple=true' );
```

**Comment by rilwis** [comment]
@sodbileg: Please just remove the `multiple=true` param. That breaks the code :)

**Comment by sodbileg** [comment]
@rilwis Thanks so much. It worked great :)

**Comment by rilwis** [comment]
I will close this issue. If there is any problem, please just reopen this. Thanks :)

**Comment by hanabukovska** [comment]
Hi, 
I have the same problem. In custom filed group I have simple image. The function rwbm_meta returns ID, not array for image.

Function.php

```
        $meta_boxes[] = [
            'title'      	=> __('O nás', 'understrap' ),
            'post_types' 	=> ['page'],
            'include'    	=> [
                'relation'	=> 'AND',
                'slug'		=> ['o-nas'],
            ],

            'fields'     => [
                [
                    'id'		=> 'cc_about_us',
                    'type'		=> 'group',
                    'fields'	=> [

                        [
                            'name'    			=> __( 'Obrázek', 'understrap' ),
                            'id'      			=> 'cc_about_us_image',
                            'type'   			=> 'single_image',
                            'label_description' => __( 'Vyberte obrázek:', 'understrap' ),
                        ],

                    ],	
                ],	
            ],
        ];

        return $meta_boxes;
```


Template.php:
<?php
$about_us = rwmb_meta( 'cc_about_us' );
?>
<h2>Result: <?php print_r($about_us); ?></h2> 

FrontEnd: 
![Snímek obrazovky 2022-08-15 v 11 35 04](https://user-images.githubusercontent.com/47121292/184612461-dd3900b9-f77e-4876-a61f-ef22419f54ba.png)

What with this?
