### ISSUE TITLE
Incorrect URL to plugin assets after upgrading to 4.8.4

### ISSUE THREAD

**Issue by rorymcdaniel** [rilwis/meta-box#825]
I use capistrano for deployment, so my wp-content/plugins directory is a symlink to ../../../shared/wp-content/plugins.  The URL is (should be) the standard /wp-content/plugins. After upgrading to 4.8.4, in the admin area, I'm getting errors in the console when plugin assets are being included. 

The URL for the css and js files is showing up as (for example):

`http://s16236.p157.sites.pressdns.com/dom16236/shared/wp-content/plugins/meta-box/css/image-advanced.css?ver=4.8.4`

When it should just be:
`http://s16236.p157.sites.pressdns.com/wp-content/plugins/meta-box/css/image-advanced.css?ver=4.8.4`

I've attached a screenshot of the console. This issue did not exist on 4.8.3. Reverting to that version resolves the issue.
![screenshot from 2016-03-29 16-13-38](https://cloud.githubusercontent.com/assets/331850/14122309/3a0ae0c0-f5c9-11e5-9ff0-1b5990435beb.png)

Any suggestions would be greatly appreciated.

**Comment by rilwis** [comment]
Just pushed a fix for this. Previously in 4.8.3, I detected the symlink by checking if the plugin's path contains ABSPATH, but it's not safe and bad coded. This new version use default `plugins_url` which is safer.

Please test and let us know.

**Comment by rorymcdaniel** [comment]
It works beautifully. I really appreciate your quick response. I've been using this plugin since you just had some code posted on your blog. Great to see it grow over the years.

**Comment by rilwis** [comment]
It's nice to know that :). It's almost 6 years since I published the 1st tutorial about meta box. Lots of things are added and changed since then and I'm very happy to have you using it all the time :)
