### ISSUE TITLE
Radio buttons in ul list - 4.8.5

### ISSUE THREAD

**Issue by wgstjf** [rilwis/meta-box#827]
Hi guys,

I see you have modified the displayed html format of radio button fields to now be in an unordered list.  I am sure there are good reasons for this but it has messed up the layout of my metaboxes.  Have you added any css (to prevent me having to do so to every site that I have built) to be able to define them as inline-lists rather than individual block items?

I had this....
![image](https://cloud.githubusercontent.com/assets/3740694/14246688/ab51bd44-fa60-11e5-84a4-1b11483f4a97.png)

and now have this :-(

![image](https://cloud.githubusercontent.com/assets/3740694/14246701/bbdbfc74-fa60-11e5-950c-4ada87bbcfa0.png)

Cheers,

Will

**Comment by wgstjf** [comment]
If you have...can it please default to inline for backward compatibility?

**Comment by wgstjf** [comment]
@funkedgeek thanks for getting on that so quickly.  I see you have also added a 'collapse' class...for full backwards compatibility would it make sense to also add the following css?

```css
.rwmb-input-list.collapse {
	margin:0;
}
.rwmb-input-list.collapse li{
 	margin-right: 0;
	line-height:1;
}
```

Cheers,

Will

**Comment by rilwis** [comment]
@funkedgeek Can you please check and update?

**Comment by funkedgeek** [comment]
Collapse is there for setting whether a hierarchical checkbox list autohides the child lists.  The code proposed makes it too cramped.

**Comment by wgstjf** [comment]
Hadn't spotted that :-)

Just trying to have a default setting that emulates the previous styling so that I don't have to go and re-code all the sites out there I have that are using this wonderful plugin...

Any other thoughts?

**Comment by funkedgeek** [comment]
Sorry, did my fix not work?

**Comment by wgstjf** [comment]
Nearly :-)

The problem is that as you are now using an unordered list there is a lot of margin and line-height stuff being added that needs to be reset to keep everything looking the same. 

If you look at the 'Header Text Colour' bit below (which are in fact radio buttons) you will see that it has a large amount of margin both on the UL and the LI that is either browser default or added from you latest CSS (especially when compared to the 'Header Height' field)

![image](https://cloud.githubusercontent.com/assets/3740694/14433570/abea5828-0006-11e6-9a59-74891909271d.png)

My above code resets the browser default margin for a UL and also resets the new meta-box CSS shown below:

```css
.rwmb-input-list.inline li {
    display: inline-block;
    margin-right: 10px;
}
.rwmb-input-list li {
    line-height: 22px;
}
```

**Comment by funkedgeek** [comment]
Can you try the latest commit?  I had to add some margin to the label, otherwise it makes text look squished

**Comment by wgstjf** [comment]
Looks much better, thanks. :-)
