### ISSUE TITLE
taxonomy_advanced not saving value

### ISSUE THREAD

**Issue by akabaka** [rilwis/meta-box#831]
Using "taxonomy_advanced" with a few different "field_type" options, and it's not saving after update.

**Comment by funkedgeek** [comment]
Can you post your code you are using so we can test it?

**Comment by akabaka** [comment]
Custom taxonomy with slug "slideshows":
`    $meta_boxes[] = array(
        'id'       => 'pageopts',
        'title'    => 'Page Options',
        'post_types'    => 'page',
        'context'  => 'normal',
        'priority' => 'high',
        'fields' => array(
			array(
				'name'  => 'Which slideshow?',
				'desc'  => 'If slideshow is selected above, which one?',
				'id'    => $prefix . 'slideshowcat',
				'field_type' => 'select',
				'type'  => 'taxonomy_advanced',
				'taxonomy' => 'slideshows',
			),
        )
    );`

**Comment by funkedgeek** [comment]
Please test with the latest commit.  Should be fixed

**Comment by akabaka** [comment]
Yep, that did it. You guys rock, thanks!
