### ISSUE TITLE
taxonomy_advanced seems identical to taxonomy

### ISSUE THREAD

**Issue by akabaka** [rilwis/meta-box#832]
This is related to #831. I'm using the taxonomy_advanced for a field showing all entries in custom taxonomy "slideshows":
`array(
				'name'  => 'Which slideshow?',
				'desc'  => 'If slideshow is selected above, which one?',
				'id'    => $prefix . 'slideshowcat',
				'field_type' => 'select',
				'type'  => 'taxonomy_advanced',
				'taxonomy' => 'slideshows',
			),`
I thought that taxonomy_advanced returned a comma-separated list of the term IDs, so I was expecting it to return a simple string with an ID or IDs (e.g. '10') but a var_dump shows it's a WP_Term object:
`object(WP_Term)#325 (10) { ["term_id"]=> int(3) ["name"]=> string(8) "Homepage" ["slug"]=> string(8) "homepage" ["term_group"]=> int(0) ["term_taxonomy_id"]=> int(3) ["taxonomy"]=> string(10) "slideshows" ["description"]=> string(0) "" ["parent"]=> int(0) ["count"]=> int(2) ["filter"]=> string(3) "raw" }`
Is this the expected behavior?

**Comment by funkedgeek** [comment]
The only difference between taxonomy taxonomy_advanced is how it saves the data.  They both should return term data.

**Comment by akabaka** [comment]
Okay, that's my mistake then. From the description it seemed like a simple way to get a string output. Thanks for clarifying!
