### ISSUE TITLE
Two taxonomy fields conflict

### ISSUE THREAD

**Issue by sptheme** [rilwis/meta-box#833]
I have registered two taxonomy fields and switch on/off base on custom page template e.g: homepage and featured video page. It's working fine, cannot saving.

// Homepage
$meta_boxes[] = array(
	'id'			=> 'homepage-options',
	'title'			=> __( 'Homepage Options', 'wpsp_meta_options' ),
	'post_types'	=> array( 'page' ),
	'context'		=> 'normal', // Where the meta box appear: normal (default), advanced, side. Optional.
	'priority'		=> 'high', // Order of meta box: high (default), low. Optional.
	'autosave'		=> true, // Auto save: true, false (default). Optional.
       'fields'		=> array(
                                array(
					'name'  => __( 'Select category', 'wpsp_meta_options' ), 
					'id'    => $prefix . "highlight_category",
					'type'  => 'taxonomy',
					'options' => array(
						'taxonomy' => 'category',
						'type'     => 'select',
						'args'     => array(),
					),
				),
       )
    );
=====================

// Featured Video
    $meta_boxes[] = array(
    	'id'			=> 'video-post-options',
		'title'			=> __( 'Featured Video Options', 'wpsp_meta_options' ),
		'post_types'	=> array( 'page' ),
		'context'		=> 'normal', 
		'priority'		=> 'high', 
		'autosave'		=> true,

		'fields'		=> array(
			array(
				'name'  => __( 'Select category', 'wpsp_meta_options' ), 
				'id'    => $prefix . "featured_video_cat",
				'type'  => 'taxonomy',
				'options' => array(
					'taxonomy' => 'category',
					'type'     => 'select', 
				),
			),
		)
    );

Could you please helps, where I'm doing wrong?

**Comment by funkedgeek** [comment]
Both fields are trying to save on the same taxonomy, which is why it doesn't work.  I suggest using separate taxonomies.

**Comment by sptheme** [comment]
Many thanks for your helps, now it's working after use different taxonomies..
