### ISSUE TITLE
Capability and edit post : file_upload vs file 

### ISSUE THREAD

**Issue by Sinusite** [rilwis/meta-box#834]
With  'type' => 'file_upload', another author (may be editor ?) that the one who has uploaded can't view the preview in edit post screen ( which is possible with the  'type' => 'file' ).

I don't know why, but adding  'manage_options' capability to the author give him the preview and file access .

**Comment by funkedgeek** [comment]
file_upload uses plupload and uploads directly to WordPress, so it makes sense you need permission to do so.  I'll look into it
