### ISSUE TITLE
Full_url stopped working over night...

### ISSUE THREAD

**Issue by boutzamat** [rilwis/meta-box#835]
Thanks for this awesome plugin - very helpful.

I have used it for a while, and without any changes, it stopped working over night.
I have never used admin_init to register the boxes, i used the same method as in the docs.

Only full_url is not working , everything else is..

My functions:
`add_filter( 'rwmb_meta_boxes', 'rw_register_meta_boxes' );

function rw_register_meta_boxes( $meta_boxes ){
	
    $prefix = 'rw_';

	//THE VARIANTER IMAGES
    $meta_boxes[] = array(
        'title'    => 'Varianter',
        'pages'    => array( 'product'),
        'fields' => array(
            array(
                'name' => 'Varianter',
                'id'   => $prefix . 'variant',
                'type' => 'file_advanced',
            ),
        )
    );
	
	//THE MANUFACTURER INFO

    $meta_boxes[] = array(
        'title'    => 'Inspiration egenskaber',
        'pages'    => array( 'inspiration'),
        'fields' => array(
            array(
                'name' => 'Inspirations billeder',
                'id'   => $prefix . 'inspirationbilleder',
                'type' => 'file_advanced',
            ),
        )
    );
	
    return $meta_boxes;
}
`

My template:
`<?php if (rwmb_meta( 'rw_variant' ) !== '') { ?>

	<label>Udvalg af farver og varianter</label>
	<div class="flexslider varianter">
		<ul class="slides">
			<?php 
				
				$images = rwmb_meta( 'rw_variant', 'type=image&size=thumbnail' );
				foreach ( $images as $image )
				{
					echo "<li><a href='{$image['full_url']}' title='{$image['title']}' target='_blank' class='zoom' data-rel='prettyPhoto[product-gallery1]'><img src='{$image['url']}' width='{$image['width']}' height='{$image['height']}' alt='{$image['alt']}' /></a></li>";
				}
			?>
		</ul>
	</div>
	<script>
	jQuery(window).load(function() {
	  jQuery('.flexslider.varianter').flexslider({
		animation: "slide",
		animationLoop: true,
		itemWidth: 80,
		itemMargin: 50,
		minItems: 1,
		maxItems: 5,
		directionNav: true
	  });
	});
	</script>

<?php } ?>`

It doesnt render the full_url...

**Comment by funkedgeek** [comment]
If all the files are images, use `image_advanced` instead.  full_url has never been returned by `file_advanced`, but it is used by `image_advanced`.  I have a feeling you were using `image_advanced` before.
