### ISSUE TITLE
MB-Settings Page Produces two notifications instead of one!

### ISSUE THREAD

**Issue by ahmadawais** [rilwis/meta-box#836]
I am using the latest version of MB-Settings-Page for the first time and it is producing two notificatiions when I press save. 

![](https://i.imgur.com/d6uHZ5P.png)

I think this is an issue.

**Comment by rilwis** [comment]
Can you describe how you get it? I saw it once in the past, but now couldn't replicate it.

**Comment by ahmadawais** [comment]
Umm, I am building the plugin in question. Once it's built in a day or two. I will send you the Git repo link to check.

**Comment by rilwis** [comment]
Hi, have you finished the plugin? Do you still see the bug?

**Comment by ahmadawais** [comment]
I stopped using the settings ext due to this bug. Never tested it again.

**Comment by rilwis** [comment]
Can you help me to fix this by sending me the code you used? I just couldn't replicate the bug to fix :(.

**Comment by ahmadawais** [comment]
@rilwis I scrubbed that code from the GIt. Maybe I will try it again later and will let you know.

**Comment by rilwis** [comment]
OK, thanks :)

**Comment by truongwp** [comment]
I have just fixed this issue. Please update MB Settings Page extension.
Thanks!
