### ISSUE TITLE
Object of class WP_Post could not be converted to int error

### ISSUE THREAD

**Issue by webbudesign** [rilwis/meta-box#841]
I am using this code for get images
`rwmb_meta( 'xx_images', array( 'type'=>'image' ));`

But I receive this error
`Notice: Object of class WP_Post could not be converted to int in xxx/wp-includes/post.php on line 4946
Notice: Object of class WP_Post could not be converted to int in xxx/wp-includes/post.php on line 4946
Notice: Object of class WP_Post could not be converted to int in xxx/wp-includes/post.php on line 4946
Notice: Object of class WP_Post could not be converted to int in xxx/wp-includes/post.php on line 4946
Notice: Object of class WP_Post could not be converted to int in xxx/wp-includes/post.php on line 4946
Notice: Object of class WP_Post could not be converted to int in xxx/wp-includes/post.php on line 4946
Notice: Object of class WP_Post could not be converted to int in xxx/wp-includes/post.php on line 4946
Notice: Object of class WP_Post could not be converted to int in xxx/wp-includes/post.php on line 4946
Notice: Object of class WP_Post could not be converted to int in xxx/wp-includes/post.php on line 4946
Notice: Object of class WP_Post could not be converted to int in xxx/wp-includes/post.php on line 4946
Notice: Object of class WP_Post could not be converted to int in xxx/wp-includes/post.php on line 4946
Notice: Object of class WP_Post could not be converted to int in xxx/wp-includes/post.php on line 4946
Notice: Object of class WP_Post could not be converted to int in xxx/wp-includes/post.php on line 4946`

Note: I think I receive error per image. Error count same with image count.

Version: 4.8.5
WP: 4.5
I am using integrated with theme mode.

**Comment by funkedgeek** [comment]
Latest commit fixes this
