### ISSUE TITLE
Empty datetime field with timestamp=>true returns January 1, 1970

### ISSUE THREAD

**Issue by d2roth** [rilwis/meta-box#842]
I am using Meta Box version 4.8.5.

Basically what I want to allow is for an event to have no start_date. So I created an events post type with a meta box and tried to set the start date to a blank value. The problem though is, when I save the post the meta field with the empty value it gets changed to a 0 then the next time the page loads the meta_value is 0 which is the unix timestamp for January 1, 1970 which is a valid date unlike a .

I also just tried to change timestamp=>false and found a var_dump() of the meta field showed the formatted string as "" while the timestamp returned 0. Though it is a side issue this also caused an `Array to string conversion` error while editing the post.

Some notes as I dug:

- As I see datetime.php using intval() numerous times when timestamp=>true I checked what the result would be of intval(''). I found out that it returns 0 so I am wondering if this is where the issue is. My thought for a solution would have to be some checks in place to make sure the value is not empty before running intval().
- Setting timestamp=>false and saving the post with an empty value did not produce the same issue. It correctly does not save the value to the database and instead deletes the meta value.

The code I am using to test is effectively this:

```PHP
add_action('rwmb_meta_boxes', 'register_meta_boxes');
function register_meta_boxes(){
	$meta_boxes[]	 = array(
		'id'		 => 'dd_events_marquee',
		'title'		 => __('Marquee'),
		'post_types' => 'dd_events',
		'context'	 => 'side',
		'priority'	 => 'low',
		'fields'	 => array(
			array(
				'name'		 => __('Start Date'),
				'id'		 => 'dd_events_start_date',
				'type'		 => 'datetime',
				'desc'		 => 'Enter the date and time the event starts.',
				'js_options' => array(
					'buttonText'	 => 'Select Date',
					'dateFormat'	 => 'DD MM d, yy',
					'stepMinute'	 => 5,
					'showTimepicker' => true,
				),
				'std'		 => '',
				'timestamp'	 => true,
			),
		),
	);
	return $meta_boxes;
}
```

**Comment by Chillifish** [comment]
Wow, thought you'd copied my issue from the support pages! I'm having the same issue.

**Comment by funkedgeek** [comment]
Fixed.  Default for empty date field with timestamp was 0; now it will be set to null
