### ISSUE TITLE
Taxonomy Advanced Not Saving

### ISSUE THREAD

**Issue by coleh33** [rilwis/meta-box#843]
I am unable to get taxonomy_advanced field to save after making a selection.  All other field types are working and saving properly.  This is on a custom post type.  The categories populate properly but just won't save.

`array(`
  `'name'  => __( 'Blog Category', 'alphamedia-framework' ),`
  `'desc'  => 'Select a blog category to appear inside the shows page.',`
 `'id'    => '_show_post_category',`
  `'type'  => 'taxonomy_advanced',`
  `'taxonomy' => 'category',`
  `'field_type' => 'select',`
`),`

**Comment by funkedgeek** [comment]
Please update to the latest version on github.
