### ISSUE TITLE
Global Post Variable is getting reset

### ISSUE THREAD

**Issue by tomcat90** [rilwis/meta-box#844]
We have a page that we pull in a bunch of other pages and list. During the first iteration of the loop the rwmb_meta call resets the global post to the page that hosts the loop and not the current post in the loop.  In the code below the first element of the loop is ID: 171 and the page that hosts the loop is ID: 59

```
<?php
$args = array( 'post_type' => ['ebook','webinar','research-paper','white-paper'], 'posts_per_page' => 10 );
$loop = new WP_Query( $args );
while ( $loop->have_posts() ) : $loop->the_post();?>
    <?php
    $post_type =  get_post_type();
    ?>
    <div class="column">
    <div class="library-card">
    <div class="type <?php echo $post_type ?>">
    <span>
        <?php echo $post_type ?>
    </span>
    </div>
        <div class="content">
        <h2>
    <?php
    the_title();
    ?>
            </h2>
            <p>
        <?php
    the_content();
////////////////////////////////////////Here is where the problem is
      echo get_the_ID();  //RETURNS 171 like it should
      $images = rwmb_meta( 'mbx_banner_img_banner_img', array(), get_the_ID());
        echo "<pre>";
        print_r($images);
        echo get_the_ID(); //This line here returns the ID of the page (59) and not the current loop (171)
       //This only happens once the second time through the ID doesn't change.
////////////////////////////////////
			if ( !empty( $images ) ) {
                foreach ( $images as $image ) {
                    echo "<img src='{$image['url']}' alt='{$image['alt']}' />";
                }
            }
    echo '</p></div></div></div>';
endwhile;
?>
```

**Comment by aerlaut** [comment]
I'm getting the same behaviour too. Current workaround is to call a `rwmb_meta()` once just before the loop.

**Comment by funkedgeek** [comment]
Weird, not replicating this.  Are you using any other plugins?

**Comment by tomcat90** [comment]
![screen shot 2016-04-22 at 8 46 54 am](https://cloud.githubusercontent.com/assets/9612610/14745065/cd69b7c4-0866-11e6-8172-491e5b338f20.png)

**Comment by funkedgeek** [comment]
Can you try disabling all the plugins and trying the code with each one one by one to see whichis causing the issue?

**Comment by rilwis** [comment]
Just asking: could you try the latest version on Github? I pushed a fix for global post object a while ago.

**Comment by funkedgeek** [comment]
Has this been resolved for you?  I'll close this but please post if you're still having issues

**Comment by WPThemer** [comment]
hi.. I dont want to upgrade at this stage, can you please tell me which file the changes were made so I can copy them.. thanks

**Comment by rilwis** [comment]
@WPThemer lots of files have changed since April. You can wait to update to the 4.8.7 version which will be released today :)
