### ISSUE TITLE
Fatal Error - WP 4.5

### ISSUE THREAD

**Issue by rafasegat** [rilwis/meta-box#846]
Hello,

Why this error is happening? Thanks

Plugin could not be activated because it triggered a fatal error.

Warning: require_once(ADDRESS/wp-content/plugins/meta-box/inc/common.php): failed to open stream: No such file or directory in ADDRESS/wp-content/plugins/reflektor-portfolio/meta-box/meta-box.php on line 33

Fatal error: require_once(): Failed opening required ‘ADDRESS/wp-content/plugins/meta-box/inc/common.php’ (include_path=’.:/usr/php/54/usr/lib64:/usr/php/54/usr/share/pear’) in ADDRESS/wp-content/plugins/reflektor-portfolio/meta-box/meta-box.php on line 33

On the installation...

Thanks
Raf

**Comment by funkedgeek** [comment]
Looks like it's trying to open up a file from the wrong folder

**Comment by rilwis** [comment]
Hi @rafasegat,

Are you the author of the plugin reflecktor-portfolio? If yes, can you please update the included version of Meta Box and check the [guide to include it into a plugin](https://metabox.io/docs/include-meta-box-plugin-themes/)?

**Comment by rafasegat** [comment]
Hi rilwis,

Yes I am. Cool, thanks.

Great plugin!

Im including the MetBox directly.

Just like that.
require get_template_directory() . '/meta-box/meta-box.php'; // Path to the plugin's main file

Should I include as you included at Glao theme?

Thanks
Raf

**Comment by rilwis** [comment]
Yes, you should use TGM Activation class. The reasons are described very carefully in the documentation.

But if you want to include the plugin directly, I guess you just need to update the plugin before including it. The error says file `common.php` is not found and this file is not available in the current version of Meta Box.

**Comment by rafasegat** [comment]
Ok,

I got it. But when my customers try to install the plugin, show this error.

This Plugin Has an Invalid Header

So I reckon the problem is MetaBox..

Did this error happen to you before?

Thanks
Raf

**Comment by Nicholas-Cardot** [comment]
@rafasegat If you include the plugin directly into your plugin or theme, I've found that you will get the invalid header error unless you open the main meta-box.php and remove the commented out section. That section contains information essentially telling WordPress that it's a standalone plugin. Since it's not standalone, because it's included inside of another plugin (or theme), that information being removed fixes and eliminates that error.

**Comment by rilwis** [comment]
@Nicholas-Cardot: Thanks for helping. I'm not aware of the file header. WP didn't show that error before.

@rafasegat: Can you please try the method that Nicholas suggested and let us know?

**Comment by rafasegat** [comment]
The problem is, if I use TGM Class my customers will not like to download other plugin to make my plugin works.

Thats weird.

Is it dangerous to include directly as I am doing?!

Thanks guys

**Comment by rilwis** [comment]
@rafasegat No, it's fine to include the plugin directly. Did you update to the latest version on Github before including into your plugin as I instructed?

**Comment by rilwis** [comment]
@rafasegat Do you see any error after updating to the latest version on Github?

**Comment by rilwis** [comment]
I will close this issue. Please add more comments if you still see the problem.

**Comment by rafasegat** [comment]
Hey

That problem is happening to my client

Constantly getting "Plugin could not be activated because it triggered a fatal error." "Fatal error: Class 'RWMB_Core' not found in /home/content/e/n/t/enterexalted/html/wp-content/plugins/reflektor-portfolio/meta-box/inc/loader.php on line 124" on different wordpress databases.

Do you know how to solve it?

Thanks
Raf

**Comment by rilwis** [comment]
Can you try the latest version on Github? We've pushed some fixes for this problem here.

Best regards
