### ISSUE TITLE
Multiple wp_localize_script

### ISSUE THREAD

**Issue by ma3ie4** [rilwis/meta-box#850]
Hi,
great plugin! I use it in all of my projects.
I've noticed that **wp_localize_script** is adding multiple i18nRwmbMedia arrays to HTML.
Line 18 - \meta-box\inc\fields\media.php
It looks like for every: field 'type' => 'image_advanced' - there is separate array.

![screenshot_17](https://cloud.githubusercontent.com/assets/18750070/14935231/4e3c2d64-0eca-11e6-8a3f-3ecc8e7a237b.png)

As I understand it's wordpress default implementation of 'wp_localize_script'.
Maybe it will be possible to call it like 'Woocommerce plugin' did in function 'private static function localize_script' (only once): 
https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-frontend-scripts.php

**Comment by rilwis** [comment]
@funkedgeek Please fix this.

**Comment by rilwis** [comment]
Just looked at this and I think it might be the same as @ma3ie4 said about the default implementation of `wp_localize_script`. I'm looking for WC for a solution.

**Comment by rilwis** [comment]
Added a fix for this. Better than the way WC does :).

The logic is checking if the script already has localized string: if no -> add localized string, if yes -> ignore. Because each field requires only 1 localized string, this works nicely :)
