### ISSUE TITLE
Cloneable group with wysiwyg editor

### ISSUE THREAD

**Issue by wgstjf** [rilwis/meta-box#853]
Hi guys,

Got a bit of an issue.  I see that in an email you sent out on 7th March that WYSIWYG editors are now cloneable.  I have one in a cloneable group but the subsequent clones do not load the editor properly.  I simply see a textarea (with no text visible).  I believe this is because both the editors have the same ID....can you suggest a work-around/fix?

Cheers,

Will

**Comment by wgstjf** [comment]
Need a solution to this guys, any thoughts?

Cheers,

Will

**Comment by rilwis** [comment]
Hi Will, did you update both Meta Box (development version on Github) and Group extension? I did work on the ID issue for the group.

**Comment by wgstjf** [comment]
Just done so as didn't know you had been working on it.  WYSIWYG editors now working fine, thanks!

Problem with [fieldset_text](https://github.com/rilwis/meta-box/issues/852) remains though...

Cheers,

Will

**Comment by rilwis** [comment]
I'm still working on the cloning nested group issue and will check this.

**Comment by AnalogMemory** [comment]
Any progress on this?

**Comment by rilwis** [comment]
@AnalogMemory What's your exact problem?
