### ISSUE TITLE
Taxonomy Type Interferes with Post category

### ISSUE THREAD

**Issue by PlayerThemes** [rilwis/meta-box#855]
I have added following meta field to "Add New Post" page. But when I update the post, the categories selected in meta box are saved as categories of post as well.

So in other words metabox data is interfering with post category data. Is this a bug or I am doing something wrong?

```
array(
		'name'  => esc_html__( 'Category', 'my_domain' ),
		'id'   => $prefix . 'meta_category',
		'type' => 'taxonomy',	
                'taxonomy' => 'category',
                'field_type'     => 'select_advanced',
                'query_args'     => array(),
		'multiple'		 => true,			
				
			)
```

**Comment by funkedgeek** [comment]
The taxonomy `category` is post category, so I'm not sure what you're asking.  What are you trying to do?

**Comment by PlayerThemes** [comment]
Sorry for not being clear enough.

I have added meta box  for some slider options (styel, slide count,etc) inside post creation page. One of which is post category list. Admin can select which category of post images to show in slider. The problem is this slider - category meta box is having issue with the normal post category section ( below publish button). Whatever selected in metabox category is reflected in post category section. These two have no relation here although have same data to use. Metabox category saves list of post categories to be used for slider while normal post category saves category of that post.

I hope this makes sense.

**Comment by funkedgeek** [comment]
That's what its supposed to do; set the term for that particular post. I
suggest using taxonomy_advanced and change the id of the field

**Comment by PlayerThemes** [comment]
Thanks.  @funkedgeek
