### ISSUE TITLE
Maps does not work for me

### ISSUE THREAD

**Issue by Infolu** [rilwis/meta-box#857]
Staff have the following code below, but it does not work for me on the front end is just a blank frame. not carrying the address of the back end except in andress, someone help me to display the map or find the problem?

```php
// Map requires at least one address field (with type = text)
			array(
				'id'   => 'address',
				'name' => __( 'Address', 'your-prefix' ),
				'type' => 'text',
				'std'  => __( 'Hanoi, Vietnam', 'your-prefix' ),
			),
			array(
				'id'            => 'mymap',
				'name'          => __( 'Location', 'your-prefix' ),
				'type'          => 'map',
				// Default location: 'latitude,longitude[,zoom]' (zoom is optional)
				'std'           => '-6.233406,-35.049906,15',
				// Name of text field where address is entered. Can be list of text fields, separated by commas (for ex. city, state)
				'address_field' => 'address',
			)
```

Display

```php
$args = array(
    'type'         => 'map',
    'width'        => '640px', // Map width, default is 640px. Can be '%' or 'px'
    'height'       => '480px', // Map height, default is 480px. Can be '%' or 'px'
    'zoom'         => 14,  // Map zoom, default is the value set in admin, and if it's omitted - 14
    'marker'       => true, // Display marker? Default is 'true',
    'marker_title' => '', // Marker title when hover
    'info_window'  => '<h3>Info Window Title</h3>Info window content. HTML <strong>allowed</strong>', // Info window content, can be anything. HTML allowed.
);
echo rwmb_meta( 'mymap', $args ); 
```

**Comment by rilwis** [comment]
@funkedgeek Can you please look at this?

**Comment by Infolu** [comment]
Hello Can anyone help me ?

**Comment by Infolu** [comment]
@funkedgeek hi, unfortunately for me it did not work with the correction in the maps-frontend.

see how is my map box in frentend

One observation I have other plugins or js loaded only the metabox-io.
http://oi65.tinypic.com/33mrc5u.jpg

tranks

**Comment by funkedgeek** [comment]
Can you post a picture of the console?  Are there any errors?

**Comment by Infolu** [comment]
@funkedgeek 
How are you? My problem is being on the map display in the frontend, the backend is saving normally as you can see in the images below.

back End  http://imgur.com/SEqojDt
front End http://imgur.com/aMiHsmC


Really do not know what might be causing this, as you can see on the image of the front end it carries the api of Google Maps, however displays not leaving the box blank.

**Comment by funkedgeek** [comment]
I need a picture of the JavaScript console on the front end.  Click on the
tab that says console so I can see if there any errors.

**Comment by Infolu** [comment]
@funkedgeek 
Hi, Sorry about that after adding the bug fix forgot to enable the tests the wp_enqueue_script ("jquery"); .

Thank now works perfectly.
