### ISSUE TITLE
Dev version image_advanced backwards compatibility

### ISSUE THREAD

**Issue by wgstjf** [rilwis/meta-box#858]
Hi guys,

To fix an issue with the cloning of wysiwyg editors I have installed the current dev version of Meta Box.  This has fixed that issue but brought in a new one.

You seem to have changed the returned value/array when one uses the helper function to return image_advanced custom fields.

In my example I am using image_advanced field to attach a single image.

Previously when I called the custom field using the following:
```php
$service_image_ids = rwmb_meta( 'service_primary_image');
```
I would get a returned value of the image id ,eg. 221

With the current dev version, using the same call as above I now get the following:

```
Array
(
    [221] => Array
        (
            [width] => 646
            [height] => 504
            [file] => 2016/05/an-image.png
            [sizes] => Array
                (
                    [thumbnail] => Array
                        (
                            [file] => an-image-200x200.png
                            [width] => 200
                            [height] => 200
                            [mime-type] => image/png
                        )
etc...
```

To avoid having to re-code endless sites which rely on your great plugin we need to have backwards compatibility on this.  Is there an arg that could be passed to get your more advanced but incompatible additional data instead?

Cheers,

Will

**Comment by rilwis** [comment]
Hi Will,

I remember this was added to Meta Box a long time ago, not in the dev version. [Here](https://github.com/rilwis/meta-box/blob/4.1.10/inc/helpers.php#L47) is the version 4.1.10. You can see that if the field type is `image_advanced`, the plugin will get image info for you.

BTW, the output format above seems come from ACF plugin :), not from Meta Box.

**Comment by wgstjf** [comment]
Sorry I disagree... :-)

With Meta Box 4.8.5 Live version installed I get the first output (ie. the ID of the field)

With Meta Box 4.8.5 Dev version from github I get the array as shown above.

ACF is definitely NOT installed - would never use it... :-)

Cheers,

Will

**Comment by rilwis** [comment]
Hmm, that must be a bug in 4.8.5 :(, as `rwmb_meta` always returns an informative array. I made that from the first day and can't be wrong with that. I will check 4.8.5 version and find the bug.

**Comment by funkedgeek** [comment]
Might be related to https://github.com/rilwis/meta-box/issues/823

**Comment by rilwis** [comment]
Hi Will, I've just tested with 4.8.5 and 4.8.4 and in all cases, the Meta Box plugin returns an array of info.

Can you give us the full code to test?

**Comment by rilwis** [comment]
Hi @wgstjf, can you help me?

**Comment by wgstjf** [comment]
Ok...figuring this out...

The situation is as follows: I have a kind of page builder (built using Meta Box) and for a certain template the user is able to over-ride a default image by uploading a different one.  The field to over-ride the default is an image_advanced field within a cloneable group.  The default image comes from a custom field in a different CPT and in this case the image_advanced field is NOT in a group...

The important bit here is that one value called via rwmb_meta is within a group and the other is not.  These therefore return two different types of array.  The group one is a simple array of IDs, the non-group one is the array as shown above.

The frontend code that previously worked was this

```php
#-----------------------------------------------------------------
# Image Stuff
#-----------------------------------------------------------------
// Set Defaults
$service_image_override_ids = ''; // Reset

$service_image_ids = $service_panel['service_landing_override_image']; // group field

// If override image being used
if ($service_image_ids!='')  {
  // Do nothing
} else { // No override so use Primary Content Image from service
  $service_image_ids = rwmb_meta( 'service_primary_image','',$service_id); // Non group field
}

echo '<pre>';
print_r($service_image_ids);  // Debugging to see the output of $service_image_ids
echo '</pre>';

if (is_array($service_image_override_ids)) {
  $service_panel_images = $service_image_ids;
} else { // If not array then fallback to old method
  $service_panel_images = explode(',',$service_image_ids);
}
foreach ($service_panel_images as $service_panel_image_single) {
  $service_image_info = RWMB_Image_Field::file_info( $service_panel_image_single, 'type=image&size=panel-image' );
  break;
}
```

The $service_image_ids (where there was no over-ride) returned a single ID (not an array).  With the DEV version of the plugin I get the array above.

The service_primary_image field is being created by the following:

```php
// IMAGE ADVANCED - Primary Content Image
array(
	'name'  => 'Primary Content Image',
	'desc'  => 'Add your image  <b>Min dimensions 600px wide</b>',
	'id'    => $prefix.'primary_image',
	'type'  => 'image_advanced',
	'std'   => '',
	'max_file_uploads' => 1,
	'columns'     => '3',
	'clone' => false,
	'visible' => array( $prefix.'primary_media_type', '=', array('image') ),
),
```

Does that help at all?

Cheers,

Will

**Comment by funkedgeek** [comment]
Probably related to https://github.com/rilwis/meta-box/issues/864

**Comment by funkedgeek** [comment]
Solution is here: https://github.com/rilwis/meta-box/issues/864#issuecomment-219907480

**Comment by wgstjf** [comment]
@funkedgeek thanks for that and yes it does work. 

My issue is that there seems to be a difference between the way the live version of Meta Box works and the way the dev version works which is going to cause backwards compatibility issues :-)

**Comment by rilwis** [comment]
Oh, I see. The problem is exactly what I answered in #864. Thanks @funkedgeek to pointing it out :)

@wgstjf: We're fixing some bugs here in the development version and when it's finished, we'll push to wordpress.org (later this week or early next week). Backward compatibility is one of the most important factor to us :)

**Comment by wgstjf** [comment]
Sounds great, thanks :-)
