### ISSUE TITLE
Idea: Merge input fields into 1 "input" field

### ISSUE THREAD

**Issue by rilwis** [rilwis/meta-box#859]
I just have an idea to optimize code for input fields. We have several similar input fields such as text, url, email, password, slider where the implementation is almost the same.

I'm thinking about a new way to merge them into 1 universal input field where we need only 1 file for all.

The concept is similar to WordPress implementation of Customizer field (see class-wp-customize-control.php, method render_content()) that can be separated into following steps:

- Set default fallback to field['type'] = input if there is no field class exists
- Output the field using <input type="field['type']" {attributes}>

If we do it well, we can remove some files and keep the plugin smaller.

We can start with text field and similar fields (email, url), not radio or checkbox.

**Comment by funkedgeek** [comment]
Isn't that just going back to version 1 of the plugin where all the fields were handled in 1 class?  Also, we have 1 input class, which all the other input classes inherit from

**Comment by rilwis** [comment]
No, definitely not. What I mean is just optimizing for only <input type=".."> field :).

For example, both text and url field has similar html function:

<input type="field[type]"...>

If we can optimize that (we currently did some parts), we can do it better, for example:

$field_class = get field class;
if ( ! class_exists( $field_class ) )
    $field_class = 'RWMB_Input_Field';

in input.php file, we can do:

function html() {
    output <input type="field[type]"...>
}

**Comment by tanng** [comment]
Looks like concept of ASP.NET, they put all input into input field even Textarea (it's a input with `multiline` attribute).

**Comment by rilwis** [comment]
No, we don't try to put all input into 1 input field. I just want to use 1 code for super-similar fields like text, url, email.

**Comment by rilwis** [comment]
It's more complicated than I think. All subfields of "input" have a sanitize method which forces us to keep their files.

**Comment by rilwis** [comment]
Just done this :). Now we can use all HTML5 input types such as `tel`, `datetime-local`, `week` without writing more files. All are handled by RWMB_Input_Field class automatically.

The trick here is if field class doesn't exist then use RWMB_Input_Field class.
