### ISSUE TITLE
Meta Box Group v.1.1 - Nested Groups

### ISSUE THREAD

**Issue by wgstjf** [rilwis/meta-box#861]
Hi guys,

Thanks for all the hard work to bring us Nested Groups...strangely excited!

I have been testing it this morning and whilst the JS seems to work I cannot get it to save more than one row of my cloneable nested group.

There is too much code to show everything here but the following is a snippet of the I am using for the nested group:

```php
// Group
array(
  'id' => $prefix . 'numbered_items',
  'type' => 'group',
  'columns' => '12',
  'clone' => true,
  'sort_clone' => true,
  // List of sub-fields
  'fields' => array(

		array(
			'name'    => __( 'Title', 'indigo-metaboxes' ),
			'id'      => 'title',
			'type'    => 'text',
			'class'    => 'big-text',
			'columns'    => 3,
			//'visible' => array( $prefix.'type', '=', array('numbered-list') ),
		),
		array(
			'name'    => __( 'Description', 'indigo-metaboxes' ),
			'id'      => 'desc',
			'type'    => 'text',
			'class'    => 'big-text',
			//'desc'    => __( 'Please enter a title and description for each item.  The numbering will be added automatically', 'indigo-metaboxes' ),
			'columns'    => 9,
			//'visible' => array( $prefix.'type', '=', array('numbered-list') ),
		),
	),
	'visible' => array( $prefix.'type', '=', array('numbered-list') ),
),
```

The group displays correctly:

![image](https://cloud.githubusercontent.com/assets/3740694/15240113/3971465c-18df-11e6-93b2-f7e8dfca53cc.png)

But when you update it returns to having just one entry:

![image](https://cloud.githubusercontent.com/assets/3740694/15240121/4cfd1d54-18df-11e6-9461-5dcc9d9a2148.png)

Any thoughts? :-)

Cheers,

Will

**Comment by rilwis** [comment]
I knew that there will be bugs, but didn't expect that so soon :)

I've just checked your code and it works without Columns extension activated. It seems that the Columns extension adds more markup and breaks the JS. I will fix it soon.

**Comment by wgstjf** [comment]
Sorry about that :-)  Look forward to the fix :-)

**Comment by rilwis** [comment]
Hi Will, I've just fixed the Group extension. Please update to version 1.1.1.

**Comment by wgstjf** [comment]
Working perfectly, thanks for the quick fix :-)
