### ISSUE TITLE
Checkbox description => label

### ISSUE THREAD

**Issue by flowdee** [rilwis/meta-box#863]
Shouldn't the checkbox **desc** become a label too? 

I'm (and many others too I think) are used to click on the text besides a checkbox in order to activate/deactivate it.

**Comment by rilwis** [comment]
Just made a fix for this. Now you can click both on checkbox's name on the left or checkbox's description to activate/deactivate it.

**Comment by flowdee** [comment]
amazing, thanks for this @rilwis ! 😄
