### ISSUE TITLE
Validation Conflict with non-RWMB Meta Fields

### ISSUE THREAD

**Issue by Nicholas-Cardot** [rilwis/meta-box#865]
I'm getting several reports that since we upgraded to the most recent version of RWMB, several users are getting validation messages for other meta plugins.

For example, one user is describing the fact that every time they try to update a post, they get a validation error on the numeric fields from ACF, but only when this is present.

I have another user who is seeing a numeric validation error on WooCommerce Membership plugin when they attempt to create a discount. They get a validation message that says, "Please enter a multiple of 0.01"

**Preliminary Thoughts:** Is it possible that the validations JS from this plugin is either:
- Attempting to validate fields that are being populated by other plugins? In which case, the validations from this plugin should be adjusted to ensure that they ONLY target fields created BY this plugin.
- Creating a conflict that causes the JS in those other plugins to malfunction? In which case, this may actually be two separate conflict issues rather than just one.

If you have any ideas off the top of your head, please let me know. Otherwise, I'm going to continue to dig into this and I'll report back any information that I'm able to come up with.

**Here's my plan moving forward:** 
- I'm going to install these two other plugins (Advanced Custom Fields & WooCommerce Memberships) and attempt to replicate these on my own server. Hopefully this allows me to identify what is actually causing this.
- I'll continue to collect more reports from users in the wild.
- I'll report any ideas and information that I collect into this thread with the hopes that the more information we gather will bring us closer to finding a solution.

**Comment by Nicholas-Cardot** [comment]
Testing with ACF:

If I delete everything from inside the validate.js folder the conflict immediately goes away.

**Comment by Nicholas-Cardot** [comment]
Changing:

`var $form = $( '#post' ),`

To:

`var $form = $('#post #My_Meta_Box_ID'), `

Eliminates the conflict as well. So something is clearly allowing the validation rules from this plugin to target every field on the page using the rules of this plugin. Thoughts?

**Comment by funkedgeek** [comment]
I'll look up the validation code and make it more precise

**Comment by Nicholas-Cardot** [comment]
Thanks @funkedgeek 

This issue can easily be replicated by installing the free version of Advanced Custom Fields and creating at least 1 number custom field. Then navigate to a post and attempt to set that number field to any value other than zero and you'll see the validation message. That's what I did to replicate it so if you want to play around with it, that's probably the easiest way.

**Comment by rilwis** [comment]
Hi @Nicholas-Cardot ,

Thanks a lot for reporting the bug. You are right about the problem that the validating JS runs for all inputs inside `#post` which includes fields from other plugins as well.

The problem is quite complicated when the Validator library requires the form to be the selector and it [queries all fields inside](https://github.com/jzaefferer/jquery-validation/blob/master/src/core.js#L597). I'll keep working on that to find a solution.

**Comment by funkedgeek** [comment]
I'm not seeing anything specific in the code that it has to be a form element.

**Comment by rilwis** [comment]
@funkedgeek It's [here](https://github.com/jzaefferer/jquery-validation/blob/master/src/core.js#L28)

**Comment by funkedgeek** [comment]
aaah, the submit event

**Comment by rilwis** [comment]
@@Nicholas-Cardot: Can you please test with the fix above? I tested with simple number field from ACF and it worked.

**Comment by Nicholas-Cardot** [comment]
@rilwis and @funkedgeek,

That fixed it right up for me. I kind of feel like a dummy. I can't believe that I didn't see that 'ignore' property sitting right there in front of my face. I was sooooooo close. lol

I believe that this is now solved and, as such, I would recommend closing this issue. 

Thanks so much to both of you for you help on this!
