### ISSUE TITLE
Add filter for user field to select which field will be displayed as select option

### ISSUE THREAD

**Issue by rilwis** [rilwis/meta-box#867]
We're using `display_name` to display options in the select/select advanced. It would be better if we can add a filter to allow developers to choose which field is used (first name, last name, username, etc.)

My concern is the filter should be consistent in other "object choise" fields (taxonomy, post) so it's easy to understand.

**Comment by funkedgeek** [comment]
Found a place to put the filter, just have to give it a name.

**Comment by rilwis** [comment]
Do you think `rwmb_object_label` is a good name?

**Comment by d2roth** [comment]
I really like this idea and I am wondering what happened to it? was it ever done?
