### ISSUE TITLE
Reporting a problem with plupload_image

### ISSUE THREAD

**Issue by Infolu** [rilwis/meta-box#868]
Hello I will try the best to explain the problem I found.

I have metabox with two fields map and plupload_image.

What happens are two different situations.

Suppose for some reason the api google map metabox is not loaded correctly, causes problems with plupload_image because it does not charge.

(I purposely removed loading api script google as a way to test)

The other situation is if I for some reason you are editing a post that has plupload_image and press the F5 oa post page editing is recharged without the uploaded photos in plupload_image and if I click update it deletes the uploaded photos, so this does not I have to happen again in the list of posts and click edit again.

Has anyone ever experienced this?

**Comment by fsp** [comment]
I've experienced the following problem using plupload_image in 4.8.5 and 4.8.6:

Uploaded images have post_parent set to 0 in wp_posts. Hence, images are not displayed when loading attachments.

Reverting to 4.8.3 fixes the problem.

**Comment by Infolu** [comment]
Hi fsp with the new version 4.8.6 the f5 problem in firefox is resolved.

Only the case of problem does not load the api google maps leading to not caregamento the upload box see the print below

http://imgur.com/vVr0RmC

simulation environment

wampserver + Wordpress 4.8.6 updated + metabox with boxes created maps and upload image.

If they are to pergutando because wampserver only for the purpose imagine that I come to a system in a locked internal server external access or for some reason have a firewall that blocks Google Maps, this ends up taking me by not loading the images upload box .

**Comment by funkedgeek** [comment]
This a common problem for JavaScript code: if a piece of code causes an error, it causes issues for other code.
