### ISSUE TITLE
taxonomy with select_advanced : first option is now default value (4.8.6)

### ISSUE THREAD

**Issue by Sinusite** [rilwis/meta-box#870]
By default, select2 take now (since 4.8.6 ?) the first option value, not the placeholder.

```
'type'		=>	'taxonomy',
'taxonomy'	=> 'taxo_name',
'placeholder'	=>	'Choose...',
'field_type'	=>	'select_advanced',
```
(no trouble with others field type as 'select')

**Comment by Lugat** [comment]
We have the same issue.

**Comment by rilwis** [comment]
Just fixed it :)

**Comment by ryanlabelle** [comment]
Awesome! Thank you for the fix. I just tested and it resolved the issue on my local install. Cheers!

**Comment by ryanlabelle** [comment]
One question, how often do you update the wp repo? Right now I'm asking people using our themes to patch via github. No pressure. Thanks.

**Comment by rilwis** [comment]
We usually update the wp repo once a month when we resolve all the issues we're working on.

Best regards

**Comment by teaganm** [comment]
If it's at all possible to have a new release sooner than that it would be great. We have a significant number of customers using our products that are currently experiencing this issue. If not, we can work around it for now.
