### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined method RW_Meta_Box::has_been_saved()

### ISSUE THREAD

**Issue by bananamariap** [rilwis/meta-box#871]
version: 4.8.6
when registering a metabox, I am getting the Fatal error: Uncaught Error: Call to undefined method RW_Meta_Box::has_been_saved() when the Metabox Group plugin is activated too

**Comment by rilwis** [comment]
This bug happens in old version of the Group extension. Please upload to the latest version.

Best regards

**Comment by bananamariap** [comment]
Thanks.
