### ISSUE TITLE
How to override image_advanced sizes medium

### ISSUE THREAD

**Issue by bananamariap** [rilwis/meta-box#872]
I am using the image_advanced type and setting the image size to medium instead of the default thumbnail, how can I set my custom width and height for 'medium' size?
type=image_advanced&size=medium

**Comment by d2roth** [comment]
@bananamariap This is not an issue with the Meta Box plugin. The image size 'medium' is defined by WordPress itself. You will need to either modify the existing image size see notes on [add_image_size](https://developer.wordpress.org/reference/functions/add_image_size/) or you can simply add your own image size and use it's name in place of 'size=medium'.

I hope that helps.
