### ISSUE TITLE
You can select more items than max_file_uploads

### ISSUE THREAD

**Issue by d2roth** [rilwis/meta-box#874]
In the Media Gallery popup you can select more items than the limit set by max_file_uploads, though they do not get outputted to the screen after pressing "Select". 

To reproduce:
1. Create a new file and set `'max_file_uploads'	 => 1,`
2. Press "Add Media"
3. Select multiple items using "CTRL + Click" and you will see they each get the selected box around them.

I do not know if you guys can fix this but I think there should be a way.

Thanks for a great plugin.

**Comment by funkedgeek** [comment]
But the files don't get selected as part of the field.  The code filters out the extra ones, so I don't see an issue.

**Comment by rilwis** [comment]
Yes, @funkedgeek is right. There should be no problems with that.

**Comment by d2roth** [comment]
The issue is the user experience. I think of it just if you were setting a featured image and you were able to pick 5 images but then mysteriously 4 of them disappeared it would be confusing I believe.

**Comment by funkedgeek** [comment]
That's why the default for limited media fields is to have the status
counter, to visually let them know they can only select n out of x files

**Comment by rilwis** [comment]
@d2roth Let us see if we can improve that for better UX :)
