### ISSUE TITLE
image advanced field within clone group index off by 1

### ISSUE THREAD

**Issue by andrewfrankel** [rilwis/meta-box#875]
**Summary**

When using a cloned group containing an image_advanced field any newly added images have an index value that is one less than is correct. This results in the first newly added image to disappear after save since it's value is tacked onto the previous item in the cloned set.

**Example Data**

Initially created input after clicking 'add more' is correct (index 2): 
`<input disabled="" class="rwmb-image_advanced" name="logos[2][logo_jpg][]" type="hidden" value="">`

After adding image, newly created input field index is off (index 1):
`<input type="hidden" name="logos[1][logo_jpg][]" value="871" class="rwmb-media-input">`

This is true for all subsequently added images.

On save, the post data winds up with the duplicate value for index 1:
```
logos[0][logo_jpg][]:905
logos[1][logo_jpg][]:898
logos[1][logo_jpg][]:871
logos[2][logo_jpg][]:865
```

The duplicate value is set to index 1 after the page returns from saving:
`<input disabled="" class="rwmb-image_advanced" name="logos[1][logo_jpg][]" type="hidden" value="898,871">`

**I haven't had much time to dig into the code, but if you could point me in the right direction I would be happy to resolve and submit a pull request**

**Comment by funkedgeek** [comment]
I'm assuming you are using groups?

**Comment by andrewfrankel** [comment]
@funkedgeek, correct. The groups generally work as expected, but (at least) image file types cause this index problem.

**Comment by andrewfrankel** [comment]
@rilwis, some additional info, that might be related. Had another bug with a color field contained within a cloned group. When you click the 'add more' button the color selector doesn't appear in the newly created group. Works fine using a text field type, or if the color field is standalone (not in a group). Let me know if you need any additional data.

## Color field in clone group - broken
<img width="589" alt="screen shot 2016-05-26 at 12 03 33 pm" src="https://cloud.githubusercontent.com/assets/1470345/15585356/17774792-233c-11e6-83b8-cb9fa9d68e36.png">

## Text field in clone group - works
<img width="599" alt="screen shot 2016-05-26 at 12 04 01 pm" src="https://cloud.githubusercontent.com/assets/1470345/15585357/177a2a3e-233c-11e6-91dd-fa83aae39590.png">

## Color field standalone as a clone - works
<img width="600" alt="screen shot 2016-05-26 at 12 03 07 pm" src="https://cloud.githubusercontent.com/assets/1470345/15585355/1776c6b4-233c-11e6-9b6e-74a68a52ea6c.png">

**Comment by rilwis** [comment]
I see the bug. I'm working on it now.

**Comment by rilwis** [comment]
@andrewfrankel Just pushed a fix for image_advanced and color field. Color still requires the Group extension to update.

**Comment by andrewfrankel** [comment]
@rilwis, thanks for the very quick turnaround! I integrated the latest commits and image_advanced is now working as expected. 

When do you anticipate pushing the group extensions changes? Will the update be available in my account downloads section, or is there a better place to retrieve the latest version of extensions?

Really **great** plugin, and support! Very likely my new go to, for custom fields. Cheers!

**Comment by rilwis** [comment]
@andrewfrankel : We're working very hard on the Meta Box plugin and there're many changes we've just made (most on coding quality improvements). We need time to test it carefully before releasing. Until then, I can release the new version for Group extension, because it depends on changes of Meta Box (if I release now, users update it and will see the error).

Anyway, I've just sent you an email with the beta version of the Group extension. Please try it and let me know if it works :)

**Comment by andrewfrankel** [comment]
Thanks! That worked.
