### ISSUE TITLE
Select default option with taxonomy field

### ISSUE THREAD

**Issue by Sinusite** [rilwis/meta-box#877]
We can't select an option by default with type'   => 'taxonomy' ?

```
			array(
				'name'     => __( 'Select Advanced', 'your-prefix' ),
				'id'       => 'select_advanced',
				'type'     => 'taxonomy',
				 'taxonomy'	=> 'mytaxo',
				'std'         => '361', // Default value, optional
				'placeholder' => __( 'Select an Item', 'your-prefix' ),
			),
```

Thx

**Comment by funkedgeek** [comment]
std only works on new posts that haven't been saved yet.  This is true for all fields.

**Comment by Sinusite** [comment]
As far as i am concerned, it doesn't work even for new posts (maybe since 4.9.2)

**Comment by rilwis** [comment]
@Sinusite : please try the fix above.

@funkedgeek : Looks like our mechanism to get meta doesn't auto applied the code to escape and set default value. We should optimize it.

**Comment by Sinusite** [comment]
OK perfect for taxonomy. Thanks !!

Not working with user field type (or select?) when multiple is set to **true** 

```
            array(
                'name'          =>  'Author(s)',
                'id'            =>  "_cons_auteurs_id",
                'type'          =>  'user',             
                'multiple'      =>  true,               
                'field_type'    =>  'select_advanced',              
            ),
```
[Please see ](https://github.com/rilwis/meta-box/issues/997)

**Comment by Sinusite** [comment]
OK it's working with :
`'std' => array(3)`
