### ISSUE TITLE
Meta Box within custom plugin

### ISSUE THREAD

**Issue by wgstjf** [rilwis/meta-box#878]
Hi there,

I am trying to integrate MB into a custom plugin I am building.  The plugin introduces a new CPT (called Events, registered as 'event').  The CPT shows as it should but the metaboxes are not visible nor is the postbox-container html created.

I am using the same code from the mb-settings-page to initiate the custom plugin and ensure that Meta Box has been loaded as shown below:

```php
add_action( 'plugins_loaded', 'indigo_events_load' );

/**
 * Load plugin files after Meta Box is loaded
 */
function indigo_events_load()
{
	if ( ! class_exists( 'RW_Meta_Box' ) )
	{
		return;
	}

	define( 'INDIGO_EVENTS_URL', plugin_dir_url( __FILE__ ) );
	define( 'INDIGO_EVENTS_DIR', plugin_dir_path( __FILE__ ) );

	require_once INDIGO_EVENTS_DIR . 'inc/init-cpts.php';
	require_once INDIGO_EVENTS_DIR . 'inc/init-metaboxes.php';
}
```

The init-metaboxes.php file looks like this:

```php
add_filter( 'rwmb_meta_boxes', 'events_plugin_meta_boxes',999 );
function events_plugin_meta_boxes() {

$event_plugin_prefix = 'event_';
	$meta_boxes[] = array(
		'id'       => 'event_info',
		'title'    => 'Event General Info',
		'pages'    => array( 'event' ),
		'context'  => 'normal',
		'priority' => 'high',
		'fields' => array(
			// HEADING
				array(
					'type' => 'heading',
					'name' => 'Testing.',
					'id'   => 'fake_id', // Not used but needed for plugin
					'columns'   => '12',
				),

		)
	);
//echo '<pre>';
//print_r($meta_boxes);
//echo '</pre>';
return $meta_boxes;
```
You will see from the above that I have been attempting to debug by displaying print_r($meta_boxes) and this does return the necessary array.  

So the issue is that, whilst everything looks correct, it still won't show the Postbox or the fields within it.

I also have the following installed: MB Settings Page, Meta Box Columns, Meta Box Group, Meta Box Conditional Logic...all latest versions.

Cheers in advance,

Will

**Comment by wgstjf** [comment]
Forgot to add that my custom theme also registers and uses meta boxes :-)

**Comment by wgstjf** [comment]
OK an update - If I disable the theme metaboxes by commenting out the following line in my theme functions.php
```php
add_filter( 'rwmb_meta_boxes', 'post_type_meta_boxes',999 );
```
then my plugin metaboxes work...the question therefore is how can I have independent metabox configurations for both the plugin and the theme that both work and don't override each other?

Cheers,

Will

**Comment by wgstjf** [comment]
Figured it out :-)

By registering the theme metaboxes like this:
```php
add_filter( 'rwmb_meta_boxes', 'post_type_meta_boxes',999 );
```
and then modifying the plugin ones to be registered like this it works!

```php
add_filter( 'rwmb_meta_boxes', 'indigo_add_events_plugin_meta_boxes',999 );

function indigo_add_events_plugin_meta_boxes($meta_boxes) {
    $event_plugin_prefix = 'event_';
	$meta_boxes[] = array(
		'id'       => 'event_info',
		'title'    => 'Event General Info',
		'pages'    => array( 'event' ),
		'context'  => 'normal',
		'priority' => 'high',
		'fields' => array(
			// HEADING
				array(
					'type' => 'heading',
					'name' => 'Testing.',
					'id'   => 'fake_id', // Not used but needed for plugin
					'columns'   => '12',
				),

		)
	);
```

**Comment by rilwis** [comment]
Thanks Will to figure it out. It's always a best option to just register the meta boxes using `rwmb_meta_boxes` without wrapping it inside any function. The filter is called only when needed and doesn't impact on the performance.
