### ISSUE TITLE
checkbox_list not displaying labels correctly

### ISSUE THREAD

**Issue by andrewfrankel** [rilwis/meta-box#879]
**Setup example**
````
'type' => 'checkbox_list',
'options' => array(
    'helvetica' => 'Helvetica',
    'sans' => 'Sans',
    'sans_serif' => "Sans Serif"
)
````

**In choice.php get_options, the values are correct:**
````
array(2) {
  ["label"]=> string(9) "Helvetica"
  ["value"]=> string(9) "helvetica"
}
array(2) {
  ["label"]=> string(4) "Sans"
  ["value"]=> string(4) "sans"
}
array(2) {
  ["label"]=> string(9) "San Serif"
  ["value"]=> string(10) "sans_serif"
}
````

**By the time it gets to RWMB_Input_List_Walker start_el, the label is set to 'label'**
````
object(stdClass)#534 (2) {
  ["label"]=> string(5) "label"
  ["value"]=> string(9) "helvetica"
}
object(stdClass)#497 (2) {
  ["label"]=> string(5) "label"
  ["value"]=> string(4) "sans"
}
object(stdClass)#496 (2) {
  ["label"]=> string(5) "label"
  ["value"]=> string(10) "sans_serif"
}
````

**Screenshot:**
<img width="528" alt="screen shot 2016-05-27 at 9 57 51 am" src="https://cloud.githubusercontent.com/assets/1470345/15613618/8492ee84-23f1-11e6-8014-a2b024d7d8ee.png">

Haven't had a chance to trace further.

**Comment by ryanlabelle** [comment]
Same goes for Advance Select :)

http://new.tinygrab.com/6407caa59e964cf53a3f1b1036f606f0af9f648466.png

**Comment by ryanlabelle** [comment]
Pretty much any label, radio, select..

http://new.tinygrab.com/6407caa59ee799b1bf79be5e866bec55896164fe75.png

**Comment by funkedgeek** [comment]
Fixed in https://github.com/rilwis/meta-box/commit/52cda628c80d5653e550de54a8028e273575dbbd

**Comment by andrewfrankel** [comment]
@funkedgeek, as always, thanks!
