### ISSUE TITLE
Can't clone groups in 4.8.6

### ISSUE THREAD

**Issue by alexvpoirier** [rilwis/meta-box#880]
Hi,

Whenever I try to clone groups with 4.8.6, only the last one will save.

Works fine with 4.8.5 and older.

**Comment by funkedgeek** [comment]
Have you upgraded the groups plugin?

**Comment by rilwis** [comment]
@alexvpoirier: Please update to the latest version and try again. Make sure you clear the cache to load the latest version of the JavaScript file :)
