### ISSUE TITLE
users fields : get_users() vs WP_User_Query

### ISSUE THREAD

**Issue by Sinusite** [rilwis/meta-box#885]
[get_users()](https://codex.wordpress.org/Function_Reference/get_users) is used by user field. 

Maybe it's better to use [WP_User_Query](https://codex.wordpress.org/Class_Reference/WP_User_Query).  it's more extensible.
For instance we could choose multiple roles ('role__in' =>	array( 'role_one', 'role_two' ),) , not only one ( with 'query_args'  => array() ) .

Regards

**Comment by funkedgeek** [comment]
Fixed in https://github.com/rilwis/meta-box/commit/0c0bb959982d7ca7ac5d9f284ad8882aff74ba8c
