### ISSUE TITLE
Meta Box Group: Nested Cloning increase index of parent group field.

### ISSUE THREAD

**Issue by owiekindisch** [rilwis/meta-box#887]
Nested Cloning increase index of parent group field.

Setup:
```
array(
	'id' => 'my_group',
	'type' => 'group',
	'clone' => true,
	'fields' => array(
		array(
			'id' => 'first',
			'type' => 'text',
			'clone' => true,
		)
	)
);
```

If you clone the parent three times and then try to clone the 'first' field in the second Group-Clone,
the indexes increase for level 1. So the group-clone function is not save for just updating nested cloning fields.

To prevent this you need to add in line 21 of group.js

```
if ( ! $( clone ).data( 'clone-group-new' ) ) {
	index = parseInt( $( clone ).index() );
}
```

Sorry, but this script-kiddie mistake is not acceptable for paying 30$!

**Comment by rilwis** [comment]
Hi @owiekindisch ,

Which version of Group extension are you using? It's very strange to insert those code in line 21

http://prntscr.com/baoidz

**Comment by owiekindisch** [comment]
I'm sorry, I mean between line 19 and 20 to avoid the miss behaviour, that the index gets increased before the replacement function is called. Otherwise the nested cloned group file will have the name `my_group[2][first][1]` instead of `my_group[1][first][1]`

**Comment by owiekindisch** [comment]
I'm sorry, I mean between line 19 and 20 to avoid the miss behaviour, that the index gets increased before the replacement function is called. Otherwise the nested cloned group file will have the name my_group[2][first][1] instead of my_group[1][first][1]

**Comment by rilwis** [comment]
@owiekindisch Thanks a lot!

I've tried your patch but it doesn't work well in all cases. So I made a patch here http://pastebin.com/YhzB331K. Can you please try it?

**Comment by rilwis** [comment]
FYI, the fix is added to the latest version of the Group extension. Please update it.
