### ISSUE TITLE
Problem with Polylang and image advanced

### ISSUE THREAD

**Issue by rilwis** [rilwis/meta-box#888]
**Problem:**

In Polylang:

- create a post (A) in a language with a meta field image_advanced (IMG)
- select some image for image advanced field
- translate post A into another language (post B)

The problem is uploaded images (IMG) are not copied to B. Other field types are copied properly.

**Solution**:

After diving into the problem, I see that:

- Image advanced use Backbone Collection which send an Ajax request to get uploaded images
- Polylang modifies the query to insert the `lang` taxonomy. In case of post B, that returns an empty array of images.

So we need to prevent Polylang to modify the query. This is the code:

```php
if ( is_admin() )
{
	add_action( 'pre_get_posts', function( $query )
	{
		if ( isset( $_POST['action'] ) && 'query-attachments' == $_POST['action'] )
		{
			unset( $query->query_vars['lang'] );
		}
	}, 20 );
}
```

**Better solution:**

@funkedgeek: I think the solution above is bad as it targets a specific plugin (and there are a lot of them out there). Can we not use ajax request to get images? Or can we not use WP ajax action?

**Comment by funkedgeek** [comment]
Good question is why Polylang does this.  My code uses similar code to what WP uses for their media modals

**Comment by rilwis** [comment]
@funkedgeek They store multilingual posts in the same table as normal posts. So they need a filter to split them out for each language. I just don't know why they apply to all things, including media files.

**Comment by funkedgeek** [comment]
https://wordpress.org/support/topic/polylang-makes-media-vanish-in-library?replies=6

There is an option in Polylang to prevent this.  Basically the media gets set languages as well, so if you switch languages you don't see the media unless you translate them or turn off the feature for media.  It would do the same thing even if we weren't using JavaScript

**Comment by rilwis** [comment]
Thanks a lot for the link.

Yes, I think we're fine with this :)
