### ISSUE TITLE
File type & max_file_uploads : only the first is saved.

### ISSUE THREAD

**Issue by Sinusite** [rilwis/meta-box#892]
With metabox 4.8.7, only the first file is saved :
```
		array( 'name' => '', 
				'name' => 'File(s)',
                		'id' => "_cons_file",
                		'type' => 'file', // file_upload
                		'max_file_uploads' => 8,
                		'force_delete'=> true,
			),
```

**Comment by Sinusite** [comment]
OK forget it... it seems not working for "big" files (6mo) ?....

**Comment by rilwis** [comment]
@Sinusite: I think your host limits the max upload size. Most hosts accept max upload size 2MB. Please try to increase it in the php.ini or .htaccess file.
