### ISSUE TITLE
Field type clone is not working

### ISSUE THREAD

**Issue by calpaq** [rilwis/meta-box#893]
Hi am trying to write a plugin using meta box and I just started with your example 
I have installed metabox  4.8.7 plugin on wordpress 4.5.2 (latest) only wordpress & metabox 

1) Add new Page
2) It shows me a single field below Album Tracks, displays sort icon, displays add more button and when I add more fields and updates it displays me a single field and a single value in last instance or combined string not array also.
3) Also tried using single field not group
4) can you please tell me what is the problem? 

following code in a plugin file just only this code

```php
add_filter( 'rwmb_meta_boxes', 'my_meta_boxes' );

function my_meta_boxes( $meta_boxes )
{
	$meta_boxes[] = array(
		'title'  => __( 'Album Tracks' ),
		'pages' => array(  'page' ),
		'fields' => array(
			array(
				'id'     => 'standard',
				// Group field
				'type'   => 'group',
				// Clone whole group?
				'clone'  => true,
				// Drag and drop clones to reorder them?
				'sort_clone' => true,
				// Sub-fields
				'fields' => array(
					array(
						'name' => __( 'Track name', 'rwmb' ),
						'id'   => 'text',
						'type' => 'text',
					),
					array(
						'name' => __( 'Release Date', 'rwmb' ),
						'id'   => 'date',
						'type' => 'date',
					),
					array(
						'name'    => __( 'Genre', 'rwmb' ),
						'id'      => 'genre',
						'type'    => 'select_advanced',
						'options' => array(
							'pop'  => __( 'Pop', 'rwmb' ),
							'rock' => __( 'Rock', 'rwmb' ),
						),
					),
				),
			),
		),
	);
	 
 
	
 	     
	return $meta_boxes;
}
```

Thanks and Regards

**Comment by rilwis** [comment]
Hi @calpaq ,

The problem seems to be in the outdated version of the Group extension. Please update the extension and clear browser cache to check again.

Thanks
