### ISSUE TITLE
Use Geolocation with Groups plugin

### ISSUE THREAD

**Issue by nickrttn** [rilwis/meta-box#896]
If I define an address Metabox using the Group addon, I would like to be able to add multiple addresses. Right now, if I try that, the Geolocation autofill fills in *all* of the address groups with the information. The lookup also only works in the first autofill field of the address groups.

**Comment by rilwis** [comment]
@tanng Can you please look at this issue?

**Comment by tanng** [comment]
I've updated both Group and Geolocation. Please update both :)
