### ISSUE TITLE
Date field defaults to non-english language

### ISSUE THREAD

**Issue by karissademi** [rilwis/meta-box#898]
Not an issue, but an FYI. After the last update (4.8.7) if you aren't specifying the language field for date pickers, it will default to an non-english language. 

Easy to change by either resetting the language field or specifying your own.

All datepickers:
`$.datepicker.setDefaults( $.datepicker.regional[ "" ] );`

Targeting meta-box:
`$('.rwmb-date').val( $.datepicker.setDefaults( $.datepicker.regional[ "" ] ) );`

**Comment by rilwis** [comment]
Thanks for your help :). The plugin is updated with the fix.
