### ISSUE TITLE
Max File Upload plupload

### ISSUE THREAD

**Issue by Infolu** [rilwis/meta-box#899]
Hello I used plupload_image with the function 'max_file_uploads' => 10, however I noticed that even limiting the charging box 10 files, if I try to climb more than 10 files these files are loaded into wp-content / uploads.

That is no matter how many files I limit with max_file_uploads the box allows you to upload as many medias like leaving the wp-content folder / upload over loaded with useless files.

Any solution for this?

**Comment by rilwis** [comment]
The plugin limits the maximum number of files to be uploaded **and** added to the post meta. It doesn't limits the upload to the Media Library (because users still can upload as many files as they want at **Media > Upload** page, it doesn't make sense to restrict here).
