### ISSUE TITLE
Metabox and page templates

### ISSUE THREAD

**Issue by RedGlow** [rilwis/meta-box#900]
Currently metaboxes can be added to pages. It would be nice to have the option to add metaboxes only to certain page templates.

An use case of this scenario would for example be an about page which can have social media links, a map, and so on.

A similar feature, which is also much more articulated, is given by Advanced Custom Fields: https://www.advancedcustomfields.com/resources/custom-location-rules/

**Comment by rilwis** [comment]
Hi,

This is can be done using the snippet [here](https://github.com/rilwis/meta-box/blob/master/demo/include-by-ID-or-page-template.php) or [here](https://github.com/rilwis/meta-box/blob/master/demo/better-include.php).

If you need more options/controls, please consider [this premium extension](https://metabox.io/plugins/meta-box-include-exclude/).
