### ISSUE TITLE
Metabox resetting $post->ID?

### ISSUE THREAD

**Issue by aerlaut** [rilwis/meta-box#901]
I'm using metabox in a custom loop like so : 

```
<?php 
$profiles = new WP_Query(array(
    'post_type' => 'profile',
));

if($profiles->have_posts()) : while($profiles->have_posts()) : $profiles->the_post(); ?>

<div class="profile-item col-md-2">
     <?php echo $post->ID; ?><br />
    <?php echo get_post_meta($post->ID, 'profile_name')[0]; ?><br />
    <?php echo rwmb_meta('profile_name'); ?><br />
    <?php echo $post->ID; ?><br />
    <?php echo get_post_meta($post->ID, 'profile_specialization')[0]; ?><br />
    <?php echo rwmb_meta('profile_specialization'); ?><br />
    </div>

    <?php endwhile; ?>
<?php endif; ?>
```

There are currently 2 dummy posts with ID and data : 
```
ID : 41 =>  profile_name : Person 1
                  profile_specialization : Spec 1
ID : 47 =>  profile_name : Person 2
                  profile_specialization : Spec 2
```

Output is like : 
```
47
Person 2
Person 1
41
Spec 1
Spec 1

41
Person 1
Person 1
41
Spec 1
Spec 1
```

Expected : 
```
47
Person 2
Person 2
47
Spec 2
Spec 2

41
Person 1
Person 1
41
Spec 1
Spec 1
```

So somehow the global $posts is overwritten when calling `rwmb_meta('profile_name')` for the first time. Aside from using MetaBox (v 4.8.7), I'm also using Polylang (v 1.9.2, https://polylang.wordpress.com/).

Help?

**Comment by aerlaut** [comment]
Retreiving metadata set using metabox using `get_post_meta()` works fine,

**Comment by rilwis** [comment]
Did you have `global $post;` in your code?

**Comment by aerlaut** [comment]
No, I'm not using `global $post` anywhere,

**Comment by rilwis** [comment]
Please add that to the code. It makes sure you're working on the global `$post` object with `rwmb_meta`.

**Comment by aerlaut** [comment]
Adding `global $post` in the loop fixes the issue :)
