### ISSUE TITLE
Multilingual site image_advanced problem polylang

### ISSUE THREAD

**Issue by jdivins** [rilwis/meta-box#902]
I use metabox.io to generate my custom fields.
I have generated this one:
```
array( 'name'             => 'gallery',
	 'id'               => 'sc_gallery',
	 'type'             => 'image_advanced',
	 'max_file_uploads' => 10,
),
```
When I try to generate the translation page with polylang I don't get the images inside the gallery created on the default language.
I have another field that it's correctly syncronized, but is of type text:
```
array(
		'name'  => 'Gallery Title',
                'desc'  => 'Title of each image in the gallery',
                'id'    =>  'sc_gallery_title',
                'type'  => 'text',
                'clone' => true
),
```
Maybe the type of field is not supported by polylang?
I have searched the action of sync when translate and I think the work proces is done in this piece of code:
```
$keys = array_unique( apply_filters( 'pll_copy_post_metas', $keys, $sync, $from, $to, $lang ) );

		// and now copy / synchronize
		foreach ( $keys as $key ) {
			delete_post_meta( $to, $key ); // the synchronization process of multiple values custom fields is easier if we delete all metas first
			if ( isset( $metas[ $key ] ) ) {
				foreach ( $metas[ $key ] as $value ) {
					// important: always maybe_unserialize value coming from get_post_custom. See codex.
					// thanks to goncalveshugo http://wordpress.org/support/topic/plugin-polylang-pll_copy_post_meta
					$value = maybe_unserialize( $value );
					// special case for featured images which can be translated
					add_post_meta( $to, $key, ( '_thumbnail_id' == $key && $tr_value = $this->model->post->get_translation( $value, $lang ) ) ? $tr_value : $value );
				}
			}
		}

```
This code is inside the file: polylangplugin/modules/sync/admin-sync.php line 202

The polylang version is the latest: 1.9.2
Meta box version is the latest: 4.8.7

I have tried to force the sync with this code on functions
```
add_filter('pll_copy_post_metas', 'copy_post_metas');
function copy_post_metas($metas) {
	return array('sc_gallery','sc_gallery_title');
}
```
But doesn't work.

Thank you for you help and work

**Comment by funkedgeek** [comment]
Probably related to https://github.com/rilwis/meta-box/issues/888.  Please read https://github.com/rilwis/meta-box/issues/888#issuecomment-223031797

**Comment by jdivins** [comment]
Yeah!
Is the same problem, thank you for the reply! The solution on the #888 post solved the problem.
Thank you!
