### ISSUE TITLE
Filter meta of field_id (Meta Box)

### ISSUE THREAD

**Issue by owiekindisch** [rilwis/meta-box#903]
Version 4.8.7
--

Most of the filter hooks that are declared in the documentation aren't in code or won't execute.

For example: [rwmb_{$field_type}_meta](https://metabox.io/docs/filters/#section-rwmb_field_id_meta).
After sniffing through your code there is no such filter.

After looking deeper, found out that the filter `rwmb_{$field_type}_meta` is actually called `rwmb_{$field_type}_field_meta`.

So change:
`rwmb_{$field_id}_meta` to `rwmb_{$field_id}_field_meta`
`rwmb_{$field_type}_meta` to `rwmb_{$field_type}_field_meta`

**Comment by rilwis** [comment]
You're right! That was my mistake. The documentation is updated. Thank you very much :)
