### ISSUE TITLE
Term meta disappeared

### ISSUE THREAD

**Issue by cedric-dagherir** [rilwis/meta-box#906]
Wordpress : 4.5.2
Metabox : 4.8.7
MB Term meta : 1.0.0
Metabox Group : 1.0.6

After updating Wordpress to 4.5.2, I can't see the meta of my taxonomy anymore. Nothing in the HTML output code of the admin page. Neither warning, nor error with WP debug mode.

Code extracts :
```
	  register_taxonomy(
	    'cat_enigmes',
	    'enigmes',
	    array(
	      'label' => __( 'Catégories d\'énigmes' ),
	      'hierarchical' => true,
	      'rewrite'   =>  array('slug' => 'speciales' ),
	    )
	  );
```
```

   $meta_boxes[] = array(
	        'id'       => 'infos_cat_enigmes',
	        'title'    => 'Informations catégorie tirage au sort',
	        'taxonomies'    => 'cat_enigmes',

	        'fields' => array(
	            array(
	                'name'  => 'Début',
	                'id'    => $prefix . 'debut',
	                'type'  => 'date',
	                'desc' => 'A partir de 00:00:00 le matin'
	            ),
	            array(
	                'name'  => 'Fin',
	                'id'    => $prefix . 'fin',
	                'type'  => 'date',
	                'desc' => 'Jusqu\'à 23:59:59'
	            ),
	          )
	    );
```

Thanks for your help !

**Comment by toshimichimiki** [comment]
Same issue is occuring to me.
My dev environment is below. 
Wordpress: 4.5.3
Meta Box: 4.8.7
MB Term meta : 1.0.0

**Comment by rilwis** [comment]
Please update to the latest version of the extension which fixes this bug.

**Comment by cedric-dagherir** [comment]
Thanks Rilwis. But the latest version of MB Term Meta I can download is the 1.0.0...

**Comment by rilwis** [comment]
Please follow [this documentation](https://metabox.io/docs/update-extensions/) to update the extension.
