### ISSUE TITLE
Cloned Group Field Uses Same Input Name as Existing Field

### ISSUE THREAD

**Issue by enummela** [rilwis/meta-box#908]
When cloning a group meta-box field, we were experiencing an issue where only one of the cloned fields was being saved, any additional cloned fields were not. Upon investigating the form inputs, I discovered that the cloned fields were being given the same name as existing fields, in this case the same index into an array (see attached screenshot). This explains why only one of the cloned fields was being recognized. I confirmed that this was the issue by manually changing the indices in the input names and submitting the form, which caused the cloned fields to be correctly saved.

This issue is present on both Meta Box 4.8.6 and 4.8.7 in combination with Meta Box Group 1.0.5.

![meta-box_clone_group_input_names](https://cloud.githubusercontent.com/assets/5798441/16343786/fd0de6d6-39ed-11e6-91a4-965266aa2ceb.png)

**Comment by rilwis** [comment]
Please update the Group extension to the latest version and try again. Make sure you clear the cache!

Related issue: #880, #875.

**Comment by enummela** [comment]
Thank you @rilwis. We will try upgrading the extension as you say.
