### ISSUE TITLE
Google Map key is now required !

### ISSUE THREAD

**Issue by Sinusite** [rilwis/meta-box#909]
Please note that ?sensor=false is useless but...

Google[ no longer support keyless access](http://googlegeodevelopers.blogspot.fr/2016/06/building-for-scale-updates-to-google.html) (any request that doesn't include an API key) !

**Comment by Infolu** [comment]
Hi, I have the same problem here no map loads
someone already has a solution?
![erro maps](https://cloud.githubusercontent.com/assets/16593922/16363206/ba9333e4-3b99-11e6-9186-59079c7a176e.PNG)

**Comment by funkedgeek** [comment]
Thanks for letting us know.  We'll work on it

**Comment by ibaianater** [comment]
This is a quick fix till they fix it :)

change this url (2 urls)
https://maps.google.com/maps/api/js?sensor=false
on this file 
meta-box/inc\fields/map.php
with
https://maps.google.com/maps/api/js?sensor=false&key=YOUR_API_KEY
you can get your api key from here 
https://developers.google.com/maps/documentation/javascript/get-api-key

it works fine with me.

**Comment by rilwis** [comment]
Just fixed. Please try and let me know if something wrong :)

**Comment by funkedgeek** [comment]
We need to make sure to document this and/or provide a default api key
