### ISSUE TITLE
Map address not working, it on some servers but not work on some 

### ISSUE THREAD

**Issue by waqasriaz** [rilwis/meta-box#910]
Hi,
I am using metabox plugin for my clients but map address field working for some clients but not working for some. Here is video https://monosnap.com/file/0lZsmD8SStIVXbaEIXbqE05yQNU6ey
Can you guy help to solve it ASAP ?

**Comment by funkedgeek** [comment]
Can you post the code you are using to create the meta box?

**Comment by Infolu** [comment]
Hello same to me, it was well after fixed
https://github.com/rilwis/meta-box/issues/909

I've tried adding a own key however still with problems not display the map

`  			array(
  				'id'   => $PrefixField .'geolocation_maps_preview',
  				'name'          => __( 'Visualização do Mapa', 'your-prefix' ),
  				'type'          => 'map',
  				// Default location: 'latitude,longitude[,zoom]' (zoom is optional)
  				//'std'           => '-23.532355,-47.193668',
          'std'           => ' -15.7941,-47.8825', /* Default Brasilia, Brasil */
  				// Name of text field where address is entered. Can be list of text fields, separated by commas (for ex. city, state)
  				'address_field' => 'real_mb_geolocation_maps_address',
          'api_key'       => 'AIzaSyC81OIFE7iwAubVYcAPsMIrzxj82aZBHK',
  			),`

on my console returns below an Front end
![ba9333e4-3b99-11e6-9186-59079c7a176e 1](https://cloud.githubusercontent.com/assets/16593922/17260689/29e61c7a-55a8-11e6-948a-02de3d770482.PNG)

**Comment by funkedgeek** [comment]
The error that is given says your key is invalid.  Please make sure you are copying the whole key from Google: https://developers.google.com/maps/documentation/javascript/get-api-key#key
