### ISSUE TITLE
Term Meta Plugin

### ISSUE THREAD

**Issue by spllogics** [rilwis/meta-box#911]
Trying to get term meta boxes to work, but even with copy and pasting the original demo.php (https://gist.github.com/rilwis/689edb31a456419e02b0#file-demo-php) I do not get any meta boxes for the category or term. 

WP Version 4.5.3
MB Version 4.8.7
MB Term Meta Version 1.0.2

``` php
add_filter( 'rwmb_meta_boxes', 'collections_register_taxonomy_meta_boxes' );
function collections_register_taxonomy_meta_boxes( $meta_boxes )
{
    $meta_boxes[] = array(
        'title'      => 'Standard Fields',
        'taxonomies' => 'collections', // List of taxonomies. Array or string

        'fields' => array(
            array(
                'name' => 'Manual',
                'id'   => 'collections_manual',
                'type'   => 'text'
            ),
        ),
    );
    return $meta_boxes;
}
```

**Comment by rilwis** [comment]
Do you have the taxonomy `collections'?

**Comment by spllogics** [comment]
Yes. I have even tried it with "category" with no results. This is also a fresh install. 
Other plugins are Custom Post Type UI, MB Admin Columns, Meta Box Builder, Meta Box Columns, Meta Box Updater. 

name: collections
label: Collections
singular_label: Collection
description:
public: true
hierarchical: true
show_ui: true
query_var: true
query_var_slug:
rewrite: true
rewrite_slug:
rewrite_withfront: true
rewrite_hierarchical: false
show_admin_column: false
post_type: products

**Comment by rilwis** [comment]
I've just tested with your code and it works. Do you see any error in the log?

**Comment by joeporterme** [comment]
was there a solution to this?  im just now starting to use this and the meta box is not showing up... no errors either....

`// Regsiter the Cities Taxonomy

if ( ! function_exists( 'gnl_city_taxonomy' ) ) {

// Register Custom Taxonomy
function gnl_city_taxonomy() {

	$labels = array(
		'name'                       => _x( 'Cities', 'Taxonomy General Name', 'text_domain' ),
		'singular_name'              => _x( 'City', 'Taxonomy Singular Name', 'text_domain' ),
		'menu_name'                  => __( 'Cities', 'text_domain' ),
		'all_items'                  => __( 'All Cities', 'text_domain' ),
		'parent_item'                => __( 'Parent City', 'text_domain' ),
		'parent_item_colon'          => __( 'Parent City:', 'text_domain' ),
		'new_item_name'              => __( 'New City Name', 'text_domain' ),
		'add_new_item'               => __( 'Add New City', 'text_domain' ),
		'edit_item'                  => __( 'Edit City', 'text_domain' ),
		'update_item'                => __( 'Update City', 'text_domain' ),
		'view_item'                  => __( 'View City', 'text_domain' ),
		'separate_items_with_commas' => __( 'Separate cities with commas', 'text_domain' ),
		'add_or_remove_items'        => __( 'Add or remove cities', 'text_domain' ),
		'choose_from_most_used'      => __( 'Choose from the most used', 'text_domain' ),
		'popular_items'              => __( 'Popular Cities', 'text_domain' ),
		'search_items'               => __( 'Search Cities', 'text_domain' ),
		'not_found'                  => __( 'Not Found', 'text_domain' ),
		'no_terms'                   => __( 'No Cities', 'text_domain' ),
		'items_list'                 => __( 'Cities list', 'text_domain' ),
		'items_list_navigation'      => __( 'Cities list navigation', 'text_domain' ),
	);
	$args = array(
		'labels'                     => $labels,
		'hierarchical'               => false,
		'public'                     => true,
		'show_ui'                    => true,
		'show_admin_column'          => false,
		'show_in_nav_menus'          => false,
		'show_tagcloud'              => false,
		'show_in_rest'               => true,
	);

	// we are not applying it directly to a post type.  We use it to feed metabox on post types
	register_taxonomy( 'city', array(), $args );

}
add_action( 'init', 'gnl_city_taxonomy', 0 );

}


// Add term meta

add_filter( 'rwmb_meta_boxes', 'gnl_city_meta_boxes' );
function gnl_city_meta_boxes( $meta_boxes )
{
	$meta_boxes[] = array(
		'title'      => 'Standard Fields',
		'taxonomies' => 'city', // List of taxonomies. Array or string
		'fields' => array(
			array(
				'name' => __( 'Featured?', 'textdomain' ),
				'id'   => 'featured',
				'type' => 'checkbox',
			),
		),
	);
	return $meta_boxes;
}
`

**Comment by rilwis** [comment]
I'll close this issue as it's quite a long time ago without responses. Feel free to re-open it if you still have any problem.
