### ISSUE TITLE
Number field alert message

### ISSUE THREAD

**Issue by pixedelic** [rilwis/meta-box#916]
Hello, tried this to allow to enter font size in EM:

```php
array(
	'name' => esc_html__( 'Change font size', 'theme' ),
	'id'   => "title_font_size",
	'type' => 'number',
	'std'  => 1,
	'min'  => -5,
	'step' => 0.005,
	'desc' => esc_html__( 'Intended as EMs', 'theme' )
)
```

If I enter a value manually I always get the red alert message: **Please enter a multiple of 0.005** even if I actually entered a multiple of 0.005

Any advice? Thank you in advance :-)

**Comment by funkedgeek** [comment]
Which browser?  Sounds like its related to how the browser handles number fields more than anything else.

**Comment by rilwis** [comment]
It works for me on Chrome but not on Firefox. I think browsers doesn't handle validation for HTML 5 fields consistently. You should change `step` to `'any'` in this case.

**Comment by pixedelic** [comment]
Chrome, Safari, Opera and Firefox on Mac. Of course, at the moment I turned it into a simple text field, but I want to report it. Thank you

**Comment by rilwis** [comment]
Thanks @pixedelic. As I commented, you can still use `number` field with `'step' => 'any'` to make browsers don't validate the field while you still benefit from up/down arrows.

The plugin outputs plain html for the number field and doesn't do anything fancy to inject validation. The validation of the field comes from the browsers and I think we couldn't do much on that :(.
