### ISSUE TITLE
Image only returns the attachment ID

### ISSUE THREAD

**Issue by OneEarthMedia** [rilwis/meta-box#917]
Hi, I have the MetaBox version 4.8.7 installed as a plugin and I've created an image field.

When I retrieve the image on the frontend using `rwmb_meta('my_image', 'size=MYSIZE');`, only the attachment ID is returned.

Using `rwmb_meta('my_image', 'type=image&size=MYSIZE');` works as expected but I understand from the documentation that this method is deprecated since 4.8.0?

Any idea why this might be or what I'm doing wrong?

Thanks,

Herman

**Comment by Infolu** [comment]
Hello, I do not know if I understand very well but you can get the id of the image and display using the function of wordpress following example

`if ( !empty( $value ) ) {
		foreach ( $value as $subvalue ) {
			$display = wp_get_attachment_url( $subvalue );
			echo 'src="' .$display.'" ';
			}
	}`

Greetings

Araujo, Luiz

**Comment by rilwis** [comment]
Do you register meta boxes via `admin_init` hook or register for the admin area only (like wrap code in `if ( is_admin() )`?

**Comment by OneEarthMedia** [comment]
Indeed, I understand now. I have a template check before returning the meta boxes which prevents it being executed on the front end. I got it working now by checking for the front-end post ID. Before I was only getting the post ID from the edit page URL.

I know there's an extension that make these type of checks really easy but I only needed a template check so I thought I'll just create my own.

Thanks for the help. Great plugin!

**Comment by rilwis** [comment]
Great :)
