### ISSUE TITLE
rwmb_meta() returns false in an AJAX action.

### ISSUE THREAD

**Issue by OneEarthMedia** [rilwis/meta-box#920]
Hello,

I'm trying to retrieve some data with an AJAX action.

Here's an example of my issue:

`get_post_meta($post_id, 'my_custom_post_title', true);`
The above returns the data as expected

`rwmb_meta('my_custom_post_title', $post_id);`
While the _rwmb()_ function returns _false_ (The AJAX response is true but the string is empty/false)

The field is registered correctly and elsewhere I can retrieve that data using _rwmb()_ without problems.

The AJAX action is registered using the `wp_ajax_` and `wp_ajax_nopriv_` hooks.

I don't mind using _get_post_meta()_ and other means to retrieve the necessary data but any ideas why _rwmb()_ isn't working in this case?

Thank you,

Herman

**Comment by rilwis** [comment]
I guess the problem is you put the function to register meta boxes somewhere that is not available for ajax request. The `rwmb_meta` works **only if** that function is available everywhere, e.g. no conditions at all.

**Comment by OneEarthMedia** [comment]
I just figured out what the issue was.

Using `rwmb_meta('my_custom_post_title', $post_id)` to retrieve meta data doesn't work because the the $args value can't be omitted if the $post_id is specified.

This worked for me `rwmb_meta('my_custom_post_title', '', $post_id);` settings the $args to be false or null works.

**Comment by rilwis** [comment]
That’s right :)
