### ISSUE TITLE
Timestamp=>true and inline=>true break datetime field

### ISSUE THREAD

**Issue by d2roth** [rilwis/meta-box#923]
Hey Guys,
Registering a metabox as follows fails to store anything in the database:
```PHP
               array(
                    'name' => __('Start Date'),
                    'id' => 'start_date',
                    'type' => 'datetime',
                    'inline'=>true,
                    'timestamp'=>true,
                    'desc' => 'When does this event start?',
                ),
```
If you comment out the inline=>true line the timestamp properly gets updated. So it seems that the issue is in the fact the timestamp field doesn't get updated by the datetime picker since the code to update the timestamp input never gets triggered.

I think it may be partly because of the solution to #849. Maybe just make it change both on update and select?

For now I am just going to disable the inline option but I would really like to be able to have that.

Thanks,

**Comment by d2roth** [comment]
This breaks #849's fix. Wouldn't it be better to set onClose if the calendar is not inline and set onSelect if it is an inline calendar? That would still give some issues if someone manually entered a date but I think without converting the date to a timestamp on the server that will be closer to seamless UX.

**Comment by funkedgeek** [comment]
Okay, think I fixed it.  Should work fine now.  Let me know if there are any more bugs
