### ISSUE TITLE
Warning: Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by claudiutilvar** [rilwis/meta-box#926]
Hello guys,

I have a problem with this plugin. I receive this error : http://screencast.com/t/p7Y3VMTSM

I check 56 line in the field.php file and this is what i find : http://screencast.com/t/BHOvJxJfMZ

Who can give me a solution for fix this issue?

**Comment by rilwis** [comment]
This error often occurs when you set up a custom field (in this case a cloned field) and then change its structure. That makes the saved meta value invalid for the new structure. A good solution for that is just change the field ID so the data is saved a new field.

**Comment by funkedgeek** [comment]
If you save the post once the error should go away
