### ISSUE TITLE
rwmb_meta show ID in front-end 

### ISSUE THREAD

**Issue by avatarr** [rilwis/meta-box#927]
I create custom post to show image gallery and use metabox 'image_advance', So When I query my post in front-end in every loop a function print ID of metabox to webpage that not my expectation (see result at below image) 

![screenshot from 2016-07-24 16 01 50](https://cloud.githubusercontent.com/assets/1640817/17082914/8008c9d4-51b8-11e6-848b-52045a68c388.png)

and here is code : http://pastebin.com/bpK46mTR

**Comment by d2roth** [comment]
In your foreach loop on line 9 you need to use the function get_the_ID() since the_ID echo out the id.
Also at the end of your echo line you need to use a single quote instead of the double quote.

That should fix the problem.

**Comment by avatarr** [comment]
Thank you is worked for me
