### ISSUE TITLE
Help with Meta Box version 4.8.7 not working

### ISSUE THREAD

**Issue by jnamnco** [rilwis/meta-box#928]
Can someone help me with the current running Meta Box version?

Basically, I cannot use this plug-in in my WordPress.

I see the options to add whatever field I want but to actually use them, I can't.

Please can someone help with this issue, thanks!

**Comment by rilwis** [comment]
What is your problem, precisely? How do you install and use the plugin?

**Comment by jnamnco** [comment]
Hi, 
Thanks for commenting back.
All I did was update the plugin to the latest version.
And when I am making a new page, for example, if I select the backend editor, there's the normal 'box' to select whatever layout etc, but nothing shows after selecting. (as you can see attached screen shot)
<img width="753" alt="screen shot 2016-07-25 at 21 33 35" src="https://cloud.githubusercontent.com/assets/20631742/17123150/8860a636-52af-11e6-95fe-c3b56a330c32.png">

OR if there was an existing page that was created with the backend editor, I don't see the layout anymore.  But if i got to the classic editor, i see all the coding.

**Comment by rilwis** [comment]
Oh, this box comes from [Visual Composer plugin](https://codecanyon.net/item/visual-composer-page-builder-for-wordpress/242431?ref=fitwp), so you need to look at Visual Composer documentation to edit this box. It's not something belongs to the Meta Box plugin, sorry :(.

**Comment by jnamnco** [comment]
Ah ok. Thanks for letting me know!!!
