### ISSUE TITLE
Customize meta box through child theme!

### ISSUE THREAD

**Issue by priyanka-Sadh** [rilwis/meta-box#929]
I am using penny auction wordpress theme, as i am new to wordpress. My question is want to add more fields in side metabox through child theme, So for this i have successfully created and activated child theme, but i am stuck here to how can i add more text fields in meta box by using child theme functions.php file?
Please help me here, would appreciate.

**Comment by rilwis** [comment]
Hi,

If you want to add more text fields in an existing meta box made by the parent theme, please follow [this documentation](https://metabox.io/docs/edit-remove-meta-boxes/)

If you just want to create a new meta box/custom fields, then you just need to follow the [getting started guide](https://metabox.io/docs/getting-started/)

**Comment by priyanka-Sadh** [comment]
please suggest what should i do in child theme as my parent theme functions file having below code for meta boxes

function PennyTheme_create_post_type() {
  $icn = get_bloginfo('template_url')."/images/auctionicon.gif";
  register_post_type( 'auction',
    array(
      'labels' => array(
        'name' 			=> __('Auctions',		'PennyTheme' ),
        'singular_name' => __('Auction',		'PennyTheme' ),
		'add_new' 		=> __('Add New Auction','PennyTheme'),
		'new_item' 		=> __('New Auction',	'PennyTheme'),
		'edit_item'		=> __('Edit Auction',	'PennyTheme'),
		'add_new_item' 	=> __('Add New Auction','PennyTheme'),
		'search_items' 	=> __('Search Auctions','PennyTheme'),	
      ),
      'public' 				=> true,
	  'menu_position'		 => 5,
	  'register_meta_box_cb' => 'PennyTheme_set_metaboxes',
	  'has_archive' => "auction-list",
      'rewrite' => true, // array('slug'=>"auctions/%auction_cat%",'with_front'=>true),
	   'supports' => array('title','editor','author','thumbnail','excerpt','comments'),
	  '_builtin' 			=> false,
	  'menu_icon' 			=> $icn,
	  'publicly_queryable' 	=> true,
	  'hierarchical' 		=> false 

    )
  );

	register_taxonomy( 'auction_cat', 'auction', array( 'hierarchical' => true, 'label' => __('Auction Categories','PennyTheme'),
	'rewrite'                       => true ));
	add_post_type_support( 'auction', 'author' );
	//add_post_type_support( 'auction', 'custom-fields' );
	register_taxonomy_for_object_type('post_tag', 'auction');	
	flush_rewrite_rules();
} 

function PennyTheme_set_metaboxes(){
		add_meta_box( 'auction_images', 'Auction Images',	'PennyTheme_theme_auction_images', 	'auction', 'advanced',	'high' );
		add_meta_box( 'penny_bids', 	'Auction Bids',		'PennyTheme_theme_penny_bids', 		'auction', 'advanced',	'high' );
		add_meta_box( 'auction_dets', 	'Auction Details',	'PennyTheme_theme_auction_dts', 	'auction', 'side',		'high', 15 );	
}
//// This is meta box field function
function PennyTheme_theme_auction_dts(){
	global $post;	
	$pid = $post->ID;	
	$price = get_post_meta($pid, "price", true);
	
	?>
    
    <ul id="post-new4"> 
    <input name="fromadmin" type="hidden" value="1a" />           
         <li>
        	<h2><?php echo __('Retail Price','PennyTheme'); ?>:</h2>
        <p><input type="text" size="10" name="retail_price" class="do_input" 
        	value="<?php echo get_post_meta($pid, 'retail_price', true); ?>" /> 
			<?php echo PennyTheme_currency(); ?></p>
        </li>
</ul> 
<? php } ?>

**Comment by rilwis** [comment]
Oh, your theme uses custom code to register meta boxes and custom fields. It doesn't use the Meta Box plugin, so sorry I can't help :(

Anyway, you can use the plugin to add **another meta box** (not editing the old one) by following the guide [here](https://metabox.io/docs/getting-started/).
