### ISSUE TITLE
multiple taxonomy_advanced field on mb_term_meta

### ISSUE THREAD

**Issue by ZeroBeeOne** [rilwis/meta-box#930]
Hi there,

I have the following term meta box registered on a new install using the Twenty Fifteen theme with only two plugins active: Metabox (4.8.7) and MB Term Meta (1.0.2):

```
$meta_boxes[] = array(
	'title'      => 'Region Linking',
	'taxonomies' => 'suburb', // List of taxonomies. Array or string
	'fields' => array(
		array(
			'name'			=> 'Regions',
			'id'			=> $prefix . 'regions',
			'type'			=> 'taxonomy_advanced',
			'desc'			=> 'Select regions this suburb is a part of.',
			'multiple'		=> true,
			'taxonomy'		=> 'region',
			'field_type'	=> 'select_advanced',
			'placeholder'	=> 'Select one or more regions'
		)
	),
);
```

It  is the only meta box registered so far (other than registering the two taxonomies: region and suburb, the metabox registration above is the only bit of code I have written in this install yet). The two taxonomies in question were registered with all the `register_taxonomy()` default args except their own labels.

The problem right now is that when I attempt to save the field, the details are not saved. The field appears fine on the term edit page, is populated properly and allows me to select terms as I would expect, however when attempting to save I get the following errors in the log:

```
[Tue Jul 26 16:26:21.638152 2016] [:error] PHP Warning:  Invalid argument supplied for foreach() in /var/www/sitename/wp-content/plugins/mb-term-meta/inc/term-meta-box.php on line 193, referer: http://sitename.dev.com/wp-admin/term.php?taxonomy=suburb&tag_ID=5&post_type=post&wp_http_referer=%2Fwp-admin%2Fedit-tags.php%3Ftaxonomy%3Dsuburb
[Tue Jul 26 16:26:21.638165 2016] [:error] PHP Stack trace:, referer: http://sitename.dev.com/wp-admin/term.php?taxonomy=suburb&tag_ID=5&post_type=post&wp_http_referer=%2Fwp-admin%2Fedit-tags.php%3Ftaxonomy%3Dsuburb
[Tue Jul 26 16:26:21.638173 2016] [:error] PHP   1. {main}() /var/www/sitename/wp-admin/edit-tags.php:0, referer: http://sitename.dev.com/wp-admin/term.php?taxonomy=suburb&tag_ID=5&post_type=post&wp_http_referer=%2Fwp-admin%2Fedit-tags.php%3Ftaxonomy%3Dsuburb
[Tue Jul 26 16:26:21.638179 2016] [:error] PHP   2. wp_update_term() /var/www/sitename/wp-admin/edit-tags.php:183, referer: http://sitename.dev.com/wp-admin/term.php?taxonomy=suburb&tag_ID=5&post_type=post&wp_http_referer=%2Fwp-admin%2Fedit-tags.php%3Ftaxonomy%3Dsuburb
[Tue Jul 26 16:26:21.638184 2016] [:error] PHP   3. do_action() /var/www/sitename/wp-includes/taxonomy.php:3530, referer: http://sitename.dev.com/wp-admin/term.php?taxonomy=suburb&tag_ID=5&post_type=post&wp_http_referer=%2Fwp-admin%2Fedit-tags.php%3Ftaxonomy%3Dsuburb
[Tue Jul 26 16:26:21.638189 2016] [:error] PHP   4. call_user_func_array() /var/www/sitename/wp-includes/plugin.php:525, referer: http://sitename.dev.com/wp-admin/term.php?taxonomy=suburb&tag_ID=5&post_type=post&wp_http_referer=%2Fwp-admin%2Fedit-tags.php%3Ftaxonomy%3Dsuburb
[Tue Jul 26 16:26:21.638196 2016] [:error] PHP   5. MB_Term_Meta_Box->save() /var/www/sitename/wp-includes/plugin.php:525, referer: http://sitename.dev.com/wp-admin/term.php?taxonomy=suburb&tag_ID=5&post_type=post&wp_http_referer=%2Fwp-admin%2Fedit-tags.php%3Ftaxonomy%3Dsuburb
[Tue Jul 26 16:26:21.638202 2016] [:error] PHP   6. MB_Term_Meta_Box->save_field() /var/www/sitename/wp-content/plugins/mb-term-meta/inc/term-meta-box.php:146, referer: http://sitename.dev.com/wp-admin/term.php?taxonomy=suburb&tag_ID=5&post_type=post&wp_http_referer=%2Fwp-admin%2Fedit-tags.php%3Ftaxonomy%3Dsuburb
```

I did a little digging in the file in question, /mb-term-meta/inc/term-meta-box.php,  (note - I inserted an `error_log()` call on line 192 while doing this, and have just realized that means the line numbers referenced above will be off by one due to that, sorry), and found that at the point the error is raised, the value of `$new` is a comma separated list of term id's, whereas the code here clearly expects an array.

Is this just me not using the field properly? I feel like I've followed the documentation to the letter but I'm not averse to finding out I missed something. I also tried using `'clone' => true` on the field definition instead of `multiple`, but the add clone button did not appear on the edit term page, so I was unable to even select multiple terms.

The field works perfectly when I remove both these attributes (such that it is just a single select), for what it's worth - but this doesn't suit my use case.

**Comment by ZeroBeeOne** [comment]
Just a note that the following workaround resolves this for me in the meantime, at least for the way I am using the field:

```
<?php
// Prevent loading this file directly
if (!defined( 'ABSPATH' )) die( 'No direct access' );

if (class_exists('RWMB_Taxonomy_Advanced_Field') && !class_exists('RWMB_Taxonomy_Advanced_Term_Field'))
{
	class RWMB_Taxonomy_Advanced_Term_Field extends RWMB_Taxonomy_Advanced_Field
	{
		public static function value( $new, $old, $post_id, $field )
		{
			return array_unique((array) $new);
		}

		public static function meta( $post_id, $saved, $field )
		{
			$meta = get_post_meta( $post_id, $field['id'], true );
			$meta = is_array($meta) ? array_filter( $meta ) : array();
			return $meta;
		}
	}
}

```

then of course changing the type of the field in question to taxonomy_advanced_term

**Comment by ZeroBeeOne** [comment]
Noting that this issue persists on MB Term Meta 1.0.3, however the workaround above is still working too.

**Comment by athossin** [comment]
Dear sir, How can I solve this problem?
When I am  using this code then it shows only id instead of its content.I want to show the content instead of id.How Can I do this?
```
array(
					'name'				=> __( 'Select Home Team ', 'themepixels' ),
					'id'				=> "{$prefix}select_home_team",
					'type'				=> 'post',
					'post_type'        =>  'football_team' ,
					'options'			=> array(
						'type'			=> 'select_advanced',
						'args'			=> array()
					),
					'multiple'			=> false,
				),
```
.....
```
<div class="home-team">
       <?php $home_team_name = rwmb_meta( 'pb_select_home_team','type=select_advanced'); ?>
      <?php  echo esc_html( $home_team_name  ); ?>
       
    </div>
```

**Comment by ZeroBeeOne** [comment]
you know spamming your problem on other people's threads is generally considered bad taste...

**Comment by rilwis** [comment]
I think we can close this thread :)

**Comment by ZeroBeeOne** [comment]
@rilwis 
Wait up - this problem is not resolved! the other guy spamming his issue into here is irrelevant but taxonomy_advanced fields still do not work on MB Term Meta.

**Comment by rilwis** [comment]
@ZeroBeeOne I've just updated the MB Term Meta with a fix for `multiple` param. Please update.

**Comment by rilwis** [comment]
I will close this issue. Feel free to re-open it if you still see the bug.

**Comment by ZeroBeeOne** [comment]
Only just had the chance to test this today, but it's working great now, thanks
