### ISSUE TITLE
image fields in mb_term_meta not working

### ISSUE THREAD

**Issue by ZeroBeeOne** [rilwis/meta-box#931]
Hi there,

on a separate site and codebase to the other mb_term_meta issue I have raised, the image field appears to have stopped working as of Wordpress 4.5.3 update. Images are not saved, though blank entries appear to be created for each image that was added. Was a bit of a disaster for us as it also meant that existing images were lost when any other update was made on a term (which is how the issue was first discovered). Was able to resolve immediately by swapping to image_advanced fields, which work still and preserves the existing images that were previously saved in the image field (as long as the term had not been updated in the interim).

The field in this case was about as simple as it could be: 
```
array(
	'name' => 'Precinct Logo',
	'id'   => 'precinct_logo',
	'type' => 'image',
),
```

The issue was first noticed on Metabox 4.8.5, but an update to 4.8.7 did not resolve. MB Term meta was already at 1.0.2.

**Comment by rilwis** [comment]
Hi,

I’ve just found a bug with MB Term Meta plugin and released the fix today. Please update the plugin and let me know if this bug still happens.

Thanks
Anh

**Comment by ZeroBeeOne** [comment]
No joy unfortunately. The system file prompt is shown when clicking 'Choose File', and I didn't see any errors in the php log when submitting, however the meta stored against the term would seem to be the filename of the image (eg. 'blue.png'), rather than it's attachment ID or full path (either of which could be useful, though I believe an array of string ID's is the expected output). The image also does not appear to be added to the media library, as far as I can tell, so it seems to just be storing the filename as though the file input is a text input, and doing nothing more?

image_advanced still works fine with the update though, for what it's worth though.

**Comment by funkedgeek** [comment]
What version of WP are you using?  I believe WordPress just added term meta a few versions ago

**Comment by ZeroBeeOne** [comment]
@funkedgeek - As per original post, Wordpress 4.5.3

**Comment by funkedgeek** [comment]
Found the reason: image uses post_edit_form_tag which isn't used in term pages so images don't get uploaded properly.  Please use image_advanced for the time being until we get a solution

**Comment by ZeroBeeOne** [comment]
Sweet, thanks for looking into this. Can confirm that image_advanced field works as a workaround, in my environment at least.
