### ISSUE TITLE
plupload_image show first image only.

### ISSUE THREAD

**Issue by koentjuh1** [rilwis/meta-box#932]
Hello,

I know how to show all images uploaded via plupload_image:
http://pastebin.com/98ZZBvSZ

But what i want is only to show the first image.. is this possible?

WP version: 4.5.3
Metabox.io version: 4.8.7

Regards koen.

**Comment by Infolu** [comment]
Hi Hello , you can use output limit
example follows

$images = rwmb_meta( 'omheiningtype1_image', 'type=image&size=omheiningsize&limit=1' );

greetings
