### ISSUE TITLE
Issue with Geolocation plugin

### ISSUE THREAD

**Issue by sebng87** [rilwis/meta-box#933]
Hi guys,

I am unsuccessfully trying to use the metabox geolocation plugin (1.0.1). I m constantly getting the following error : js?libraries=places&API_KEY=MY_API_KEY:31 Google Maps API error: MissingKeyMapError  

I have already : 
- add the 'gmap_api_params' filter, filled with my own api key
- overwrite the 'api_key' param in map.php
- replace the map.js with the current master version 

Any ideas on what could block here ? 

Thank you

**Comment by tanng** [comment]
Dear Seb,

We've resolved this bug on Github and will release on wordpress.org shortly. Please download `dev-master` version on Github if you need to fix it immediately :)
