### ISSUE TITLE
meda data not working in pre-made pages

### ISSUE THREAD

**Issue by atashinbar** [rilwis/meta-box#934]
To clarify the situation I’ve prepared a file and put “functions.php” and “header.php” inside of it. After installing 2016 theme and putting attached files instead of related theme files on a fresh WordPress, if you review “wordpress admin dashboard > pages > sample page” it comes without header but if you enter to page edit and click on update the header appears.
[functions.txt](https://github.com/rilwis/meta-box/files/299805/functions.txt)
[header.txt](https://github.com/rilwis/meta-box/files/299804/header.txt)

**Comment by funkedgeek** [comment]
I don't think this has anything to do with our plugin

**Comment by atashinbar** [comment]
You can check it with my information in default WordPress theme.

**Comment by funkedgeek** [comment]
Have you tried using a child theme?  Are you choosing this file as the template for the page?
