### ISSUE TITLE
Run function on save/update

### ISSUE THREAD

**Issue by wgstjf** [rilwis/meta-box#935]
Hi,

I have a field that defines whether an item is 'Featured'.  There can be only one 'Featured' item so I am looking to call a function when the user updates a custom post with the ID "service_featured' and sets it to 'yes' to enable me to set all other posts' 'service_featured' post meta to 'no'.

Is there a hook that I can use to call this function on the save of this type of custom post (or the specific field)?

Cheers,

Will

**Comment by ZeroBeeOne** [comment]
I'd suggest giving this a try - it's not something baked into Metabox.io, but rather a wordpress core filter: http://hookr.io/filters/update_post_metadata/

You could use it something like this:
```
function filter_update_post_metadata( $check, $post_id, $meta_key, $meta_value, $prev_value ) { 
    if ('YOUR_TARGET_META_KEY' === $meta_key) {
        // Check for other featured posts, update a site option for the currently featured post, whatever else.
        // If you need to change the metadata of other posts here, like removing the 'featured' metadata from them or something
        // You'll need to unhook this callback to prevent infinite recursion. See http://wordpress.stackexchange.com/questions/163859/how-to-use-update-meta-type-metadata-filter-to-modify-meta-value
        // If you want to prevent the default metadata action from being taken (that the value is added to the wp_postmeta table), return false here. Otherwise just return $check and wordpress will continue as normal
        // return false;
    }
    return $check; 
}
add_filter('update_post_metadata', 'filter_update_post_metadata', 10, 5);
```

**Comment by funkedgeek** [comment]
I'm assuming this is solved.  Please re-open if it isn't
