### ISSUE TITLE
Field Type URL - allow values beginning with # (hash)

### ISSUE THREAD

**Issue by wgstjf** [rilwis/meta-box#936]
Hi guys,

It would be great if the URL field type would allow values beginning with a hash symbol as we sometimes need to link to items within a page as well as allow for validated links to other pages.  What do you think?

Cheers,

Will

**Comment by funkedgeek** [comment]
You can use the pattern option in the url field to do this for just those type of hash link.

**Comment by funkedgeek** [comment]
This is the standard behavior of the url key.  Instead of just using hash, use hash with the page its supposed to be used with
