### ISSUE TITLE
Cant display Meta Box Fields using shortcodes

### ISSUE THREAD

**Issue by semuk** [rilwis/meta-box#939]
Hi

I have created 3 metaboxes for {city} {state} {zip}

I want to display the content of these using the shortcode in posts and other places in my theme but cannot get this to work!

Tried these

[rwmb_meta  meta_key="post_city"]

[echo rwmb_meta meta_key="post_city" type="text"]

but no luck...

I havent added anything to the theme functions - please can you help so I can display the content from the fields

Thanks

**Comment by zabestof** [comment]
If you want to echo shortcode content you need to use `echo do_shortcode`

**Comment by rilwis** [comment]
Hi @semuk ,

Please use `echo do_shortcode( '[rwmb_meta meta_key="post_city"]' );`
