### ISSUE TITLE
Translation box items Plupload IMAGE UPLOAD

### ISSUE THREAD

**Issue by Infolu** [rilwis/meta-box#942]
Hello boys,
It is possible to translate the items box Plupload IMAGE UPLOAD? It would be something short of great help.

Grateful
![traduzir](https://cloud.githubusercontent.com/assets/16593922/17587923/a7745302-5fa1-11e6-8c53-0a612c032c45.JPG)

**Comment by ZeroBeeOne** [comment]
This page includes the details of what you'll need to do: https://github.com/moxiecode/plupload/wiki/Plupload-in-Your-Language - as far as I know wordpress doesn't bundle the i18n folder from plupload, so you'll need to download and host the language you need (assuming it's been created already on Transifex), then do something like:

```
function add_plupload_translation($hook) {
    if ( $hook == 'post-new.php' || $hook == 'post.php' ) {
            wp_enqueue_script(  'plupload_translation', get_stylesheet_directory_uri().'/js/plupload/i18n/ka.js', array('plupload') ); // Change ka.js to the translation file you need
    }
}
add_action( 'admin_enqueue_scripts', 'add_plupload_translation', 10, 1 );
```

You may want to add additional checks in, like if you are only loading plupload on a certain custom post type or whatever, but this ought to get you started.

**Comment by rilwis** [comment]
Those texts are translatable by default. However, to make it easier for developers, I've just pushed a commit with new filters to change them:

`rwmb_media_upload_instructions_string`: Filter to change **Drop files here to upload**
`rwmb_media_or_string`: Filter to change **or**
`rwmb_media_select_string`: Filter to change **Select Files**

Enjoy!
