### ISSUE TITLE
Conditional Logic Not hiding or showing

### ISSUE THREAD

**Issue by Muazhesam** [rilwis/meta-box#950]
I am using latest version of metabox.I am trying to use conditional logic with some post formats stuffs.
But the conditioned fields are show when the page is load and don't change with post format change.

My codes are below
`add_filter( 'rwmb_meta_boxes', 'the_foody_post_meta' );

function the_foody_post_meta( $post_meta_boxes ){
	$post_meta_boxes[] = array(
			'title' => __( 'Test Meta Box', 'the_foody' ),
	        'post_types' => 'post',
	        'fields'     => array(
	            array(
	            	'id' => 'video_link',
	            	'name' => __('Upload Your Video Link', 'the_foody'),
	            	'type' => 'text',
	            	'hidden' => array('post-format', 'aside'),
	            	'desc' => __('This link will be used for showing video', 'the_foody'),
            	),
	        ),
	    );

	    return $post_meta_boxes;
}`

**Comment by tanng** [comment]
Sorry, I do support Conditional Logic on website as highest priority and rarely up on Github.

You have missed syntax. Please change post-format to post_format and it will work.
