### ISSUE TITLE
rwmb_meta() not working after update to 4.9 -- or so it seems.

### ISSUE THREAD

**Issue by OneEarthMedia** [rilwis/meta-box#955]
Hi,

A website I've developed completely stopped working after updating to MetaBox 4.9. It seems that none of the fields are being retrieved when using rwmb_meta(). I have some areas of the site that use get_post_meta() instead and those are working fine still.

I get no PHP errors aside from a few notices where I'm pulling other data using values from meta fields.

I had a look at the changelog but couldn't read out anything that could cause this issue. I've restored the previous version of MetaBox for now and the site is working fine again.

Any ideas what could be causing this?

Thanks a lot for your help!

Herman

**Comment by d2roth** [comment]
How are you registering your metaboxes? I had a similar issue after an upgrade to 4.8.0. Basically, the rwmb_meta function was modified a little so it needs access to the array that creates the metaboxes. You can read more about the changes on their site [https://metabox.io/docs/get-meta-value/#section-historical-note](https://metabox.io/docs/get-meta-value/#section-historical-note)

**Comment by funkedgeek** [comment]
Also please include code so we can test it

**Comment by OneEarthMedia** [comment]
I'm using the `rwmb_meta_boxes` hook to register the metaboxes.

I have a simple template check that could be causing the problems:

```
add_filter( 'rwmb_meta_boxes', 'nuyu_homepage_meta_boxes' );
function nuyu_homepage_meta_boxes($meta_boxes) {
    $meta_boxes;
    
    // Get Post ID
    if (isset( $_GET['post'])) {
        $post_id = $_GET['post'];
    } elseif (isset($_POST['post_ID'])) {
        $post_id = $_POST['post_ID'];
    } else {
        $post_id = get_the_ID();
    }
    
    // Only show these fields when the homepage template is assigned to the page
    if (isset($post_id)) {
        $page_template = get_post_meta($post_id, '_wp_page_template', true);
        if($page_template == 'template-homepage.php' ) {
            // Remove the default editor
            remove_post_type_support('page', 'editor');
            
            // Add the custom meta boxes
            // Homepage Welcome Section
            $meta_boxes[] = array(
                'title'      => __( 'Header', 'nuyu' ),
                'post_types' => 'page',
                'fields'     => array(
                    array(
                        'id'   => 'nuyu_homepage_heading',
                        'name' => __( 'Welcome Heading', 'nuyu' ),
                        'type' => 'text',
                    ),
                ),
            );
        }
    }
    
    return $meta_boxes;

}
```

**Comment by OneEarthMedia** [comment]
Thanks d2roth for pointing out that `rwmb_meta() `has to access the arrays that create the metaboxes. That was exactly the problem. I made the code skip the template check if it's not the admin and everything is back to normal again.

Previously using `get_the_ID`, it was able to identify the template at the front-end and gain access to the arrays. I wonder why that doesn't work anymore?

This new solution seems more bulletproof anyway.

Thanks again for the help!

Herman
