### ISSUE TITLE
page template 

### ISSUE THREAD

**Issue by robbisy** [rilwis/meta-box#956]
Not an issue but a question is it possible to add a Select dropdown with the page template thanks to metabox fields ?
![02-page-attributes-opt](https://cloud.githubusercontent.com/assets/18592516/18351822/00396ef0-75dc-11e6-8d72-f4ed6c9c00dc.jpg)

The goal is to populate the custom page with the info in the metabox

**Comment by rilwis** [comment]
You can use `select` field with [`get_page_templates()`](https://codex.wordpress.org/Function_Reference/get_page_templates) function.
