### ISSUE TITLE
Date and time fields not properly saved

### ISSUE THREAD

**Issue by Jordi-m** [rilwis/meta-box#957]
Hi,

After the latest update (installed yesterday evening) I'm experiencing issues with the 'date' and 'time' field. I have the following 'date' field defined:

		array(
			'name'		=> 'Event date',
			'id'		=> "event_date",
			'type'		=> 'date',
			'js_options' => array('dateFormat' => 'dd/mm/y', 'showButtonPanel' => true),
			'std'		=> date('d/m/y'),
			'desc'		=> 'Format: day/month/year (dd/mm/yy)',
		)

When I press 'Save draft' or 'Publish' the post, the value is not fully saved, only the first numer of the date string is stored in the database. This also applies to the 'time' field.

Example: When I selected '09/09/16' via the date picker plugin, after saving the page, I only see '0'. Directly reading out the value from the database also only returns the '0'.

As far as I could see the options did not change in the online docs (http://metabox.io/docs/define-fields/#section-date)? Also the js_options should be unchanged.

Did I miss something (new) or is this a plugin bug? Thanks in advance.

**Comment by funkedgeek** [comment]
It works as intended on my computer.  Can you disable all other plugins to see if that helps?  Also please update to latest version of the plugin on github

**Comment by Jordi-m** [comment]
I have a duplicate setup running with the same plugins, but kept it as Metabox 4.8.7. That one still works fine. I'll try to do some debugging to find out if the client sends the wrong value, the backend never receives/processes it, or maybe its read in a wrong way from the database. I'll try to see what I can find...

**Comment by rilwis** [comment]
I just tested again with your code and it seems to work with me.

Can you check the HTML output of the field, especially the `name` attribute of the input? If the value is not sent, then that might be the reason. Also, please check if there is any other field with the same ID?

**Comment by Jordi-m** [comment]
@rilwis The HTML seems to be fine (also compared to the other version that works just fine):

    Broken version:
    <input type="text" name="barendrechtnu_datum_gebeurtenis" id="barendrechtnu_datum_gebeurtenis" class="rwmb-date hasDatepicker" size="30" data-options="{&quot;timeFormat&quot;:&quot;HH:mm&quot;,&quot;separator&quot;:&quot; &quot;,&quot;dateFormat&quot;:&quot;dd\/mm\/y&quot;,&quot;showButtonPanel&quot;:true}">

    Working version:
    <input type="text" name="barendrechtnu_datum_gebeurtenis" id="barendrechtnu_datum_gebeurtenis" class="rwmb-date hasDatepicker" size="30" data-options="{&quot;timeFormat&quot;:&quot;HH:mm&quot;,&quot;separator&quot;:&quot; &quot;,&quot;dateFormat&quot;:&quot;dd\/mm\/y&quot;,&quot;showButtonPanel&quot;:true}">

Also, the value is send with the correct name to the backend.

Could you give be a hint about which piece of the code triggers the 'save' method in your plugin? That way I can track down the part that does something weird with my (posted) value. Only for date and time fields I have this issue (strings do not have this issue).

**Comment by Jordi-m** [comment]
Tips/suggestions about which code triggers the 'save' method in the meta-box plugin are still very welcome. I did not find the cause of the problem yet. I'm currently considering rolling back to a working version untill the cause is found.

**Comment by funkedgeek** [comment]
Are you using any iof our other plugins at all?

**Comment by Jordi-m** [comment]
@funkedgeek No, just Meta Box.

**Comment by funkedgeek** [comment]
What plugins do you have active and what theme are you using?

**Comment by Jordi-m** [comment]
@funkedgeek Plugins: Google Auth + Meta Box + OB page Numbers + Social + Wordpress Backup to Dropbox. (Note: Running the same setup on together with Meta Box 4.8.7 works without a problem).

I'm not using any front-end template. I only use the Wordpress administration area.

**Comment by funkedgeek** [comment]
What is code you are using for the meta box itself?  I'm trying all options because I can't replicate this.  I've trying your code and the field works fine for me so I need everything you got so I can try to replicate this

**Comment by Jordi-m** [comment]
@funkedgeek The field code I'm using is in the issue text itself. I'm not doing enything else, just a lot of meta box fields, where only this one is broken.

I appreciate your help in trying to replicate, but since no other users seem to have the same issue, it might be related to some specific piece of my setup that I can't figure out.

It's no problem for me to do some debugging myself, It's just that I'm stuck in the save() method, it's just returning the wrong value there already (and thus storing it wrong). If you have any indication for me on where to look (any code that runs before save()), that would be really helpful for me to find the cause and provide a fix if needed.

**Comment by Jordi-m** [comment]
@funkedgeek @rilwis Just found out the value is 'broken' when this code ran:

				echo $field['id'].' - '.$new.'<br />';
				$new = RWMB_Field::call( $field, 'value', $new, $old, $post_id );
				$new = RWMB_Field::filter( 'sanitize', $new, $field );
				echo $field['id'].' - '.$new.'<br />';

Output:

    datum_gebeurtenis - 17/09/16
    datum_gebeurtenis - 1

So I'll try to see what I find in value and/or sanitize...

**Comment by funkedgeek** [comment]
My guess is the filter

**Comment by Jordi-m** [comment]
@funkedgeek Apparently $new['timestamp'] in fields/datetime.php is set to 1, and thats why 1 is used as return value... Any thoughts on this? Is timestamp supposed to be 1?

	public static function value( $new, $old, $post_id, $field )
	{
		echo 'TS: '.$new['timestamp'].'<br />';
		echo 'NW:'.$new.'<br />';
		return isset( $new['timestamp'] ) ? $new['timestamp'] : $new;
	}

Output:

	TS: 1
	NW:17/09/16
	datum_gebeurtenis - 1

**Comment by funkedgeek** [comment]
Wierd, considering the timestamp code shouldn't even be used in your case

**Comment by funkedgeek** [comment]
Just put out a fix.  please redownload from github and give it a try

**Comment by Jordi-m** [comment]
@funkedgeek Awesome, that small patch solved the issue. Thanks for the help!

**Comment by lopinsjk** [comment]
Hello,

I have the same issue and I have resolved with the replace above. What happen if I update the plugin next time?

Thank you
