### ISSUE TITLE
Metabox 4.9 incompatibility with WordPress 4.6.1

### ISSUE THREAD

**Issue by JettH** [rilwis/meta-box#958]
All submenus rendered inactive, also lost call outs in body of page text, but not certain what feature of Metabox was being used. Also made Gravity Forms Plugin for Mailchimp hose the entire website, would not produce valid HTML.

4.8.7 works great, does not cause problems.

Here is code for the header template with menus that no longer work. Not a WordPress expert, inherited project. If other files would be of help, let me know.

```php
<?php
  /*
  * Theme Header file
  * contains opening <body> tag and the <header>
  */
  $options = get_option( 'bamboo_theme_options' );
?>
<?php get_template_part('head'); ?>

  <div class="container">
    <header class="page-header" role="banner">
      <div class="content-row header-top">
        <?php get_search_form(); ?>
        <ul class="super-nav menu">
          <li><a href="<?php echo $options['bill_link']; ?>">Pay Bill</a></li>
          <li class="contact-link"><a href="<?php echo $options['contact_url']; ?>">Contact Us</a></li>
          <li class="phone"><span><?php echo $options['phone']; ?></span></li>
          <li class="account"><a href="https://myaccount.tlie.org/" target="blank">My Account</li>
        </ul>
        <a class="logo" href="<?php echo home_url(); ?>/"><?php bloginfo('name'); ?></a>
        <a href="#" class="mobile-menu-trigger"><span class="menu-icon"></span>Menu</a>
      </div><!-- /.header-top -->
      <nav class="nav-main row" role="navigation">
        <?php
          // need custom menu structure, so doing this manually
          $menu_name = 'main_menu';
          if ( ($locations = get_nav_menu_locations()) && isset($locations[ $menu_name ]) ):
            $menu = wp_get_nav_menu_object( $locations[ $menu_name ] );
            $menu_items = wp_get_nav_menu_items($menu->term_id);
        ?>
        <div class="main-menu">
          <ul class="menu">
          <?php foreach ( (array) $menu_items as $key => $menu_item ):
            $title = $menu_item->title;
            $url = $menu_item->url;

            // check if on current page/page child
            $current_url = $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'];
            $url_parts = explode('//', $url);
            $is_current_link = strpos($current_url, $url_parts[1]) !== false;

            // get dropdown menu id
            $page_id = $menu_item->object_id;
            $dropdown_menu = rwmb_meta('mb_page_menu', '', $page_id);
          ?>
            <li role="presentation"<?php if($dropdown_menu){ echo ' class="js-dropdown-trigger js-hover"'; } ?>>
              <a href="<?php echo $url; ?>" class="primary-link<?php if($dropdown_menu) { echo ' has-dropdown js-dropdown-trigger js-hover'; } if($is_current_link) { echo ' current'; } ?>" role="menuitem"><?php echo $title; ?></a>
              <?php
                if ($dropdown_menu) {
                  wp_nav_menu(array('menu' => $dropdown_menu, 'menu_class' => 'menu dropdown-primary js-dropdown' ));
                }
              ?>
            </li>
          <?php endforeach; ?>
          </ul>
        </div>
        <?php endif; ?>
        <div class="nav-callout">
          <a href="<?php echo $options['apply_url']; ?>" class="button"><span>Apply</span></a>
        </div>
      </nav><!-- /.nav-main -->
    </header>

    <?php if (!is_front_page()) { get_template_part('templates/page-header'); } ?>
```

**Comment by JettH** [comment]
Sorry, the tags are incompatible with posting code. Will upload a file...

**Comment by JettH** [comment]
Text of file header.php.
[header.txt](https://github.com/rilwis/meta-box/files/464710/header.txt)

**Comment by tigredanky** [comment]
I'm having this same issue on my http://havcapital.com site. Another admin updated everything to the latest (for plugin and for WP core). Any solutions y'all getting? Images are displaying but text is not rendering on the front end.

**Comment by rilwis** [comment]
Hey guys, can you please check with the recent fix above?

Thanks
Anh

**Comment by tigredanky** [comment]
Looks like that solved it. Thanks, @rilwis!

**Comment by Jordi-m** [comment]
I just installed this latest quickfix and now ALL my meta-box fields are not showing up in the WP admin... Anyone else with the same issue?

**Comment by amilham** [comment]
That latest commit hasn't solved the problem I'm seeing. Using Metabox 4.9 with WordPress 4.6.1 is completely broken on my site - the boxes don't even appear on the custom post type I have set up. I reverted to Metabox 4.8.7 and everything is fine again.

**Comment by Jordi-m** [comment]
@amilham Check out your plugins page, for some reason this update disabled the Metabox plugin. I quickly reported the same issue, but then sound it the plugin was just disabled for some unknown reason.

cc @rilwis

**Comment by amilham** [comment]
@Jordi-m Thanks, I did check that and the plugin was active. Seems to be something that changed in 4.9.

**Comment by rilwis** [comment]
@amilham Have you tried version 4.9.1?

**Comment by funkedgeek** [comment]
@amilham P{lease post the code you are using to create the meta boxes so we can debug them

**Comment by andreas-manusm** [comment]
4.9.1 version made my tineMCE on posts.php unusable, just for posts not for sites; The editor had no buttons, made switching visual/code inactive; Text was only visible when selecting CMD+all  in the form. Hope this helps.

**Comment by rilwis** [comment]
@andreas-manusm Please post your code you're using to register meta boxes.

**Comment by andreas-manusm** [comment]
@rilwis Oh, I use a professional theme that was working properly before. I will adress the developer to get in touch with you as I found many places where metabox is used. Many thanks so far.

**Comment by IchFloque** [comment]
I also have a problem with 4.9 that was not there in 4.8.7
When I go to edit a wordpress page (not a post) the editor for the content doesn't work any more.
I register the boxes with $groupsBig = rwmb_meta( 'box_group_big' );

**Comment by JettH** [comment]
4.9.1 is working for us. Thanks. Will show as working on the WordPress page.

**Comment by billreed85** [comment]
I started having issues on my local install after the move from 4.8.7 to 4.9+. The issue sounds similar to @amilham. I was able to find the specific commit that started causing issues: 4c6f9e0 (specifically what was removed on lines 314-323).

The issue that's happening is any post type that has a meta box registered doesn't fully load in the backend of wordpress and leaves off all the metaboxes.

**Comment by sungraiz** [comment]
Hi,
Image advanced field shows only one image, no matter how many images are defined in max_file_uploads setting. See the below video

http://jmp.sh/IHZPQnx

I have also update your plugin to latest version but it didn’t fix the issue.

Kindly help us asap because our clients getting angry on us.

Thanks

**Comment by funkedgeek** [comment]
@billreed85 if you re-add the code does it work properly?

**Comment by billreed85** [comment]
@funkedgeek Upon further testing, that brings back some of the functionality, but not all of it. I added back in all the code that was removed in the commit I listed above, and it made the meta boxes appear, and function, but it is missing some of the meta boxes that are setup in my code. So, that isn't an actual fix.

**Comment by rilwis** [comment]
@billreed85 Do you use any premium extensions? If yes, can you update them all to the latest versions?

**Comment by billreed85** [comment]
@rilwis That did it! I totally forgot about Meta Box Group. That's updated and everything is working as intended. Thanks!

**Comment by amilham** [comment]
This problem is still there in 4.9.2. Client updated the plugin and suddenly the site stopped working again (it's reliant on meta boxes).
