### ISSUE TITLE
Incorrect dependency name – jquery-validate

### ISSUE THREAD

**Issue by steve-vancouver** [rilwis/meta-box#961]
There’s an incorrect dependency name on line 46 of:
/plugins/meta-box/inc/validation.php

Currently is:
`wp_enqueue_script( 'rwmb-validate', RWMB_JS_URL . 'validate.js', array( 'jquery-validate' ), RWMB_VER, true );`

Should be:
`wp_enqueue_script( 'rwmb-validate', RWMB_JS_URL . 'validate.js', array( 'jquery-validation' ), RWMB_VER, true );`

**Comment by rilwis** [comment]
Thanks for reporting. This is fixed in #959
