### ISSUE TITLE
Incorrect URL to plugin assets when included in a theme using a symlinked directory

### ISSUE THREAD

**Issue by abarani** [rilwis/meta-box#962]
Similar issue as #825 but with meta-box included in a theme.

#### In brief:
- We use capistrano for deployment.
- The theme directory is symlinked to the releases directory.
- We're using a theme which includes meta-box and some extensions ([Real Homes](https://themeforest.net/item/real-homes-wordpress-real-estate-theme/5373914)).

#### Issue:
In the admin area URLs for js and css files are showing up with a full server path instead of the correct url.

---

I tracked down the issue to the `get_path` method of the `RWMB_Loader` class not accounting for a symlinked theme folder and assuming it's a child of `WP_CONTENT_DIR`.

I'm adding a pull request for more details.

**Comment by rilwis** [comment]
Thank you very much for the Pull Request. I'll close this issue and let's work on the PR instead :)
