### ISSUE TITLE
Image advance field is not saving multiple images

### ISSUE THREAD

**Issue by sungraiz** [rilwis/meta-box#964]
Hi,
Image advanced field shows only one image, no matter how many images are defined in max_file_uploads setting. See the below video

http://jmp.sh/IHZPQnx

I have also update your plugin to latest version but it didn’t fix the issue.

Kindly help us asap because our clients getting angry on us.

Thanks

**Comment by funkedgeek** [comment]
Please post all the code you use to create the meta box and any other sister plugins that you are using.

**Comment by sungraiz** [comment]
Hi,
    I have uploaded the config file. You can see the plugins list in below screenshot.

https://drive.google.com/a/inspirythemes.com/file/d/0B53hX4hWJvZ3TUZscXFnNk9KTDg/view?usp=drivesdk

FYI: I have checked it after disabling all plugins but the issue remains.

Kindly help us asap.

Thanks
[config-meta-boxes.zip](https://github.com/rilwis/meta-box/files/478206/config-meta-boxes.zip)

**Comment by rimkashox** [comment]
Same problem here, after saving only one image remains... Any fix in sight ?

**Comment by funkedgeek** [comment]
Please post your version of WordPress and the version of the plugin you have installed.  Please make sure that both are up to date.  I can't replicate the issue.

**Comment by rimkashox** [comment]
Hey @funkedgeek, thanks for your fast reply! All latest versions.. Done for you a 3 minutes demo in HD (video is unlisted so only you guys can see it).. Hope this helps! Also @sungraiz, as the theme owner, please give him access to the theme for debug purposes! Thanks so much to all of you for your help.. https://www.youtube.com/watch?v=BYLi_qcnK9U

**Comment by funkedgeek** [comment]
Please post the code for the meta box.

**Comment by Gnodesign** [comment]
I have the same issue. Did you guys find any fix for this issue?

**Comment by funkedgeek** [comment]
Please post your code and a list of all your plugins.  In the past, this
issue was due to filters from other plugins

**Comment by Gnodesign** [comment]
Hi @funkedgeek thank you very much for your response.

It seems another plugin was causing the issue. Everything is working great now.

Thank you very much! :)
