### ISSUE TITLE
MB Settings and get_plugin_data()

### ISSUE THREAD

**Issue by wgstjf** [rilwis/meta-box#968]
Hi guys,

No issues with plugin just looking for a bit of advice which I hope you can help with.

I am using MB Settings Page to create the options pages for a custom plugin.  One of my metaboxes contains reference to the plugin's version which is a defined constant called WPJ_PLUGIN_VERSION.

This constant gets set by a function that is called on 'admin_init' and uses the get_plugin_data() function as follows: 

```php
function indigo_wpj_define_version() {
	/* Set plugin version data for use elsewhere in the plugin */
	if (!defined( 'WPJ_PLUGIN_VERSION' )) {
		if ( function_exists( 'get_plugin_data' ) ) {
			$plugin_data = get_plugin_data( __FILE__ );
		  $plugin_version = $plugin_data['Version'];
			define( 'WPJ_PLUGIN_VERSION', $plugin_version );
			//echo 'WPJ_PLUGIN_VERSION: '.WPJ_PLUGIN_VERSION;  //DEBUG
		}
		else { // If the function get_plugin_data does not exist, return empty array
		}
	}
}
add_action( 'admin_init', 'indigo_wpj_define_version' ); // Hook plugin admin initialization
```

My issue is that is believe that the filter rwmb_meta_boxes is being called before the plugin can define the version and as such the following code:

```php
echo '<p>Version: '.WPJ_PLUGIN_VERSION.'<p>'
```
Simply returns: **Version: WPJ_PLUGIN_VERSION**.  The WP function get_plugin_data() seems to only be able to be called quite late in the initialization so prevents me from setting any earlier.

The Debug line in the function above enables me to see that the constant has been set correctly, I just can't access it within one of my meta boxes.

Any help would be greatly appreciated.

Cheers,

Will

**Comment by rilwis** [comment]
Hi Will,

You're right about the order of execution. The `rwmb_meta_boxes` are executed in `init` hook which runs before `admin_init`. I suggest you make a small change to the function `indigo_wpj_define_version` by adding this line at the beginning of the function:

```php
include_once APSPATH . '/wp-admin/includes/plugin.php';
```

Then call the function asap, e.g. don't call it on `admin_init`. Then the plugin constants will be available everywhere.

Cheers
Anh

**Comment by wgstjf** [comment]
Anh,

That's great! Works perfectly, thank you...in case anyone else is looking for the completed solution this is what the final code looks like
```php
function indigo_wpj_define_version() {
		if ( !function_exists( 'get_plugin_data' ) ) {
			include_once ABSPATH.'/wp-admin/includes/plugin.php';
		}
			$plugin_data = get_plugin_data( __FILE__ );
		  $plugin_version = $plugin_data['Version'];
			define( 'WPJ_PLUGIN_VERSION', $plugin_version );
}
indigo_wpj_define_version();
```

Cheers,

Will
