### ISSUE TITLE
Fatal error in options page 4.8.7 > 4.9.2

### ISSUE THREAD

**Issue by cedric-dagherir** [rilwis/meta-box#969]
Hi,
I tried to update metabox plugin to improve WPML compatibility, but I got a fatal error on options pages.

`Fatal error: Uncaught Error: Call to undefined method RW_Meta_Box::get_class_name() in /home/viragegr/new-viragegroup/wp-content/plugins/mb-settings-page/inc/settings-page-meta-box.php:105 Stack trace: #0 /home/viragegr/new-viragegroup/wp-includes/plugin.php(291): MB_Settings_Page_Meta_Box->field_meta(Array, Array) #1 /home/viragegr/new-viragegroup/wp-content/plugins/meta-box/inc/field.php(533): apply_filters_ref_array('rwmb_field_meta', Array) #2 /home/viragegr/new-viragegroup/wp-content/plugins/meta-box/inc/field.php(40): RWMB_Field::filter('field_meta', Array, Array, true) #3 /home/viragegr/new-viragegroup/wp-content/plugins/meta-box/inc/field.php(474): RWMB_Field::show(Array, true) #4 /home/viragegr/new-viragegroup/wp-content/plugins/meta-box/inc/meta-box.php(178): RWMB_Field::call('show', Array, true) #5 /home/viragegr/new-viragegroup/wp-admin/includes/template.php(1045): RW_Meta_Box->show(NULL, Array) #6 /home/viragegr/new-viragegroup/wp-content/plugins/mb-settings-page/inc/settings-page.php(145): do_meta_boxes(Obje in /home/viragegr/new-viragegroup/wp-content/plugins/mb-settings-page/inc/settings-page-meta-box.php on line 105`

Any idea ?

**Comment by rilwis** [comment]
Please update the Settings Page extension to the latest version.

**Comment by cedric-dagherir** [comment]
Thanks Rilwis !

My mistake... I have not had the reflex
