### ISSUE TITLE
Fatal Error when updating to latest version

### ISSUE THREAD

**Issue by microcurse** [rilwis/meta-box#970]

**Comment by microcurse** [comment]
Fatal error: Call to undefined method RW_Meta_Box_User::get_fields() in /home/content/a2pnexwpnas03_data01/86/3452586/html/wp-content/plugins/roker-loader/meta-box/extensions/user_meta/meta_box_user.php on line 40

meta_box_user.php line 40:

             // Add additional actions for fields
             $fields = self::get_fields( $this->fields );
             foreach ( $fields as $field )
             {
                 call_user_func( array( self::get_class_name( $field ), 'add_actions' ) );
             }

**Comment by robertomf** [comment]
SAME PROBLEM HERE!!! :S 

Any way to solve it?

**Comment by rilwis** [comment]
Hi, please update the [MB User Meta](https://metabox.io/plugins/mb-user-meta/) to the latest version. The code above looks quite different in the official release.
