### ISSUE TITLE
plupload image - issues if post is updated while field is loading

### ISSUE THREAD

**Issue by ZeroBeeOne** [rilwis/meta-box#972]
Hi there,

Just reporting an issue with usage of the `plupload_image` field type, in a very specific circumstance.

The code for the metabox in question is below, though I don't believe it's directly related to the issue:

```
$meta_boxes[] = array(
    'id' => 'cpt-details',
    'title' => 'Post Gallery',
    'pages' => array('food'),
    'context' => 'normal',
    'priority' => 'default',
    'fields' => array(
        array(
            'name' => 'Images',
            'desc' => 'Upload your photos by dragging or pressing the button inside the box above. The maximum size for each image is 1200x1200 pixels.',
            'id' => $prefix . 'cpt_gallery',
            'type' => 'plupload_image'
        ),
    )
);
```

In order to reproduce this issue, the post edit page and the upload field must take a few moments to load - I cause this by including a decent amount of copy in the WYSIWYG (I've used 10 paragraphs of Lorem Ipsum, with an 600x600 jpg image between each), and uploading a very large image to the field (I used http://edmullen.net/test/rc.jpg as a test image. The server and Wordpress config allows for uploads of this size).

When I initially publish the post, eventually I am redirected back to the post edit page. After a few moments, the image is loaded into the field as expected (I believe this assures that the server/Wordpress config is not disagreeing with the size or type of the file - it has clearly been successfully uploaded at this point).

If I then perform a hard refresh and, immediately after the refreshed page renders, I click the update button (while below, the `plupload_image` field is shown, but does not yet show the uploaded image), when the edit page loads again the image has been removed from the post. It still exists in the Media Library, but it's ID is no longer stored in the metadata for the post.

Now, I've outlined a particularly detailed reproduction plan in this case, but I originally encountered this issue as a report from users - for them, they had drafted posts related to an e-newsletter waiting in the backend, and at a set time were opening them up and publishing them, not performing any updates or anything else that would have them leave the tab open long enough for the images to load, and were finding that suddenly these published posts were lacking images. So this is definitely a problem that can occur in normal usage.

I am aware there are a number of workarounds available to this - I can advise the users to use the Bulk Edit functionality to publish the posts, meaning the metabox never attempts to load or overwrite the gallery metadata, I can advise the users to use a Post Scheduling plugin, once again meaning that the posts will be published without interaction from metabox. What I've actually done in the meantime is advise users to make sure they are waiting to see all the gallery images appear before clicking Publish/Update. However I think it should be expected that the field will not remove images from the post metadata in this circumstance. 

I would suggest that maybe rather than/as well as storing the id's in the `value` attribute of the field, dummy html elements be created for each image in the media field `html()` method, which would submit their ID value even if an image has not been loaded into them yet. Or alternatively catching the form submit event in the controller and checking if images have finished loading yet, and creating hidden inputs for not yet loaded images. Or I don't know, there are probably other, better ways for this to happen given your architecture.

**Comment by funkedgeek** [comment]
This should be fixed in version 4.11.  Please test and let us know if it works now
