### ISSUE TITLE
How we make required field?

### ISSUE THREAD

**Issue by rvpatel** [rilwis/meta-box#973]
How to manage filed show hide based on checkbox?
How to set date field with today's date and end time  for event post end date field

**Comment by rilwis** [comment]
1) To make field required, try using [custom attributes](https://metabox.io/docs/custom-attributes-for-inputs/) or [validation](https://metabox.io/docs/validation/).

2) To hide a field based on checkbox, please use [Conditional Logic extension](https://metabox.io/plugins/meta-box-conditional-logic/) (premium)

3) To set the default value for date/time, please try the `std` param. See more [here](https://metabox.io/docs/define-fields/)
