### ISSUE TITLE
Date input issue

### ISSUE THREAD

**Issue by clairetnet** [rilwis/meta-box#975]
Hi, 
With the last version of the plugging, when we save a date input, datas are not correctly saved. 
Only the first number of the year is saved ?
Thanks

**Comment by d2roth** [comment]
What code are you using to register your meta boxes?
Also a similar issue was reported over on issue #957. It might help you.

**Comment by funkedgeek** [comment]
Please download the latest version of the plugin on Github.  It has a fix for this

**Comment by clairetnet** [comment]
Thank you the github resolved this issue ;)
I think it should be great to fix it also on the wordpress plugin distribution
