### ISSUE TITLE
User field : display [Name Firstname] instead of [display_name]

### ISSUE THREAD

**Issue by Sinusite** [rilwis/meta-box#976]
Hi,
What is the best syntax or hook (if there any) to replace the default [display_name] options by [Name FIrstname] in a specific select_advanced of users ?
Thank You !

**Comment by rilwis** [comment]
@funkedgeek Can you help?

**Comment by funkedgeek** [comment]
Here is the rundown on how to use the new filters:
If you are using a field called `some_user`:

```
function some_user_filter( $label, $field, $user )
{
	return $user->first_name ;
}

add_filter( 'rwmb_some_user_choice_label', 'some_user_filter', 10, 3);
```

There are 3 new filters:
- `rwmb_choice_label`, which will effect labels for all choice fields
- `rwmb_{$field_type}_choice_label`, which will effect all of a particular type
- `rwmb_{$field_id}_choice_label`, which will effect all of a the field with a particular id

The filters take 3 arguments: the label, the field array and the objecy( post, user or term)

**Comment by Sinusite** [comment]
Great. Thank you.

**Comment by stevygee** [comment]
I saw these filters in the documentation and tried to use them without success. It seems they have been removed (accidentally?) in https://github.com/wpmetabox/meta-box/commit/ee6aaffcf071423b6c4ae0152198e685159901f2
