### ISSUE TITLE
Fatal error: Call to undefined method RW_Meta_Box::get_class_name()

### ISSUE THREAD

**Issue by robertomf** [rilwis/meta-box#978]
Huge issue with this plugin!!!! 

I'm using **WP Soccer** (Themeforest theme) and it has **Meta Box and Meta Box Group** plugins for some custom fields. I updated Wordpress and everything and now I have this error so I can't edit some Wordpress pages: 

“**Fatal error: Call to undefined method RW_Meta_Box::get_class_name() in /home/wwwrcf/public_html/wp-content/plugins/meta-box-group/class-rwmb-group-field.php on line 63**”

```
foreach ( $field['fields'] as $child_field )
{
	$child_field['field_name']       = self::child_field_name( $field['field_name'], $child_field['field_name'] );
	$child_field['attributes']['id'] = ( isset( $child_field['attributes']['id'] ) ? $child_field['attributes']['id'] : $child_field['id'] ) . $clone_index;
	call_user_func( array( RW_Meta_Box::get_class_name( $child_field ), 'show' ), $child_field, RWMB_Group::$saved );
}
```

We need to fix this because our client can't work with his website!!! :S

Thanks for your help!

**Comment by rilwis** [comment]
Please just update the Group extension to the latest version. (Or ask the theme developer to update it).

**Comment by robertomf** [comment]
I just have "Meta Box Group" extension in the version 1.1.1, this is not the proper version?

**Comment by rilwis** [comment]
No, the [latest version](https://metabox.io/plugins/meta-box-group/) is 1.1.5.
