### ISSUE TITLE
taxonomy_advanced field does not work with term meta extension

### ISSUE THREAD

**Issue by ZeroBeeOne** [rilwis/meta-box#979]
Hi there,

As reported in #930 , the taxonomy_advanced field does not work on terms (using the mb term meta plugin) when given the option `'multiple' => true` or `'clone' => true`. With the former, the field is not saved and generates an error:

```
[Tue Sep 27 14:19:49.640700 2016] [:error] [pid 1589] [client 192.168.2.237:57581] PHP Stack trace:, referer: http://local.dev.com/test-site/wp-admin/term.php?taxonomy=suburb&tag_ID=6&post_type=post&wp_http_referer=%2Ftest-site%2Fwp-admin%2Fedit-tags.php%3Ftaxonomy%3Dsuburb
[Tue Sep 27 14:19:49.640712 2016] [:error] [pid 1589] [client 192.168.2.237:57581] PHP   1. {main}() /var/www/test-site/wp-admin/edit-tags.php:0, referer: http://local.dev.com/test-site/wp-admin/term.php?taxonomy=suburb&tag_ID=6&post_type=post&wp_http_referer=%2Ftest-site%2Fwp-admin%2Fedit-tags.php%3Ftaxonomy%3Dsuburb
[Tue Sep 27 14:19:49.640719 2016] [:error] [pid 1589] [client 192.168.2.237:57581] PHP   2. wp_update_term() /var/www/test-site/wp-admin/edit-tags.php:183, referer: http://local.dev.com/test-site/wp-admin/term.php?taxonomy=suburb&tag_ID=6&post_type=post&wp_http_referer=%2Ftest-site%2Fwp-admin%2Fedit-tags.php%3Ftaxonomy%3Dsuburb
[Tue Sep 27 14:19:49.640734 2016] [:error] [pid 1589] [client 192.168.2.237:57581] PHP   3. do_action() /var/www/test-site/wp-includes/taxonomy.php:3019, referer: http://local.dev.com/test-site/wp-admin/term.php?taxonomy=suburb&tag_ID=6&post_type=post&wp_http_referer=%2Ftest-site%2Fwp-admin%2Fedit-tags.php%3Ftaxonomy%3Dsuburb
[Tue Sep 27 14:19:49.640740 2016] [:error] [pid 1589] [client 192.168.2.237:57581] PHP   4. call_user_func_array() /var/www/test-site/wp-includes/plugin.php:524, referer: http://local.dev.com/test-site/wp-admin/term.php?taxonomy=suburb&tag_ID=6&post_type=post&wp_http_referer=%2Ftest-site%2Fwp-admin%2Fedit-tags.php%3Ftaxonomy%3Dsuburb
[Tue Sep 27 14:19:49.640746 2016] [:error] [pid 1589] [client 192.168.2.237:57581] PHP   5. MB_Term_Meta_Box->save() /var/www/test-site/wp-includes/plugin.php:524, referer: http://local.dev.com/test-site/wp-admin/term.php?taxonomy=suburb&tag_ID=6&post_type=post&wp_http_referer=%2Ftest-site%2Fwp-admin%2Fedit-tags.php%3Ftaxonomy%3Dsuburb
[Tue Sep 27 14:19:49.640751 2016] [:error] [pid 1589] [client 192.168.2.237:57581] PHP   6. MB_Term_Meta_Field::save() /var/www/test-site/wp-content/plugins/mb-term-meta/inc/meta-box.php:101, referer: http://local.dev.com/test-site/wp-admin/term.php?taxonomy=suburb&tag_ID=6&post_type=post&wp_http_referer=%2Ftest-site%2Fwp-admin%2Fedit-tags.php%3Ftaxonomy%3Dsuburb
```

Whereas with the latter option, `'clone' => true`, the add/remove buttons are not rendered, so the clone functionality is not useable.

As per the original report, when `'multiple' => true` is passed, the value received by `MB_Term_Meta_Field::save()` is NOT an array, that can be iterated (as is attempted on line 93), but rather a comma separated string. it would need to be `explode()`'d or otherwise converted to an array before it can be iterated.

This behavior persists using Metabox 4.9.2, MB Term Meta 1.0.4, and is reproduced with no other plugins activated or installed, but has existed since at least Metabox 4.8.7, MB Term Meta 1.0.2 .

Although the previously noted issue (#930) was closed, I do not believe anything ever happened to resolve this issue.

**Comment by rilwis** [comment]
I've checked the code and sadly, the 'clone' is set to `false` in `taxonomy` field (which is reasonable as the values are set as post terms) and inherited in `taxonomy_advanced` (which is incorrect).

**Comment by rilwis** [comment]
I've fixed the `multiple` param. The `clone` will be fixed later in both Meta Box and MB Term Meta. Please update.

**Comment by ZeroBeeOne** [comment]
Update resolved the issue with `multiple`, which was my preferred way anyway, thanks!
