### ISSUE TITLE
Sorting group empty wysiwyg metabox

### ISSUE THREAD

**Issue by cedric-dagherir** [rilwis/meta-box#980]
Hi,

When I sort a group of metabox, I lose the content of my wysiwyg meta (only this type of meta). You can see it on this video : http://tools.dahive.fr/metabox-empty.mp4

Meta Box 4.9.2
Meta Box Group  1.1.15
Meta Box Conditional Logic 1.3.3
MB Settings Page 1.1.4
MB Admin Columns 1.0.1

Thanks for the help !

**Comment by rilwis** [comment]
Currently, the WYSIWYG field doesn't support sorting. It works only with clone :(.

There are various issues related to the DOM/JS that makes the field impossible to be dragged.
