### ISSUE TITLE
Clone not working since 4.9.x

### ISSUE THREAD

**Issue by fredbradley** [rilwis/meta-box#981]
Hello, 

I've noticed that the CLONE feature has stopped functioning properly. 

I rolled back my plugin to [4.9](https://github.com/rilwis/meta-box/releases/tag/4.9) and it's working again. 

But I can't work out what's changed since then that would break it? 

Could you have a look at it!? 👍 

## What's happening?
I click the `+ Add More` button, and a new field appears, however it's got exactly the same name, and id as the first field, and as such also auto populates the same input into those fields. When you go and save it only saves the data from the last element in the clone - obviously, as they were all called the same name so HTTP `$_POST` only thinks there's one, rather than it saving as an array!?

**Comment by lopinsjk** [comment]
I have a similar issue with Meta Box Group plugin:

I click the Add More button, I fill the fields and I click save but only the last group of fields has been saved.

**Comment by graphem** [comment]
Same thing here, also my group field are all readonly and deactivated. I revert back to 4.8.7 and now it is working. I hope there will be a fix soon.

**Comment by lukeragno** [comment]
Having a similar problem. Whenever I try to clone an item the cloned group has the same values as the original, and they cannot be changed.

**Comment by eriktdesign** [comment]
Yep, this has seriously jacked up the admin interface for every site I've built for the last two years. Please fix!

**Comment by rilwis** [comment]
Just fixed it in the version 4.9.4. Please update!

**Comment by fredbradley** [comment]
Thank you. Just updated! 👍

**Comment by graphem** [comment]
This issue seems to be back, I have Group extension 1.2.1 and Metabox 4.10.4
