### ISSUE TITLE
Cannot download the latest version 

### ISSUE THREAD

**Issue by darktemplate** [rilwis/meta-box#984]
Hi, i have bought your plugin long time ago and the only way i have to download it is a direct link from an email sent by Tran Ngoc Tuan Ann:  https://gumroad.com/d/XXXXXXXXXXXX  "Version 1.0.1 with fix for Strict Standards warning. Please update.  (i do not put the link in clear here)
"
 How can i download the latest version as my theme is broken because i need the latest version (Version	1.1.5). On Gumroad i can only  download  V 1.0.7

In case you need it here is the receipt of my command on Gumroad : Meta Box Group
Télécharger
Prix du produit :	$29
TVA (20%):	$5.80
Total de la commande :	$34.80
Passez le mot !	   
Vous avez besoin d'une facture pour ceci ?	Générer

My Name is Simon Rouan and company is 3RAX TEAM

Thanks in advance
Simon Rouan

**Comment by rilwis** [comment]
Hi Simon,

Please create an account on metabox.io with your email used to purchase the product. Then you can download the latest version. For more info, please [read this guide](https://metabox.io/docs/update-extensions/).

**Comment by darktemplate** [comment]
THANKS !

**Comment by darktemplate** [comment]
I have follow the procedure but i got this message when i go to my account : Licenses expired
Your licenses are expired. Please consider extend your licenses by purchasing a new copy of the extensions to get the update.

**Comment by rilwis** [comment]
That means you purchased the extension more than 1 year ago. Each license has 1 year of support and update. Please buy 1 more copy of the extension and then you can register a new account.

**Comment by darktemplate** [comment]
This is not clear when i purchased the 1st copy that it will be limited in 1year for updates ! Support i can understand but i trusted your plugin when i decided to include it with my theme and now you are telling me your practice it to make devs pay every year for the plugins ??? ! It's not fair

**Comment by darktemplate** [comment]
Or you could at list make it clear and visible when user purchase the plugins.

**Comment by rilwis** [comment]
I think I made this very clear in the [FAQ](https://metabox.io/faq/). It's also visible clearly on the extension page: http://prntscr.com/co3f5m

**Comment by darktemplate** [comment]
This is not from where i bought the plugin originally. Not sure what is this link... looks like made it at the last moment and for that purpose

**Comment by darktemplate** [comment]
One year update is really greedy... specially for an add-on. Again when i bought it on the 1st website with gumroad it was not specified... just saying

**Comment by darktemplate** [comment]
Could you please generate exceptionally a coupon i can use on metabox.io ? i am now aware that the update are possible only for 1year. But now me an all the people who bought my theme are stuck with their website because of that

**Comment by rilwis** [comment]
Please drop me an email rilwis[at]gmail.com.
