### ISSUE TITLE
Time field popup displays twice but one is broken.

### ISSUE THREAD

**Issue by d2roth** [rilwis/meta-box#985]
Hey Guys,
The time picker seems to be messed up with WordPress 4.6.1, Meta Box 4.9.4 and Meta Box Group 1.1.5.

Before clicking on the input field: [http://prntscr.com/co6lvx](http://prntscr.com/co6lvx)
After clicking in the input field: [http://prntscr.com/co6le2](http://prntscr.com/co6le2)

Note: the time saved in the database is the one from when I click on the input field.

I register the meta box on the `rwmb_meta_boxes` filter and use the following code for the fields

```PHP
$meta_boxes[]	 = array(
	'id'		 => $prefix . 'other_properties',
	'title'		 => __('Other Properties ', 'textdomain'),
	'post_types' => array(self::$cpt),
	'context'	 => 'normal',
	'fields'	 => array(
		array(
			'name'	 => 'Start Date',
			'id'	 => $prefix . 'start_date',
			'type'	 => 'date',
		),
		array(
			'name'	 => 'Start Time',
			'id'	 => $prefix . 'start_time',
			'type'	 => 'time',
		),
	),
);
```

It was working with Metabox 4.8.7.

I will keep looking into it but any insight would be beneficial.

**Comment by rilwis** [comment]
Please update to v4.9.5 and let me know if it works. The 4.9.3 and 4.9.4 has a bug in the HTML class which might break the JS.

**Comment by d2roth** [comment]
It appears to work now.

Just FYI I did need to grab the plugin from GitHub instead of WordPress repository.
