### ISSUE TITLE
Question Update Term Database

### ISSUE THREAD

**Issue by vanbaodo** [rilwis/meta-box#987]
hi . I am update term child and term parrent from front end in taxonomy-advanced user select_tree. I use wp_set_object_terms but it only update term child parrent . Can you help me

**Comment by rilwis** [comment]
I'm not sure I understand the question. Can you add some details?

**Comment by vanbaodo** [comment]
Hi a . E muốn tạo 1 phần sửa bài ở ngoài frontend . Và e đang gặp rắc rối trong việc update image_advanced. Hiện tại nó chỉ update được ảnh cuối cùng còn lại k hiển thị những ảnh còn lại. Dưới đây là code của  e . Hi vọng nhận được sự giúp đỡ của a . Thanks !
// Insert attachments front end
function wpcads_insert_attachment($file_handler,$post_id,$setthumb='false') {
  // check to make sure its a successful upload
  if ($_FILES[$file_handler]['error'] !== UPLOAD_ERR_OK) __return_false();
  require_once(ABSPATH . "wp-admin" . '/includes/image.php');
  require_once(ABSPATH . "wp-admin" . '/includes/file.php');
  require_once(ABSPATH . "wp-admin" . '/includes/media.php');
  $attach_id = media_handle_upload( $file_handler, $post_id );
  if ($setthumb) update_post_meta($post_id, array_push($post_id,'hrm-images',$attach_id) );
  return $attach_id;
}

///
            if ( $_FILES ) {
                $files = $_FILES['upload_attachment'];
                foreach ($files['name'] as $key => $value) {
                    if ($files['name'][$key]) {
                        $file = array(
                            'name'     => $files['name'][$key],
                            'type'     => $files['type'][$key],
                            'tmp_name' => $files['tmp_name'][$key],
                            'error'    => $files['error'][$key],
                            'size'     => $files['size'][$key]
                        );

                        $_FILES = array("upload_attachment" => $file);

                        foreach ($_FILES as $file => $array) {
                            $newupload = wpcads_insert_attachment($file,$post_id);
                        }
                    }
                }
            }
<form class="form-item" action="" id="primaryPostForm" method="POST" enctype="multipart/form-data">
    <fieldset class="input-title">
        <label for="edit-field-category-und" class="control-label"><?php _e('Add Images', 'agrg') ?></label>
        <input id="upload-images-ad" type="file" name="upload_attachment[]" multiple />
    </fieldset>
</form>

**Comment by rilwis** [comment]
Cách em dùng `update_post_meta` ở trên ko đúng. Em xem docs ở đây:

https://codex.wordpress.org/Function_Reference/update_post_meta

Ngoài ra, để update đúng vào field `image_advanced`, em xem cách lưu dữ liệu của meta box ở đây:

https://metabox.io/docs/how-post-meta-is-saved-in-the-database/

Nói đơn giản thì mỗi 1 ID của ảnh được upload sẽ được lưu ở 1 dòng trong database (dùng `add_post_meta` với tham số cuối là false).
