### ISSUE TITLE
"post" field query for posts created by user only

### ISSUE THREAD

**Issue by ghost** [rilwis/meta-box#990]
I'm using the meta Box Builder plugin and created a dropdown where one can select a related post from a custom post type. Is it right that I can't add the option to show only posts created by the current user as query value with the Builder plugin? Do I have to build the metabox manually to be able to query only for such posts created by the user?

**Comment by funkedgeek** [comment]
You should be able to using either `author` or `author__in` in the `query` parameter

**Comment by tanng** [comment]
If you use Builder, it support nested array by using dot notation. 

[Here](https://metabox.io/docs/how-to-create-nested-array-field-with-meta-box-builder/) is the detail about it :)

**Comment by leadelazer** [comment]
Thanks @tangg this should somehow work!  As for the author__in or author query I don't know how to set the current user as a parameter but I'll keep fiddling around :)

**Comment by leadelazer** [comment]
for now adding any parameter do not make a difference. Does using this option require a meta-box extension? I already tried to make conditionals work until I found out that I need an extension...

i tried to set author as query parameter and current_user as value but that didn't work. I assume it is not possible to add a variable to the value field...

**Comment by tanng** [comment]
Ah. Sorry I thought you want to pass array to `author` param. Yes, `current_user` is not supported. You have to register it manually and use author params.

**Comment by funkedgeek** [comment]
In the function you use to create the meta box, get the current user by: 
`current_user = wp_get_current_user();`

then ion the post field, you add in `query_vars` an arg for an author:

```
array(
    'name'	=> __('My posts', 'FoodRecipe'),
    'id'	=> "{$prefix}posts",
    'type'	=> 'post',
    'query_args' => array(
        'posts_per_page' => '-1',
	'author' => $current_user->ID
    )
),

```
