### ISSUE TITLE
MissingKeyMapError 

### ISSUE THREAD

**Issue by TarikTz** [rilwis/meta-box#991]
Hello,

I've just added google map option to my theme. In dashboard there is no problem, but in the front I'm getting 
`Google Maps API error: MissingKeyMapError https://developers.google.com/maps/documentation/javascript/error-messages#missing-key-map-error`

This is in dashboard: http://prntscr.com/crylsi
And this is the error in the front: http://prntscr.com/crym2j

Any idea what could be a problem?
API Key is included in the front and the back btw.

**Comment by rilwis** [comment]
Thanks for your PR :). It's fixed in 30b5db802d8cb4c0c76a8c85407f2301a5671052 and da5ee28c2849ec99444afd151b534d66a29886c4
