### ISSUE TITLE
Advice rather than issue...generating unique id in cloneable group field

### ISSUE THREAD

**Issue by wgstjf** [rilwis/meta-box#992]
Hi guys,

I hope you don't mind me asking for a generic piece of advice here....

I am creating a kind of form builder with Meta Box.  I have a cloneable & sortable group of fields (used to define and create individual form fields) and one of the fields needs to be a unique id to ensure that, whatever the sort order the admin chooses, the form field is always identifiable and remains constant.

I imagine that the best way to do this is to insert a random id using PHP's uniqid function and insert it into the group field_ID field.  The group can be cloned however so need to figure out how to generate a new one (and insert into the proper field) each time the admin clicks 'Add More'.

Any thoughts would be much appreciated.

Cheers,

Will

**Comment by rilwis** [comment]
Does the field still have a unique id after cloning? The clone will copy that id, so you need to use JS to re-generate another one.

Maybe you should use jQuery to add a callback function on `clone` event of the input. [Here](https://github.com/rilwis/meta-box/blob/master/js/date.js#L75) is an example.

**Comment by ZeroBeeOne** [comment]
Disclaimer - I'm not related to the metabox theme development in any way, just another user.

I'd suggest there are two ways you could do this - 

One would be to expose PHP's `uniqid()` via an ajax call - Use [Wordpress's AJAX filters](https://codex.wordpress.org/AJAX_in_Plugins) to return the result of `uniqid()` to a particular call like `https://youinstall.com/wp-admin/admin-ajax.php?action=wgstjf_get_uniqid`

Separately, you could abandon the generation of ID's in PHP and generate them using random v4 GUIDS. This way you can just have your client-side scripts generate and replace/fill ID's when the page loads (for any fields that are loaded without ID's) and when cloning the field. This removes the AJAX latency from your interface (although it should be vanishingly small for such a simple AJAX call), but won't work for people without javascript turned on (though neither will clone, reorder, etc as far as I know, so maybe it's a non-issue?).

This stackoverflow post gives a good, simple code example for generating version 4 GUIDs - which should be sufficient to avoid collisons unless you plan on allowing users to generate a few quadrillion fields.

**Comment by wgstjf** [comment]
Thanks both, that's great.

I have gone down the ajax route as that is the one I am most familiar with.  In case anyone needs something similar in future this is what I have done (which works as planned)...

The Field
```php
// TEXT - Field
array(
  'name'  => __( 'Field ID', 'indigo-options' ),
  'desc' => '<span style="color:#FF0000">Used by webmaster only</span>',
  'id'    => 'field_id',
  'class'  => 'big-text get-field-id',
	'readonly'	=> true,
  'type'  => 'text',
  'std'   => indigo_event_field_id_generate(),
  'clone' => false,
  'columns'   => '3',
	'visible' => array('type', 'not in', array('') ),
),
```

The ID Generation
```php
add_action('wp_ajax_indigo_event_ajax_field_id_generate', 'indigo_event_ajax_field_id_generate');

function indigo_event_ajax_field_id_generate() {
  $id = indigo_event_field_id_generate();
  echo $id;
  exit;
}

function indigo_event_field_id_generate() {
  return uniqid('field_');
}
```

The JS
```js
$( '.rwmb-input' ).on( 'clone', '.get-field-id', function() {
 var element = $(this);
 jQuery.ajax({
    url: ajaxurl,
    type: 'post',
    data: {action: 'indigo_event_ajax_field_id_generate'},
		dataType: 'html',
    success: function (response) {
       if (response=='') {
            //ERROR
						alert('Failed to generate unique field ID.  Please contact the webmaster');
       } else {
            element.find('input').val(response);
            console.log('ID: ' + response );
       }
    }
    });
});
```

Thanks again,

Will

**Comment by rilwis** [comment]
If you prefer JS-only solution, then this is [a good one](http://underscorejs.org/#uniq).

**Comment by wgstjf** [comment]
That looks interesting...might have a play with that too :-)

Cheers,

Will
