### ISSUE TITLE
Checkbox_list

### ISSUE THREAD

**Issue by dgmaia** [rilwis/meta-box#996]
Just notice that using checkbox_list for multiple options the plugin create identical custom fields.

Eg: 
'id'      => 'colour',
              'name'    => __( 'colour', 'textdomain' ),
              'type'    => 'checkbox_list',
              'options' => array(
                  'red' => __( 'red' ),
                  'blue' => __( 'blue' ),
                  'black' => __( 'black' ),
              ),  

If all 3 were select in the admin
It results in 3 customs fields inputs with the same name (Colour) and different values for each.

Any way to this be combined?  One custom field with all the values.

**Comment by funkedgeek** [comment]
Not sure what you're asking.  The field is working as it should.  Checkbox list is a list of checkboxes that allows you to select multiple items.  Can you clarify what you are asking for?

**Comment by dgmaia** [comment]
It works indeed.

Just in a odd way in my opnion.
Here is a screen on the admin:

![screen shot 2016-10-12 at 12 08 55 pm](https://cloud.githubusercontent.com/assets/3528298/19291908/b007cbf8-9074-11e6-9365-0549fb683995.png)

It results in this:

![screen shot 2016-10-12 at 12 11 05 pm](https://cloud.githubusercontent.com/assets/3528298/19291952/f953e7a6-9074-11e6-81bb-b2e7a613eb9e.png)

Any way to generate this?
![screen shot 2016-10-12 at 12 12 18 pm](https://cloud.githubusercontent.com/assets/3528298/19291972/237b6a40-9075-11e6-99cf-6f6b2743ccb0.png)

**Comment by funkedgeek** [comment]
checkbox_list is a field that is multiple by default.  Fields that are multiple save their pieces of data in separate entries in the database.  If you want a comma separated list, call the data either using rwmb_meta or get_post_meta, which will return an array of data, then use implode to create a comma delimited list
